vaadin/flow-components

build.sh
scripts/updateFromMaster.sh
scripts/updateSources.js
vaadin-charts-flow-parent/documentation/java-api/css-styling.asciidoc
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/pom.xml
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/BasicChartIT.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangingChartIT.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/EditOnClickIT.java
vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java
vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridDetailsRowIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridPageSizeIT.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/MainView.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/BasicIT.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
vaadin-iron-list-flow-parent/vaadin-iron-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/ironlist/tests/IronListIT.java
vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/RendererIT.java
vaadin-tabs-flow-parent/vaadin-tabs-flow-demo/src/main/java/com/vaadin/flow/component/tabs/demo/TabsView.java
vaadin-tabs-flow-parent/vaadin-tabs-flow-integration-tests/src/test/java/com/vaadin/flow/component/tabs/tests/TabsIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/ValueChangeModeIT.java

manually fix here, but need to fix in the script too.
bug #36

Correct the artifact name for chart demo

---

pom.xml
scripts/updateJavaPOMs.js
scripts/updateSources.js
vaadin-accordion-flow-parent/vaadin-accordion-flow/pom.xml
vaadin-app-layout-flow-parent/vaadin-app-layout-flow/pom.xml
vaadin-custom-field-flow-parent/vaadin-custom-field-flow/pom.xml
vaadin-details-flow-parent/vaadin-details-flow/pom.xml
vaadin-login-flow-parent/vaadin-login-flow/pom.xml
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/ValueChangeModeIT.java

Update the pro components list

---

pom.xml

flow 5.0-snapshot is used for platform 18.0

Update flow version for master branch

---

build.sh

test: Adjust script for snapshot build

---

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDataViewPageIT.java

Web-component: vaadin-radio-button

test: fix tests because not correctly resetting browser

---

build.sh

fixes #206 
added completed/skipped tests number into build status.

ci: include more infos in the build status

---

build.sh

ci: include more infos in the build status 

---

build.sh

* ci: include more infos in the build status 
fix #206

ci: include more infos in the build status (#218)

---

vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/HelperPage.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/HelperIT.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java

Fixes: vaadin/vaadin-checkbox#191
Web-component: checkbox

fix: Keep HelperComponent after reset

---

scripts/updateWebjars.js

Add dependencyManagement updates
fix #249 
need to cherry-pick to 14.5 branch

ci: fix the faulty use of const type [skip ci]

---

scripts/updatePlatform.sh

ci: allow pass target to platform update script [skip ci] (#254)

---

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/HelperPage.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/HelperIT.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java

Fix: Keep HelperComponent after reset (#253)

---

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/HelperPage.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/HelperIT.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java

Fix: Keep HelperComponent after reset (14.5) (#253)

---

vaadin-grid-flow-parent/vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java

refactor: remove unused event handler from Grid demo

---

vaadin-tabs-flow-parent/vaadin-tabs-flow-demo/src/main/java/com/vaadin/flow/component/tabs/demo/TabsView.java

details: the previous link is down.

chore: update the external avatar link

---

vaadin-tabs-flow-parent/vaadin-tabs-flow-demo/src/main/java/com/vaadin/flow/component/tabs/demo/TabsView.java

details: the previous link is down.

chore: update the external avatar link (#288)

---

scripts/generateChangeLog.js
scripts/mergeITs.js
scripts/prepareDeploy.sh

Consider changes that modifies version of WC

ci: use same way in scripts to discover modified modules.

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/pom.xml
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/data/performance/AbstractBeansMemoryTest.java

test: fix compilation in Java11

---

scripts/generateChangeLog.js
scripts/mergeITs.js
scripts/prepareDeploy.sh

Consider changes that modifies version of WC

ci: use same way in scripts to discover modified modules. (#318)

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/service/PersonService.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/dataview/ComboBoxListDataView.java

Address DX test issues for ComboBox, including new demo to demonstrate how to use filter converter and enhancing java-docs for better developer experience. 
Fixes: #314

docs: add demo for custom type filter converter and enhance javadocs

---

vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/it/FileBufferView.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/AbstractUploadIT.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/FileBufferIT.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/AbstractFileBuffer.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/FileBuffer.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/FileData.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/MultiFileBuffer.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/UploadOutputStream.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/FileBufferTest.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/MultiFileBufferTest.java

Fixes vaadin/vaadin-upload#334

Fix: FileBuffer getInputStream is closed

---

vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/it/FileBufferView.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/AbstractUploadIT.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/FileBufferIT.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/AbstractFileBuffer.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/FileBuffer.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/FileData.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/MultiFileBuffer.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/UploadOutputStream.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/FileBufferTest.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/MultiFileBufferTest.java

* Fix: FileBuffer getInputStream is closed
Note: This version does not create new public APIs

CP 14.4: FileBuffer getInputStream is closed (#405)

---

vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/it/FileBufferView.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/AbstractUploadIT.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/FileBufferIT.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/AbstractFileBuffer.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/FileBuffer.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/FileData.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/MultiFileBuffer.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/UploadOutputStream.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/FileBufferTest.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/MultiFileBufferTest.java

* Fix: FileBuffer getInputStream is closed

CP 14.5: FileBuffer getInputStream is closed (#405)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridMultiSelectionModel.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java

Cherry Picks for 18.0

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridMultiSelectionModel.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java

Cherry Picks for 17.0

---

vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridElement.java

Correctly wait for grid to finish loading

---

vaadin-iron-list-flow-parent/vaadin-iron-list-flow-demo/src/main/java/com/vaadin/flow/component/ironlist/demo/IronListView.java

test: fix iron-list test using broken url images generated by faker

---

vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerTest.java

fix vaadin/vaadin-date-time-picker#60

fix: use right value at getErrorMessage

---

vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java

Fixes https://github.com/vaadin/vaadin-radio-button/issues/184

fix: allow null items in RadioButtonGroup

---

vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerTest.java

fix vaadin/vaadin-date-time-picker#60

fix: use right value at getErrorMessage (#507) (CP: 18.0)

---

vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerTest.java

fix vaadin/vaadin-date-time-picker#60

fix: use right value at getErrorMessage (#507) (CP: 14.5)

---

vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerTest.java

fix vaadin/vaadin-date-time-picker#60

fix: use right value at getErrorMessage (#507) (CP: 14.4)

---

scripts/lib/versions.js

chore: fix npmpackage update script

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/SortingPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTestScrollingOver100kLinesIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js

fix: ensure first page is loaded; sorting not breaking on hidden grid (cherry-pick #529)

---

vaadin-crud-flow-parent/vaadin-crud-testbench/src/main/java/com/vaadin/flow/component/crud/testbench/CrudElement.java

fix: update openRowForEditing to get vaadin-crud-edit based on row.index (#541)

---

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/FieldValidationUtil.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/FieldValidationUtil.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/FieldValidationUtil.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/FieldValidationUtil.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/FieldValidationUtil.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java

fix: Fix client side validation overriding (#512) (CP: 14.4)

---

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/FieldValidationUtil.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/FieldValidationUtil.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/FieldValidationUtil.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/FieldValidationUtil.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/FieldValidationUtil.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java

fix: Fix client side validation overriding (#512) (CP: 18.0)

---

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/FieldValidationUtil.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/FieldValidationUtil.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/FieldValidationUtil.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/FieldValidationUtil.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/FieldValidationUtil.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java

fix: Fix client side validation overriding (#512) (CP: 14.5)

---

vaadin-accordion-flow-parent/vaadin-accordion-flow-integration-tests/pom.xml
vaadin-accordion-flow-parent/vaadin-accordion-flow/src/main/java/com/vaadin/flow/component/accordion/Accordion.java
vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java

fix: add HasStyle interface to the Accordion, AccordionPanel and Details components.
* fix: Add a missing dependency for the Accordion integration tests.
Web-Component: Accordion, AccordionPanel, Details
Fixes #564

fix: added HasStyle interface to the Accordion, AccordionPanel and Details components.

---

vaadin-accordion-flow-parent/vaadin-accordion-flow-integration-tests/pom.xml
vaadin-accordion-flow-parent/vaadin-accordion-flow/src/main/java/com/vaadin/flow/component/accordion/Accordion.java
vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java

* fix: Add a missing dependency for the Accordion integration tests.
Web-Component: Accordion, AccordionPanel, Details
Fixes #564

feat: added HasStyle interface to the Accordion, AccordionPanel and Details components. (CP: #569)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridChildRemoval.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridChildRemovalIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js

#Fixes https://github.com/vaadin/vaadin-grid/issues/1819

Fix: Clear subchildren when refreshing item

---

scripts/updatePlatform.js

filter out vaadin-core, as this will not be update anyway from here.

chore: fix the update platform script [skip ci]

---

scripts/lib/versions.js

Chore: aligning script [skip-ci]

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/dataview/ItemCountUnknownComboBoxIT.java

Fixes: https://github.com/vaadin/vaadin-combo-box/issues/988

test: fix and enable ComboBox switch to defined count test

---

vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/TimePickerPage.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerIT.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js

cherry-pick of https://github.com/vaadin/vaadin-time-picker-flow/pull/79
Web-component: vaadin-time-picker

Cherrypick: Added timeout between calls of when vaadin/vaadin-time-picker-flow#81 (14.5)

---

vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/src/main/java/com/vaadin/flow/component/messages/tests/MessageInputPage.java
vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/src/test/java/com/vaadin/flow/component/messages/tests/MessageInputIT.java
vaadin-messages-flow-parent/vaadin-messages-flow/src/main/java/com/vaadin/flow/component/messages/MessageInput.java

Resolves https://github.com/vaadin/vaadin-messages/issues/38

feat: MessageInput::setEnabled

---

scripts/prepareDeploy.sh

fix the issue mentioned in https://github.com/vaadin/vaadin-flow-components/pull/669 by @manolo

chore: replace the hard coded branch version [skip-ci]

---

scripts/mergeITs.js
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/frontend/src/ImplicitLumoThemedTemplate.js
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/frontend/src/LumoThemedTemplate.js
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/frontend/theme/lumo/ImplicitLumoThemedTemplate.js
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/frontend/theme/lumo/LumoThemedTemplate.js
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/src/main/java/com/vaadin/flow/theme/lumo/ExplicitLumoTemplateView.java
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/src/main/java/com/vaadin/flow/theme/lumo/ImplicitLumoTemplateView.java
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/src/main/java/com/vaadin/flow/theme/lumo/LumoAppShell.java
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/src/main/java/com/vaadin/flow/theme/lumo/LumoView.java
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/src/test/com/vaadin/flow/theme/lumo/LumoIT.java
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/src/test/java/com/vaadin/flow/theme/lumo/AbstractThemedTemplateIT.java
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/src/test/java/com/vaadin/flow/theme/lumo/ExplicitLumoTemplateIT.java
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/src/test/java/com/vaadin/flow/theme/lumo/ImplicitLumoTemplateIT.java
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/src/test/java/com/vaadin/flow/theme/lumo/LumoIT.java
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/frontend/src/MaterialThemedTemplate.js
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/frontend/src/NotThemedTemplate.js
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/frontend/theme/lumo/MaterialThemedTemplate.js
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/frontend/theme/material/MaterialThemedTemplate.js
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/src/main/java/com/vaadin/flow/theme/material/MaterialAppShell.java
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/src/main/java/com/vaadin/flow/theme/material/MaterialThemedTemplateView.java
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/src/main/java/com/vaadin/flow/theme/material/MaterialView.java
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/src/main/java/com/vaadin/flow/theme/material/NotThemedTemplateView.java
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/src/test/com/vaadin/flow/theme/material/MaterialIT.java
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/src/test/java/com/vaadin/flow/theme/material/MaterialIT.java
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/src/test/java/com/vaadin/flow/theme/material/MaterialNotThemedTemplateIT.java
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/src/test/java/com/vaadin/flow/theme/material/MaterialThemedTemplateIT.java

In draft mode until https://github.com/vaadin/vaadin-flow-components/pull/706 is merged

test: add test modules for lumo and material

---

vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/main/java/com/vaadin/flow/component/richtexteditor/examples/RichTextEditorSetHtmlValuePage.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/test/RichTextEditorSetHtmlValueIT.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java

Fixes: vaadin/vaadin-rich-text-editor#175

Fix: Call updateValue after server-side setHtml

---

vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/main/java/com/vaadin/flow/component/richtexteditor/examples/RichTextEditorSetHtmlValuePage.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/test/RichTextEditorSetHtmlValueIT.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java

Cherrypick: Call updateValue after server-side setHtml (#734)

Call updateValue after server-side(#734) (CP:14.5)

---

vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/main/java/com/vaadin/flow/component/richtexteditor/examples/RichTextEditorSetHtmlValuePage.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/test/RichTextEditorSetHtmlValueIT.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java

Cherrypick: Call updateValue after server-side setHtml (#734)

Call updateValue after server-side(#734) (CP:14.4)

---

vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/AppLayout.java
vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/DrawerToggle.java
vaadin-board-flow-parent/vaadin-board-flow/src/main/java/com/vaadin/flow/component/board/Board.java
vaadin-board-flow-parent/vaadin-board-flow/src/main/java/com/vaadin/flow/component/board/Row.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/Chart.java
vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow/src/main/java/com/vaadin/flow/component/cookieconsent/CookieConsent.java
vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java
vaadin-custom-field-flow-parent/vaadin-custom-field-flow/src/main/java/com/vaadin/flow/component/customfield/CustomField.java
vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/Icon.java
vaadin-login-flow-parent/vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginForm.java
vaadin-login-flow-parent/vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java
vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/Scroller.java
vaadin-progress-bar-flow-parent/vaadin-progress-bar-flow/src/main/java/com/vaadin/flow/component/progressbar/ProgressBar.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/GeneratedVaadinRichTextEditor.java
vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java

Noticed these while updating web components versions, let's remove them.

chore: fix some trailing whitespaces

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridCellFocusPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridCellFocusPageIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/CellFocusEvent.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js

* extended grid connector to handle the client side event and integrate the grid event context
* added a CellFocusEvent class and respective listener to Grid
* integration tests

Flow integration for Grid's cell-focus event

---

vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValuePage.java
vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValueIT.java
vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/ListBoxBase.java

fix: move clear from rebuild to correct places (#773) (CP 19.0)

---

vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValuePage.java
vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValueIT.java
vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/ListBoxBase.java

fix: move clear from rebuild to correct places (#773) (CP 14.7)

---

vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValuePage.java
vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValueIT.java
vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/ListBoxBase.java

fix: move clear from rebuild to correct places (#773) (CP 14.6)

---

scripts/updateWebjars.js

for pro components, they are released to different places (maven central for stable and vaadin-prerelease for prerelease) instead of standard webjar (using webjars.org)

chore: fix webjar updates for pro components [skip ci]

---

vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/pom-bower-mode.xml
vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/pom.xml
vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValuePage.java
vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValueIT.java

test: fix listBoxRetainValueWhenRemovedAndAdded test (#814) 

---

scripts/prepareDeploy.sh

chore: dont deploy testbech/demo when missing [skip ci]

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/RemoveSortableColumnPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/RemoveSortableColumnsIT.java

Work in progress
Fixing flaky RemoveSortableColumnsIT introduced by #468

test: fix flaky RemoveSortableColumnsIT

---

README.md

Added section to the readme on how to bump versions for all modules when creating a new major/minor.

chore: document how to bump versions

---

CONTRIBUTING.md

Copying flow contributing message to this repo

chore: Create CONTRIBUTING.md [skip-ci]

---

pom.xml

Chore: update testbench to 6.4.0

---

vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogWithShortcutPage.java

chore: Remove @NpmPackage annotation (CP 14.7)

---

PULL_REQUEST_TEMPLATE.md

Use the same as in the `web-components` repo, added there in https://github.com/vaadin/web-components/pull/194
Related to https://github.com/vaadin/components-team-tasks/issues/114

chore: add PR template [skip ci]

---

package.json
pom.xml
vaadin-app-layout-flow-parent/vaadin-app-layout-flow/pom.xml
vaadin-board-flow-parent/vaadin-board-flow/pom.xml
vaadin-charts-flow-parent/vaadin-charts-flow/pom.xml
vaadin-checkbox-flow-parent/vaadin-checkbox-flow/pom.xml
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/pom.xml
vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/pom.xml
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/pom.xml
vaadin-crud-flow-parent/vaadin-crud-flow/pom.xml
vaadin-custom-field-flow-parent/vaadin-custom-field-flow/pom.xml
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/pom.xml
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/pom.xml
vaadin-details-flow-parent/vaadin-details-flow/pom.xml
vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithShortcutIT.java
vaadin-dialog-flow-parent/vaadin-dialog-flow/pom.xml
vaadin-form-layout-flow-parent/vaadin-form-layout-flow/pom.xml
vaadin-grid-flow-parent/vaadin-grid-flow/pom.xml
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridMultiSelectionModelTest.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/pom.xml
vaadin-list-box-flow-parent/vaadin-list-box-flow/pom.xml
vaadin-login-flow-parent/vaadin-login-flow/pom.xml
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/pom.xml
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/pom.xml
vaadin-select-flow-parent/vaadin-select-flow/pom.xml
vaadin-text-field-flow-parent/vaadin-text-field-flow/pom.xml
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/pom.xml
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/pom.xml

fixes https://github.com/vaadin/flow-components/issues/997 
Notice that out of the scope of this PR is remove powermock that should be done separately https://github.com/vaadin/flow-components/issues/1708

test: fix mockito errors accessing protected API in JDK16

---

vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupDisabledItemPage.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupDisabledItemIT.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java

Fixes: https://github.com/vaadin/flow-components/issues/993

fix: Disable checkbox after applying value

---

vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java

fixes: https://github.com/vaadin/flow-components/issues/1697

documentation: Add note to RadioButtonGroup#setRendered JavaDoc

---

README.md

doc: update documentation with formatting conventions (#844) [skip ci]

---

vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js
vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/package.json
vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/pom.xml
vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/src/main/java/com/vaadin/flow/component/charts/export/SVGGenerator.java
vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/test/index.test.js

Plus:
- add tests
- make tests run on mvn verify

[svg-generator] Add options to the JS API

---

vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/pom-bower-mode.xml
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/pom.xml
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/it/NonImmediateUploadView.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/NonImmediateUploadIT.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java

Cherry-pick of https://github.com/vaadin/flow-components/pull/919

Fix: Prevent NPE with autoUpload=false and multiple files are being uploaded (CP: 14.6)

---

vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/pom-bower-mode.xml
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/pom.xml
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/it/NonImmediateUploadView.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/NonImmediateUploadIT.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java

Cherry-pick of https://github.com/vaadin/flow-components/pull/919

Fix: Prevent NPE with autoUpload=false and multiple files are being uploaded (CP: 14.7)

---

vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/pom.xml
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/it/NonImmediateUploadView.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/NonImmediateUploadIT.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java

Cherry-pick of https://github.com/vaadin/flow-components/pull/919

Fix: Prevent NPE with autoUpload=false and multiple files are being uploaded (CP: 19.0)

---

vaadin-grid-flow-parent/vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ColumnResizeEventPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridSingleSelectionPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridView.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/RecalculateColumnWidthsPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridInitialExpandPage.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTest.java

fixes: #1009
related PRs:
vaadin/flow-components#1795
vaadin/web-components#2099
vaadin/vaadin-grid#2184

feat: deprecate setHeightByRows in favor of setAllRowsVisible

---

vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/AbstractTBTest.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/BasicChartIT.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ChartSizeIT.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ChartStyleIT.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ColumnWithLazyMultiLevelDrilldownCallbackTestsIT.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ColumnWithLazyMultiLevelDrilldownIT.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangesIT.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangingChartIT.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicExtremesIT.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/GlobalOptionsIT.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/PieWithoutAccessibilityIT.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java
vaadin-flow-components-shared/src/main/java/com/vaadin/tests/AbstractParallelTest.java
vaadin-flow-components-shared/src/main/java/com/vaadin/tests/ComponentDemoTest.java

This is a continuation of https://github.com/vaadin/flow-components/pull/1822

test: fix using selenium hub in charts tests

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridHugeTreeIT.java

test: fix hung situation when running grid tests in jdk16

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/SortingPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java

fix: Update client side sort indicators after header is updated

---

vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupTest.java

Move fixed validation to hasValidValue

---

scripts/cherryPick.js

chore: filter closed but no-merge commit [skip ci]

---

scripts/mergeITs.js

exclude the messages component test in V14.x(14.7) bower validation

chore:fix messages component validation under bower mode

---

pom.xml
scripts/templates/pom-flow-pro.xml
scripts/templates/pom-flow.xml
scripts/updateJavaPOMs.js
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow/pom.xml
vaadin-material-theme-flow-parent/vaadin-material-theme-flow/pom.xml
vaadin-renderer-flow-parent/vaadin-renderer-flow/pom.xml

fix: export OSGi packages for themes and renderer modules

---

vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/demo/AbstractChartExample.java
vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/demo/examples/dynamic/ServerSideEvents.java
vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/demo/examples/pie/PieWithLegend.java
vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/demo/examples/pie/PieWithLegendEvents.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/main/java/com/vaadin/flow/component/charts/ui/MainView.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/PieWithLegendEventsIT.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/tests/elements/SpanElement.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/ClickEvent.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/MouseEventDetails.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointLegendItemClickEvent.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/SeriesLegendItemClickEvent.java

Feat: Add modifiers and position metadata to PointLegendItemClickEvent and SeriesLegendItemClickEvent

---

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/BasicRenderer.java
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/ClickableRenderer.java
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/ComponentDataGenerator.java
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/IconRenderer.java
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LocalDateRenderer.java
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LocalDateTimeRenderer.java
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/NativeButtonRenderer.java
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/NumberRenderer.java
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/Renderer.java
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/RendererUtil.java
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/Rendering.java
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/TemplateRenderer.java
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/TextRenderer.java

chore: deprecate template-specific API from Renderer

---

scripts/generateChangeLog.js

chore: no vaadin prefix in repo name [skip ci]

---

vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/main/java/com/vaadin/flow/component/crud/examples/DetachAttachView.java
vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/main/java/com/vaadin/flow/component/crud/examples/EditorButtonsView.java
vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/DetachAttachIT.java
vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/EditorButtonsIT.java
vaadin-crud-flow-parent/vaadin-crud-flow/pom.xml
vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java

Add getters to Save, Cancel and Delete buttons on Crud.
Fixes https://github.com/vaadin/flow-components/issues/1112

feat: add API for editor buttons on Crud

---

vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/demo/examples/dynamic/ServerSideEvents.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java

Cherry pick of https://github.com/vaadin/flow-components/pull/2140

chore: improve flaky ServerSideEventsIT (CP: 22)

---

vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/src/main/java/com/vaadin/flow/component/charts/export/NodeRunner.java

Fixes compilation errors that came up due to recent changes in the flow-server snapshot.

chore: fix NodeRunner compilation errors after API change in flow-server

---

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java

Cherry pick: https://github.com/vaadin/flow-components/pull/2046

fix: Validate first day of the week

---

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePickerVariant.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerVariantTest.java

feat: Add support for theme variants for DatePicker

---

vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/AbstractFileBuffer.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/TempDirectory.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/TemporaryFileFactory.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/TemporaryFileFactoryTest.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/UploadSerializableTest.java

cherry-pick of https://github.com/vaadin/flow-components/pull/2254

refactor: use java nio API for creating temp files and directory. (#2254) (CP: 21.0)

---

vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/AbstractFileBuffer.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/TempDirectory.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/TemporaryFileFactory.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/TemporaryFileFactoryTest.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/UploadSerializableTest.java

refactor: use java nio API for creating temp files and directory (#2254) (CP: 14.7)

---

pom.xml

align version with flow and osgi plugin
https://github.com/vaadin/flow/pull/12252
https://github.com/vaadin/osgi/pull/75

chore: Upgrade bnd-maven-plugin to 6.0.0

---

pom.xml

chore: update testbench version to 7.0.3

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/SortingPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js

fix: don't access empty visibleRows in gridConnector

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
vaadin-combo-box-flow-parent/vaadin-combo-box-testbench/src/main/java/com/vaadin/flow/component/combobox/testbench/ComboBoxElement.java

Cherry pick of: #2340 
(cherry picked from commit 885128a45941e265a4299d361e208747e2fd3043)

fix: clear input element value when clearing custom value in ComboBox (#2340) (CP: 14.8)

---

vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListViewIT.java

Fixes `VirtualListViewIT.disabledListWithTemplates` test.

chore: fix virtual list disabled test

---

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/TextAreaPatternPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/TextAreaPatternIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/TextAreaTest.java

Cherry pick of #2158 
Fixes #2077
(cherry picked from commit db35ef284f511c78cabbc473f8464d033f57a8d0)
No noteworthy changes, only resolved a merge conflict in a test file.

feat: add pattern validation to TextArea (#2158) (CP: 14.8)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js

Fixes https://github.com/vaadin/flow-components/issues/2389

fix: make grid connector request content update on missing data

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java

Add the IT from https://github.com/vaadin/flow-components/pull/2392 to make sure the issue doesn't produce in V14 Grid

test: add a grid filtering test from #2392

---

vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/DrilldownEvent.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/HasItem.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointClickEvent.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointLegendItemClickEvent.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointMouseOutEvent.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointMouseOverEvent.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointRemoveEvent.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointSelectEvent.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointUnselectEvent.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointUpdateEvent.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/test/java/com/vaadin/flow/component/charts/HasItemTest.java

Cherry-pick of: #2390 
Fixes: https://github.com/vaadin/flow-components/issues/1040
(cherry picked from commit 5b6ba0608c1e728843c53f6331d0dee8b85508bd)

fix: prevent HasItem.getItem throwing ClassCastException (#2390) (CP: 21)

---

pom.xml
vaadin-charts-flow-parent/vaadin-charts-flow/pom.xml
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/serializers/BeanSerializerDelegator.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/serializers/ThemeGradientColorBeanSerializer.java

https://github.com/vaadin/flow/blob/b8e69d5e16a6e17c67118a12d753aebe8dfa18b4/pom.xml#L90

chore: align jackson.version with flow project

---

vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/it/GridProDetachAttachPage.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/GridProDetachAttachIT.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/EditColumnConfigurator.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java

Fixes [#2466](https://github.com/vaadin/web-components/issues/2466)
Fixes https://github.com/vaadin/flow-components/issues/2319

fix: register custom editor onAttach

---

vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/button/tests/TemplateButtonIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPageIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/StringItemsWithTextRendererIT.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerValidationPageIT.java
vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java
vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithComboBoxIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetailsGridIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridDetailsRowIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridFilteringIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridFullSizeInATemplateIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridHeaderFooterRowIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridHeaderRowWithComponentsIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTestPageIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridWithTemplateIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridDetailsRowIT.java
vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/test/java/com/vaadin/flow/component/notification/tests/NotificationWithTemplateIT.java
vaadin-split-layout-flow-parent/vaadin-split-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitLayoutIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/EmailFieldPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/PasswordFieldPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/TextAreaPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/TextFieldPageIT.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/AbstractUploadIT.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadI18nIT.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java

* test: Remove usage of Shadowroot methods
* chore: format
Co-authored-by: ZheSun88 <zhe@vaadin.com>

test: Remove usage of Shadowroot methods (#2433)

---

vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/it/GridProDetachAttachPage.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/GridProDetachAttachIT.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/EditColumnConfigurator.java

Cherry-pick of: #2409
Fixes #2466
Fixes #2319
Co-authored-by: Sascha Ißbrücker <sissbruecker@vaadin.com>
Co-authored-by: Sascha Ißbrücker <sascha.issbruecker@googlemail.com>
(cherry picked from commit 56c878aa1e3f9fdfc031186c99dcf55052e66593)

fix: register custom editor onAttach (#2409) (CP: 14.8)

---

vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/it/GridProDetachAttachPage.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/GridProDetachAttachIT.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/EditColumnConfigurator.java

Cherry-pick of: #2409 
Fixes #2466
Fixes #2319
Co-authored-by: Sascha Ißbrücker <sissbruecker@vaadin.com>
Co-authored-by: Sascha Ißbrücker <sascha.issbruecker@googlemail.com>
(cherry picked from commit 56c878aa1e3f9fdfc031186c99dcf55052e66593)

fix: register custom editor onAttach (#2409) (CP: 22)

---

vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/it/GridProDetachAttachPage.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/GridProDetachAttachIT.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/EditColumnConfigurator.java

Cherry-pick of: #2409
Fixes #2466
Fixes #2319
Co-authored-by: Sascha Ißbrücker sissbruecker@vaadin.com
Co-authored-by: Sascha Ißbrücker sascha.issbruecker@googlemail.com
(cherry picked from commit 56c878a)

fix: register custom editor onAttach (#2409) (CP: 21)

---

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java

Provide APIs to disable (and enable) an entire menu-bar.
Depends on https://github.com/vaadin/web-components/pull/3246
Fixes https://github.com/vaadin/web-components/issues/3202

feat: implement HasEnabled interface in MenuBar

---

vaadin-custom-field-flow-parent/vaadin-custom-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/customfield/examples/NameFieldView.java
vaadin-custom-field-flow-parent/vaadin-custom-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/customfield/test/NameFieldViewIT.java

Restored the IT previously refactored in https://github.com/vaadin/flow-components/pull/2483/commits/bc6c3e50bd504266ba208bb059efe51ad2cabfa0
- Tests

test: restore CustomField helper component IT

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/InitiallyEmptyPage.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/InitiallyEmptyPageIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js

fix: patch _isItemSelected once combobox is finalized (#2487) (#2509)

---

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java

fix: don't disable a readonly radio group

---

vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/Map.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/MapBase.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/mapConnector.js
vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/synchronization/index.js
vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/synchronization/layers.js
vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/synchronization/sources.js
vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/synchronization/util.js

Adds a connector to the Flow Map component, and moves the client-side configuration synchronization logic to it.

chore: add map connector and move client-side sync logic

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridDetachAttachPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridDetachAttachIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js

fix: check sub cache queue of a grid instance in connector (#2540)

---

vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/resources/vaadin-featureflags.properties
vaadin-map-flow-parent/vaadin-map-flow/pom.xml
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/ExperimentalFeatureException.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/MapBase.java
vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/FeatureFlagTest.java

Adds support for the new map feature flag to the map component.
Fixes #2495

feat: implement map feature flag

---

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/DisabledItemsPage.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/DisabledItemsPageIT.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java

Fixes [#2528](https://github.com/vaadin/flow-components/issues/2528)

fix: enforce radio button web component disabled state

---

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/DisabledItemsPage.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/DisabledItemsPageIT.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java

fix: enforce radio button web component disabled state (#2563)

---

vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/MapEventsPage.java
vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/MapEventsIT.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/Map.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/MapBase.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Extent.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/View.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/ViewExtent.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/events/MapViewMoveEndEvent.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/mapConnector.js

Adds support for viewport change event (center, zoom, rotation, extent).
Adds IT for updating view states.
Fixes: https://github.com/vaadin/flow-components/issues/2501

[map] Viewport change event

---

pom.xml
scripts/prepareDeploy.sh

after adding this module, we should add it for releasing, as the shared module depends on it.

chore: add demo helper and update TB version

---

vaadin-map-flow-parent/pom.xml
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Coordinate.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Projection.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/View.java
vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/CoordinateTest.java

Adds converter for latitude / longitude coordinates. Clarifies that coordinates can be in any projection.
Fixes #2500

feat: add support for lat/long coordinates

---

vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/FeatureLayerPage.java
vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/SourcesPage.java
vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/demo/TileWMSDemo.java
vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/FeatureLayerIT.java
vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/SourcesIT.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Constants.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/TileWMSSource.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/synchronization/index.js
vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/synchronization/sources.js
vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/source/TileWMSSourceTest.java
vaadin-map-flow-parent/vaadin-map-testbench/src/main/java/com/vaadin/flow/component/map/testbench/MapElement.java

Adds support for configuring tile WMS sources.
Part of #2498

feat: add support for tile wms source

---

vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/SourcesPage.java
vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/demo/XYZSourceDemo.java
vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/SourcesIT.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/XYZSource.java

XYZ source was already usable, to finalize it I improved JavaDoc, added basic IT, demo page.
Part of #2498

feat: finalize support for XYZ source

---

vaadin-list-box-flow-parent/vaadin-list-box-flow-demo/src/main/java/com/vaadin/flow/component/listbox/demo/ListBoxView.java
vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/listbox/test/ListBoxViewDemoPage.java
vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxIT.java
vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/ListBoxBase.java

Fixes https://github.com/vaadin/flow-components/issues/1631

feat: add missing setItemLabelGenerator for a ListBox

---

vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/SourcesPage.java
vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/demo/ImageWMSDemo.java
vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/SourcesIT.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Constants.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/layer/ImageLayer.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/ImageSource.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/ImageWMSSource.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/synchronization/index.js
vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/synchronization/layers.js
vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/synchronization/sources.js
vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/source/ImageWMSSourceTest.java

Adds support for WMS single image sources.
Part of #2498

feat: add support for wms image sources

---

vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/BasicUseIT.java
vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/CrudGrid.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridHeaderFooterRowIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java

Fixes https://github.com/vaadin/web-components/pull/3366
Related https://github.com/vaadin/web-components/pull/3394

fix: add aria-label to crud sorter and filter

---

vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/it/GridProDetachAttachPage.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/GridProDetachAttachIT.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/EditColumnConfigurator.java

Backport https://github.com/vaadin/flow-components/pull/2493 to Vaadin 22

fix: add custom field when column has been added (#2493)

---

vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/Map.java

Updates the JS module annotation for the map component to import the theme-agnostic source module.
Fixes https://github.com/vaadin/flow-components/issues/2506

chore: make map class theme-agnostic

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/DataProviderPage.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/DataProviderIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

fix: don't remove lazy-open registration on detach

---

vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/confirmdialog/examples/FeaturesDiy.java
vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/test/FeaturesDiyIT.java
vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java

fix: clean confirm dialog slots before adding new content

---

vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/button/tests/ButtonView.java

Fixes https://sonarcloud.io/project/issues?resolved=false&types=BUG&pullRequest=2779&id=vaadin_flow-components&open=AX9Uj2DOsF4NpWIAWkRG

chore: fix thread interruption sonar error

---

vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/SelectVariant.java
vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectVariantTest.java

Added `HasTheme` and corresponding theme variants (copied from `ComboBox`)
Part of #2343
- Feature

feat: add theme variants support for Select

---

vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/main/java/com/vaadin/flow/component/charts/examples/AbstractChartExample.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/main/java/com/vaadin/flow/component/charts/examples/combinations/ScatterAndPolygon.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/main/java/com/vaadin/flow/component/charts/examples/dynamic/DynamicChanges.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/main/java/com/vaadin/flow/component/charts/examples/lineandscatter/SplineUpdatingEachSecond.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/main/java/com/vaadin/flow/component/charts/examples/other/DynamicChangingChart.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/main/java/com/vaadin/flow/component/charts/examples/other/Gauge.java
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/main/java/com/vaadin/flow/component/charts/examples/other/GaugeWithDualAxes.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridViewBasicFeaturesPage.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarTestPage.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarPageIT.java
vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow-integration-tests/src/main/java/com/vaadin/flow/component/orderedlayout/it/OrderedLayoutView.java

Fixes:
- https://sonarcloud.io/project/issues?resolved=false&types=BUG&pullRequest=2829&id=vaadin_flow-components&open=AX9vNFsYOnyZ4QsM1hbp
- https://sonarcloud.io/project/security_hotspots?id=vaadin_flow-components&pullRequest=2829

chore: resolve bugs and security issues reported by sonar cloud

---

scripts/run.sh

All the demo modules have been removed so this script needs to be updated accordingly.

chore: remove demo option from the script

---

vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/CustomGridIT.java
vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/ProtectedBackendIT.java
vaadin-crud-flow-parent/vaadin-crud-testbench/pom.xml
vaadin-crud-flow-parent/vaadin-crud-testbench/src/main/java/com/vaadin/flow/component/crud/testbench/CrudElement.java

Closes https://github.com/vaadin/flow-components/issues/2876

feat: Add getters for confirm delete / cancel dialogs in CrudElement

---

vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/ProtectedBackendIT.java
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow/src/main/java/com/vaadin/flow/theme/lumo/LumoUtility.java

Executed `mvn formatter:format` on whole project

chore: run mvn formatter:format

---

vaadin-login-flow-parent/vaadin-login-flow-integration-tests/pom.xml
vaadin-login-flow-parent/vaadin-login-flow-integration-tests/src/main/java/com/vaadin/flow/component/login/examples/OverlayClassNameView.java
vaadin-login-flow-parent/vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/OverlayClassNameIT.java
vaadin-login-flow-parent/vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginForm.java
vaadin-login-flow-parent/vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java
vaadin-login-flow-parent/vaadin-login-flow/src/main/resources/META-INF/resources/frontend/loginOverlayConnector.js
vaadin-login-flow-parent/vaadin-login-flow/src/test/java/com/vaadin/flow/component/login/LoginFormTest.java

Added HasStyle to LoginForm component.
Added HasStyle and the connector to copy CSS class names from the host to the LoginOverlay component.
Fixes #2858
Type of change
Checklist

feat: Add HasStyle interface to LoginOverlay and LoginForm

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridView.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridMultiSelectionModelTest.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridMultiSelectionWithIdProviderTest.java

Cherry-pick of: #2947 
(cherry picked from commit 11f0c3e58728825c1ebcf3d5e27807c7aecd4c65)

fix: ensure GridMultiSelectionModel uses identity given by DataProvider (#2947) (CP: 23.0)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridSelectionColumn.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.html
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelWithHierarchicalDataProviderTest.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/MockUI.java

Cherry-pick of: #2954 
(cherry picked from commit 08fcccf06b733d4760d66bf83f840cd20edd0af1)

fix: grid selection column indeterminate state (#2954) (CP: 14.8)

---

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridVariant.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridProVariant.java

Add missing theme variants enum to GridPro
Fixes #2925

feat: add Grid Pro theme variants enum

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridViewConfiguringColumnsPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewConfiguringColumnsIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/ColumnBase.java

feat: add support for freezing columns to end

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

Add shorthand constructors accepting value change listener
Fixes #2995

feat: add shorthand constructors accepting value change listener

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridSingleSelectionDeselectAllowedPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionDeselectAllowedIT.java

Cherry-pick of: #3009 
(cherry picked from commit f94905d80db9d736e54b520f51fcce7368fd5242)

chore: rename single selection IT (#3009) (CP: 23)

---

vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuItemsArrayGenerator.java
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuConnector.js
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuTargetConnector.js
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenuTest.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/resources/META-INF/resources/frontend/menubarConnector.js

The PR cherry-picks the following refactoring to 23.0:
- #3025
Part of #2134

refactor: extract target connector, refactor items tree construction logic (#3025) (CP: 23.0)

---

.prettierrc
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/resources/META-INF/resources/frontend/confirmDialogConnector.js
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuConnector.js
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuTargetConnector.js
vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow/src/main/resources/META-INF/resources/frontend/cookieConsentConnector.js
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/resources/META-INF/resources/frontend/dialogConnector.js
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js
vaadin-iron-list-flow-parent/vaadin-iron-list-flow/src/main/resources/META-INF/resources/frontend/ironListConnector.js
vaadin-login-flow-parent/vaadin-login-flow/src/main/resources/META-INF/resources/frontend/loginOverlayConnector.js
vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/mapConnector.js
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/resources/META-INF/resources/frontend/menubarConnector.js
vaadin-messages-flow-parent/vaadin-messages-flow/src/main/resources/META-INF/resources/frontend/messageListConnector.js
vaadin-notification-flow-parent/vaadin-notification-flow/src/main/resources/META-INF/resources/frontend/notificationConnector.js
vaadin-select-flow-parent/vaadin-select-flow/src/main/resources/META-INF/resources/frontend/selectConnector.js
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js
vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/resources/META-INF/resources/frontend/virtualListConnector.js

This PR is a result of running Prettier on Flow JS connectors.
It is recommended to review the PR with the enabled `Hide whitespace` to exclude indent changes.

chore: format JS connectors with Prettier

---

vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuItemsArrayGenerator.java
vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarVisibilityPage.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarVisibilityIT.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerLocalizationIT.java

Run formatter to fix formatting in files that we missed due to broken CI validation. CI Validation has also been fixed now, by using Java 11 to run the formatter.

chore: run formatter

---

vaadin-avatar-flow-parent/vaadin-avatar-flow-demo/src/main/java/com/vaadin/flow/component/avatar/demo/AvatarGroupView.java
vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/Button.java
vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuCreatedOnAttachIT.java
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuItemsArrayGenerator.java
vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/ModalityDialogsPage.java
vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/ModalityDialogsPageIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTestPageIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/MapEventsIT.java
vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/MarkerFeatureIT.java
vaadin-map-flow-parent/vaadin-map-testbench/src/main/java/com/vaadin/flow/component/map/testbench/MapElement.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarVisibilityPage.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarVisibilityIT.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/Scroller.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/dataview/RadioButtonGroupListDataView.java

Run formatter to fix formatting in files that we missed due to broken CI validation. CI Validation has also been fixed now, by using Java 11 to run the formatter.

chore: run formatter (23.0)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
vaadin-grid-flow-parent/vaadin-grid-testbench/pom.xml
vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridElement.java
vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridTHTDElement.java

fix: make GridElement dispatch selection events (#3080) (CP: 23)

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java

chore: Remove private API related to v8 designer 
chore: remove commented v8 state annotations

chore: spreadsheet.java cleanup

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java

Cherry-picked https://github.com/vaadin/spreadsheet/pull/838

chore: fix typo

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/component/spreadsheet/client/js/SpreadsheetJsApi.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/component/spreadsheet/client/js/SpreadsheetServerRpcImpl.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SpreadsheetEventListener.java

Fixes #3094
- reduces final bundle size on about 10Kb
- fixes null errors when deserialising undefined numbers

chore: use proper JsInterop functions

---

vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/ChartSelectionEvent.java
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuManager.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridSelectionModel.java
vaadin-tabs-flow-parent/vaadin-tabs-testbench/src/main/java/com/vaadin/flow/component/tabs/testbench/TabsElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/PasswordFieldElement.java

Fixed a couple of typos in Javadoc comments.

chore: fix typos in javadoc comments

---

vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/ChartSelectionEvent.java
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuManager.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridSelectionModel.java
vaadin-tabs-flow-parent/vaadin-tabs-testbench/src/main/java/com/vaadin/flow/component/tabs/testbench/TabsElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/PasswordFieldElement.java

chore: fix typos in javadoc comments (#3138) (CP: 14.8) [skip ci]

---

vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckboxGroup.java
vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow-integration-tests/src/test/java/com/vaadin/flow/component/cookieconsent/StylingIT.java
vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow/src/main/java/com/vaadin/flow/component/cookieconsent/CookieConsent.java
vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/CompositeIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridViewSelectionPage.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java
vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/DetachAttachIT.java
vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/test/java/com/vaadin/flow/component/notification/tests/NotificationWithClassNamesIT.java
vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/main/java/com/vaadin/flow/component/virtuallist/tests/VirtualListViewPage.java

Using the same technique as in #2701

chore: cleanup unused imports

---

vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxDataViewIT.java

Fixed several mentions of `Radio Button` in the ITs of the `ListBox` component.

chore: fix copy-paste leftovers in ListBox ITs

---

vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/main/java/com/vaadin/flow/component/notification/tests/NotificationView.java
vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationTest.java

fix: close a notification on detach

---

vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/main/java/com/vaadin/flow/component/notification/tests/NotificationView.java
vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationTest.java

fix: close a notification on detach (#3154) (CP: 23.1)

---

vaadin-notification-flow-parent/vaadin-notification-flow-demo/src/main/java/com/vaadin/flow/component/notification/demo/NotificationView.java
vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationTest.java

fix: close a notification on detach (#3154)

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/ConditionalFormatter.java

Fixes https://sonarcloud.io/project/issues?resolved=false&types=BUG&pullRequest=3185&id=vaadin_flow-components&open=AYDL6MUU2DYGVBE0nvFb
Fixes https://sonarcloud.io/project/issues?resolved=false&types=BUG&pullRequest=3185&id=vaadin_flow-components&open=AYDL6MUU2DYGVBE0nvFa
Fixes https://sonarcloud.io/project/issues?resolved=false&types=BUG&pullRequest=3185&id=vaadin_flow-components&open=AYDL6MUU2DYGVBE0nvFZ
These issues cause SonarCloud validation to fail for other PRs.

chore: fix spreadsheet typecast errors

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxRenderManager.java

Extracts label generator and renderer logic from the ComboBox to allow re-use in the multi select combo box.
Part of https://github.com/vaadin/platform/issues/2961

refactor: extract label generator and renderer logic from ComboBox

---

vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListViewIT.java
vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/java/com/vaadin/flow/component/virtuallist/VirtualList.java

Fixes #3206
Depends on https://github.com/vaadin/web-components/pull/3907 and https://github.com/vaadin/web-components/pull/3908

refactor: remove empty placeholder height

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java

Part of https://github.com/vaadin/platform/issues/2961
Extracts the remaining common functionality from `ComboBox` to `ComboBoxBase`, to be shared with the upcoming `MultiSelectComboBox`. Changes:
- move common interfaces such as `HasLabel`, `HasTheme`, ...
- move constructor, connector initialization
- move custom value event registration logic
- move shared `setValue` logic
After this change all of the common functionality should be covered by `ComboBoxBase`, some small changes might show up when working on the actual `MultiSelectComboBox`. If you spot something that you think could be moved as well, please note it in the review.
- Refactor

refactor: extract common combo box functionality

---

vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/EditColumnConfigurator.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/test/java/com/vaadin/flow/component/gridpro/GridProEditColumnTest.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/test/java/com/vaadin/flow/component/gridpro/GridProTest.java

refactor: Replace AbstractField with HasValueAndElement

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/AbstractSpreadsheetIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/NavigationIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/NumberFormatIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/RemoveInsertRowIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ResizeIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/RowHeaderDoubleClickIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/RowShiftIT.java

Part of https://github.com/vaadin/components-team-tasks/issues/604
Migrate a few ITs from FW8 repo.
Note: 
- There are a few tests tagged with `@Ignore`. Most of them point to opened tickets and I decided to keep them, so it is easier to simply remove the `@Ignore` annotation while fixing these tickets.

test: migrate some ITs from FW8

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridView.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js

Manual cherry-pick of #3242 to `23.0` branch. I had to move the newly added IT to the old demo module 🙈 
- Cherry-pick

fix: do not trigger item click listener for prevented click (#3242) (CP: 23.0)

---

vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java

small typo fix in setDropLabelIcon Parameters section
- [X ] Feature
- [X ] I have read the contribution guide: https://vaadin.com/docs-beta/latest/guide/contributing/overview/
- [X ] I have added a description following the guideline.
- [X ] The issue is created in the corresponding repository and I have referenced it.
- [X ] I have added tests to ensure my change is effective and works as intended.
- [X ] New and existing tests are passing locally with my change.
- [ X] I have performed self-review and corrected misspellings.

small typo fix

---

pom.xml
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-testbench/src/main/java/com/vaadin/flow/component/spreadsheet/testbench/SpreadsheetElement.java

* chore: upgrade TB to 8.0.1
* chore: fix compilation

chore: upgrade TB to 8.0.1 (#3264)

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/UndoRedoIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/command/CellValueCommand.java

Fixes #3232 
Also migrates the related ITs from https://github.com/vaadin/spreadsheet/blob/flow-port/legacy/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/UndoRedoTest.java

fix: change cell remove order in cell value command

---

vaadin-iron-list-flow-parent/vaadin-iron-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/ironlist/tests/IronListIT.java

Cherry-pick of https://github.com/vaadin/flow-components/pull/2957

test: attempt to make IronListIT more reliable (CP: 23.0)

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/AbstractSpreadsheetIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/SheetTabSheetIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java

fix: update initialSheetSelection on reload

---

vaadin-accordion-flow-parent/vaadin-accordion-flow-integration-tests/src/test/java/com/vaadin/flow/component/accordion/tests/BasicIT.java
vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/main/java/com/vaadin/flow/component/crud/tests/CustomSearchView.java
vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/main/java/com/vaadin/flow/component/crud/tests/PersonCrudDataProvider.java

Fixes the 4 potential bugs reported by Sonarcloud.

test: fix potential bugs reported by sonar

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridSingleSelectionUpdateAndDeselectPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionUpdateAndDeselectIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java

fix: do not refresh datacommunicator with previously selected item on select

---

pom.xml

chore: upgrade to TB 8.1.0.alpha7

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java

The test was ignored by #551 but not unskipped back after the web component issue was fixed. Let's unskip it.
- Test

test: re-enable test for sorting hidden grid

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridViewSortingPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewSortingIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridSortingTest.java

feat: add setMultiSort override to provide priority

---

vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/MapView.java

chore: remove api key from map sampler (CP: 23.1)

---

vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow/src/main/resources/META-INF/resources/frontend/lumo-includes.ts

fix: only include needed Lumo modules

---

vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/Avatar.java
vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/AvatarGroup.java
vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/GeneratedVaadinButton.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/RefreshEmptyLazyDataProviderIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxDataViewTest.java
vaadin-custom-field-flow-parent/vaadin-custom-field-flow/src/main/java/com/vaadin/flow/component/customfield/CustomField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/binder/BigDecimalFieldValidationTest.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/binder/EmailFieldValidationTest.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/binder/IntegerFieldValidationTest.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/binder/NumberFieldValidationTest.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/binder/PasswordFieldValidationTest.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/binder/TextAreaValidationTest.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/binder/TextFieldValidationTest.java

Removed some no longer used imports and fixed few other warnings.

chore: remove unused imports, fix some Sonar warnings

---

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarPageIT.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-testbench/src/main/java/com/vaadin/flow/component/menubar/testbench/MenuBarElement.java

feat: Add API to get sub menus in MenuBarElement

---

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/ValueChangeModeIT.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/BigDecimalFieldElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextFieldElement.java

Manual cherry-pick of #3501 to `23.1` branch (conflict was caused by import removed in #3490)
- Cherry-pick

fix: delegate sendKeys calls to the input element (#3501) (CP: 23.1)

---

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/ValueChangeModeIT.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/BigDecimalFieldElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextFieldElement.java

Manual cherry-pick of #3501 to `23.0` branch (conflict was caused by import removed in #3490)
- Cherry-pick

fix: delegate sendKeys calls to the input element (#3501) (CP: 23.0)

---

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/ValueChangeModeIT.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/BigDecimalFieldElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextFieldElement.java

Manual cherry-pick of #3501 to `22.0` branch (conflict was caused by import removed in #3490)
- Cherry-pick

fix: delegate sendKeys calls to the input element (#3501) (CP: 22.0)

---

vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/StepsUtil.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
vaadin-time-picker-flow-parent/vaadin-time-picker-testbench/src/main/java/com/vaadin/flow/component/timepicker/testbench/TimePickerElement.java

doc: Fix javadoc warnings for vaadin-time-picker-flow

---

vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupDisabledItemIT.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupIT.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupListDataViewIT.java
vaadin-checkbox-flow-parent/vaadin-checkbox-testbench/src/main/java/com/vaadin/flow/component/checkbox/testbench/CheckboxGroupElement.java

Fixes #3153 
This TestBenchElement has similar API to RadioButtonGroupElement and aligned with MultiSelectComboBoxElement for multiselection part.

feat: Add CheckboxGroupElement

---

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelSelectedItemsTest.java

Based on https://github.com/vaadin/flow-components/pull/3438.
WIP (documentation updates)

feat: introduce getSelectedItemIds

---

vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/validation/AbstractValidationIT.java
vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/validation/AbstractValidationPage.java

This PR adds abstract classes that are supposed to be used when testing the new validation behavior for different field components.
Part of https://github.com/vaadin/platform/issues/3066

feat: add abstract validation test classes

---

vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java
vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheetVariant.java
vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/resources/META-INF/resources/frontend/tabsheet/src/vaadin-tabsheet.js
vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetTest.java

Add `TabSheetVariant` and make `TabSheet` implement `HasThemeVariant<TabSheetVariant>`
- Feature

feat: add TabSheetVariant

---

vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/UploadTestsI18N.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/UploadI18N.java

This PR allows configuring i18n translations for the file action buttons of the Upload component.
Fixes https://github.com/vaadin/flow-components/issues/2065

feat: add i18n translations for the file action buttons

---

vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/Assets.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Coordinate.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Extent.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/style/Icon.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/events/FeatureEventDetails.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/serialization/MapSerializer.java
vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/MapSerializableTest.java

Fixes several map classes which can end up in the UI / session to be serializable.
Fixes #3672
- Bugfix

fix: make map classes serializable

---

vaadin-tabs-flow-parent/vaadin-tabs-flow-integration-tests/src/main/java/com/vaadin/flow/component/tabs/tests/TabSheetPage.java
vaadin-tabs-flow-parent/vaadin-tabs-flow-integration-tests/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetIT.java
vaadin-tabs-flow-parent/vaadin-tabs-testbench/src/main/java/com/vaadin/flow/component/tabs/testbench/TabSheetElement.java

Add `TabSheetElement` and related ITs
- Feature

feat: add TabSheetElement and ITs

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ClearValuePage.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java

Reorganized ComboBox ClearValue integration tests for more readability, also made naming more consistent.
A preparation for https://github.com/vaadin/flow-components/pull/3712

test: reorganize ComboBox ClearValue ITs

---

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java
vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/TooltipTest.java

Aligned `Tooltip` API with the change in the web component: https://github.com/vaadin/web-components/pull/4567
- Refactor

refactor: align delay properties with web component

---

vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/Assets.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Coordinate.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Extent.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/style/Icon.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/events/FeatureEventDetails.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/serialization/MapSerializer.java
vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/MapSerializableTest.java

Fixes several map classes which can end up in the UI / session to be serializable.
Fixes #3672
Co-authored-by: Serhii Kulykov <iamkulykov@gmail.com>
(cherry picked from commit 3fd6cd3d87708ded5aef7468fc2ca77835e573bb)

fix: make map classes serializable (#3689) (CP: 23.1)

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ClearValuePage.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java

This PR cherry-picks the following commits to `23.2`:
- https://github.com/vaadin/flow-components/pull/3716
- https://github.com/vaadin/flow-components/pull/3712
Fixes https://github.com/vaadin/flow-components/issues/1090

fix: force refreshValue to update input value on the client-side (CP: 23.2) (#3712)

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ClearValuePage.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

This PR cherry-picks the following commits to `23.1`:
- https://github.com/vaadin/flow-components/pull/3716
- https://github.com/vaadin/flow-components/pull/3712
Fixes https://github.com/vaadin/flow-components/issues/1090

fix: force refreshValue to update input value on the client-side (CP: 23.1) (#3712)

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ClearValuePage.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

This PR cherry-picks the following commits to `14.8`:
- https://github.com/vaadin/flow-components/pull/3716
- https://github.com/vaadin/flow-components/pull/3712
Fixes https://github.com/vaadin/flow-components/issues/1090

fix: force refreshValue to update input value on the client-side (CP: 14.8) (#3712)

---

vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java
vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetTest.java

Apply the following changes (as agreed in the API review):
- add tabsheet index-based operation API as specified in the [tabsheet API summary](https://github.com/orgs/vaadin/discussions/3175#discussioncomment-3624242)
- Feature

feat: tabsheet index-based operation API

---

vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java

When an item updater in GridPro modifies a field that is used in generating that item's data provider ID, that can lead to issues with the grid not refreshing individual items correctly.
This change adds a warning when an item updater modifies the item's data provider ID, which provides hints for the probable cause and how to fix it.
Closes https://github.com/vaadin/flow-components/issues/1680
-  Feature

feat: warn about item id changes after editing field

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewSortingIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js

Fixes the sort indicator order when sorting on server-side with append multi-sort priority.
Fixes #3779
- Bugfix

fix: sort indicator order for append multi-sort priority

---

vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/main/java/com/vaadin/flow/component/notification/tests/PreserveOnRefreshPage.java
vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/test/java/com/vaadin/flow/component/notification/tests/PreserveOnRefreshIT.java
vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationTest.java

Cherry-pick of #3784 
(cherry picked from commit 1226ab376cc6f3aa5738519302aa71059f9cf471)

fix: keep opened state with preserve on refresh (#3784) (CP: 23.1)

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/FilterTableTest.java

Add unit tests for [SpreadsheetFilterTable](https://github.com/vaadin/flow-components/blob/master/vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SpreadsheetFilterTable.java)

test: add unit tests for SpreadsheetFilterTable

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/CustomDataFormatterTest.java

Add tests for custom data formatting, accepting four formats (positive number, negative number, zero, and text).

test: add tests for custom data format

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/pom.xml

pick the license-checker update

chore: update license-checker to 1.10.1

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/ConditionalFormatterTest.java

Add some JUnit tests for conditional formatting to check if cells matching formulas receive the styles.

test: add tests for conditional formatting

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTooltipIT.java

Cherry-pick of https://github.com/vaadin/flow-components/pull/3940

test: adapt grid tooltip ITs to WC changes

---

vaadin-map-flow-parent/LICENSE

Add missing license file to map component module.

chore: add licence file to map module

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet.js

`vaadin-spreadsheet.js`
- Cleaned up dev-time comments
- Ran Prettier
`Spreadsheet.java`
- Corrected the Javadoc not to claim it's an add-on

chore: cleanup and format vaadin-spreadsheet

---

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/lit-renderer.ts

Fixes https://github.com/vaadin/flow-components/issues/3991

fix: address lit-renderer TypeScript errors

---

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridSortingTest.java

feat: add onShiftClickOnly to multiSort

---

pom.xml

chore: bump testbench to 9.0.0.alpha4

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/CellShiftValuesUndoRedoIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/CopyPasteCellLayoutSizeFullIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/CopyPasteCellsIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/SheetTabSheetIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/UndoRedoIT.java

Some ITs started failing on CI. Ignore the tests to unblock working on the repo until the issue is resolved.

test: ignore tests failing on CI

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTooltipIT.java

Disable flaky grid tooltip ITs to unblock releases.

test: disable flaky grid tooltip ITs

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/FormulasTest.java

Disable flaky spreadsheet unit test to unblock releases.

test: ignore flaky spreadsheet unit test

---

vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/frontend/lit-renderer-test-component.js
vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/main/java/com/vaadin/flow/data/renderer/tests/LitRendererTestComponent.java
vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/test/java/com/vaadin/flow/data/renderer/tests/LitRendererIT.java

Manual cherry-pick of https://github.com/vaadin/flow-components/pull/4127

test: use JS for lit-renderer-test-component (#4127)

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComboBoxDemoPage.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComboBoxView.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/AddingColumnsPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/BeanGridPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ColumnPathPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridItemRefreshPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridTestPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridViewItemDetailsPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridViewUsingTemplatesPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridWithTemplatePage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/LitRendererEventHandlerPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/SelectDuringDataProviderChangePage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/AddingColumnsIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ColumnPathIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridItemRefreshPageIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTestPageIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewItemDetailsIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewUsingTemplatesIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/LitRendererEventHandlerIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridColumnTest.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridSortingTest.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java
vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/main/java/com/vaadin/flow/component/virtuallist/tests/VirtualListPage.java
vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/main/java/com/vaadin/flow/component/virtuallist/tests/VirtualListViewPage.java
vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListIT.java

Replace `TemplateRenderer` with `LitRenderer` in tests 
Part of https://github.com/vaadin/flow-components/issues/4059
- Test refactoring

test: replace TemplateRenderer with LitRenderer in tests

---

vaadin-upload-flow-parent/vaadin-upload-flow/pom.xml
vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/UploadSlotsTest.java

Another attempt to fix the failure reported at https://github.com/vaadin/flow-components/pull/4218#issuecomment-1328034131.
- Tests

test: mock VaadinSessison in Upload slots tests

---

vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/UploadTest.java

fix: Delay setting attribute until attached

---

scripts/updateSources.js
vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/BasicChartIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DynamicEditorKBNavigationIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridDetailsRowIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridPageSizeIT.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/tests/BasicIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/IntegerFieldPageIT.java
vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListIT.java

The script used to update sources when merging ITs contains a lot of outdated logic.
Removed some of it to keep it smaller. There might be still more things to remove.

chore: remove outdated updateSources script parts

---

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/pom.xml

Add Lumo theme for easier visual debugging of invalid state etc.

chore: add Lumo theme to text field ITs

---

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/validation/DatePickerValidationBasicPage.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/validation/DateTimePickerValidationBasicPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextFieldValidationBasicPage.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/validation/TimePickerValidationBasicPage.java

Fixes detach buttons in field validation tests to actually remove the component from its container.

refactor: fix detach field test logic

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet-styles.js

Set Spreadsheet host background white
Fixes https://github.com/vaadin/flow-components/issues/4265
Bugfix

fix: set spreadsheet host background white

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetConnector.java

Remove unnecessary spreadsheet client logging
Fixes https://github.com/vaadin/flow-components/issues/4223

chore: remove unnecessary spreadsheet client logging

---

pom.xml

same change as https://github.com/vaadin/flow-components/pull/4281

chore: update jetty to 10 (CP: 23.2)

---

pom.xml

same change as https://github.com/vaadin/flow-components/pull/4281

chore: update jetty to 10 (CP: 23.1)

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/HyperlinkIT.java

Fixes a flaky spreadsheet test to wait for a cell to be visible after scrolling.

chore: fix spreadsheet test to wait for cell to be visible (23.2)

---

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/validation/BasicValidationIT.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BasicValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBasicValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBasicValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBasicValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBasicValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextFieldBasicValidationIT.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/BasicValidationIT.java

This PR aligns the structure of validation tests and adds some missing tests.
A follow-up to https://github.com/vaadin/flow-components/pull/4336

test: align the structure of validation tests

---

vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/Avatar.java
vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/AvatarGroup.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java

Removed overrides that were added to v23 for backwards compatibility.

refactor!: remove overrides for HasThemeVariants methods

---

vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java
vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridOnClientAndSlot.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldValidationBasicPage.java

Removed some imports that are unused after recent changes related to generated classes, renderer, and validation.
- Refactor

refactor: remove unused imports after recent changes

---

vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java
vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/DetailsVariant.java

Changed `Details` to use `HasThemeVariant` and updated the enum accordingly.
- Refactor

refactor: update Details to implement HasThemeVariant

---

vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/InternalFieldBase.java

Follow-up to #4377. Changed constructors as suggested in https://github.com/vaadin/flow-components/pull/4377#discussion_r1053072892
- Refactor

refactor: make InternalFieldBase constructors package private

---

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/EmailFieldPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/EmailFieldPageIT.java

The PR removes EmailField integration tests that duplicate the modern validation tests.

test: remove duplicate integration tests

---

vaadin-app-layout-flow-parent/vaadin-app-layout-flow/pom.xml
vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/AppLayout.java
vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/Button.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/pom.xml
vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
vaadin-crud-flow-parent/vaadin-crud-flow/pom.xml
vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java
vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/SlotUtils.java
vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java
vaadin-form-layout-flow-parent/vaadin-form-layout-flow/pom.xml
vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
vaadin-grid-flow-parent/vaadin-grid-flow/pom.xml
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-login-flow-parent/vaadin-login-flow/pom.xml
vaadin-login-flow-parent/vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/pom.xml
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButton.java
vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/HasPrefixAndSuffix.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/InternalFieldBase.java
vaadin-upload-flow-parent/vaadin-upload-flow/pom.xml
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java

Extracted `addToSlot` method as suggested by @knoobie here: https://github.com/vaadin/flow-components/pull/4377#discussion_r1050036193
- Refactor

refactor: extract addToSlot helper method to SlotUtils

---

vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java

Updated `TabSheet` to use new interfaces added in #4458
- Refactor

refactor: use HasPrefix and HasSuffix in TabSheet

---

vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/UploadI18N.java

Fixes #4473
Related to #4197
Similar to #4423
- Refactor

refactor: remove no longer used string from UploadI18N

---

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java

Based on #4458
Related to #4459
- Feature

feat: add HasPrefix interface to TimePicker

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java

Based on #4458
Fixes #1594
- Breaking change / Feature

feat!: add HasPrefix to ComboBox, remove addToPrefix

---

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java

Based on #4458
Related to #4459
- Feature

feat: add HasPrefix interface to DatePicker

---

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasOverlayClassName.java
vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/HasOverlayClassNameTest.java

Part of #3593
Based on the web component mixin: https://github.com/vaadin/web-components/pull/5207
- Feature

feat: add HasOverlayClassName shared interface

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java

feat: add HasOverlayClassName interface to ComboBox

---

vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java

feat: add HasOverlayClassName interface to Select

---

vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java

feat: add HasOverlayClassName interface to TimePicker

---

vaadin-context-menu-flow-parent/vaadin-context-menu-flow/pom.xml
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java

feat: add HasOverlayClassName interface to ContextMenu

---

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarTest.java

feat: add HasOverlayClassName interface to MenuBar

---

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBarVariant.java

Updated `MenuBar` to implement `HasThemeVariant` and changed `MenuBarVariant` enum accordingly.
- Refactor

refactor: update MenuBar to implement HasThemeVariant

---

vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/pom.xml
vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/Scroller.java
vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/ScrollerVariant.java

Fixes #4527
Based on https://github.com/vaadin/web-components/pull/5144
- Feature

feat: add ScrollerVariant and overflow-indicators variant

---

vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/main/java/com/vaadin/flow/component/richtexteditor/tests/MainView.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/main/java/com/vaadin/flow/component/richtexteditor/tests/RichTextEditorI18nPage.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/main/java/com/vaadin/flow/component/richtexteditor/tests/RichTextEditorTemplatePage.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/tests/BasicUseIT.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/tests/RichTextEditorI18nIT.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/tests/RichTextEditorTemplateIT.java

Extracts RTE I18N and template ITs into separate files.
- Refactoring

refactor: extract I18N and template ITs

---

PULL_REQUEST_TEMPLATE.md

Add new checkbox to the PR template.

chore: add new checkbox to the PR template

---

vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java

test: update resize listener IT to round dimensions

---

vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerTest.java

feat: add HasOverlayClassName interface to DateTimePicker

---

vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/tests/MainView.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/tests/Person.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/tests/BasicIT.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js

fix: select custom editor text after value is set (#4555)

---

vaadin-map-flow-parent/vaadin-map-flow/pom.xml
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/MapBase.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/MapVariant.java

Updated `Map` to implement `HasThemeVariant` and changed the `MapVariant` enum accordingly.
- Refactor

refactor: update Map to implement HasThemeVariant

---

vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/ListBoxBase.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LocalDateRenderer.java
vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java

Make various deprecated methods private or remove them where possible

refactor!: make various deprecated API private or remove where possible

---

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java

Cherry-pick of: https://github.com/vaadin/flow-components/pull/2526
Fixes: https://github.com/vaadin/flow-components/issues/1058

fix: don't disable a readonly radio group (#2526) (CP: 14.10)

---

vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/Button.java
vaadin-button-flow-parent/vaadin-button-flow/src/test/java/com/vaadin/flow/component/button/tests/ButtonTest.java

fix: ignore tooltips when determining icon theme

---

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java

Manual cherry-pick of #4638 to 23.3 branch.
- Cherry-pick

refactor: remove static element to tooltip map (#4638)

---

vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/UploadTest.java

Fixes https://github.com/vaadin/flow-components/issues/4646
Bugfix

fix: make isAutoUpload return correct boolean value

---

vaadin-details-flow-parent/vaadin-details-flow-integration-tests/src/main/java/com/vaadin/flow/component/details/tests/DetailsEventsPage.java
vaadin-details-flow-parent/vaadin-details-flow-integration-tests/src/main/java/com/vaadin/flow/component/details/tests/Home.java
vaadin-details-flow-parent/vaadin-details-flow-integration-tests/src/test/java/com/vaadin/flow/component/details/tests/BasicIT.java
vaadin-details-flow-parent/vaadin-details-flow-integration-tests/src/test/java/com/vaadin/flow/component/details/tests/DetailsEventsIT.java
vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java

fix: use property change listener for opened change event (#4665) (CP: 23.3)

---

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerLocalePage.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocaleIT.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js

fix: do not modify reference date in connector (#4682) (CP: 14.10)

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/FormulasTest.java

Test ignored since it always passes locally but randomly fails on CI
Tests

test: ignore a flaky spreadsheet test

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/FreezePaneLocaleIT.java

A cherry-pick of the following PR to `23.3`:
- #4745

chore: ignore flaky spreadsheet test (#4745) (CP: 23.3)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-no-connector.test.ts
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-tree.test.ts
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/shared.ts

Add some more grid connector tests
Tests

test: add more gridConnector tests

---

vaadin-board-flow-parent/vaadin-board-flow/src/main/java/com/vaadin/flow/component/board/Board.java
vaadin-board-flow-parent/vaadin-board-flow/src/main/java/com/vaadin/flow/component/board/Row.java
vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/resources/META-INF/resources/frontend/tooltip.ts
vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/Icon.java
vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/Scroller.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/EmailFieldPage.java
vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/java/com/vaadin/flow/component/virtuallist/VirtualList.java

fix: Use non themed imports (#4817) (CP: 24)

---

vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogCloseActionListenerTest.java
vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java

Back-ports [4850](https://github.com/vaadin/flow-components/pull/4850) to v23.3.

test: back-port addDialogCloseActionListener related test refactoring (#4850) (CP: 23.3)

---

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/IntegerFieldClearValuePage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/NumberFieldClearValuePage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/IntegerFieldClearValueIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldClearValueIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java

A manual cherry-pick of #4815 to `23.3`.

fix: do not attempt to clear bad input when value is present (#4815) (CP: 23.3)

---

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/ColumnRendering.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridColumnRenderingTest.java

Add Flow Grid API for the [column rendering](https://github.com/vaadin/web-components/pull/5124) feature 
Part of https://github.com/vaadin/platform/issues/3909
Feature

feat: grid lazy column rendering mode

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxBaseTest.java

Make `ComboBoxBase` implement `HasAriaLabel` interface.
Part of #2946 
Fixes #4713

feat: make ComboBoxBase implement HasAriaLabel

---

.gitattributes
pom.xml

Cherrypick to 23.3 
There was a conflict in pom.xml

chore: stop enforcing LF line endings by formatter (#4824) (CP: 23.3)

---

vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/test/flow-component-renderer.test.ts
vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/web-test-runner.config.mjs
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-directive.js

Fixes https://github.com/vaadin/flow-components/issues/4919
Bugfix

fix: wait for components in flow-component-directive

---

vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java
vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java
vaadin-details-flow-parent/vaadin-details-flow/src/test/java/com/vaadin/flow/component/details/DetailsTest.java
vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationTest.java
vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java

fix: allow unregistering event handlers through event (#4909) (CP: 24.0)

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/README.md
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/patches/gwt-sdm-debugging.patch

Adds GWT SDM debugging instructions for the Spreadsheet client module, and a Git .patch for adding the necessary code changes that enable debugging.

chore: add spreadsheet client debugging instructions

---

vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/dataview/CheckboxGroupDataViewTest.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxDataViewTest.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridDataViewTest.java
vaadin-list-box-flow-parent/vaadin-list-box-flow/src/test/java/com/vaadin/flow/component/listbox/test/dataview/ListBoxDataViewTest.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/dataview/RadioButtonGroupDataViewTest.java
vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/data/SelectDataViewTest.java

Fixes compilation errors in custom data provider implementations that are the result of introducing new data provider API in Flow: https://github.com/vaadin/flow/pull/16650

chore: fix compilation failures for new data provider API

---

vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java
vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetTest.java

Add `TabSheet::getComponent(Tab)`and `TabSheet::getTab(Component` to improve DX.
Fixes #4099

feat: add TabSheet::getComponent(Tab) and TabSheet::getTab(Component)

---

pom.xml

chore: update TB version to 9.0.4 (#4995) (CP: 24.0)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeComponentColumnsPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridComponentHierarchyColumnPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridComponentRendererPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandAllPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridHugeTreeNavigationPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridHugeTreePage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridItemDetailsRendererPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridPageSizePage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridStringDataBuilder.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridStringDataGenerator.java

This PR extracts `TreeGrid` test data generation logic to a new class as suggested in a PR [comment](https://github.com/vaadin/flow-components/pull/4934#discussion_r1176570889).
Related to #3505

test: extract tree grid test data generator

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/pom.xml

Bumps `framework.version` from 8.20.0 to 8.20.1.
Updates `vaadin-client` from 8.20.0 to 8.20.1
- [Release notes](https://github.com/vaadin/framework/releases)
- [Changelog](https://github.com/vaadin/framework/blob/master/CHANGELOG-VAADIN8.md)
- [Commits](https://github.com/vaadin/framework/commits)
Updates `vaadin-client-compiler` from 8.20.0 to 8.20.1
- [Release notes](https://github.com/vaadin/framework/releases)
- [Changelog](https://github.com/vaadin/framework/blob/master/CHANGELOG-VAADIN8.md)
- [Commits](https://github.com/vaadin/framework/commits)
---
updated-dependencies:
- dependency-name: com.vaadin:vaadin-client dependency-type: direct:production update-type: version-update:semver-patch
- dependency-name: com.vaadin:vaadin-client-compiler dependency-type: direct:production …

chore: bump framework.version from 8.20.0 to 8.20.1 (#5008) (CP: 23.3)

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/pom.xml

Bumps `framework.version` from 8.20.0 to 8.20.1.
Updates `vaadin-client` from 8.20.0 to 8.20.1
- [Release notes](https://github.com/vaadin/framework/releases)
- [Changelog](https://github.com/vaadin/framework/blob/master/CHANGELOG-VAADIN8.md)
- [Commits](https://github.com/vaadin/framework/commits)
Updates `vaadin-client-compiler` from 8.20.0 to 8.20.1
- [Release notes](https://github.com/vaadin/framework/releases)
- [Changelog](https://github.com/vaadin/framework/blob/master/CHANGELOG-VAADIN8.md)
- [Commits](https://github.com/vaadin/framework/commits)
---
updated-dependencies:
- dependency-name: com.vaadin:vaadin-client dependency-type: direct:production update-type: version-update:semver-patch
- dependency-name: com.vaadin:vaadin-client-compiler dependency-type: direct:production …

chore: bump framework.version from 8.20.0 to 8.20.1 (#5008) (CP: 24.0)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js

Cherry-picks the following PR to `23.3`:
- https://github.com/vaadin/flow-components/pull/5018
Fixes https://github.com/vaadin/flow-components/issues/4967

fix: prevent adding duplicate items to selectedItems on selection (#5018) (CP: 23.3)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js

Cherry-picks the following PR to `24.0`:
- https://github.com/vaadin/flow-components/pull/5018
Fixes https://github.com/vaadin/flow-components/issues/4967

fix: prevent adding duplicate items to selectedItems on selection (#5018) (CP: 24.0)

---

pom.xml

This update is needed to accept this PR in flow without having a dependency conflict later.
- https://github.com/vaadin/flow/pull/16734

chore: bump javaparser-core to 3.25.3

---

README.md

Add instructions on how to debug wtr tests
Documentation

docs: add instructions on how to debug wtr tests

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-cell-focus.test.ts
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-generators.test.ts
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-item-click.test.ts
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-tree.test.ts
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/shared.ts

Add more tests for grid connector
- cell focus event
- (class name) generators
- item-click event
Tests

test: add more grid connector tests

---

vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavIT.java
vaadin-side-nav-flow-parent/vaadin-side-nav-testbench/src/main/java/com/vaadin/flow/component/sidenav/testbench/SideNavElement.java
vaadin-side-nav-flow-parent/vaadin-side-nav-testbench/src/main/java/com/vaadin/flow/component/sidenav/testbench/SideNavItemElement.java

Cherry-pick of [#5076](https://github.com/vaadin/flow-components/pull/5076).

refactor: improve testbench api (CP: 24.1)

---

vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/main/java/com/vaadin/flow/component/sidenav/tests/SideNavPage.java

This PR removes unused and untested code to make the page more readable.

test: cleanup side nav test page

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridScrollToPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridScrollToIT.java

Follow-up PR after https://github.com/vaadin/flow-components/pull/5120 was merged to add a test for the use case described in #5045 to prevent re-introducing this issue in the future.

test: check tree grid expand with small page size

---

vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow/src/main/java/com/vaadin/flow/theme/lumo/LumoUtility.java

This reverts #3383
Fixes https://github.com/vaadin/flow-components/issues/5106

Revert "feat: automatically include utility styles when using LumoUtility class (#3383)"

---

vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow/src/main/java/com/vaadin/flow/theme/lumo/LumoUtility.java

Revert "feat: automatically include utility styles when using LumoUtility class (#3383)" (#5188) (CP: 24.1)

---

pom.xml

Updated the Flow snapshot version to `2.10-SNAPSHOT`.

chore: update Flow snapshot version to 2.10-SNAPSHOT

---

vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/main/java/com/vaadin/flow/component/sidenav/tests/SideNavForwardingSourceView.java
vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/main/java/com/vaadin/flow/component/sidenav/tests/SideNavPage.java
vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavForwardingIT.java
vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavIT.java

This PR adds forwarding and navigation tests for side nav. The issue was fixed in a Flow [PR](https://github.com/vaadin/flow/pull/17146).
Closes [#5825](https://github.com/vaadin/web-components/issues/5825)

test: add side nav forwarding and navigation tests

---

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/ClientValidationUtil.java
vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasClientValidation.java
vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/validation/AbstractBasicValidationTest.java
vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/validation/AbstractValidationIT.java
vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/validation/AbstractValidationPage.java

This PR adds shared files. Copies them from latest V24 structure

feat: add shared and abstract classes from latest (CP: 14)

---

vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavItemTest.java

This PR refactors the `SideNavItem` unit tests by:
- grouping them under several categories
- extracting common functionality
- merging similar tests
- removing duplicates
- updating some of the test names
- introducing a test regarding constructors to prevent regression
Follow-up to a [comment](https://github.com/vaadin/flow-components/pull/5150#discussion_r1257893098) in path alias feature [PR](https://github.com/vaadin/flow-components/pull/5150).

test: group and refactor side nav item unit tests

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DragAndDropGridPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DragAndDropGridIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js

Manual cherry-pick from #5250.

fix: check for null item in drag and drop filters (#5250) (CP: 23.3)

---

scripts/templates/pom-bower-mode.xml
scripts/templates/pom-integration-tests.xml
vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/pom-bower-mode.xml
vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/pom.xml
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/pom-bower-mode.xml
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/pom.xml
vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/pom-bower-mode.xml
vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/pom.xml
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/pom-bower-mode.xml
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/pom.xml
vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/pom-bower-mode.xml
vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/pom.xml
vaadin-select-flow-parent/vaadin-select-flow-integration-tests/pom-bower-mode.xml
vaadin-select-flow-parent/vaadin-select-flow-integration-tests/pom.xml
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/pom-bower-mode.xml
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/pom.xml
vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/pom-bower-mode.xml
vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/pom.xml

Enables the validation feature flag for integration tests of the components involved in the backport.
Part of #5144

test: enable validation feature flag for ITs (CP: 14)

---

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasAllowedCharPattern.java

Attempt to clarify how allowed char pattern works.
Closes https://github.com/vaadin/flow-components/issues/4307

docs: clarify allowed char pattern JavaDoc

---

vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java

- Missing part of https://github.com/vaadin/flow-components/pull/5260

fix: add missing feature flag check (CP: 14)

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/pom.xml
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/pom.xml
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

- https://github.com/vaadin/flow-components/pull/4323

feat: integrate client-side validation into ComboBox (CP: 14)

---

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js

The `ItemCache.prototype.getCacheAndIndexByKey` and `grid.$connector.getCacheByKey` do not actually return the cache associated with that key, but its parent cache, which is rather confusing. In all usages, the code then extracts the child cache by key / index. 
We can simplify that by just using a single method that actually returns the cache for the key. That also makes `getCacheAndIndexByKey` obsolete, as the index from the result was only ever used to access the child cache again.

refactor: simplify getting cache by key

---

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextFieldBasicValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextFieldValidationSupport.java

- https://github.com/vaadin/flow-components/pull/4263

fix!: do not check minlength and pattern when value is an empty string

---

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BinderValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/TextAreaPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBasicValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBinderValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BinderValidationPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/TextAreaPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBasicValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBinderValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java

- https://github.com/vaadin/flow-components/pull/4258

feat: integrate client-side validation into TextArea (CP: 14)

---

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BinderValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/PasswordFieldPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBasicValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBinderValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BinderValidationPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/PasswordFieldPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBasicValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBinderValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java

- https://github.com/vaadin/flow-components/pull/4249

feat: integrate client-side validation into PasswordField (CP: 14)

---

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BinderValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBasicValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBinderValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BinderValidationPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBasicValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBinderValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java

- https://github.com/vaadin/flow-components/pull/4264

 feat: integrate client-side validation into EmailField (CP: 14)

---

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarTooltipPage.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarTooltipIT.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java

chore: expose MenuBar setTooltipText (#5294)

---

vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/BigDecimalFieldElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/EmailFieldElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/IntegerFieldElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/NumberFieldElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/PasswordFieldElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextAreaElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextFieldElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextFieldElementHelper.java

Part of  
- https://github.com/vaadin/flow-components/pull/5299

fix: update setValue to operate on inputElement (CP:14)

---

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/ValidationUtil.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BinderValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/IntegerFieldClearValuePage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/NumberFieldClearValuePage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/NumberFieldPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBasicValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBinderValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BinderValidationPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/IntegerFieldClearValueIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldClearValueIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBasicValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBinderValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java

- https://github.com/vaadin/flow-components/pull/4272
- https://github.com/vaadin/flow-components/pull/4438

feat: integrate client-side validation into NumberField (CP: 14)

---

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldValidationBasicPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldValidationBinderPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBasicValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBinderValidationIT.java

- https://github.com/vaadin/flow-components/pull/4294

feat: integrate client-side validation into IntegerField (CP: 14)

---

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/ItemClickEvent.java

docs: state that getColumn() returns null for multi-selection column

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridDragSelectPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridDragSelectIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridMultiSelectionModel.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridSelectionColumn.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java

Add support for selecting and deselecting rows by dragging the mouse cursor over Grid's selection column.
Note: Needs https://github.com/vaadin/web-components/pull/6098 to be merged before.
Fixes #2422

feat: add rows selection by dragging support to Grid

---

vaadin-board-flow-parent/LICENSE
vaadin-charts-flow-parent/LICENSE
vaadin-cookie-consent-flow-parent/LICENSE
vaadin-crud-flow-parent/LICENSE
vaadin-grid-pro-flow-parent/LICENSE
vaadin-rich-text-editor-flow-parent/LICENSE

Updated the LICENSE file to the latest version. 
This change applies to 24.2 (main branch) and possible v23 minors.
- License

chore: update LICENSE file for Pro components

---

vaadin-map-flow-parent/LICENSE
vaadin-spreadsheet-flow-parent/LICENSE

Follow-up to #5357
I missed to update these packages in the first PR, so here's another one.
- License

chore: update LICENSE file for Map and Spreadsheet

---

vaadin-board-flow-parent/LICENSE
vaadin-charts-flow-parent/LICENSE
vaadin-confirm-dialog-flow-parent/LICENSE
vaadin-cookie-consent-flow-parent/LICENSE
vaadin-crud-flow-parent/LICENSE
vaadin-grid-pro-flow-parent/LICENSE
vaadin-rich-text-editor-flow-parent/LICENSE

Same as #5357 but for `14.11` branch (the one which will have a new minor).
This replaces old license with the updated Vaadin Commercial License and Service Terms.
- License

chore: update LICENSE file for Pro components (v14.11)

---

pom.xml

Update testbench version to 2.8.4

chore: Update testbench to 2.8.4

---

vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/main/resources/vaadin-featureflags.properties

Follow up to another feature flag removal [PR](https://github.com/vaadin/flow-components/pull/5195). This one completes the Flow component part by removing the feature flag properties file.
Partially fixes #[6020](https://github.com/vaadin/web-components/issues/6020).

chore: remove side nav feature flag prop file

---

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerViewDemoPage.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java

fire the OpenedChangeEvent for the opened-changed dom event

---

vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationTest.java

fix: add opened property change listener for all Notification constructors

---

vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/SvgIcon.java
vaadin-icons-flow-parent/vaadin-icons-flow/src/test/java/com/vaadin/flow/component/icon/tests/SvgIconTest.java

Add the symbol related API to `SvgIcon` component.

feat: add symbol API to SvgIcon class

---

README.md
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridScrollToPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridScrollToIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector.test.ts
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/shared.ts
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridScrollTest.java

Cherry-pick https://github.com/vaadin/flow-components/pull/5459 to 24.1

refactor: preload items on grid scroll to index (#5459)

---

scripts/prepareDeploy.sh

chore: update the deploy script to take the new modules [skip ci]

---

.github/ISSUE_TEMPLATE/bug-report.yaml

Related `web-components` PR: https://github.com/vaadin/web-components/pull/6570

chore: improve bug report template

---

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarVisibilityPage.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarVisibilityIT.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/resources/META-INF/resources/frontend/menubarConnector.js

Fixes https://github.com/vaadin/flow-components/issues/4984

fix: attach observer before filtering hidden items

---

vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/confirmdialog/tests/FeaturesDiy.java
vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java

Element API should not be exposed to the component level.
Refactor

refactor: deprecate Element APIs in ConfirmDialog

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridChangingHierarchyPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridChangingHierarchyIT.java

IT for https://github.com/vaadin/flow/issues/14351.
Unable to test this issue in flow, looks like a real TreeGrid is needed for it to surface.
The test should not pass until run with a flow version containing the fix: https://github.com/vaadin/flow/pull/17774

Add test for Flow issue #14351

---

vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/src/main/java/com/vaadin/flow/component/messages/tests/MessageListPage.java
vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/src/test/java/com/vaadin/flow/component/messages/tests/MessageListIT.java
vaadin-messages-flow-parent/vaadin-messages-flow/src/main/java/com/vaadin/flow/component/messages/MessageListItem.java
vaadin-messages-flow-parent/vaadin-messages-flow/src/main/resources/META-INF/resources/frontend/messageListConnector.js
vaadin-messages-flow-parent/vaadin-messages-flow/src/test/java/com/vaadin/flow/component/messages/tests/MessageListTest.java

Fixes #4579
Depends on https://github.com/vaadin/web-components/pull/6628
- Feature

feat: add methods for setting class names to MessageListItem

---

vaadin-avatar-flow-parent/vaadin-avatar-flow-integration-tests/src/main/java/com/vaadin/flow/component/avatar/tests/AvatarGroupPage.java
vaadin-avatar-flow-parent/vaadin-avatar-flow-integration-tests/src/test/java/com/vaadin/flow/component/avatar/tests/AvatarGroupIT.java
vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/AvatarGroup.java
vaadin-avatar-flow-parent/vaadin-avatar-flow/src/test/java/com/vaadin/flow/component/avatar/tests/AvatarGroupTest.java

Fixes #4582
Depends on https://github.com/vaadin/web-components/pull/6622
- Feature

feat: add methods for setting class names to AvatarGroupItem

---

pom.xml

https://github.com/vaadin/flow/blob/94c20b49689b14dea36e78d07bbc0329e42e82e0/pom.xml#L270

chore: keep mockito-core version in sync with flow

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandedAutoWidthPreserveOnRefreshPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandedAutoWidthPreserveOnRefreshIT.java

Add an IT for https://github.com/vaadin/web-components/pull/6684
Depends on https://github.com/vaadin/web-components/pull/6684
Tests

test: add a missing tree grid IT

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxGroupItemsPage.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxGroupItemsIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBox.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxTest.java

Fixes https://github.com/vaadin/web-components/issues/4185
Based on https://github.com/vaadin/web-components/pull/6685
- Feature

feat: add API to group selected items at the top of the overlay

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxAllChipsPage.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxAllChipsIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBox.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxTest.java

Fixes https://github.com/vaadin/web-components/issues/4625
Based on https://github.com/vaadin/web-components/pull/6515
- Feature

feat: add API to display chips for all selected items

---

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/validation/BasicValidationPage.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/validation/BinderValidationPage.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/validation/BasicValidationIT.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/validation/BinderValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBasicValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBinderValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldEagerBinderValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldEagerValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBasicValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBinderValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBasicValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBinderValidationPage.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBasicValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBinderValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldEagerBinderValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldEagerValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBasicValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBinderValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBasicValidationIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBinderValidationIT.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/validation/BasicValidationPage.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/validation/BinderValidationPage.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/BasicValidationIT.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/BinderValidationIT.java

There is no longer need to reset the validation count manually after https://github.com/vaadin/flow-components/pull/5629#discussion_r1372726805.

test: remove manual validation count resets

---

vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/Button.java
vaadin-button-flow-parent/vaadin-button-flow/src/test/java/com/vaadin/flow/component/button/tests/ButtonTest.java

fixes https://github.com/vaadin/flow-components/issues/5414

fix: ignore programmatic clicks when disabled

---

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java
vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/TooltipTest.java

fix: make Tooltip.forComponent return existing tooltip handle (#5676) (CP: 23.4)

---

vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java

Fixes https://github.com/vaadin/flow-components/issues/5597
I [wasn't able to write unit tests](https://github.com/vaadin/flow-components/issues/5597#issuecomment-1794754772) for this case. The issue was, however, reproducible in a local Kubernetes cluster and I verified that this change fixes the issue in the same environment.
Bugfix

fix: replace lambda in fields to fix notification and dialog serialization

---

vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/main/java/com/vaadin/flow/component/charts/examples/other/Sankey.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/ChartType.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/DataSeriesItemSankey.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/PlotOptionsSankey.java

Fixes #5639
Added `PlotOptionsSankey` based on https://api.highcharts.com/highcharts/series.sankey
- Feature

feat: add support for Sankey chart type

---

vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitLayoutUnitTest.java

Manual chery-pick from #5750 to 24.1

fix: remove previous compoennt on slot in add to primary/secondary (#5750) (CP: 24.1)

---

vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitLayoutUnitTest.java

Manual cherry-pick from #5750 to V23.4

fix: remove previous component on slot in add to primary/secondary (#5750) (CP: 23.4)

---

vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitLayoutUnitTest.java

Manual cherry-pick from #5750 to V23.3

fix: remove previous component on slot in add to primary/secondary (#5750) (CP: 23.3)

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxSelectedItemsOnTopPage.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxSelectedItemsOnTopIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBox.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxTest.java

Cherry-pick of #5620 to `23.4` branch.
- Cherry-pick

feat: add setSelectedItemsOnTop to MultiSelectComboBox (23.4)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DetachReattachPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachReattachIt.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java

Manual cherry-pick from #5768 to 23.3

fix: call updateSelectionModeOnClient on attach (#5768) (CP: 23.3)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DetachReattachPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachReattachIt.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java

Manual cherry-pick from #5768 to 23.4

fix: call updateSelectionModeOnClient on attach (#5768) (CP: 23.4)

---

README.md

fix: correct mvn parameter in README file [skip ci]

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DetachReattachPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachReattachIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java

Addresses the known issues mentioned in the "Follow-up" section of https://github.com/vaadin/flow-components/pull/5748
Bugfix

fix: make sure connector exists on grid js function calls

---

pom.xml

chore: upgrade vaadin-parent to 2.2.1 [skip ci]

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComboBoxView.java

The PR fixes the pattern regexp in the ComboBox test to fix the JS error that was shown when opening the corresponding page in the browser.

test: fix pattern regexp

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxAutoExpandPage.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxAutoExpandIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBox.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxTest.java

Cherry-pick of #5626 and #5701 to `23.4` branch.
- Cherry-pick

feat: add setAutoExpand to MultiSelectComboBox (CP: 23.4)

---

vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuTargetConnector.js
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js

Fixes https://github.com/vaadin/flow-components/issues/5833

fix: prevent context menu on selection column left-click  (#5881) (CP: 24.3)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-data-range.test.ts

The PR improves test coverage for the grid connector's `fetchPage` method.
Part of #5865

test: improve test coverage for $connector.fetchPage

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-data-range.test.ts
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-no-connector.test.ts
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/shared.ts
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts

The PR cherry-picks a few recent improvements to `24.3` to facilitate future backports:
- https://github.com/vaadin/flow-components/pull/5882
- https://github.com/vaadin/flow-components/pull/5890
- https://github.com/vaadin/flow-components/pull/5899

refactor: simplify grid connector with optional chaining (#5899) (CP: 24.3)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-no-connector.test.ts
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/shared.ts
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts

The PR cherry-picks the following improvement to `24.3` to facilitate future backports:
- https://github.com/vaadin/flow-components/pull/5899

refactor: simplify grid connector with optional chaining (#5899) (CP: 24.2) 

---

vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/tests/GridProDetachAttachPage.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/tests/GridProDetachAttachIT.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/EditColumnConfigurator.java

fix: wraps client setEditModeRenderer call in a runWhenAttached callback (#5927) (CP: 23.4)

---

vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/tests/GridProDetachAttachPage.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/tests/GridProDetachAttachIT.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/EditColumnConfigurator.java

fix: wraps client setEditModeRenderer call in a runWhenAttached callback (#5927) (CP: 23.3)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-tree-data-range.test.ts
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts

The PR cherry-picks the following fix to `24.3`:
- #5916
Fixes #5902

fix: prevent grid from requesting too many sub-level items (#5916) (CP: 24.3)

---

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts

The PR simplifies the grid connector's `updateGridCache` helper to improve its readability.
Part of #5904

refactor: simplify updateGridCache helper

---

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts

The PR removes a dead call to the `itemsUpdated` function from the `$connector.clear()` method.

refactor: remove dead itemsUpdated call

---

vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenuTest.java

fix: Remove connector only if it still exists

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/pom.xml

chore: update license-checker to 1.12.6 (CP 24.3)

---

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarTest.java

Manually cherry-pick #6048 to `23.4` branch
Depends on https://github.com/vaadin/flow-components/pull/6057
Feature

feat: support reverse button collapsing order in menu-bar (#6048)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector.test.ts
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/shared.ts
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts

fix: sanitize last requested range on clear (#6010) (CP: 24.3)

---

vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/main/java/com/vaadin/flow/component/crud/tests/NewButtonView.java
vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/NewButtonIT.java
vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java

Fixes #6080
Depends on https://github.com/vaadin/web-components/pull/7181 - ITs will fail until that fix is released.
- Bugfix

fix: ensure Crud buttons are only created on the server

---

vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
vaadin-custom-field-flow-parent/vaadin-custom-field-flow/src/main/java/com/vaadin/flow/component/customfield/CustomField.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/InputField.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextFieldBase.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java

Fixes #6188
Depends on #6166
- Feature / refactor

feat: add HasHelper to the InputField interface

---

vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/validation/CheckboxBasicValidationPage.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/validation/CheckboxBinderValidationPage.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/validation/CheckboxBasicValidationIT.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/validation/CheckboxBinderValidationIT.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxUnitTest.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/validation/CheckboxBasicValidationTest.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/validation/CheckboxBinderValidationTest.java

Part of https://github.com/vaadin/platform/issues/5190
Depends on https://github.com/vaadin/web-components/pull/7285
- Feature

feat: add required state and validation support to Checkbox

---

vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java

These imports are no longer used since #5629

chore: remove unused imports after validated event removal

---

vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldTest.java

fix: do not throw when min is set to negative infinity

---

vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitLayoutUnitTest.java

fix: clear primary and secondary components on remove

---

scripts/updatePlatform.js

This reverts commit 82ce1be5d293970ec0f399864e6a10b146f69f9b.

Revert "remove non-exist entry in versions.json [skip ci] (#6288)" [skip ci]

---

vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/AppLayout.java
vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/Avatar.java
vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/AvatarGroup.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBox.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
vaadin-messages-flow-parent/vaadin-messages-flow/src/main/java/com/vaadin/flow/component/messages/MessageInput.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNav.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java

The PR improves the wording of the getI18n JavaDoc across components.

docs: improve wording of getI18n JavaDoc across components

---

vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/AppLayout.java
vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/Avatar.java
vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/AvatarGroup.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBox.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java

The PR combines the null check and assignment for the i18n object in the `setI18n` methods into a single line to make the code slightly more concise.

refactor: combine null check and assignment for i18n object

---

vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutTest.java

Add a convenience method for setting label width. 
Fixes #6223

feat: add convenience method for setting label width

---

vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java

Add the Flow API to the new feature done in https://github.com/vaadin/web-components/pull/7492.
Part of https://github.com/vaadin/web-components/issues/5101

feat: add noVerticalOverlap API to Select

---

vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/ButtonVariant.java

Add warning variant to button.
Related: vaadin/web-components#7485

feat: add warning variant to button

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/pom.xml
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridViewClickListenersPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewClickListenersIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js

Manual cherry-pick of #6412 to `23.5` branch.
- Cherry-pick

fix: do not fire ItemClickListener on focusable element click (#6412) (CP: 23.5)

---

pom.xml
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow/src/main/java/com/vaadin/flow/theme/lumo/LumoUtility.java

Added missing utility classes to `LumoUtility`.

feat: add missing utility classes to LumoUtility

---

vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewClickListenersIT.java
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow/src/main/java/com/vaadin/flow/theme/lumo/LumoUtility.java

The formatter check is broken and some files weren't formatted. This PR fixes formatting.

chore: run mvn formatter: format

---

vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/main/java/com/vaadin/flow/component/contextmenu/it/ContextMenuClosePage.java
vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuCloseIT.java
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java

fix: set fromClient to false on programmatic ContextMenu close

---

vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java

The PR contains changes from running `mvn formatter:format` on the main branch.

refactor: fix format errors

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/InertTreeGridPage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/InertTreeGridIT.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java

Manually cherry-pick #6465 to `24.4`

fix: allow data fetch for inert grid (#6465)

---

vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
vaadin-popover-flow-parent/vaadin-popover-flow/src/test/java/com/vaadin/flow/component/popover/PopoverTest.java

Based on https://github.com/vaadin/web-components/pull/7610
- Feature

feat: add setAutofocus and isAutofocus API to Popover

---

README.md
pom.xml

chore: replace formatter with spotless [skip ci] (#6512) (CP: 14.12)

---

README.md
pom.xml
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetJsniUtil.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java

chore: replace formatter with spotless [skip ci] (#6512) (CP: 23.4)

---

README.md
pom.xml
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetJsniUtil.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java

chore: replace formatter with spotless [skip ci] (#6512) (CP: 23.5)

---

README.md
pom.xml
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetJsniUtil.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java

chore: replace formatter with spotless [skip ci] (#6512) (CP: 24.3)

---

README.md
pom.xml
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetJsniUtil.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java

chore: replace formatter with spotless [skip ci] (#6512) (CP: 24.4)

---

README.md
pom.xml

chore: replace formatter with spotless [skip ci] (#6512) (CP: 14.11)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridHugeTreePage.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridHugeTreeIT.java

Test for regression https://github.com/vaadin/flow/issues/19728

test: add test for root key removal from keymapper

---

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarTest.java

Add the getters and setters for the html `tabNavigation` attribute added in the web component.
Fixes https://github.com/vaadin/web-components/pull/7525
Acceptance criteria https://github.com/vaadin/platform/issues/6552

Add setTabNavigation/isTabNavigation

---

vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonSerializableTest.java

Fixes https://github.com/vaadin/flow-components/issues/6555

fix: make radio button group with size request serializable

---

vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java

This PR
- removes 2 duplicate tests
- updates some test names to reflect the case better and be more consistent with the other tests

test: remove duplicate test and rename tests

---

vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java

Allows disabling side nav items, follow up for https://github.com/vaadin/web-components/pull/6095
Fixes https://github.com/vaadin/web-components/issues/5827

feat: allow disabling side nav items

---

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasValidationProperties.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextFieldBase.java

Part of https://github.com/vaadin/flow-components/issues/6545

docs(TextField): explain constraint validation

---

vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBox.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java

Give a general description of how the constraint validation works, including such aspects as validation triggers, constraints, error messages, Binder, manual validation, for the following components:
- ComboBox
- MultiSelectComboBox
- Select
- RadioButtonGroup
- CheckboxGroup
- Checkbox
Part of https://github.com/vaadin/flow-components/issues/6545

docs(rest components): explain constraint validation

---

vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java

docs: update Popover javadoc to mention closing limitation

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuConnector.js
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuTargetConnector.js
vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow/src/main/resources/META-INF/resources/frontend/cookieConsentConnector.js
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js
vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/mapConnector.js
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/resources/META-INF/resources/frontend/menubarConnector.js
vaadin-messages-flow-parent/vaadin-messages-flow/src/main/resources/META-INF/resources/frontend/messageListConnector.js
vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java
vaadin-select-flow-parent/vaadin-select-flow/src/main/resources/META-INF/resources/frontend/selectConnector.js
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/resources/META-INF/resources/frontend/vaadin-big-decimal-field.js
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/vaadin-time-picker/timepickerConnector.js

Removes self-invoking function wrappers from connectors and some other places. These wrappers are unnecessary for JS modules, which already provide encapsulation.
> [!NOTE]
> I recommend reviewing this PR with "Hide whitespace" enabled.

refactor: remove self-invoking function wrappers

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuConnector.js
vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuTargetConnector.js
vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/test/env-setup.ts
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/env-setup.ts
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/resources/META-INF/resources/frontend/menubarConnector.js
vaadin-messages-flow-parent/vaadin-messages-flow/src/main/resources/META-INF/resources/frontend/messageListConnector.js
vaadin-select-flow-parent/vaadin-select-flow/src/main/resources/META-INF/resources/frontend/selectConnector.js
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/vaadin-time-picker/timepickerConnector.js

Cherry-picks #6732 to 24.5 branch with manual conflict resolution in each individual file.

refactor: remove tryCatchWrapper for better stack trace (#6732) (CP: 24.5)

---

vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/Chart.java

Removes the last tryCatchWrapper usage that was in charts.

refactor: remove last tryCatchWrapper usage

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/dataview/AbstractItemCountComboBoxIT.java
vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/AbstractComponentIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ContextMenuIT.java

Cherry-pick of https://github.com/vaadin/flow-components/pull/6859

test: make integration tests work with new headless mode (24.5)

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/dataview/AbstractItemCountComboBoxIT.java
vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/AbstractComponentIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ContextMenuIT.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerIT.java

Cherry-pick of https://github.com/vaadin/flow-components/pull/6859
Sonar failure is an unrelated issue.

test: make integration tests work with new headless mode (23.5)

---

vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/AbstractComponentIT.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerIT.java

Cherry-pick of https://github.com/vaadin/flow-components/pull/6859

test: make integration tests work with new headless mode (14.12)

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java

docs: fix incorrect getOffset() usage in ComboBox JavaDoc

---

vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavI18NIT.java

Cherry pick of 949d0ec66b5a188af67337b8f590d3175900b5e8

test: use textContent property in side nav i18n tests

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/validation/MultiSelectComboBoxBasicValidationIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/validation/MultiSelectComboBoxBinderValidationIT.java

Cherry-pick of 862aa485e570ea1a60507ba5acbe02a633e088e3

test: use Enter to commit custom values

---

vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java

(cherry picked from commit c893888a6b59c7b628cb7e56fee28aa6f990e3d3)

test: change test setup for UploadElement.waitForUploads (#6926) (CP: 24.5)

---

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/frontend/src/grid-on-client-and-slot.js
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/frontend/src/ImplicitLumoThemedTemplate.js
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/frontend/theme/lumo/ImplicitLumoThemedTemplate.js
vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/frontend/theme/lumo/LumoThemedTemplate.js
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/frontend/src/MaterialThemedTemplate.js
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/frontend/src/NotThemedTemplate.js
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/frontend/theme/lumo/MaterialThemedTemplate.js
vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/frontend/theme/material/MaterialThemedTemplate.js

Applied `prettier` formatting to some `.js` files in the project.

chore: format JS in connectors and integration tests with Prettier

---

.husky/pre-commit
package.json

The PR sets up `lint-staged` to run Prettier on Git commit.

chore: add lint-staged to run prettier on git commit

---

.husky/pre-commit
package.json

Cherry-picks #6986 to branch 24.6

chore: add lint-staged to run prettier on commit (#6986) (CP: 24.5)

---

.husky/pre-commit
package.json

Cherry-picks #6986 to branch 24.6

chore: add lint-staged to run prettier on commit (#6986) (CP: 24.6)

---

scripts/templates/apache2-license-header.txt
scripts/templates/vaadin-commercial-license-header.txt

(cherry picked from commit 186ae6a0a323972b8ec1db93ae6ac4320a27fc9b)

chore: improve license header formatting (#7082) (CP: 24.6)

---

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java

fix: Use correct formatting for logging

---

vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/ButtonVariant.java
vaadin-card-flow-parent/vaadin-card-flow/src/main/java/com/vaadin/flow/component/card/CardVariant.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/ChartVariant.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroupVariant.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxVariant.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxVariant.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePickerVariant.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePickerVariant.java
vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/DialogVariant.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridVariant.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridProVariant.java
vaadin-material-theme-flow-parent/vaadin-material-theme-flow/src/main/java/com/vaadin/flow/theme/material/Material.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBarVariant.java
vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/PopoverVariant.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioGroupVariant.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditorVariant.java
vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/SelectVariant.java
vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheetVariant.java
vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabsVariant.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextAreaVariant.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextFieldVariant.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePickerVariant.java

Related to https://github.com/vaadin/web-components/issues/8580

chore: mark the Material theme as deprecated

---

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java

Fixes internal API usage after switch from Elemental to Jackson in Flow

chore: fix compilation errors

---

vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java

Describes the auto-responsive mode and the related feature flag in FormLayout's JavaDoc.
Part of #7164

docs(FormLayout): describe auto-responsive mode and feature flag

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/pom.xml
vaadin-grid-flow-parent/vaadin-grid-flow/pom.xml

Solves compilation issues on old Eclipse versions
Fixes #7213

chore: Make Spring Data non-optional

---

vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNav.java

Related to https://github.com/vaadin/flow/issues/21085

fix: use allowInert to not spam the logs

---

vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/HorizontalLayout.java
vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/test/java/com/vaadin/flow/component/orderedlayout/tests/HorizontalLayoutSlotsTest.java

Fixes #7230
Fixes #7233
- Bugfix

fix: do not throw when adding the same component twice

---

vaadin-card-flow-parent/vaadin-card-testbench/src/main/java/com/vaadin/flow/component/card/testbench/CardElement.java

Adds TestBench methods for CardElement.
Related to [#7212](https://github.com/vaadin/flow-components/issues/7212)

feat: add card testbench methods

---

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/ClientValidationUtil.java

The PR addresses the finding made by @mshabarov in https://github.com/vaadin/flow-components/pull/6792#discussion_r2018144528

chore: add missing @Deprecated annotations

---

vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow/src/main/java/com/vaadin/flow/component/masterdetaillayout/MasterDetailLayout.java
vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow/src/test/java/com/vaadin/flow/component/masterdetaillayout/MasterDetailLayoutTest.java

Part of https://github.com/vaadin/platform/issues/7173
Implemented the following APIs:
- `setOrientation()` / `getOrientation()`
- `setContainment()` / `getContainment()`
- `setForceOverlay()` / `isForceOverlay()`
- `setAnimationEnabled()` / `isAnimationEnabled()`
- `setStackThreshold()` / `getStackThreshold()`
- Feature

feat: add master-detail-layout Flow component APIs

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComboBoxDemoPage.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-testbench/src/main/java/com/vaadin/flow/component/combobox/testbench/ComboBoxElement.java
vaadin-combo-box-flow-parent/vaadin-combo-box-testbench/src/main/java/com/vaadin/flow/component/combobox/testbench/MultiSelectComboBoxElement.java

Fixes https://github.com/vaadin/testbench/issues/1901

feat: Implement HasPlaceholder in ComboBoxElement

---

vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow/src/main/java/com/vaadin/flow/component/masterdetaillayout/MasterDetailLayout.java
vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow/src/test/java/com/vaadin/flow/component/masterdetaillayout/MasterDetailLayoutTest.java

- Improve JavaDoc
- Add non-null checks for orientation and containment
- Fix parameter order in assertions
- Refactor

refactor: small code improvements in MasterDetailLayout

---

vaadin-card-flow-parent/vaadin-card-flow-integration-tests/src/main/java/com/vaadin/flow/component/card/tests/CardPage.java
vaadin-card-flow-parent/vaadin-card-flow-integration-tests/src/test/java/com/vaadin/flow/component/card/tests/CardIT.java
vaadin-card-flow-parent/vaadin-card-flow/src/main/java/com/vaadin/flow/component/card/Card.java
vaadin-card-flow-parent/vaadin-card-flow/src/main/java/com/vaadin/flow/component/card/CardVariant.java
vaadin-card-flow-parent/vaadin-card-flow/src/main/java/com/vaadin/flow/component/card/ExperimentalFeatureException.java
vaadin-card-flow-parent/vaadin-card-flow/src/test/java/com/vaadin/flow/component/card/CardTest.java
vaadin-card-flow-parent/vaadin-card-flow/src/test/java/com/vaadin/flow/component/card/FeatureFlagTest.java
vaadin-card-flow-parent/vaadin-card-testbench/src/main/java/com/vaadin/flow/component/card/testbench/CardElement.java

Adds all commits for `Card` that have been made since branching out 24.8 to 24.7. This allows a preview release of the Flow API in 24.7.
Depends on https://github.com/vaadin/web-components/pull/8905
- Feature

 feat: Card Flow API preview (CP 24.7)

---

vaadin-master-detail-layout-flow-parent/pom.xml
vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow-integration-tests/pom.xml
vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/masterdetaillayout/tests/MasterDetailLayoutIT.java
vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-testbench/pom.xml
vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-testbench/src/main/java/com/vaadin/flow/component/masterdetaillayout/testbench/MasterDetailLayoutElement.java

Adds a TestBench element for testing `MasterDetailLayout`.
Part of https://github.com/vaadin/platform/issues/7173
- Feature

feat: add MasterDetailLayoutElement TestBench element

---

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/ClearValueIT.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/ClearValuePage.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/ClearValueIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/IntegerFieldClearValueIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldClearValueIT.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/ClearValueIT.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java

Fixes https://github.com/vaadin/flow-components/issues/7250, https://github.com/vaadin/flow-components/issues/7227

fix: do not clear displayed value if component value was reverted (#7277) (CP: 24.6)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridScrollToIT.java
vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/TreeGridElement.java

See: https://github.com/vaadin/flow-components/issues/7293

feat: Add TreeGridElement#scrollToEnd

---

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js

Adapted from: https://github.com/vaadin/flow-components/pull/5897

fix: reset fetch range when requested page is out of visible range

---

vaadin-progress-bar-flow-parent/vaadin-progress-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/progressbar/tests/ProgressBarView.java
vaadin-progress-bar-flow-parent/vaadin-progress-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/progressbar/tests/ProgressBarIT.java
vaadin-progress-bar-flow-parent/vaadin-progress-bar-flow/src/test/java/com/vaadin/flow/component/progressbar/tests/ProgressBarVariantTest.java

- Replaced `assertVariants()` IT with the unit test similar to how it's tested in other components
- Removed not relevant code from `ProgressBarView` so that it only contains actually used stuff
- Updated `ProgressBarIT` to use the `ProgressBarElement` testbench API instead of `WebElement`
- Test

test: cleanup ProgressBarIT, use unit test for theme variant

---

vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupDemoPage.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupIT.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupVariantTest.java

Replaced `assertThemeVariant()` IT with the unit test similar to how it's tested in other components.
- Test

test: replace CheckboxGroup theme variants IT with unit test

---

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDemoPage.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupVariantTest.java

Replaced `assertThemeVariant()` IT with the unit test similar to how it's tested in other components.
- Test

test: replace RadioButtonGroup theme variants IT with unit test

---

vaadin-tabs-flow-parent/vaadin-tabs-flow-integration-tests/src/main/java/com/vaadin/flow/component/tabs/tests/TabsPage.java
vaadin-tabs-flow-parent/vaadin-tabs-flow-integration-tests/src/test/java/com/vaadin/flow/component/tabs/tests/TabsIT.java
vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabVariantTest.java
vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabsVariantTest.java

Replaced `assertThemeVariant()` IT with the unit test similar to how it's tested in other components.
Note: didn't add separate test file for `TabSheet` becomes it is already covered by `TabSheetTest`.
- Test

test: replace Tabs theme variants IT with unit test

---

vaadin-details-flow-parent/vaadin-details-flow-integration-tests/src/main/java/com/vaadin/flow/component/details/tests/Home.java
vaadin-details-flow-parent/vaadin-details-flow-integration-tests/src/test/java/com/vaadin/flow/component/details/tests/BasicIT.java
vaadin-details-flow-parent/vaadin-details-flow/src/test/java/com/vaadin/flow/component/details/DetailsVariantTest.java

Replaced theme variants IT with the unit test similar to how it's tested in other components.
- Test

test: replace Details theme variants IT with unit test

---

vaadin-accordion-flow-parent/vaadin-accordion-flow-integration-tests/src/test/java/com/vaadin/flow/component/accordion/tests/BasicIT.java
vaadin-details-flow-parent/vaadin-details-testbench/src/main/java/com/vaadin/flow/component/details/testbench/DetailsElement.java

While testing Lit integration I noticed that most Accordion ITs were not active. This restores them.
- Test

test: restore accordion ITs

---

vaadin-checkbox-flow-parent/vaadin-checkbox-testbench/src/main/java/com/vaadin/flow/component/checkbox/testbench/CheckboxElement.java
vaadin-checkbox-flow-parent/vaadin-checkbox-testbench/src/main/java/com/vaadin/flow/component/checkbox/testbench/CheckboxGroupElement.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-testbench/src/main/java/com/vaadin/flow/component/combobox/testbench/ComboBoxElement.java
vaadin-combo-box-flow-parent/vaadin-combo-box-testbench/src/main/java/com/vaadin/flow/component/combobox/testbench/MultiSelectComboBoxElement.java
vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/EventHandlingIT.java
vaadin-date-picker-flow-parent/vaadin-date-picker-testbench/src/main/java/com/vaadin/flow/component/datepicker/testbench/DatePickerElement.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-testbench/src/main/java/com/vaadin/flow/component/datetimepicker/testbench/DateTimePickerElement.java
vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/validation/AbstractValidationIT.java
vaadin-radio-button-flow-parent/vaadin-radio-button-testbench/src/main/java/com/vaadin/flow/component/radiobutton/testbench/RadioButtonGroupElement.java
vaadin-select-flow-parent/vaadin-select-testbench/src/main/java/com/vaadin/flow/component/select/testbench/SelectElement.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/EmailFieldPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/IntegerFieldPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/PasswordFieldPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/TextAreaPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/TextAreaPatternIT.java
vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/TextFieldPageIT.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/BigDecimalFieldElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/EmailFieldElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/IntegerFieldElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/NumberFieldElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/PasswordFieldElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextAreaElement.java
vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextFieldElement.java
vaadin-time-picker-flow-parent/vaadin-time-picker-testbench/src/main/java/com/vaadin/flow/component/timepicker/testbench/TimePickerElement.java

I grouped these two into one PR to avoid further rebase and conflicts resolution as these two changes are touching the same places.
MERGE, NOT SQUASH.

Cherry pick HasValidation and HasClearButton to 23.6 (CP: 23.6)

---

vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/src/main/java/com/vaadin/flow/component/messages/tests/MessageListPage.java
vaadin-messages-flow-parent/vaadin-messages-flow/src/main/java/com/vaadin/flow/component/messages/MessageListItem.java

Add `MessageListItem` constructor with text and userName
Fixes https://github.com/vaadin/flow-components/issues/7456
Related to https://github.com/vaadin/platform/issues/7601
Feature

feat: add MessageListItem constructor with text and userName

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetEventListener.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetJsniUtil.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/Slot.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetConnector.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/CustomEditorIT.java

Cherry-pick from #7401 to the 24.7 branch.

fix: align keyboard/mouse behavior for custom editors in Spreadsheet (#7401) (CP 24.7)

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/CustomEditorIT.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/FormulaFormatIT.java

Cherry-pick of #7479 to the 24.7 branch.

test: try improve flaky spreadsheet custom editor tests (#7479) (CP 24.7)

---

vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardVariant.java

Cherry-pick of https://github.com/vaadin/flow-components/pull/7317 to v24.8.

Feat/dashboard style variants (#7317) (CP 24.8)

---

vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/ButtonVariant.java
vaadin-card-flow-parent/vaadin-card-flow/src/main/java/com/vaadin/flow/component/card/CardVariant.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/ChartVariant.java
vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroupVariant.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxVariant.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxVariant.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePickerVariant.java
vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerVariantTest.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePickerVariant.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerVariantTest.java
vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/DialogVariant.java
vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogThemeVariantTest.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridVariant.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridProVariant.java
vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBarVariant.java
vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/PopoverVariant.java
vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioGroupVariant.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditorVariant.java
vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/SelectVariant.java
vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectVariantTest.java
vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheetVariant.java
vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabsVariant.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextAreaVariant.java
vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextFieldVariant.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePickerVariant.java
vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerVariantTest.java

Removed Material theme variants.

refactor!: remove deprecated Material theme variants

---

vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/UploadInterruptView.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/AbstractUploadIT.java
vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadInterruptIT.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java

Cherry-pick of https://github.com/vaadin/flow-components/pull/7616

fix: interrupt all uploads (CP: 14.13)

---

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridArrayUpdater.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java

Depends on 
- https://github.com/vaadin/flow-components/pull/7692
Fixes #7688

refactor!: remove deprecated grid APIs

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxDataController.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxSpringDataTest.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboboxSerializableTest.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxFilteringTest.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxDataViewTestHelper.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxLazyDataViewTest.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-data-range.test.ts
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector.test.ts
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/shared.ts
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridScrollTest.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTest.java
vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridLazyDataViewTest.java
vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/main/java/com/vaadin/flow/data/renderer/tests/LitRendererTestComponentWrapper.java
vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/java/com/vaadin/flow/component/virtuallist/VirtualList.java
vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/resources/META-INF/resources/frontend/virtualListConnector.js

Cherry-picks https://github.com/vaadin/flow-components/pull/7759 to 24.9

refactor: use modern setViewportRange method (#7759) (CP: 24.9)

---

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/AbstractTreeGridIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridBasicFeaturesIT.java
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridComponentHierarchyColumnIT.java

The PR adds integration tests to verify that rows have expected level and expanded state.
Part of #7684

test: verify that rows have expected level and expanded state

---

vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/CompositeIT.java
vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/CustomGridIT.java
vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/EditorPositionIT.java
vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/ProtectedBackendIT.java
vaadin-crud-flow-parent/vaadin-crud-testbench/src/main/java/com/vaadin/flow/component/crud/testbench/CrudElement.java

Update CRUD ITs to handle changes to the CRUD dialog not being teleported to the body anymore.

chore: update crud dialog ITs

---

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxItemClassNameIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPageIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComponentRendererIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/DetachReattachIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxItemClassNameIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxLitRendererIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxSelectedItemsOnTopIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/RefreshEmptyLazyDataProviderIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/StringItemsWithTextRendererIT.java
vaadin-combo-box-flow-parent/vaadin-combo-box-testbench/src/main/java/com/vaadin/flow/component/combobox/testbench/MultiSelectComboBoxElement.java
vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithComboBoxIT.java

Adjustments needed for ITs to pass with the web component changes.
- Test

test: adjust ComboBox and MultiSelectComboBox ITs to pass with native popover

---

vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/mapConnector.js

Changed the import to use file name instead of directory.

chore: update map connector to import from the specific file

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/pom.xml

set the license-checker as provided

chore: upgrade license-checker to 2.0.0-alpha1 (24.9)

---

vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java

To allow other tools such as Copilot to prevent dialog's from closing, make `Dialog` listen for `vaadin-overlay-close` globally on `document`, and only call the closing logic on the server side if the event was not prevented somewhere else.
- Refactor

refactor: use close event to prevent client-side dialog from closing

---

vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/validation/AbstractDateTimePickerValidationIT.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BasicValidationIT.java
vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BinderValidationIT.java
vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/validation/AbstractValidationIT.java

Cherry-pick of https://github.com/vaadin/flow-components/pull/7892 to v24.9.

test: refactor and cleanup DateTimePicker validation tests (#7892) (CP: 24.9)

---

vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/MapVariant.java
vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/MapVariantTest.java

Fixes https://github.com/vaadin/flow-components/issues/7666

refactor: deprecate BORDERLESS map variant, add NO_BORDER

---

vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/AvatarGroup.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/Chart.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/ProxyChangeForwarder.java
vaadin-charts-flow-parent/vaadin-charts-flow/src/test/java/com/vaadin/flow/component/charts/ChartsSerializableTest.java
vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/MapBase.java
vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/serialization/MapSerializer.java
vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/serialization/MapSerializerTest.java
vaadin-messages-flow-parent/vaadin-messages-flow/src/main/java/com/vaadin/flow/component/messages/MessageList.java
vaadin-messages-flow-parent/vaadin-messages-flow/src/test/java/com/vaadin/flow/component/messages/tests/MessageListTest.java
vaadin-messages-flow-parent/vaadin-messages-flow/src/test/java/com/vaadin/flow/component/messages/tests/MessageListUpdatesTest.java
vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
vaadin-popover-flow-parent/vaadin-popover-flow/src/test/java/com/vaadin/flow/component/popover/PopoverTest.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/test/java/com/vaadin/flow/component/richtexteditor/RichTextEditorTest.java
vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java
vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavItemTest.java
vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java

Updates more component APIs to use Jackson instead of elemental.json.
- Refactor

refactor: update components to use Jackson for setting properties

---

vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java

Cherry-pick of https://github.com/vaadin/flow-components/pull/8056
Code needed to be refactored to use `elemental.json` APIs.

refactor: use static JS script for CSP support (CP: 24.9)

---

vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java

Fixes https://github.com/vaadin/flow-components/issues/6627
- Behavior altering change

refactor!: make getAcceptedFileTypes return unmodifiable list

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/pom.xml
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java
vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/CustomHandlerTest.java

Cherry-pick from #7914 to V24.9.
- Cherry-pick

feat: allow Spreadsheet handler customizations (#7914) (CP: 24.9)

---

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/pom.xml

This align dependencies with all other flow components

fix: bring flow dependency as provided in spreadsheet (24.9)
