vaadin/flow-components

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerLocalePage.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocaleIT.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
Currently the date picker connector subtracts a month from the reference date, causing a reference date of `2000-01-01` to be interpreted as `1999-12-01`. Due to a separate issue in date-fns, that leads to an effective reference date of `1999-01-01` (see this comment: https://github.com/vaadin/flow-components/issues/4629#issuecomment-1431578099).
This fixes the connector to not subtract the month. The fact that date-fns ignores the day and month of the reference date is not addressed in this PR.
Fixes #4629
- Bugfix
> fix: do not modify reference date in connector

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridRefreshAllPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridRefreshAllIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
The effective size was not correctly updated after `grid.$connector.clear`. This led to miscalculation of indexes, requests, and page numbers. This PR adds the update to the end of `clear`.
Back-port of the changes in v24 [PR](https://github.com/vaadin/flow-components/pull/4657) to v23.3.
Fixes #4611
> fix: back-port update effectiveSize at the end of clear

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
When multiple hierarchy updates in `TreeGrid` take place at once, the `confirmParent` function in `gridConnector` gets called multiple times. Currently, the `confirmParent` function requests `<vaadin-grid>` to update its rows synchronously after each invocation.
This PR debounces the update request which reduces the overhead on hierarchy updates.
The change has a 40% impact on the `expandtime` metric in the [Grid benchmark tests](https://bender.vaadin.com/buildConfiguration/Flow_Components_BenchmarkTests_Grid?mode=builds).
> refactor: debounce update in grid connector confirm parent

- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/UploadView.java
- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/AbstractUploadIT.java
- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/FileBufferIT.java
- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/NonImmediateUploadIT.java
- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
The name of the event contained a typo, which lead to event not being caught. This PR fixes the typo and adds a file rejection test.
Fixes #4695
> fix: listen to file-reject instead of file-rejected

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridPreloadIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
TreeGrid's eager fetch mode aims to ensure the grid's viewport is covered with items on as few server roundtrips as possible. Knowing the exact viewport size isn't necessary so an estimate of 40 rows is used instead. Such a large number results in having to process an excessive amount of items both on the server and the client when dealing with multiple hierarchy levels. We can safely cut down the estimate to reduce the overhead of processing the items.
This PR cuts down the viewport size estimate by half to 20 rows.
The change has a 30% impact on the `expandtime` metric in the [Grid benchmark tests](https://bender.vaadin.com/buildConfiguration/Flow_Components_BenchmarkTests_Grid?mode=builds).
> refactor: reduce grid eager fetch viewport size estimate

- vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/Button.java
- vaadin-button-flow-parent/vaadin-button-flow/src/test/java/com/vaadin/flow/component/button/tests/ButtonTest.java
Make `Button` implement `HasAriaLabel` interface.
Part of #2946 
Fixes #4716
> feat: make Button implement HasAriaLabel

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
The PR removes an unused `getLevel` method from the grid connector. Let's see if the tests pass.
> refactor: remove an unused getLevel method

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Replace a call to the heavy `updateAllGridRowsInDomBasedOnCache()` in the grid connector's data provider with a manual size update to avoid an unnecessary content update.
The change has a 21% impact on the `expandedrendertime` and 55% impact on the `expandtime` metrics in the [Grid benchmark tests](https://bender.vaadin.com/buildConfiguration/Flow_Components_BenchmarkTests_Grid?mode=builds).
> refactor: avoid unnecessary update in grid connector

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Avoid an unnecessary re-render when the `Grid` sorters change. The `<vaadin-grid>` web component [clears its internal cache and re-renders](https://github.com/vaadin/web-components/blob/6eb1e181763c67abb71bd406f2ded33495d63c02/packages/grid/src/vaadin-grid-sort-mixin.js#L176) automatically whenever the sorter-elements change. In Flow `Grid`'s case, this is unnecessary and causes an extra re-render
The change has a 40% impact on the `expandedsorttime` and 27% impact on the `sorttime` metrics in the [Grid benchmark tests](https://bender.vaadin.com/buildConfiguration/Flow_Components_BenchmarkTests_Grid?mode=builds).
> refactor: avoid an extra render on Grid sort

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridPreloadIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
This PR reverts https://github.com/vaadin/flow-components/pull/4748
Even though the first contentful paint is a bit faster with a lower viewport estimate, the Grid immediately needs to start fetching more items for the rows that are in the DOM but still outside the viewport. This has an overall negative impact on how performant the component feels especially on a slower network connection.
Refactor
> Revert "refactor: reduce grid eager fetch viewport size estimate"

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridBasicFeaturesIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
An item value matching the `<vaadin-grid>`'s [`itemHasChildrenPath`](https://github.com/vaadin/web-components/blob/07792ca769bf9abeb11c1c51eb61223a06cf1c0a/packages/grid/src/vaadin-grid-data-provider-mixin.js#L207) is required for the row focus expand feature to work. The default value for the property is "children".
Before V24, a property with the correct name got accidentally generated by TreeGrid's [addHierarchyColumn](https://github.com/vaadin/flow-components/blob/b7d6d625308285138585e9b4d29c158fead9091a/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java#L527-L528) but since [switching](https://github.com/vaadin/flow-components/commit/c680d340811978b2ed4efee054938c53e369fa84#diff-475e451a86c2b6f7ac94ac86ea50ef4eb3b7b9cbdc0c7169c4bce5 …
> fix: make treegrid generate a value for itemHasChildrenPath

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
The PR drops grid connector logic that removes the sub-cache when its associated item collapses. This logic only worked when the toggle action would originate from the web component but not from the server. For example, it didn't work in the most common use case, when you are toggling a row with <kbd>Space</kbd> or a click.
> refactor: do not remove the sub-cache on item collapse

- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/main/java/com/vaadin/flow/component/richtexteditor/tests/MainView.java
- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/tests/BasicUseIT.java
- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
When used in a value change listener, `RichTextEditor.asHtml().getValue()` produces incorrect results in the second value change. When `asHtml()` is called the first time, it is initialized with the current value. The constructor also adds a value change listener to the editor which clears the value in `AsHtml`. In each editor value change, the `AsHtml` value should be cleared and calculated again. If a value change listener is added and used before calling `asHtml()`, that listener takes precedence and the `AsHtml` value cannot be cleared before the value change. Therefore, the `AsHtml` value is not updated. This PR moves the listener to the `RichTextEditor` constructor. This way, the value is properly cleared before  `getValue` is executed.
Fixes #4767
> fix: move listener from AsHtml constructor to RTE constructor

- pom.xml
Testbench version bump to 9.0.1 for v24.0.
> chore: test bench version bump to 9.0.1 for v24.0

- vaadin-board-flow-parent/vaadin-board-flow/src/main/java/com/vaadin/flow/component/board/Board.java
- vaadin-board-flow-parent/vaadin-board-flow/src/main/java/com/vaadin/flow/component/board/Row.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/resources/META-INF/resources/frontend/tooltip.ts
- vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/Icon.java
- vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/Scroller.java
- vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/java/com/vaadin/flow/component/virtuallist/VirtualList.java
All imports should be for the non-themed version so the components can be used without Lumo
Fixes https://github.com/vaadin/flow/issues/16249
> fix: Use non themed imports

- vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java
- vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow/src/main/resources/META-INF/resources/frontend/lumo-includes.ts
Adapts the Lumo class to the changes done in https://github.com/vaadin/web-components/pull/5666
> fix: Use global style imports

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-tree.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
This change improves how a data provider callback is processed in `gridConnector`. When the callback resolves synchronously from the cache, the updated data provider checks if there is a pending request for another parent item which could be resolved synchronously as well.
The change has a 73% impact on the `expandedsorttime` and 62% impact on the `expandedrendertime` metrics in the [Grid benchmark tests](https://bender.vaadin.com/buildConfiguration/Flow_Components_BenchmarkTests_Grid?mode=builds).
Depends on https://github.com/vaadin/web-components/pull/5647
> refactor: avoid unnecessary render cycles in the data provider callback

- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/IntegerFieldClearValuePage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/NumberFieldClearValuePage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/IntegerFieldClearValueIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldClearValueIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/ClearValueIT.java
There is an optimization in Flow to only send the final value for an element property in the case the property is updated multiple times using `setProperty()` within one round-trip. In terms of a set of commands that Flow sends to the client, the first value set command will be replaced with the final value set command. However, the optimization doesn't apply to `executeJs()`. It is sent as many times as you call it. 
It is therefore possible that
```java
integerField.setValue(null);
integerField.setValue(1234);
```
will result in Flow sending the following commands to the browser:
```js
{ command: 'setProperty', name: 'value', value: '1234' }
{ command: 'executeJs', value: 'this._inputElementValue = ""' }
```
instead of the following ones, as you might expect:
```js
{ command: …
```
> fix: do not attempt to clear bad input when value is present

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Remove deprecation description from `setDataProvider` since the decision to remove it was reverted. 
Fixes #4642
> refactor: remove deprecation description from setDataProvider

- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogCloseActionListenerTest.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
This PR refactors tests regarding `addDialogCloseActionListener` and `onCloseConfigured` and extracts them to a new class. The changes include renaming, updating the assertion logic, breaking down tests, and deleting unnecessary blocks. 
See: [related PR 1](https://github.com/vaadin/vaadin-dialog-flow/pull/91)
See: [related PR 2](https://github.com/vaadin/flow-components/pull/4778)
> test: refactor and extract dialog close action listener tests

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Make Grid's `scrollToIndex` method preload the items for the target index so another server roundtrip wouldn't be needed for fetching the items.
This works as expected with `TreeGrid` also since https://github.com/vaadin/web-components/pull/5428. After https://github.com/vaadin/flow-components/issues/3505#issuecomment-1477442171 is fully implemented, we can optimize this further for `TreeGrid` specifically.
The change has a 19% impact on the `scrolltoindextime` metric in the [Grid benchmark tests](https://bender.vaadin.com/buildConfiguration/Flow_Components_BenchmarkTests_Grid?mode=builds).
> refactor: preload items on grid scroll to index

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Now that https://github.com/vaadin/web-components/pull/5647 has been done, there seem to be no cases where `ensureSubCacheQueue` would contain items beyond the viewport:
- The grid web component [requests a sub-cache only for visible rows](https://github.com/vaadin/web-components/blob/7a117e810f8f62977a60e9860248c48db1975a28/packages/grid/src/vaadin-grid-data-provider-mixin.js#L411-L417) while resolving a page request.
- Before resolving a page request, the grid connector [clears](https://github.com/vaadin/flow-components/blob/5949537412cc0dabe1f3b7a57dee5faa409a1f32/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L370) `ensureSubCacheQueue` completely.
which means the grid connector doesn't need anymore to additionally check …
> refactor: do not check for item visibility before ensuring a sub-cache

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/ClearValuePage.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/ClearValueIT.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
There is an optimization in Flow to only send the final value for an element property in the case the property is updated multiple times using `setProperty()` within one round-trip. In terms of commands sent to the client, the first value set command will be replaced with the final value set command. However, the optimization doesn't apply to `executeJs()`. It is sent as many times as you call it. 
It is therefore possible that
```java
datePicker.setValue(null);
datePicker.setValue(LocalDate.of(2022, 1, 1));
```
will result in Flow sending the following commands to the browser:
```js
{ command: 'setProperty', name: 'value', value: '2022-01-01' }
{ command: 'executeJs', value: 'this._inputElementValue = ""' }
```
instead of the following ones, as you might expect:
```js
{ command: …
```
> fix(DatePicker): do not attempt to clear bad input when value is present

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Skip the debouncing on ensureSubCache if the parentItem is already in the connector's cache.
The change has a 4% impact on the `expandedrendertime` metric in the [Grid benchmark tests](https://bender.vaadin.com/buildConfiguration/Flow_Components_BenchmarkTests_Grid?mode=builds).
> refactor: ensure sub-cache for cached parents synchronously

- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldClearValuePage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldClearValueIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
There is an optimization in Flow to only send the final value for an element property in the case the property is updated multiple times using `setProperty()` within one round-trip. In terms of commands sent to the client, the first value set command will be replaced with the final value set command. However, the optimization doesn't apply to `executeJs()`. It is sent as many times as you call it. 
It is therefore possible that
```java
bigDecimalField.setValue(null);
bigDecimalField.setValue(BigDecimal.valueOf(1234));
```
will result in Flow sending the following commands to the browser:
```js
{ command: 'setProperty', name: 'value', value: '1234' }
{ command: 'executeJs', value: 'this._inputElementValue = ""' }
```
instead of the following ones, as you might expect:
```js
{ command: …
```
> fix(BigDecimalField): restore input value when setting a non-empty value

- vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/AbstractComponentIT.java
The PR forces the legacy Chrome headless mode until https://github.com/SeleniumHQ/selenium/issues/11706 is resolved. That issue doesn't let tests adjust the browser window size with `getDriver().manage().window().setSize(...)` which results in their failure.
Related to https://github.com/vaadin/flow/pull/15865
> test: force the legacy Chrome headless mode

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java
Make `DatePicker` implement `HasAriaLabel` interface.
Part of #2946 
Fixes #4707
> feat: make DatePicker implement HasAriaLabel

- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextFieldBase.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/EmailFieldTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/IntegerFieldTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/PasswordFieldTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/TextAreaTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/TextFieldTest.java
Make `TextFieldBase` implement `HasAriaLabel` interface.
Part of #2946 
Blocked by https://github.com/vaadin/web-components/pull/5671
Fixes #4708
> feat: make TextFieldBase implement HasAriaLabel

- vaadin-button-flow-parent/vaadin-button-flow/pom.xml
- vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/Button.java
- vaadin-button-flow-parent/vaadin-button-flow/src/main/resources/META-INF/resources/frontend/buttonFunctions.js
- vaadin-button-flow-parent/vaadin-button-flow/src/test/java/com/vaadin/flow/component/button/tests/ButtonTest.java
Only init disable on click
if actually enabled for button.
Move function to buttonFunctions.js
so each button only needs to call the function.
Moving function makes 5000 buttons request
0.5 MB smaller and lazy init to only calll
method for disbleOnClick buttons drops 1MB
from the request.
> fix: Lazy init of disable on click

- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/ClearValuePage.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/ClearValueIT.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
There is an optimization in Flow to only send the final value for an element property in the case the property is updated multiple times using `setProperty()` within one round-trip. In terms of commands sent to the client, the final value set command will replace the first value set command. However, the optimization doesn't apply to `executeJs()`. It is sent as many times as you call it. 
It is therefore possible that
```java
timePicker.setValue(null);
timePicker.setValue(LocalTime.of(12, 0));
```
will result in Flow sending the following commands to the browser:
```js
{ command: 'setProperty', name: 'value', value: '12:00' }
{ command: 'executeJs', value: 'this._inputElementValue = ""' }
```
instead of the following ones, as you might expect:
```js
{ command: 'setProperty', name: …
```
> fix(TimePicker): do not attempt to clear bad input when value is present 

- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java
Make `TimePicker` implement `HasAriaLabel` interface.
Part of #2946 
Fixes #4710
> feat: make TimePicker implement HasAriaLabel

- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldClearValuePage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldClearValueIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
A manual cherry-pick of the following fix to `23.3`:
- #4834
> fix: restore input value when setting a non-empty value (#4834) (CP: 23.3)

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeComponentColumnsIT.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-directive.js
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js
Passing nodes as such to Lit for rendering seems to have issues. I assume it relates to how Lit caches what it renders (since removing the `_$litPart$` property from the cell content element also fixes it): passing the same element instance vs passing a fresh new wrapper instance.
~Wrapping the nodes in document fragments and then passing the fragment instead works more reliably.~ 
UPD: Rendering the nodes via a custom Lit directive that compares them against the real DOM rather than `_$litPart$_` to see if they should be re-rendered fixes the issue, see https://github.com/vaadin/flow-components/pull/4822#issuecomment-1491514853.
Fixes https://github.com/vaadin/flow-components/issues/4821
Bugfix
> fix: render flow components via a custom Lit directive

- vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/main/java/com/vaadin/flow/component/notification/tests/NotificationView.java
- vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/test/java/com/vaadin/flow/component/notification/tests/NotificationIT.java
- vaadin-notification-flow-parent/vaadin-notification-testbench/src/main/java/com/vaadin/flow/component/notification/testbench/NotificationElement.java
If a `Notification` is being animated open and it contains text, `WebElement.getText()` may still return empty if the notification card hasn't become fully visible yet. This manifests especially with Notifications that are positioned at the top of the screen so that they slide down until visible.
This PR works around the issue by making `getCard()` wait until the notification content is considered visible.
Fixes https://github.com/vaadin/flow-components/issues/4921
- Bugfix
> fix: wait until content visible in notification element

- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/TextRenderer.java
Users might assume that using a built-in renderer such as the `TextRenderer` in the `Grid` columns would work fast. However, `TextRenderer` is currently a `ComponentRenderer` which makes it unnecessarily heavy for its purpose with components that support client-side rendering such as `Grid`.
This PR refactors `TextRenderer` to be a `BasicRenderer` which is a hybrid type renderer that works as a
- `ComponentRenderer` for components that render `Component`s on the server-side (RadioButtonGroup...)
- `LitRenderer` for components that support client-side renderering (Grid...)
Refactor / Performance enhancement
> refactor: make TextRenderer extend BasicRenderer

- vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/test/flow-component-renderer.test.ts
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-directive.js
Fixes a regression from https://github.com/vaadin/flow-components/pull/4920, where removing the content of a component renderer, for example when closing a grid details cell, would not remove the existing content node.
> fix: remove old node when nodeid is not defined

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/dataview/AbstractItemCountGridPage.java
`ItemCountEstimateGridIT.itemCountEstimateGrid_estimateLessThanCurrentRange_estimateNotChanged` fails consistently on my system, apparently because size of the grid is tied to the size of the browser window. Let's use a fixed grid size to get a consistent setup regardless of the size of the browser window.
> test: use fixed grid height in count estimate tests

- vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java
- vaadin-details-flow-parent/vaadin-details-flow/src/test/java/com/vaadin/flow/component/details/DetailsTest.java
> fix: allow unregistering event handlers through event (#4909) (CP: 14.10)

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/PreMultiSortedIT.java
This test fails quite often in 14.10 and 14.9 snapshots validation. The test uses a page size of 5, and then does an assertion on row 6. Though I can't reproduce the test failure locally it's visible that it first loads the first page and then later on the remaining pages, so my guess is that at the time of the assertion row 6 might not have loaded yet. Adding a wait for the row's text to appear in the DOM should make this more reliable.
> test: fix flaky sorting test

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ColumnAutoWidthPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ColumnAutoWidthIT.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-directive.js
Currently the `flowComponentDirective` is wrapped into an `until` directive, which breaks the auto-width feature when refreshing items. It seems like the `until` is not needed anymore now that the logic has been refactored into its own directive, and the IT mentioned in the comment passes without it.
Fixes #4944
> fix: run component renderer in sync

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java
Currently the `Chart` class is not directly referenced from `Spreadsheet`, as the `DefaultChartCreator` class that creates  charts is not directly referenced in the spreadsheet code. This results in the chart JS sources not being included in the production bundle, and at runtime an additional fallback bundle needs to be loaded, increasing the overall amount of JS that is being loaded. Apart from that it breaks 24.1 snapshots, where the fallback bundle is (at least at this point in time) not loaded anymore.
Adding an explicit reference to the `Chart` class fixes that.
> fix: add explicit reference to Chart class

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNav.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java
Removes fluency from the SideNav API, to better align with the rest of the components.
Fixes vaadin/vcf-nav#20
> refactor: remove fluency from SideNav API to align with rest of Vaadin

- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
Added two constructors to Dialog Component. It is very frequent that a dialog includes a title so these constructors would help this use case. Also this way Flow Dialog would have the same signatures than V8 Window constructors helping upgrading V8 apps.
```java 
public Dialog(String title);
public Dialog(String title, Component... components);
```
Fixes #4987
> feat: add Dialog constructors with title parameter

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/main/java/com/vaadin/flow/component/sidenav/tests/SideNavHierarchyPage.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/main/java/com/vaadin/flow/component/sidenav/tests/SideNavPage.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavHierarchyIT.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavIT.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNav.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-testbench/src/main/java/com/vaadin/flow/component/sidenav/testbench/SideNavElement.java
The Flow API has setExpanded() method to have the ability to programmatically expand/collapse SideNav and SideNavItems (if they have a hierarchical structure). There is also `isExpanded()` method on both components to check the expanded state. However, this method does not return correct state is user clicks on the expand/collapse button the browser. The state of the client property is not synchronized back to the server.
> fix: synchronize expanded/collapsed state to server

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-selection.test.ts
The PR adds web-test-runner tests that verify the correct setting of `activeItem` in single selection mode when there is server => client communication.
> test: add tests for activeItem in single selection mode

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-selection-multi-mode.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
The PR updates `$connector.doSelection` to prevent adding duplicate items to `selectedItems` which can happen when selecting the same item first through the client and then through the server. Previously, possible duplicate items were removed by `$connector.updateFlatItems` but as of https://github.com/vaadin/flow-components/pull/4902 that method is no longer called on selection. Duplicate items are problematic because `$connector.doDeselection` is currently designed so that it only removes the first occurrence of an item, which can lead to UI inconsistencies as was observed in the issue.
Fixes https://github.com/vaadin/flow-components/issues/4967
> fix: prevent adding duplicate items to selectedItems on selection

- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
`BigDecimalField` uses `vaadin-text-field` as a base for its custom web component: 
https://github.com/vaadin/flow-components/blob/876adfa0eb2097558f5f35de0eeb1aac08d959f8/vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/resources/META-INF/resources/frontend/vaadin-big-decimal-field.js#L19-L20
With a recent change in Flow, all pages / routes have their own bundle / chunk in production mode. As `BigDecimalField` doesn't explicitly reference `TextField`, and doesn't have annotations to include it, the `vaadin-text-field` web component might not be loaded if a page only uses big decimal fields, but no text fields. That is the case in our integration test pages which started failing due to this change.
Adding an explicit reference to `TextField` should ensure that the …
> refactor: make BigDecimalField reference TextField

- vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
- vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java
Make `Select` implement `HasAriaLabel` interface.
Part of #2946 
Blocked by https://github.com/vaadin/web-components/pull/5781
Fixes #4711
> feat: make Select implement HasAriaLabel

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/pom.xml
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavItemTest.java
Use `ComponentUtil.getRouter` to access the router, which under the hood does the same as the current logic. Also add tests for creating a nav item from a view, and setting the path from a view.
> refactor: simplify accessing router in SideNavItem

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridEmptyPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridEmptyIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Cherry-pick of https://github.com/vaadin/flow-components/pull/5040
Replaced the connector test with an integration test, as the connector test setup is not available in 24.0. The original issue was applying a server-side sort, calling `clearCache` on the grid element has the same effect to reproduce the issue.
> fix: make empty grid clear loading state (CP: 24.0)

- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/FileBuffer.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/MultiFileBuffer.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/UploadSerializableTest.java
Currently the file buffer implementations in `Upload` serialize the output streams of uploaded files, which can not be deserialized:
```
java.io.InvalidClassException: com.vaadin.flow.component.upload.receivers.UploadOutputStream; no valid constructor
```
This change removes the file data, and with that the output streams, from serialization. As before, uploaded files can not be retrieved after serialization + deserialization. 
Fixes https://github.com/vaadin/flow-components/issues/5039
- Bugfix
> fix: do not serialize file output stream

- vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/FeatureTextPage.java
- vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/FeatureTextIT.java
- vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/style/TextStyle.java
- vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/synchronization/styles.js
- vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/AbstractConfigurationObjectTest.java
- vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/ConfigurationTestUtil.java
- vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/style/TextStyleTest.java
Currently `textBaseline` in `TextStyle` has no default value, which causes synchronization into the OL `Text` class to fail if the developer does not provide a custom value. 
This change adds a default, and also adapts the sync logic to handle missing values.
- Bugfix
> fix: add default for marker text baseline

- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/dataview/CheckboxGroupDataViewTest.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxDataViewTest.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridDataViewTest.java
- vaadin-list-box-flow-parent/vaadin-list-box-flow/src/test/java/com/vaadin/flow/component/listbox/test/dataview/ListBoxDataViewTest.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/dataview/RadioButtonGroupDataViewTest.java
- vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/data/SelectDataViewTest.java
The new data provider API was reverted by https://github.com/vaadin/flow/pull/16774.
> Revert "chore: fix compilation failures for new data provider API (#4982)"

- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java
Make `RadioButtonGroup` implement `HasAriaLabel` interface.
Part of #2946 
Blocked by https://github.com/vaadin/web-components/pull/5818
Fixes #4715
> feat: make RadioButtonGroup implement HasAriaLabel

- vaadin-login-flow-parent/vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginI18n.java
- vaadin-login-flow-parent/vaadin-login-flow/src/main/resources/com/vaadin/flow/component/login/i18n.json
- vaadin-login-flow-parent/vaadin-login-flow/src/test/java/com/vaadin/flow/component/login/LoginFormI18nTest.java
Follow up of https://github.com/vaadin/web-components/pull/5836.
Adds the new properties to the `LoginI18n.ErrorMessage` class.
Fixes https://github.com/vaadin/web-components/issues/101
> feat: allow setting error message for login fields

- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupTest.java
Make `RadioButtonGroup` implement `HasAriaLabel` interface.
Part of #2946 
Blocked by https://github.com/vaadin/web-components/pull/5818
Fixes #4714
> feat: make CheckBoxGroup implement HasAriaLabel

- vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/main/java/com/vaadin/flow/component/notification/tests/NotificationView.java
- vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/NotificationVariant.java
Theme variant enum for Warning notification.
Fixes https://github.com/vaadin/web-components/issues/4110
> feat: notification warning variant

- scripts/wtr.js
web-test-runner tests currently fail in snapshot validation, a recent change in Flow seems to now clean up frontend resources (package.json, node_modules) after a build, which means WTR can't load dependencies during the tests.
Ensuring that an empty node_modules / package.json exist before the Flow build fixes that because the build does not remove folders/files that existed before.
> chore: fix WTR test setup

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavIT.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-testbench/src/main/java/com/vaadin/flow/component/sidenav/testbench/SideNavElement.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-testbench/src/main/java/com/vaadin/flow/component/sidenav/testbench/SideNavItemElement.java
This PR addresses some shortcomings and issues discovered during the Start integration of `SideNav`. 
Improvements regarding item access through the component:
- `includeChildren` option for `SideNavElement.getItems`
- querying items with the new `SideNavElement.getItemByPath` and `SideNavElement.getItemByLabel`
- getting the active item with the new `SideNavElement.getSelectedItem`
Improvements regarding the individual items:
- `includeChildren` option for `SideNavItemElement.getItems`
- a separate way of clicking the anchor via `SideNavItemElement.clickAnchor`
- `SideNavItemElement.navigate` was renamed to `SideNavItemElement.click` (overrides the regular `click`)
- getting the path via `SideNavItemElement.getPath`
- bug fix in `SideNavItemElement.getLabel`
Note: Should be back-ported …
> refactor: improve testbench api

- vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow/src/main/java/com/vaadin/flow/theme/lumo/LumoUtility.java
Adds constants for new warning colors to Lumo Utility Class constants in Flow
Fixes https://github.com/vaadin/web-components/issues/1655
> feat: add constants for warning colors in Lumo Utility Classes

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-tree.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
This reverts commit b6ff3ffada160ad5ab90b3b95de8cd37e39fbf75 that causes the regression described in #5045.
I am planning to add a test with the same use case in a separate PR.
Fixes #5045
> Revert "refactor: avoid an extra render on grid connector confirm parent (#4894)"

- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/ListBoxBase.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
- vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
Some components, like Grid and ComboBox, have publicly exposed `setDataProvider` and `getDataProvider` methods - others do not, and they were modified recently to have these methods private. These two methods are made public in this patch, mainly for API consistency and for letting developers use filterable data providers (non Void filter generic parameter), which is not possible with `setItems` methods in most of the components.
Motivated by a comment from user https://github.com/vaadin/flow/issues/15665#issuecomment-1527067023 and internal discussion about having public `getDataProvider` method in all components.
> feat: Expose data provider setter and getters in components

- vaadin-accordion-flow-parent/vaadin-accordion-flow/src/main/java/com/vaadin/flow/component/accordion/AccordionPanel.java
- vaadin-details-flow-parent/vaadin-details-flow-integration-tests/src/main/java/com/vaadin/flow/component/details/tests/Home.java
- vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java
- vaadin-details-flow-parent/vaadin-details-flow/src/test/java/com/vaadin/flow/component/details/DetailsTest.java
This PR 
- deprecates `addContent` and `setContent`
- implements `HasComponents`
- overrides the component handling logic to use the custom component container
Fixes #5085
> refactor: implement hascomponents for details and deprecate old api

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SheetState.java
Currently the `SheetState` class uses a `static ` reference to its spreadsheet, which means:
- the last constructed spreadsheet will be kept in memory indefinitely, causing a minor memory leak
- previously constructed spreadsheets will use the last constructed spreadsheet for storing selected cells
This change removes the static references (intention might have been to use `final` instead).
Related to this comment: https://github.com/vaadin/flow-components/issues/5130#issuecomment-1596800160
- Bugfix
> fix: remove static spreadsheet reference

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
As a follow-up to https://github.com/vaadin/web-components/pull/5962, updates the grid connector to use `_getRenderedRows`.
> refactor: update grid connector to use _getRenderedRows

- vaadin-split-layout-flow-parent/vaadin-split-layout-flow-integration-tests/src/main/java/com/vaadin/flow/component/splitlayout/test/SplitterPositionView.java
- vaadin-split-layout-flow-parent/vaadin-split-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitterPositionIT.java
- vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
- vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitLayoutUnitTest.java
As requested in the issue, it's now possible to get the new splitter position in drag end event after moving the splitter manually. Also added the new primary and secondary components width to the same event.
Implementation based on this recipe https://github.com/vaadin/cookbook/pull/264
Fixes #1517
> feat: access updated splitter position from drag end event

- vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/BasicUseIT.java
- vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java
Added a flag that was introduced by https://github.com/vaadin/web-components/pull/5955 
This indicates that the button created by the Flow counterpart is the default one.
- Fix
> fix: mark CRUD buttons as default to handle them properly

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
Attempt to clarify that `TreeGrid.scrollToIndex(int rowIndex)` only considers rows in the root level of the tree, and `TreeGrid.scrollToIndex(int... indexes)` allows scrolling to nested items.
Part of https://github.com/vaadin/flow-components/issues/5182
> docs: clarify TreeGrid.scrollToIndex JavaDoc

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/frontend/side-nav-in-template.js
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/pom.xml
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/main/java/com/vaadin/flow/component/sidenav/tests/SideNavInTemplatePage.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavInTemplateIT.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-testbench/src/main/java/com/vaadin/flow/component/sidenav/testbench/SideNavItemElement.java
Fixes #5143
- Updated the script used by `getLabel()` to filter out empty "anonymous" text nodes,
- Added `SideNavInTemplateIT` using `LitTemplate` where this case was reproducible.
- Bugfix
> fix: make SideNavItemElement#getLabel() return correct text

- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
The PR adds a check for the presence of `this.inputElement` before `BigDecimalField` assigns a value to it. As discovered, `this.inputElement` can be `undefined` during initialization when `BigDecimalField` is rendered by the component render. 
Only version 23.3 is affected. The latest versions are using a setter that includes that check already.
Fixes https://github.com/vaadin/flow-components/issues/5169
> fix: check for presence of inputElement before assigning a value

- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/validation/CheckboxGroupBasicValidationTest.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/validation/ComboBoxBasicValidationTest.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/validation/MultiSelectComboBoxBasicValidationTest.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/validation/BasicValidationTest.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BasicValidationTest.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasValidationProperties.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/validation/AbstractBasicValidationTest.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/validation/BasicValidationTest.java
- vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
- vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/validation/BasicValidationTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/BigDecimalFieldBasicValidationTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/EmailFieldBasicValidationTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/IntegerFieldBasicValidationTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/NumberFieldBasicValidationTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/PasswordFieldBasicValidationTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/TextAreaBasicValidationTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/TextFieldBasicValidationTest.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/BasicValidationTest.java
The PR introduces a manual validation mode that disables the component's built-in validation to allow developers to have manual control over the component's invalid state without conflicts.
Depends on 
- https://github.com/vaadin/flow/pull/17029
Fixes https://github.com/vaadin/flow-components/issues/5074, https://github.com/vaadin/flow-components/issues/4804
> feat: introduce manual validation mode for manual invalid state control

- vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
- vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitLayoutUnitTest.java
Fixes a regression from #5158. If the current splitter position is `null`, which is the initial value, then it was not assignable as `double`.
Fixes #5224 
- Bugfix
> fix: handle initial null position when calculating splitter position

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridScrollToPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridScrollToIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Reverts #4854 which introduced a regression when using `scrollToIndex` and adds a respective test.
Fixes https://github.com/vaadin/flow-components/issues/5187
> Revert "refactor: preload items on grid scroll to index (#4854)"

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Refactors the `isLoading` method to get rid of duplicate checks by reusing the [original `isLoading` method](https://github.com/vaadin/web-components/blob/21e3826c882c863909aa4b48b57369b799ef2b59/packages/grid/src/vaadin-grid-data-provider-mixin.js#L41C16-L48) provided by the web component.
> refactor: remove duplicate checks from isLoading

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java
Reintroduce removed constructor.
> refactor: reintroduce side nav item constructor

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavItemTest.java
This PR
- fixes the case where an alias does not require some of the provided route parameters, and therefore does not get added
- adds tests for not adding aliases that have parameters that are not provided
- expands the Side Nav Item route parameter tests with more aliases
> fix: apply route parameters to side nav item correctly

- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/InertDialogPage.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/InertDialogIT.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogCloseActionListenerTest.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogOpenedChangeListenerTest.java
Currently a dialog's opened state can desync between the client and the server, for example:
- on mouse down, a focus out is triggered, which opens a second modal dialog, which sets the first dialog to be inert
- on the subsequent click event, the dialog closes on the client, but the server will never process the opened-changed event from the client because the dialog is inert, so the server-side dialog stays open
This fix involves:
- prevent the client dialog overlay from closing itself on outside click and escape presses (should be the only ways to close a dialog on the client)
- instead, make a call to the server component to close itself - if the dialog has become inert in the meantime this call will never be processed and the dialog will stay open on both the client and the server
- …
> fix: keep dialog open when inert

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewSelectionIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridSelectionColumn.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelWithHierarchicalDataProviderTest.java
Reuse the `GridSelectionColumnBaseMixin` introduced with https://github.com/vaadin/web-components/pull/6143 in the `<vaadin-grid-flow-selection-column>` element.
Closes https://github.com/vaadin/web-components/issues/6103
- Refactoring
> refactor: reuse GridSelectionColumnBaseMixin in Flow Grid selection column

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
The item key caches are currently only created and then again removed in `clear` - there is no other usage. They can be removed.
> refactor: remove item key caches

- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarTooltipPage.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarTooltipIT.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
Makes the previously private `setTooltipText` in `MenuBar` public, which enables changing a tooltip's text dynamically.
Closes https://github.com/vaadin/flow-components/issues/5226
> chore: expose MenuBar setTooltipText

- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/EmailFieldBasicValidationTest.java
As indicated in issue https://github.com/vaadin/flow/issues/17333, this PR changes the validation pattern of an email address by invalidating the dot-dot in the domain name.
In PR https://github.com/vaadin/flow/pull/17353, I made EmailValidator.PATTERN public to use it in EmailField class. So the pattern is not longer duplicates between EmailValidator and EmailField
Fixes vaadin/flow#17333
> fix: reject emails with double dot between domain and tld

- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/EmailFieldBasicValidationTest.java
> fix: reject emails with double dot between domain and tld (#5327) (CP: 24.1)

- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/EmailFieldBasicValidationTest.java
> fix: reject emails with double dot between domain and tld (#5327) (CP: 24.0)

- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/EmailFieldTest.java
> fix: reject emails with double dot between domain and tld (#5327) (CP:23.3)

- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
In the Dialog#ensureAttached callback, check if the Dialog is still open before adding it to the UI and registering it in the modal stack.
Fixes #5345
> fix: only auto add dialog if it is still open

- vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
- vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java
`getItemPosition` in `Select` is delegated to the underlying `InternalListBox` field to return the correct item position.
Fixes #1094
> fix: return the item position of an item in Select if it exists

- vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/AbstractIcon.java
- vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/Icon.java
Use the correct type in the `ClickNotifier` generic param.
Fixes #5395
> fix: use correct generic type in ClickNotifier

- vaadin-icons-flow-parent/vaadin-icons-flow-integration-tests/src/main/java/com/vaadin/flow/component/icon/demo/FontIconPage.java
- vaadin-icons-flow-parent/vaadin-icons-flow-integration-tests/src/test/java/com/vaadin/flow/component/icon/tests/FontIconIT.java
- vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/FontIcon.java
- vaadin-icons-flow-parent/vaadin-icons-flow/src/test/java/com/vaadin/flow/component/icon/tests/FontIconTest.java
Adds `FontIcon` component, which can be used to render glyphs from an icon font collection.
Related to https://github.com/vaadin/web-components/issues/6212
> feat: add FontIcon component

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridScrollToPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridScrollToIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
With the empty grid stuck in loading state [fix](https://github.com/vaadin/flow-components/pull/5043), it became possible that the size is set after `scrollToIndex` is called. This issue is only present in v23.3.
This PR uses `queueMicrotask` in order to delay the `scrollToIndex` call just enough to make sure that the size is initialized.
Fixes #5375
> fix: grid scroll to index after setting size

- vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
- vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java
> fix: return the item position of an item in Select if it exists (#5369) (CP: 24.0)

- vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/confirmdialog/tests/ShortcutsPage.java
- vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/tests/ShortcutsIT.java
- vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
Fixes #5389
Added `Shortcuts.setShortcutListenOnElement()` call similarly to how it was done for `Dialog` in #725
- Bugfix
> fix: set listenOn to make shortcuts work in ConfirmDialog

- vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
- vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java
> fix: return the item position of an item in Select if it exists (#5369) (CP: 14.11)

- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/SlotUtils.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/SlotUtilsTest.java
> fix: remove slot attribute from children in SlotUtils.clearSlot

- vaadin-icons-flow-parent/vaadin-icons-flow-integration-tests/src/test/java/com/vaadin/flow/component/icon/tests/FontIconIT.java
Ignore a `FontIcon` IT which currently relies on the web component API of an alpha version. This is to enable smooth web component version bumps. Let's re-enable the test once the `FontIcon` API stabilizes.
Tests
> test: ignore a font icon IT to enable web component bumps

- vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/FontIcon.java
- vaadin-icons-flow-parent/vaadin-icons-flow/src/test/java/com/vaadin/flow/component/icon/tests/FontIconTest.java
Related to https://github.com/vaadin/web-components/pull/6452
As a follow-up of the `FontIcon` DX test results, we decided to split the `FontIcon::setChar`, which currently accepts either a code point or a ligature, into separate `FontIcon::setChar` and `FontIcon::setLigature` methods.
Since "char" can no longer be a ligature name, the updated `FontIcon::setChar` method now also supports unprefixed code points (like "ea0e").
Before:
```java
var lumoIcon = new FontIcon();
lumoIcon.setFontFamily("lumo-icons");
lumoIcon.setChar("\uea0e");
var materialIcon = new FontIcon();
materialIcon.setFontFamily("Material Icons");
materialIcon.setChar("face");
```
After:
```java
var lumoIcon = new FontIcon();
lumoIcon.setFontFamily("lumo-icons");
lumoIcon.setChar("ea0e");
var materialIcon = new …
```
> feat: split char into ligature and char

- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/tests/RichTextEditorDetachReattachIT.java
Added a check to cover an initially set HTML value for a view containing this code:
```java
RichTextEditor editor = new RichTextEditor();
editor.setValue("<h1>foo</h1>");
```
This change is intended to cover the scenario implemented in https://github.com/vaadin/web-components/pull/6506
- Test
> test: update DetachReattachIT to check for initial value

- vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/test/flow-component-renderer.test.ts
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-directive.js
There's currently an issue in flow-component-directive that can cause an infinite loop in case a re-render is requested for a node that has already been removed from the Flow client registry.
The bug can be reproduced on the `/vaadin-grid/treegrid-component-renderer` IT page by sorting the first column. The issue is sneaky because the user doesn't necessarily notice there's an infinite loop running behind the scene, but you can catch it with a debugger.
This PR fixes the issue by storing the id of a node render retry timeout, and then clearing the timeout whenever the directive is requested to update (and also on disconnect).
Bugfix
> fix: ignore removed nodes in flow component directive

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Remove an unnecessary check from the grid connector. `<vaadin-grid>` had the [`_debounceIncreasePool` debouncer in version 20](https://github.com/vaadin/web-components/blob/03da16363a1e41e29361cf0ac6d2664d9d801c19/packages/vaadin-grid/src/vaadin-grid-scroller.js#L181), but it's [removed](https://github.com/vaadin/web-components/commit/7d61135602943079c6029e1f6971e20d42aa5884) since version 21.
> chore: remove unused connector logic

- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java
- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabsTest.java
Certain [internal logic](https://github.com/vaadin/flow-components/blob/51aefa5f2512be6644b031da1aadcb55e6725a52/vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java#L674) of `Tabs` currently uses `isEnabled()` to determine if the currently selected tab is enabled or not. Using `isEnabled()` is problematic for this purpose because it also [traverses the node's ancestors](https://github.com/vaadin/flow/blob/cb63006b56777d46c881d41bc416d8d7189cd47d/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L1158) and assumes a tab is disabled even if the tab itself was actually enabled but one of its ancestor containers wasn't.
This PR addresses the issue by changing the logic to use …
> fix: ignore ancestor enabled state in tabs internal logic

- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java
- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabsTest.java
Manually cherry-pick #5506 to 23.3
> fix: ignore ancestor enabled state in tabs internal logic (#5506)

- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/TooltipTest.java
With the Flow [change](https://github.com/vaadin/flow/pull/17695) regarding `removeFromTree`, it is now necessary to explicitly specify if there should be no detach event sent to the client while moving components between different UIs. This PR adds the boolean for the `Tooltip` target attach listener and the relevant test.
Related issue: #5427
> fix: do not send detach on removeFromTree

- vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/main/java/com/vaadin/flow/data/renderer/tests/ComponentRendererInNewThreadPage.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/test/java/com/vaadin/flow/data/renderer/tests/ComponentRendererInNewThreadIT.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java
When a grid witch a component column is initialized in a new thread, the template expression is determined while `UI.getCurrent()` is still `null` for that thread. `ComponentRenderer` uses it to get `appid`, so when the grid is finally added and rendered, the template expression will have the wrong `appid` and functionalities like `getNodeById` will break.
This PR makes it so that the element renderer is initially set only if the container element is attached. This way, the UI is already defined when the template expression is calculated and the grid is rendered correctly.
Fixes #5493
> fix: set element renderer initially only if container is attached

- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/tests/MainView.java
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/tests/BasicIT.java
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js
In the GridPro connector, `getEditorValue` from the web component is overridden to do nothing an return. The comment there suggests that that block was introduced to prevent flickering. This override interferes with the item property change event mechanism since it is used to determine whether there has been a change. With the current way, it always returns `undefined`, causing the comparison to fail and an unwanted event to be fired. 
This PR removes the override. The flickering does not appear to be there even without the override.
Fixes #5529
> fix: do not override geteditorvalue for custom editor

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/FormulasTest.java
With an Apache POI version bump [PR](https://github.com/vaadin/flow-components/pull/5525), a formula cell [test](https://github.com/vaadin/flow-components/blob/main/vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/FormulasTest.java#L40-L48) fails. It seems that it is resolved when the cell is explicitly refreshed after being converted into a formula cell.
This PR updates the test to refresh the cell, and assert the values accordingly.
> test: refresh cell after conversion to formula cell

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractRow.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/ColumnBase.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/FooterRow.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/HeaderRow.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java
Add support for setting custom `part` names to Grid header and footer cells.
Part of https://github.com/vaadin/web-components/issues/1434
Depends on https://github.com/vaadin/web-components/pull/6629
Feature
> feat: grid column header and footer part names

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
The PR refactors the field components to make them prefer `valueEquals` to `Objects.equals` where possible, as the former appears to be an appropriate API to be used in such cases. It's also shorter.
> refactor: prefer valueEquals to Objects.equals

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/validation/BasicValidationIT.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/validation/BinderValidationIT.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BasicValidationIT.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/BasicValidationIT.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/BinderValidationIT.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
The PR prevents field components that support bad input from invalidating when clearing a valid value programmatically.
Depends on 
- #5586 
Fixes #5462 
Part of #5537
> fix: do not invalidate when clearing a valid value

- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextFieldBase.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/EmailFieldTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/IntegerFieldTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/PasswordFieldTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/TextAreaTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/TextFieldTest.java
Ensures that TextField initializes its client-side value property with an empty string to prevent Polymer from generating `value-changed` events when converting `null` to `""` on its own. Refer to https://github.com/vaadin/flow-components/pull/5581#issuecomment-1764670968 for more details on why this is necessary.
Note, the same fix was applied to DatePicker a while ago: https://github.com/vaadin/flow-components/pull/2878.
Part of #5537
> fix: ensure client-side value property is initialized

- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuConnector.js
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarTestPage.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarPageIT.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBarRootItem.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/resources/META-INF/resources/frontend/menubarConnector.js
Add functionality to copy the class name value defined on a `MenuBar` item to its parent button on the root level.
That allows users to specify selectors for the button and for the item to style the components
differently.
Fixes https://github.com/vaadin/web-components/issues/5342
> feat: reflect class name set on item to root level button in MenuBar

- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/NativeButtonRenderer.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/test/java/com/vaadin/flow/data/renderer/NativeButtonRendererTest.java
Use `CopyOnWriteArrayList` in `NativeButtonRenderer` to avoid a possible concurrent modification exception.
Bugfix
> fix: avoid a concurrent modification in native button renderer

- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBinderValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBinderValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/IntegerFieldBasicValidationTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/NumberFieldBasicValidationTest.java
The PR refactors NumberField and IntegerField to make them trigger validation on `unparsable-change` event instead of the `validated` event.
Depends on 
- https://github.com/vaadin/web-components/pull/6599
- https://github.com/vaadin/flow-components/pull/5570
- https://github.com/vaadin/flow-components/pull/5590
Precedes:
- #5592 
> **Warning**
Part of #5537
> fix!(NumberField): use unparsable-change instead of validated event

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/validation/BasicValidationPage.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/validation/BinderValidationPage.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/validation/BasicValidationIT.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/validation/BinderValidationIT.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/vite.config.ts
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/validation/BasicValidationTest.java
The PR refactors DatePicker to make it trigger validation on `unparsable-change` event instead of the `validated` event.
Depends on 
- https://github.com/vaadin/web-components/pull/6594
- https://github.com/vaadin/flow-components/pull/5570
> **Warning**
Part of #5537
> fix!(DatePicker): use unparsable-change instead of validated event

- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBinderValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldEagerBinderValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldEagerValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldEagerBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldEagerValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/BigDecimalFieldBasicValidationTest.java
The PR refactors BigDecimalField to make it trigger validation whenever a `value-changed` event is received from the client while the value still remains empty on the server, instead of relying on the `validated` event.
Depends on
- https://github.com/vaadin/flow-components/pull/5590
> **Warning**
Part of #5537
> fix!(BigDecimalField): use custom logic instead of validated event

- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/validation/BasicValidationPage.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/validation/BinderValidationPage.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/BasicValidationIT.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/BinderValidationIT.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/BasicValidationTest.java
The PR refactors TimePicker to make it trigger validation on `unparsable-change` event instead of the `validated` event.
Depends on 
- https://github.com/vaadin/web-components/pull/6604
- https://github.com/vaadin/flow-components/pull/5570
> **Warning**
Part of #5537
> fix!(TimePicker): use unparsable-change instead of validated event

- vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
- vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitLayoutUnitTest.java
Organize the constructor such that all call to the `SplitLayout(Orientation)`, which ensures that the component is initialized correctly with all constructors.
Fixes #5563
> fix: ensure all SplitLayout constructors call to addSplitterDragendListener

- vaadin-split-layout-flow-parent/vaadin-split-layout-flow-integration-tests/src/main/java/com/vaadin/flow/component/splitlayout/test/SplitterPositionView.java
- vaadin-split-layout-flow-parent/vaadin-split-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitterPositionIT.java
- vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
Change the `@EventData` selector to query for the direct children of the `SplitLayout` to avoid returning the wrong values in case a nested split layout is in one of the slots.
Also refactored to change the names of the variables, because they don't map to widths in case of vertical splits.
Fix #5602
> fix: make sure to get direct children in SplitterDragendEvent

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
The PR replaces the custom method `getCacheByKey` with the `getItemContext` method added recently to DataProviderController in https://github.com/vaadin/web-components/pull/6613.
> refactor: replace getCacheByKey with getItemContext

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandedAutoWidthPreserveOnRefreshPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandedAutoWidthPreserveOnRefreshIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes https://github.com/vaadin/flow-components/issues/5595
The related [fix](https://github.com/vaadin/web-components/pull/6684) for V24 does not fix the issue in V23 because the component has changed between the major versions. This is why a different fix is required.
Bugfix
> fix: flush grid virtualizer until row count stabilizes

- vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/validation/AbstractValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBinderValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBinderValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBinderValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextFieldBinderValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextFieldBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java
The PR removes the subscription to the `validated` event from the remaining text field components.
> **Warning**
Part of #5537
> fix!(TextField): remove validated event subscription

- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/SubDialogPage.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/SubDialogIT.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js
Fixes https://github.com/vaadin/flow-components/issues/5615
The current implementation of `setChildNodes` in `flow-component-renderer` always clears the root of the content and then adds the desired content back. This causes a detach-reattach for all content nodes on re-render, which can have unexpected side effects such as losing the scroll position. This issue affects Dialog and Notification.
This PR fixes the issue by changing the function to use `lit`, which handles the re-renders more gracefully so that the content nodes don't get unnecessarily detached.
Bugfix
> fix: do not detach and reattach content on re-render

- vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/validation/BasicValidationPage.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/validation/BinderValidationPage.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/validation/BasicValidationIT.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/validation/BinderValidationIT.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/validation/ComboBoxBasicValidationPage.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/validation/ComboBoxBinderValidationPage.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/validation/MultiSelectComboBoxBasicValidationPage.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/validation/MultiSelectComboBoxBinderValidationPage.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/validation/ComboBoxBasicValidationIT.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/validation/ComboBoxBinderValidationIT.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/validation/MultiSelectComboBoxBasicValidationIT.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/validation/MultiSelectComboBoxBinderValidationIT.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/validation/BasicValidationPage.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/validation/BinderValidationPage.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/validation/BasicValidationIT.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/validation/BinderValidationIT.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
- vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/main/java/com/vaadin/flow/component/select/tests/validation/BasicValidationPage.java
- vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/main/java/com/vaadin/flow/component/select/tests/validation/BinderValidationPage.java
- vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/tests/validation/BasicValidationIT.java
- vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/tests/validation/BinderValidationIT.java
- vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
The PR removes the subscription to the `validated` event from the remaining components.
> **Warning**
> It's a behavior altering change because it removes validation on blur when the value hasn't changed.
Part of #5537
> fix!: remove validated event subscription

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.html
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js
Part of https://github.com/vaadin/web-components/issues/6737
This PR fixes the issue with the `vaadin-checkbox` in the Flow selection column not getting focus on <kbd>Enter</kbd> key press.
The actual problem is that focus target detection falls back to [`firstElementChild`](https://github.com/vaadin/vaadin-grid/blob/d6073f1a9224be32ce3d0ae152cb1fa08601572e/src/vaadin-grid-keyboard-navigation-mixin.html#L387-L388) which is the `<style>` element 🙈 
- Bugfix
> fix: set focus-target attribute on the select all checkbox (14.11)

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.html
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js
Same as #5672 but for `14.10` branch.
- Bugfix
> fix: set focus-target attribute on the select all checkbox (14.10)

- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/TooltipTest.java
This change will make `Tooltip.forComponent(component)` return an existing Tooltip handle in case one was already created before.
Fixes https://github.com/vaadin/flow-components/issues/4736
Bugfix
> fix: make Tooltip.forComponent return existing tooltip handle

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DragAndDropGridPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DragAndDropGridIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Remove DnD mobile polyfill from Grid. The polyfill was initially added to support DnD on mobile Safari which was lacking the feature back then. Safari has had native DnD support since iOS 15 so the polyfill is no longer required.
Additionally, including the polyfill seems to be causing an [error in certain cases](https://github.com/vaadin/flow-components/issues/1434#issuecomment-1790897160), so this is labeled as a bugfix.
Bugfix
> fix: remove grid dnd polyfill

- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogContentView.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogContentIT.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js
Fixes https://github.com/vaadin/flow-components/issues/5719
Make `setChildNodes` in `flow-component-renderer.js` use the `flowComponentDirective`.
The current implementation relies on Lit defaults which assume a previously rendered node to still be inside the render container even in the case where it has been manually "hijacked" to another container by some external logic (in this case FlowClient, after calling `dialog.add(content)` again for the same content).
The `flowComponentDirective` is intended specifically for rendering Flow components obtained by node id and has [logic](https://github.com/vaadin/flow-components/blob/13b89ea0674f02872ceb93862fe8bca794d8fa3f/vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-directive.js#L …
> fix: use flowComponentDirective in setChildNodes

- vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
- vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitLayoutUnitTest.java
Change the SplitLayout behavior to remove only the previous component in the same slot when a new component is added to the primary or secondary slots.
SplitLayout currently removes all children first before adding the components to their slots. This might be unexpected when adding a component to the secondary slot leads to detaching the primary component.
Fixes #3586
> fix: remove previous component on slot in add to primary/secondary

- vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/pom.xml
- vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/Scroller.java
- vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/test/java/com/vaadin/flow/component/orderedlayout/tests/ScrollerTest.java
Fixes #3766 
Added Focusable interface to Scroller.
- [ X ] Feature
- [ x ] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [ x ] I have added a description following the guideline.
- [ x ] The issue is created in the corresponding repository and I have referenced it.
- [ x ] I have added tests to ensure my change is effective and works as intended.
- [ x ] New and existing tests are passing locally with my change.
- [ x ] I have performed self-review and corrected misspellings.
- [] I have not completed some of the steps above and my pull request can be closed immediately.
- [ x ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.
> feat: make Scroller implement Focusable

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerCustomFormatPage.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerCustomFormatIT.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
Date picker does a year correction for short year formats when calculating the full year. This correction does not get applied properly when the selection is done through the overlay. The reason is that there is no previously parsed date. 
This PR:
- Refactors the parsing logic to reduce duplication and increase clarity
- Uses the date picker value to correct the century in the first parse after overlay open
- Uses last parsed date to correct the century if last parse attempt is successful and the dates match except the century
- Does not correct the century if last parse attempt was a failure
Fixes #4636
> fix: use last parsed date and value to correct century of short year

- vaadin-split-layout-flow-parent/vaadin-split-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitterPositionIT.java
- vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
Add a call to `setSplitterPosition` on the default `splitter-dragend` listener to force synching the value from the client-side to the server-side. Previously, although we saved the split position in the server when the user changes it in the client, we can't reset it to the previous value from the server because Flow still thinks that the split position hasn't been changed.
This effectively will send a command to the client on every split change, but as it's part of the same roundtrip that the event is triggered, it won't cause any extra communication.
Fixes #2124
> fix: call to setSplitterPoisition on splitter-dragend event

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-sorting.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/shared.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
The PR refactors the grid connector to avoid duplicate requests to the server when sorting. The number of duplicate requests has increased after #4774, but the issue has been present even before. The cause is the grid connector that listened to the `_previousSorters` property to notify the server when the sort model changes. This property changes twice on every `__applySorters()` call because `mapSorters()` always generates a new array when called. Also, the grid can call `__applySorters()` multiple times within a round-trip even when the sort model hasn't changed.
Finding from #5513.
> fix: avoid duplicate requests to the server when sorting

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-sorting.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/shared.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
The PR fixes a bug in the grid connector where sort directions could be applied in an order that didn't match the order in which they were built on the server. This happened because the grid connector only reset the direction of sorters that were missing from the new set of directions, whereas it should've reset the direction for _all_ sorters before applying new directions.
The example scenario:
```js
$connector.setSorterDirections([
{ column: 'name', direction: 'asc' }, 
{ column: 'price', direction: 'asc' }
]);
// The sorters' order: (1) name (2) price – OK
$connector.setSorterDirections([
{ column: 'price', direction: 'asc' }, 
{ column: 'name', direction: 'asc' }
]);
// The sorters' order: (1) name (2) price – WRONG, expected the other way around
```
Finding from …
> fix: apply sort directions in the correct order

- scripts/generateChangeLog.js
previous regex only get the last number from version string. 
for example "23.3.29", it will only return 9 then do plus one, which results in 23.3.210.
> fix: regex to get the version for computing [skip ci]

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
A VaadinRequest is not serializable
> fix: Make request transient so it does not prevent serialization

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComponentRendererPage.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComponentRendererIT.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js
This PR handles the empty nodeid case for Flow component renderer. This is already [handled](https://github.com/vaadin/flow-components/blob/8cebb28a0f8ecb55dc3e79c78da42b4831bcbb42/vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-directive.js#L34-L35) in the newer Flow component directive. With the new change, if a null/undefined node ID is received and there is a rendered child, it is removed.
Note: The test will succeed without the change in v24. The reason is that the Flow component renderer has already been refactored out of the renderer.
Note 2: There is no test added to the renderer package since I could not come up with a good test. This test is added to test at least the use-case provided in the related issue for this …
> fix: handle empty node id in component renderer

- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/UploadView.java
- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/FileRemovedEvent.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
- vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java
Based on the [suggested API](https://github.com/vaadin/flow-components/issues/1342#issuecomment-1827745328), this PR:
- Introduces `addFileRemoveListener` for `Upload`
- Introduces `FileRemovedEvent`
- Fixes the `testClearFileList` test which was a false positive
- Adds a test for the new API
- Makes the `TestBench` API `removeFile` public
**!!! IMPORTANT !!! - Should be merged to the new minor branch.**
Fixes #1342
> feat: implement file remove listener for upload (24.4)

- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/UploadView.java
- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/FileRejectedEvent.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/ProgressUpdateEvent.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
This PR 
- adds file name support to progress update listeners and file rejected listeners
- updates tests in order to check for the file names in events
The file name can be accessed via `FileRejectedEvent.getFileName()` and `ProgressUpdateEvent.getFileName()`.
**!!! IMPORTANT !!! - Should be merged to the new minor branch.**
Fixes #1328 
Fixes #3087
> feat: add file name to progress and file rejected listeners

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxLitRendererPage.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxLitRendererIT.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxRenderManager.java
The `MutliSelectComboBox` (MSCB) overlay seems to be empty because the configured `LitRenderer` misses the data configured by `.withProperty()` methods and is therefore unable to render the item properly. An example of such `LitRenderer` is this:
```
return LitRenderer.<Person> of("<div>Name: ${item.fullName}</div>")
.withProperty("fullName", Person::getFullName);
```
If the renderer does not have the `fullName` data, it will render only "Name: " in the dropdown.
When the MSCB is in read-only mode, you can still open the dropdown overlay (in contrast to normal ComboBox) to review all the selected items. However, when in `read-only` mode, the backend data provider is **not** invoked to fetch the dropdown data, but rather the `selectedItems` property on the web component is used as a data …
> fix: refresh also combobox value json-data when renderer is set

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-data-range.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
The PR slightly simplifies the grid connector's `fetchPage` method to improve its readability. It also adds basic tests to cover that method.
Part of #5865
> refactor: simplify $connector.fetchPage method

- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuTargetConnector.js
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js
You can set the grid context menu to also open on left-click (instead of right-click which is the default) by calling `gridContextMenu.setOpenOnClick(true)`. However, this interferes with checkboxes in the selection column when in multi-selection grid (only the context menu is opened, but the selection checkbox is not checked -> therefore, no row can be selected)
I described the reasons why this has been working in V24.1 and why it's not working now in [this comment](https://github.com/vaadin/flow-components/issues/5833#issuecomment-1867933676). The comment also presents the context for the solution (and also some worse solutions that I tried).
This PR introduces a way how to prevent calling `e.preventDefault()` inside `contextMenuTargetConnector.js -> openOnHandler` that is responsible …
> fix: prevent context menu on selection column left-click 

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridEditorPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridEditorIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/EditorImpl.java
Calling `Grid.getEditor().editItem(item)` multiple times in a single server request results in only the first call being processed and the rest of the calls being ignored. i.e. in the following code:
```
editor.editItem(itemA)
editor.editItem(itemB)
```
The `itemA` is edited in the browser, while you would expect that `itemB` is edited.
This PR changes the implementation of the `Editor.editItem` method, so only the last `editItem` call is processed. 
Inspiration for the implementation taken from [DatePicker](https://github.com/vaadin/flow-components/blob/dcdf56173c8dff47c4a4c48630a65fbfe2e253ba/vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L448)
Fixes #5740
> fix: process the last registered grid edit request

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
The PR removes an old workaround from the grid connector because it no longer works correctly. The workaround traces back to https://github.com/vaadin/vaadin-grid-flow/pull/241 where the tree grid was merged with the regular grid. Back then, the grid could apparently request pages beyond the grid size.
> refactor: remove incorrect workaround from grid connector

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
The PR refactors the grid connector to access pending requests directly from the web component via DataProviderController. This eliminates the need for an extra storage of page callbacks in the connector.
Part of #5865
> refactor: remove extra storage layer for pending requests

- vaadin-tabs-flow-parent/vaadin-tabs-flow/pom.xml
- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java
- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetTest.java
The `TabSheet` component uses `Tab` id attribute to link the associated `content` element with it. When a `Tab` is selected, the element with `tab='tab-id-xxxxxx'` attribute is searched and displayed in the `TabSheet` content pane.
When using `TabSheet` as a web-component, it's the responsibility of the developer to make sure that the `id` of the `vaadin-tab` matches with the `tab` attribute of it's content. See [example here](https://vaadin.com/docs/latest/components/tabs#tab-sheet). However, when used from Flow, the developer does not have to set the `Tab` id at all -> it'll be generated for him.
The problem was when the developer _wanted_ to set a custom `Tab` id. You could call the `Tab.setId()`, but this did not change the `tab` attribute on the content element -> the `Tab` and …
> fix: use a custom Tab id if available

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-no-connector.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/shared.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
The PR simplifies the grid connector's code with the optional chaining operator. It also converts the grid connector into a TypeScript file to ensure optional chaining is properly transformed in apps that still use webpack.
> refactor: simplify grid connector with optional chaining

- vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/src/test/java/com/vaadin/flow/component/charts/export/NodeRunnerTest.java
The `com.vaadin.flow.component.charts.export.NodeRunnerTest` has been failing when executed on Windows machines due to usage of the UNIX-specific paths and path separators.
Fixed that by using `java.nio.file.Path` in the test, instead of path Strings.
The logic of the test was not changed at all.
Fixes #5692
> test: make NodeRunnerTest work also on Windows machines

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SelectionWidget.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetEventListener.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetContextMenuPolyfill.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java
Add a polyfill to trigger context-menu events for long presses in iOS devices.
The polyfill is heavily based on this one provided by @WoozyG in [his comment on the issue he reported](https://github.com/vaadin/flow-components/issues/5787#issuecomment-1832744531).
The polyfill only triggers the context-menu event when the user presses down for more than 750 milliseconds. The event is handled by the same method that handles the click button, except that it now checks for the type of the event for the cases where the right click should be handled.
Below a demonstration of the feature working on a iPhone:
https://github.com/vaadin/flow-components/assets/262432/45bbbc94-706b-417c-a81d-7b994f6fee8c
Not sure yet how to add tests for this behavior.
Fixes #5787
> fix: add polyfill to trigger context-menu on long press

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-data-range.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
The PR updates the grid connector's `fetchPage` method to reset the fetch range instead of extending it to avoid server exceptions about too large range when the requested page is outside the visible range.
The requested page can end up outside the visible range when the user, for example, scrolls the grid to the end and then back to the start within 150 ms (= root request debouncer timeout). Since the first page is already loaded, there will be only a request for the last page scheduled in the debouncer. The fetch range needs to be reset to ensure the resolution of that "last page" request, as well as any other requests that happen to be hanging, by the `confirm` method. After that, the grid will request the first page or whatever in the viewport again. The obvious drawback is that there …
> fix: reset fetch range when requested page is out of visible range

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-data-range.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
A cherry-pick of the following fix to `24.3`:
- https://github.com/vaadin/flow-components/pull/5897
Fixes https://github.com/vaadin/flow-components/issues/5865
> fix: reset fetch range when requested page is out of visible range (#5897) (CP: 24.3)

- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
Upload file types are checked in browser by we-component, not on the server side.
> docs: Clarify the uploaded file types are checked by web-component

- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/tests/GridProDetachAttachPage.java
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/tests/GridProDetachAttachIT.java
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/EditColumnConfigurator.java
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js
Wrapps the `setEditModeRenderer` method in a `runWhenAttached` callback. 
Both calls to `setEditModeRenderer` private method in the `EditColumnConfigurator` class due to two factors:
- the attach listener is only called when the whole GridPro is attached to the client, because the listener is not called when the column is created to an already attached GridPro
- because of the previous issue, there's still the need to keep a call to `setEditModeRenderer` inside the `custom` set it when the column is added afterward
To avoid the issue of two calls for the same column/component on the initialization, I implemented the same flags used in the `AbstractColumn` class for the `scheduleHeaderRendering`/`scheduleFooterRendering` methods.
Fixes #5925
> fix: wraps client setEditModeRenderer call in a runWhenAttached callback

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-data-range.test.ts
Extracted from #5916
The PR simplifies the data range tests by shortening their names, eliminating unnecessary nesting, extracting repetitive code into helpers. Also, it adds `$connector.updateSize` to every range update to better align the tests with the actual server flow.
> test: improve data range tests

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-data-range.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-tree-data-range.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
The PR cherry-picks the following fix to `23.3`:
- #5940
- #5916
Fixes #5902
> fix: prevent grid from requesting too many sub-level items (#5916) (CP: 23.3)

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxKeepFilterPage.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxKeepFilterIT.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBox.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxTest.java
Adds Flow API for the new multi-select combo box `keepFilter` option.
Closes vaadin/web-components#5930
WC PR: https://github.com/vaadin/web-components/pull/7063
- Feature
> feat: add keepFilter option

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
The PR removes the `deleteObjectContents` helper from the grid connector.
Part of #5904
> refactor: remove deleteObjectContents helper

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-tree.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
The PR restores https://github.com/vaadin/flow-components/pull/4894 which was reverted some time ago due to being misidentified as the cause of this [regression](https://github.com/vaadin/flow-components/issues/5045).
Part of https://github.com/vaadin/flow-components/issues/5904
> refactor: avoid an extra render on grid connector confirm parent

- vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/test/flow-component-renderer.test.ts
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-directive.js
It is possible that a node cannot be retrieved when it is requested. In this case, the directive continuously tries to retrieve the node. If this is the case for multiple updates in the same round-trip for the same item, the node retrieval can lead to an infinite loop. Usually, the newer update overwrites the previous one in the same directive, which clears the retry timeout. But it is possible that there is a new directive, and the first retry loop is not overwritten by the new one since it operates on another directive. This leads to the old directive never being cleaned, and this loop ramps up quickly to render the browser tab unusable.
This PR uses the parent node of the directive to control the retry timeout. The parent node is the same for any directive for an item. This prevents …
> fix: use parent node in directive to control retry timeout

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridScrollToPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridScrollToIT.java
The PR reverts the test that was intended to prevent the #5045 regression. The regression is still present which means the test isn't working correctly.
Part of https://github.com/vaadin/flow-components/issues/5904
> Revert "test: check tree grid expand with small page size (#5176)"

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
The grid connector contains code that retrieves the sub-cache instance by an item, and this code is duplicated in several places. The PR extracts it into a method `getItemSubCache` on the DataProviderController instance.
> refactor: extract getItemSubCache method

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavItemTest.java
Add two new API for setting/getting the `target` property of a `SideNavItem`, whose value is used to set the `target` attribute in the internal anchor element inside the web-component:
- `setTarget(String)`/`getTarget()` - which receives any string as argument
- `setOpenInNewBrowserTab(boolean)`/`isOpenInNewBrowserTab()`- a convenience method that internally calls `setTarget` with `_blank` as value when called with `true`.
Depends on vaadin/web-components#7088
Fixes #5091
AC https://github.com/vaadin/platform/issues/4850
> feat: add target API to SideNavItem

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridScrollToPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridScrollToIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridScrollTest.java
This PR adds `scrollToItem` support to Grid, which takes an item as a parameter instead of an index. Note that this feature is not supported for TreeGrid.
Based on another [PR](https://github.com/vaadin/flow-components/pull/5628). The PR was updated based on the new [getItemIndex](https://github.com/vaadin/flow/pull/18306) API in Flow.
Fixes https://github.com/vaadin/web-components/issues/1951
> feat: add scrolltoitem support for grid

- vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
This PR deprecates the removal-related methods that are inherited from `HasComponents` and `HasOrderedComponents` since they are not properly supported.
Part of #5275
> refactor: deprecate confirmdialog removal methods

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerCustomFormatIT.java
This test has been failing multiple times in [snapshot validation](https://bender.vaadin.com/buildConfiguration/FlowComponents_Snapshot/491905?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) for `main` and also fails for me locally. The first assertion checks whether the output span contains a certain date, however the output span is only populated when the date picker opens or closes:
https://github.com/vaadin/flow-components/blob/52f392be4e08c6392b41ee796b6e76b6bca25474/vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerCustomFormatPage.java#L221-L230
The test never opens the date picker before …
> test: fix date picker custom format IT

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DetachReattachPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachReattachIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
When a grid component is detached, its data communicator will clear all data generators, which also removes all components rendered by component renderers. If the grid is then reattached in the same roundtrip, the components are not rendered again, causing them to disappear on the client-side.
This fixes the issue by resetting the data communicator on attach, which forces items to be regenerated, thus triggering a new render of the component renderers. This causes additional roundtrips in the detach / reattach scenario, but doesn't change how the component behaves when detaching / attaching in separate roundtrips, or when attaching the component for the first time.
Fixes #5732
> fix: re-render components on attach

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/DetachReattachPage.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/DetachReattachIT.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxDataController.java
When a ComboBox with a component renderer is detached and attached in the same roundtrip, the data is destroyed but never rendered again. This PR adds a reset call on attach in the data controller to fix this issue.
Based on the approach in a [fix](https://github.com/vaadin/flow-components/pull/5989) for a similar Grid [issue](https://github.com/vaadin/flow-components/issues/5732).
Fixes #5100
> fix: reset controller on attach to re-render components

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridHeaderFooterRowPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridHeaderFooterRowIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java
This PR adds 4 new APIs to Grid:
- `removeHeaderRow(HeaderRow)`
- `removeAllHeaderRows()`
- `removeFooterRow(FooterRow)`
- `removeAllFooterRows()`
Notes:
- The first column layer is never removed. Instead, the content on it is manipulated.
- The default header row can only be removed only when there is no other header row.
Fixes #1538
> feat: add remove functionality for grid header and footers

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxSelectedItemsOnTopPage.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxSelectedItemsOnTopIT.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxDataCommunicator.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxDataController.java
The data is destroyed and rebuilt on data communicator reset. When component renderers are used, this means that the nodeIds for the items should also be updated. However, the `selectedItems` property is manually set in `refreshValue()`. Therefore, the selected items can contain obsolete nodeIds. 
This PR adds a `refreshValue()` call on every data communicator reset to make sure that the nodeIds of selected items to remain in sync.
Fixes #5985
> fix: refresh value on data communicator reset

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DetachReattachPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachReattachIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Fixes a regression from https://github.com/vaadin/flow-components/pull/5788
The `updateSelectionModeOnClient()` js call should not use `beforeClientResponse` because that might lead to the selection mode getting updated _after_ applying selections.
Fixes https://github.com/vaadin/flow-components/issues/5996
Fixes https://github.com/vaadin/flow-components/issues/5986
Bugfix
> fix: do not defer updating client-side selection mode

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachReattachIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Fixes a regression from https://github.com/vaadin/flow-components/pull/5788
Similarly to https://github.com/vaadin/flow-components/pull/6028, `beforeClientResponse` mustn't be used for updating the client-side sorter directions.
Fixes https://github.com/vaadin/flow-components/issues/5994
Bugfix
> fix: do not defer updating client-side sorter directions

- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarTest.java
Support reverse button collapsing order in menu-bar
https://github.com/vaadin/platform/assets/1222264/5a5f469f-d69f-4808-95c5-72ac2df0bc5a
Part of https://github.com/vaadin/platform/issues/5018
Related https://github.com/vaadin/web-components/pull/7124
Feature
> feat: support reverse button collapsing order in menu-bar

- vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/main/java/com/vaadin/flow/data/renderer/tests/LitRendererPage.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/test/java/com/vaadin/flow/data/renderer/tests/LitRendererIT.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/lit-renderer.ts
Inject the `live` directive into the closure where the render is executed.
It's beneficial for cases where components can have their state changed by users to reset their value when the render is called.
> feat: allow using live directive in LitRenderer

- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarPageIT.java
Menu bar ITs added in https://github.com/vaadin/flow-components/pull/6031 fail quite often, seemingly because the menu overlay isn't closed yet before tests attempt to open the menu again:
- https://bender.vaadin.com/buildConfiguration/FlowComponents_Snapshot/506523?buildTab=log&focusLine=25356&logView=flowAware&linesState=644.25355
- https://bender.vaadin.com/buildConfiguration/FlowComponents_Snapshot/506507?buildTab=log&focusLine=25426&logView=flowAware&linesState=645.25424
Waiting for them to be closed after clicking buttons seems to help.
> test: fix flaky menubar ITs

- .gitignore
- scripts/wtr.js
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/test/date-picker-connector.test.ts
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/test/env-setup.ts
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/test/shared.ts
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/web-test-runner.config.mjs
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
Fixes #6065
This PR adds `web-test-runner` tests to the `datepickerConnector`, especially `parseDate` and `formatDate`.
The logic is as follows:
- The date format is now considered short unless it contains a four-digit year: `yyyy` or `YYYY`
- When using `ddMM` format (and any other format without year set), current year is assumed. 
- With `dd` format, both current month and year are assumed (see `beforeEach` in unit tests)
- Bugfix
> fix: allow short formats, add date-picker connector WTR tests

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
A cherry-pick of https://github.com/vaadin/flow-components/pull/6096 to 23.3.
> refactor: drop obsolete workaround from connector (#6096) (CP: 23.3)

- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java
Fixes #6040
Note: the original issue happens without `setValue()` but I was unable to create a proper unit test reproducing this scenario. 
The `hasValidValue()` is called by Flow on [property change event](https://github.com/vaadin/flow/blob/fb9661ff515c1a728f50dea382fd029836bbe1c0/flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java#L350-L351) so I used `setProperty()` + `fireEvent` to test the fix.
- Bugfix
> fix: do not call itemEnabledProvider for null values

- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java
Manual cherry-pick of #6119 to `24.3` branch.
- Cherry-pick
> fix: do not call itemEnabledProvider for null values (#6119) (CP: 24.3)

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/SortingPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
Fixes #6122
When calling `setHeader()` on the column, Grid updates sorter indicators (as implemented in #1841). Currently it is done by re-setting `direction` to `null` in the connector and then setting directions in the right order.
The logic was changed to reset `direction` for all sorters in #5822, which introduced the regression: when calling `setHeader()` for more than one column in one request, it caused grid to incorrectly apply sorters change.
Updated the connector to add a check for this case, and added new ITs to verify that sort listeners are not invoked.
- Bugfix
> fix: prevent sorters change when updating multiple headers

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/SortingPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Manual cherry-pick of #6125 to `24.3` branch.
- Cherry-pick
> fix: prevent sorters change when updating multiple headers (#6125) (CP: 24.3)

- vaadin-login-flow-parent/vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java
Related to #6098
Updated JavaDoc of `getCustomFormArea()` as suggested by https://github.com/vaadin/flow-components/issues/6098#issuecomment-1988556787.
I will also submit a PR to the docs project, as the original issue isn't obvious and deserves a note.
> docs: add note about fields in LoginOverlay custom form area

- vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/button/tests/ButtonView.java
- vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/button/tests/ButtonIT.java
- vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/Button.java
- vaadin-button-flow-parent/vaadin-button-flow/src/test/java/com/vaadin/flow/component/button/tests/ButtonTest.java
When using disable on click, `Button` has a workaround for the case where the button is enabled again in the same roundtrip that it was disabled. Basically the client-side component disables itself right after the click, the server-side component disables itself, and then the application code enables the button again in the same roundtrip. In that case Flow doesn't detect any changes to the disabled state and wouldn't enable the client-side component again. This is the original issue that caused the workaround to be introduced: https://github.com/vaadin/vaadin-button-flow/issues/115.
The existing workaround does some tampering with state nodes that doesn't seem to work if the component is invisible, probably because Flow ignores updates to invisible components. This change replaces the …
> fix: enable invisible button after disable on click

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavItemTest.java
Adds API to `SideNavItem` that allows to opt out of client-side routing, which makes it work like a regular anchor that causes a full page reload. Related WC PR: https://github.com/vaadin/web-components/pull/7233, requires a new WC release before merging.
Closes https://github.com/vaadin/flow-components/issues/5189
> feat: add router-ignore API to SideNavItem

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ColumnPathPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ColumnPathIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/EditorRenderer.java
The `path` property is currently removed when an editor renderer is used. This is unnecessary since the editor renderer uses the original renderer when not in edit mode. 
This PR 
- updates the editor renderer to use the the default renderer if there is no renderer set
- removes the block that removes the `path` property
Fixes #6124
> fix: use default renderer if no renderer set in editor renderer

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandedKeysPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandedKeysIT.java
Test for https://github.com/vaadin/flow/issues/19006
> test: add test for Flow issue #19006

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/SelectComponentColumnAfterExpandPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/SelectComponentColumnAfterExpandIT.java
This PR moves a TreeGrid IT page from Grid test package to the TreeGrid test package.
> test: move treegrid test page to the correct package

- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/tests/CellEditableProviderPage.java
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/tests/CellEditableProviderIT.java
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/EditColumnConfigurator.java
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/test/java/com/vaadin/flow/component/gridpro/GridProTest.java
Adds an API for configuring a predicate that determines whether individual cells in columns are editable or not.
Depends on: https://github.com/vaadin/web-components/pull/7269
Part of: https://github.com/vaadin/flow-components/issues/4524
AC: https://github.com/vaadin/platform/issues/5177
> feat: disable editing for individual cells

- vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupIT.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupTest.java
Part of https://github.com/vaadin/platform/issues/5178
Depends on https://github.com/vaadin/web-components/pull/7199
Updated `CheckboxGroup.setReadonly(true)` to use `readonly` property on the web component instead of disabling.
- Feature
> feat: implement proper readonly state in CheckboxGroup

- vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/HelperPage.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/HelperIT.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
Part of https://github.com/vaadin/platform/issues/5190
Depends on https://github.com/vaadin/web-components/pull/7285
- Feature
> feat: add Checkbox helper and CheckboxGroup item helper generator

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/FilterDebounceIT.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxDataController.java
Currently, when a filter is quickly changed, the combobox is left in a loading state. The reason is the data communicator is never reset because the new filter applied is the same one as before. Even if the connector explicitly [handles](https://github.com/vaadin/flow-components/blob/main/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js#L99-L105) this case, the server side reset does not happen. The client-callable `resetDataCommunicator` is only used for this purpose, and calling it from the client side should be enough to trigger the reset in any case.
This PR removes the legacy workaround in the reset logic in the controller and directly resets the communicator.
Fixes #5468
> fix: reset communicator regardless of filter

- vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/button/tests/ButtonView.java
- vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/button/tests/ButtonIT.java
- vaadin-button-flow-parent/vaadin-button-flow/src/main/resources/META-INF/resources/frontend/buttonFunctions.js
Fixes #6183
This changes the client side JS listener as suggested in the issue to only set `disabled` to `true` and not `false`.
- Bugfix
The IT setup represents an edge case as it uses `setDisableOnClick(true)` followed by `setDisableOnClick(false)` and is based on the code example https://github.com/vaadin/flow-components/issues/6183#issuecomment-2046669463. Also, clicking the button in the IT requires firing an event manually.
> fix: prevent setting disabled to false with pointer events: auto

- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarTestPage.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarPageIT.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/resources/META-INF/resources/frontend/menubarConnector.js
The changes done in #6031 don't work if the root item is inside the overflow part of the `MenuBar`. That happens because the `setClassName` method in the connector changes the `className` value in the `component._item` object that should be reflected to the item when the items are regenerated.
Usually, the `_item` object of `component` refers to one instance inside of the `__generatedItems` array in the menu bar instance, but when the menu item becomes part of the overflow, it receives a new instance of `_item` and the reference is lost.
Saving the original reference in another property solves the issue and now the class name is changed properly for items inside the overflow.
> fix: fix setting class name to menu-bar items in overflow

- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/TimePickerPage.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerIT.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/vaadin-time-picker/timepickerConnector.js
Currently, when `formatTime` in the time picker connector calls the helper function `formatMilliseconds`, the provided milliseconds value can be a string or a number. However, the helper function expects a number at this point and the calculations get broken. Therefore, the ms values smaller than 100 gets rounded down to 0. This PR makes sure that the helper function is only called with a number ms value.
Fixes #5101
> fix: ensure time parts in parsed time object are numeric

- vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/DataSeriesItemSankey.java
- vaadin-charts-flow-parent/vaadin-charts-flow/src/test/java/com/vaadin/flow/component/charts/DataSeriesItemSerializationTest.java
Without this call, the object would be serialized as [an array containing two values](https://github.com/vaadin/flow-components/blob/main/vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/serializers/DataSeriesItemBeanSerializer.java#L75-L80) from `bean.getLow()` and `bean.getHigh()`, which are not usually set on the Sankey type, so the result would be `[null, null]`, instead of the actual JSON string expected (containing the `from`, `to`, and `weight` keys).
The Sankey example in the IT works because it uses `setDataLabels`, which in turn [calls `makeCustomized`](https://github.com/vaadin/flow-components/blob/main/vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/DataSeriesItem.java#L366-L369) …
> fix: mark `DataSeriesItemSankey` as customized to ensure its proper serialization

- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
This is a fix for DX test finding. As suggested, added `ItemHelperGenerator` interface and clarified Javadoc.
- Refactor
> refactor: add ItemHelperGenerator interface to CheckboxGroup

- vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/VerticalLayout.java
- vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/test/java/com/vaadin/flow/component/orderedlayout/tests/LayoutDefaultsTest.java
Fixes #6206
Updated `VerticalLayout` to use correct default value to align with `flex-start` used by the [web component](https://github.com/vaadin/web-components/blob/e6281faa75364c97beb220b220f414aec58c679a/packages/vertical-layout/src/vaadin-vertical-layout.js#L43).
This seems to be the only case where Flow counterpart default value was actually misaligned.
- Bugfix
> fix: use correct default value for getAlignItems in VerticalLayout

- pom.xml
- vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/CompositeIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/NumberFieldPage.java
Fixed tests to adapt to the new semantic of 'id()' query selector throwing an exception when there are more elements with the same id.
For CompositeIT, two modal dialogs are opened, adding two elements with 'overlay' id. The test now takes the last one, that corresponds to the Language edit dialog.
> chore: bump Testbench to 9.3.0.alpha1

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridLitRendererSerializationPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridLitRendererSerializationIT.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java
When a LitRenderer is used in a Grid, it may happen that UI deserialization fails because of a self-reference lambda caused by the DataGenerator instance provided by LitRenderer and store into the Grid CompositeDataGenerator.
Using an anonymous class instead of a lambda expression fixes the issues.
Fixes #6256
> fix: prevent potential deserialization issue in LitRenderer

- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/FileRejectedEvent.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/ProgressUpdateEvent.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
fixes: https://github.com/vaadin/flow-components/issues/6221
> chore: overload constructor in order not to break API

- vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/BigDecimalFieldElement.java
- vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/EmailFieldElement.java
- vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/IntegerFieldElement.java
- vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/NumberFieldElement.java
- vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/PasswordFieldElement.java
- vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextAreaElement.java
- vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextFieldElement.java
- vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextFieldElementHelper.java
The PR aims to improve the JavaDoc of the TestBench `setValue` method by mentioning
- that the events it fires are synthetic
- that sendKeys should be used for more complex scenarios
- that  sendKeys should be used when needing to enter unparsable values to test the validation workflow
Related to https://github.com/vaadin/flow-components/pull/6138
> docs: improve JavaDoc of TestBench setValue method

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/dataview/AbstractItemCountComboBoxPage.java
Currently some ITs based on `AbstractItemCountComboBoxIT` open the ComboBox on `beforeEnter`. This causes a timing issue where the overlay is opened before the `vaadin-input-container` is rendered so the overlay has zero width.
- Test
> test: ensure the combo-box overlay is visible in IT

- vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
- vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutTest.java
Form layout responsive steps getter does not work at all.
Included test describes the case.
> fix: make getResponsiveSteps getter work properly

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Deprecate `grid.setClassNameGenerator` and `gridColumn.setClassNameGenerator` in favor of `setPartNameGenerator`.
The corresponding [web component API](https://github.com/vaadin/web-components/blob/4038b4c30136f9f929ca90df9ade35db231071d0/packages/grid/src/vaadin-grid-styling-mixin.js#L32) is already deprecated.
Even though we don't recommend it, the part names could also be used with shadow DOM style injection so the class names don't serve a purpose anymore.
Closes https://github.com/vaadin/flow-components/pull/6267
Documentation
> chore: deprecate grid class name generator

- vaadin-list-box-flow-parent/vaadin-list-box-testbench/src/main/java/com/vaadin/flow/component/listbox/testbench/ListBoxElement.java
The PR removes HasLabel interface from ListBoxElement because ListBox doesn't support labels.
> fix: remove HasLabel interface from ListBoxElement

- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/SwitchReceiversPage.java
- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/SwitchReceiversIT.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/UploadTest.java
Fixes an issue where the user was unable to select more than one file after switching from a single-file receiver to a multi-file one. It was because the Flow component didn't set the `maxFiles` client-side property to `Infinity` – the web component's default value for that property – when a multi-file receiver was set.
Fixes https://github.com/vaadin/flow-components/issues/6227
> fix: set maxFiles to Infinity when setting a MultiFileReceiver

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Add a new paragraph to mention the issue of using `em` length unit in columns width.
Part of #6260
> docs: add note about 'em' unit on Column#setWidth javadoc

- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
The PR renames `i18n` to `datePickerI18n` and `dateTimePickerI18n` to `i18n`, which is more conventional.
Part of https://github.com/vaadin/flow-components/issues/4618
> refactor: rename i18n internal property to datePickerI18n

- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/tests/MainView.java
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/tests/BasicIT.java
Add a test case to verify https://github.com/vaadin/web-components/pull/7453 fixes the [item click listener regression](https://github.com/vaadin/web-components/issues/637#issuecomment-2133068801) in Grid Pro which manifested after [this addition](https://github.com/vaadin/flow-components/blob/62acdd978b3d1a6c04c7c836019c76e4d5d628cf/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts#L1128-L1131) to the grid connector.
Related to https://github.com/vaadin/web-components/issues/637
Tests
> test: add a test for item click on edit column cell

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridEmptyStatePage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridEmptyStateIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridEmptyStateTest.java
- vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridElement.java
Depends on https://github.com/vaadin/web-components/pull/7429
Add empty state API to `Grid`:
- `setEmptyStateComponent`
- `setEmptyStateText`
- `getEmptyStateComponent`
- `getEmptyStateText`
Setting empty state content to the `Grid` makes it display the content whenever there are no items to render.
Part of https://github.com/vaadin/platform/issues/5719
Feature
> feat: grid empty state content

- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
The PR changes the return type of DateTimePickerI18n methods from `void` to `DateTimePickerI18n` to allow them to be chained, same as i18n methods in other components.
> [!WARNING]
>  It's marked as a behavior-altering change because there is a slight chance it could affect some custom extensions of DateTimePicker.
Part of #4618
> refactor!: change DateTimePickerI18n methods to return this

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DragAndDropGridIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- Run `getDataCommunicator().reset();` when "drop mode" changes dynamically because the [drop filters only apply if drop mode is non-null](https://github.com/vaadin/flow-components/blob/836f59b092a52a1a01e08ddb9cc7f307659fe6cc/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java#L4314).
- Run `getDataCommunicator().reset();` when "rows draggable" changes dynamically because the [drag filters apply if the rows are draggable](https://github.com/vaadin/flow-components/blob/836f59b092a52a1a01e08ddb9cc7f307659fe6cc/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java#L4318).
Fixes https://github.com/vaadin/flow-components/issues/6310
Bugfix
> fix: run grid dnd filters on dropmode and draggable change

- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/ValidationUtil.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
- vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextFieldValidationSupport.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
- Added new methods `validateRequiredConstraint`, `validateMinConstraint` and `validateMaxConstraint` to `ValidationUtil`. They accept a string error message to return in the `ValidationResult` when the check fails.
- Deprecated the previous methods without an error message in favor of the new ones.
Part of https://github.com/vaadin/flow-components/issues/4618
> refactor(ValidationUtil): add methods accepting error message, deprecate old ones

- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextFieldBase.java
Finding from #6346 
The PR fixes a bug where the `setRequired` method didn't activate the required validation for number fields, unlike `setRequiredIndicatorVisible` which did.
> fix: make setRequired also activate required validation

- pom.xml
The PR bumps `net.revelc.code.formatter:formatter-maven-plugin` from 2.24.0 to 2.24.1, which contains a fix for the issue where the formatter skipped all files despite changes.
Related to https://github.com/vaadin/flow-components/pull/6335
> chore: bump net.revelc.code.formatter:formatter-maven-plugin

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridEmptyStateTest.java
Fix DX test finding issues related to Grid "empty state" feature:
- Mention that "null" can be passed as the parameter for `setEmptyStateText` and `setEmptyStateContent` to clear the empty state content
> docs: improve grid empty state documentation

- vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/validation/BasicValidationPage.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/validation/BasicValidationPage.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/validation/BasicValidationPage.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/validation/BasicValidationPage.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/validation/BasicValidationPage.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
Continuation of #6347 
The PR refactors the implementation of the `setRequired` and `isRequired` methods to delegate their calls to the `setRequiredIndicatorVisible` and `isRequiredIndicatorVisible` methods, which are considered the primary methods.
> refactor: align setRequired implementation across components

- vaadin-messages-flow-parent/vaadin-messages-flow/src/main/java/com/vaadin/flow/component/messages/MessageInput.java
- vaadin-messages-flow-parent/vaadin-messages-flow/src/test/java/com/vaadin/flow/component/messages/tests/MessageInputTest.java
Fixes #6243
Note: this will only make `focus()` work once https://github.com/vaadin/web-components/pull/7364 is released.
Also, there will be problems with `addFocusListener` like the one we have in `DateTimePicker`, see #2284
- Feature
> feat: make MessageInput implement Focusable

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.html
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js
Fixes https://github.com/vaadin/web-components/issues/7503 for V14.11
As described in https://github.com/vaadin/web-components/issues/7503#issuecomment-2210637653, the actual fix is to make `vaadin-checkbox` element the first child of its corresponding header cell, so that the [click logic](https://github.com/vaadin/vaadin-grid/blob/d0663ccaebcdcae17c52226975fde60cc693243f/src/vaadin-grid-keyboard-navigation-mixin.html#L484) on <kbd>Space</kbd> key press works as expected.
- Bugfix
> fix: make sure select all checkbox is clicked on cell Space (14.11)

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.html
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js
Fixes https://github.com/vaadin/web-components/issues/7503 for V14.12
As described in https://github.com/vaadin/web-components/issues/7503#issuecomment-2210637653, the actual fix is to make `vaadin-checkbox` element the first child of its corresponding header cell, so that the [click logic](https://github.com/vaadin/vaadin-grid/blob/d0663ccaebcdcae17c52226975fde60cc693243f/src/vaadin-grid-keyboard-navigation-mixin.html#L484) on <kbd>Space</kbd> key press works as expected.
- Bugfix
> fix: make sure select all checkbox is clicked on cell Space (14.12)

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/pom.xml
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridViewClickListenersPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewClickListenersIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
Fixes #4065
This fixes the case with "a Button with only an Icon inside" to make sure clicking the `vaadin-icon` element doesn't cause `ItemClickListener` to be fired, making it consistent with a regular `vaadin-button` element click.
- Bugfix
I don't think we should add special logic to stop `ItemClickListener` for `Icon` component when it's not inside a focusable element like `Button`. In fact, a standalone `Icon` should be used inside a `Button` to convey its interactive meaning.
As mentioned in https://github.com/vaadin/flow-components/issues/4065#issuecomment-2210829465, as a workaround it's possible to use `.addEventData("event.preventDefault()")` on the `Icon` click listener in this case, in order to prevent `ItemClickListener` from being fired:
```java
grid.addColumn(new …
```
> fix: do not fire ItemClickListener on focusable element click

- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
- vaadin-popover-flow-parent/vaadin-popover-flow/src/test/java/com/vaadin/flow/component/popover/PopoverTest.java
Added methods to set properties available in the web component:
- `hoverDelay`
- `focusDelay`
- `hideDelay`
- Feature
> feat: add focusDelay, hoverDelay and hideDelay to Popover

- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
- vaadin-popover-flow-parent/vaadin-popover-flow/src/test/java/com/vaadin/flow/component/popover/PopoverTest.java
Based on https://github.com/vaadin/web-components/pull/7446
- Feature
> feat: make Popover implement HasAriaLabel, add overlayRole

- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
- vaadin-popover-flow-parent/vaadin-popover-flow/src/test/java/com/vaadin/flow/component/popover/PopoverTest.java
Based on https://github.com/vaadin/web-components/pull/7442
The API looks similar to what we have in `ConfirmDialog` as implemented in https://github.com/vaadin/vaadin-confirm-dialog-flow/pull/89.
Note, I didn't add `HasSize` interface because it also has methods like `setMinWidth`, `setMaxWidth` etc. 
If users request these, we can consider adding them later like it's done in `Dialog`- see [`setDimension()`](https://github.com/vaadin/flow-components/blob/60244a7113d203871efe5da6735927ce370d9512/vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L1011-L1014).
- Feature
> feat: add setWidth and setHeight methods to Popover

- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
- vaadin-popover-flow-parent/vaadin-popover-flow/src/test/java/com/vaadin/flow/component/popover/PopoverTest.java
Replaces #6446
Added the following methods to `Popover`:
- `setModal()` / `isModal()`
- `setBackdropVisible()` / `isBackdropVisible()`
Note: as discussed internally, for now we only add web component property without using server-side modality.
- Feature
> feat: add methods to set modal and withBackdrop to Popover

- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasValidationProperties.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/ValidationUtil.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextFieldBinderValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextFieldBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextFieldBase.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/TextFieldTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/TextFieldBasicValidationTest.java
The PR introduces TextFieldI18n with methods for setting error messages and updates the TextField's validation logic to show these error messages when validation fails.
> [!NOTE]
Depends on
- https://github.com/vaadin/flow-components/pull/6322
Part of #4618
> feat: add i18n error message support for TextField

- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java
The PR removes the `isConnectorAttached` class field because it's not being used.
> refactor: remove unused class field

- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/validation/BasicValidationPage.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/validation/BinderValidationPage.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/BasicValidationIT.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/BinderValidationIT.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/BasicValidationTest.java
The PR introduces TimePickerI18n with methods for setting error messages and updates the TimePicker's validation logic to show these error messages when validation fails.
> [!NOTE]
Part of #4618
> feat: add i18n error message support for TimePicker

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/InertTreeGridPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/InertTreeGridIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
Fixes https://github.com/vaadin/flow-components/issues/6428
The issue occurs because the dialog's server-side modality by default blocks calls to `@ClientCallable` methods for components outside of it. As the grid outside the dialog encounters rows without data, it tries to make a data request but the call gets blocked and the rows will remain empty.
This PR fixes the issue by allowing an inert Grid to fetch data for rows.
Note: We can't rely on the Grid's item preloading logic to fix this (as mentioned [here](https://github.com/vaadin/flow-components/issues/6428#issuecomment-2219610825)) since it's merely a performance optimization and wouldn't help in cases where unloaded rows are revealed due to other reasons, for example, if the grid's height gets increased programmatically or by …
> fix: allow data fetch for inert grid

- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/validation/BasicValidationPage.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/validation/BinderValidationPage.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BasicValidationIT.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BinderValidationIT.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BasicValidationTest.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java
The PR enhances DateTimePickerI18n with methods for setting error messages and updates the DateTimePicker's validation logic to show these error messages when validation fails.
> [!NOTE]
Part of #4618
> feat: add i18n error message support for DateTimePicker

- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBinderValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/IntegerField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/IntegerFieldBasicValidationTest.java
The PR introduces IntegerFieldI18n with methods for setting error messages and updates the IntegerField's validation logic to show these error messages when validation fails. 
> [!NOTE]
Part of #4618
> feat: add i18n error message support for IntegerField

- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBinderValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/BigDecimalFieldBasicValidationTest.java
The PR introduces BigDecimalFieldI18n with methods for setting error messages and updates the BigDecimalField's validation logic to show these error messages when validation fails.
> [!NOTE]
Part of #4618
> feat: add i18n error message support for BigDecimalField

- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBinderValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/EmailFieldBasicValidationTest.java
The PR introduces EmailFieldI18n with methods for setting error messages and updates the EmailField's validation logic to show these error messages when validation fails.
> [!NOTE]
Part of #4618
> feat: add i18n error message support for EmailField

- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBinderValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/PasswordFieldBasicValidationTest.java
The PR introduces PasswordFieldI18n with methods for setting error messages and updates the PasswordField's validation logic to show these error messages when validation fails.
> [!NOTE]
Part of #4618
> feat: add i18n error message support for PasswordField

- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBasicValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBinderValidationPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBinderValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/TextAreaBasicValidationTest.java
The PR introduces TextAreaI18n with methods for setting error messages and updates the TextArea's validation logic to show these error messages when validation fails.
> [!NOTE]
Part of #4618
> feat: add i18n error message support for TextArea

- vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
- vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java
Part of https://github.com/vaadin/web-components/issues/7502
Depends on https://github.com/vaadin/web-components/pull/7578
Added `setOverlayWidth()` method like the one added to `ComboBox` in #5743.
- Feature
> feat: add method to customize Select overlay width

- vaadin-split-layout-flow-parent/vaadin-split-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitterPositionIT.java
- vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
Update server-side `flex` style with px values from client instead of recalculating percentage values on the server.
Fixes https://github.com/vaadin/web-components/issues/7583
> fix: preserve flex-basis after splitter drag end

- vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/main/java/com/vaadin/flow/component/select/tests/validation/BasicValidationPage.java
- vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/tests/validation/BasicValidationIT.java
- vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
- vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/validation/BasicValidationTest.java
The PR introduces SelectI18n with a method for setting a required error message and updates the Select's validation logic to show this error message when validation fails.
Part of #4618
> feat: add i18n error message support for Select

- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
Part of https://github.com/vaadin/web-components/issues/4977
Depends on https://github.com/vaadin/web-components/pull/7582
Added `setOverlayRole()` and `getOverlayRole()` methods to `Dialog` (the logic is copied from the `Popover`).
- Feature
> feat: add method to customize Dialog overlay ARIA role

- vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/validation/BinderValidationIT.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/validation/BasicValidationTest.java
The PR introduces RadioButtonGroupI18n with a method for setting a required error message and updates the RadioButtonGroup's validation logic to show this error message when validation fails. It should be mentioned that RadioButtonGroup is an atypical component in terms of validation. It has a required flag, but no user interaction can trigger the required error message – the message only appears if the value is programmatically reset to null. Therefore, the i18n object is practically unnecessary, but it's still added to maintain consistency with other components.
Part of #4618
> feat: add i18n error message support for RadioButtonGroup

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/validation/ComboBoxBasicValidationPage.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/validation/MultiSelectComboBoxBasicValidationPage.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/validation/ComboBoxBasicValidationIT.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/validation/MultiSelectComboBoxBasicValidationIT.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBaseI18n.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBox.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxI18n.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/validation/ComboBoxBasicValidationTest.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/validation/MultiSelectComboBoxBasicValidationTest.java
The PR introduces ComboBoxI18n and enhances the existing MultiSelectComboBoxI18n with a method for setting a required error message and updates the corresponding validation logic to show this error message when validation fails.
Part of #4618
> feat: add i18n error message support for ComboBox, MultiSelectComboBox

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridEditorPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridEditorIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/Editor.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/EditorImpl.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/editor/EditorImplTest.java
Fixes https://github.com/vaadin/flow-components/issues/6384
The current Flow Grid editor implementation has a [validation rule](https://github.com/vaadin/flow-components/blob/403b1809b5058de2537b5dc2ca979e61b228d4f3/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/EditorImpl.java#L220-L223) that throws an exception when [`editItem(item)`](https://github.com/vaadin/flow-components/blob/403b1809b5058de2537b5dc2ca979e61b228d4f3/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/EditorImpl.java#L130) is called with an item that is not in the active range (i.e., there is no key for it in the key mapper). However, the exception is [documented](https://github.com/vaadin/flow-components/blob/403b1809b5058de2537b5 …
> fix: allow editing items outside grid's active range

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridEditorPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridEditorIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/Editor.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/EditorImpl.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/editor/EditorImplTest.java
Manually cherry-pick #6476 to `24.3`
> fix: allow editing items outside grid's active range (#6476)

- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
This PR makes `DialogHeaderFooter` implement `HasComponents`. This introduces the following APIs to both `DialogHeader` and `DialogFooter`:
- `add(Collection<Component> components)`
- `add(String text)`
- `remove(Collection<Component> components)`
- `removeAll()`
- `addComponentAtIndex(int index, Component component`
- `addComponentAsFirst(Component component)`
NOTE:
This might be breaking if `dialog.getHeader().add(null);` is used anywhere since it is going to be ambiguous after the refactoring. However, this is unlikely in practice since it is not supported and would throw a `NullPonterException` anyway.
Fixes #5735
> feat: make dialogheaderfooter implement hascomponents

- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java
- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java
- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetTest.java
- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabsTest.java
This PR
- deprecates `Tabs::getComponentCount`
- introduces `getTabCount` for both `Tabs` and `TabSheet`
Fixes #6015
> feat: introduce gettabcount and deprecate getcomponentcount

- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheetVariant.java
- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetTest.java
Add the flow counterpart of https://github.com/vaadin/web-components/pull/7606 (released with 24.5.0-alpha7)
Fixes #4388 (internally decided that a theme variant is enough)
> feat: add no-padding theme variant

- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/PopoverVariant.java
Based on https://github.com/vaadin/web-components/pull/7550
Note: the `arrow` variant is available for both Lumo and Material.
- Feature
> feat: add PopoverVariant enum with the arrow variant

- vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
This PR replaces the use of the deprecated `Label` with `NativeLabel` in `FormItem`.
Fixes #5171
> refactor: use native label in formitem instead of deprecated label

- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/PopoverVariant.java
Based on https://github.com/vaadin/web-components/pull/7650
Added `LUMO_NO_PADDING` and `MATERIAL_NO_PADDING` to align with `DialogVariant`:
https://github.com/vaadin/flow-components/blob/7cf4900e4e756f53ae25e37db6429c16079a2fd6/vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/DialogVariant.java#L24
- Feature
> feat: add no-padding theme variant to Popover

- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java
- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabsTest.java
The PR changes the Tabs behavior so that, instead of throwing an exception when selecting an invalid index, it now logs a warning and reverts to the previous selected index, which was valid. This is a rare case that can occur when the user manages to click on a tab that is already in the process of removal by the server, which is in turn a result of some previous action.
Fixes #5214
> fix: warn and revert to prev index when selecting invalid index

- pom.xml
- vaadin-tabs-flow-parent/vaadin-tabs-flow/pom.xml
- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java
- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabsTest.java
The PR backports #6543 to 14.12
Fixes https://github.com/vaadin/flow-components/issues/5214
> fix: warn and revert to prev index when selecting invalid index (#6543) (CP: 14.12)

- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/UploadTestsI18N.java
- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadI18nIT.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/UploadI18N.java
This PR introduces a way to set units size base in `UploadI18N`. The changes are:
- New field `sizeBase` in `Units` with getter and setter
- New constructor in `Units` including `sizeBase` as a parameter.
- New `setUnits` method in `UploadI18N` including `sizeBase` as a parameter.
Fixes #6404
> feat: add units size base apis to uploadi18n

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Remove property sorting from Grid. Logic moves to Flow side (https://github.com/vaadin/flow/pull/19796).
> refactor: property sort moved to Flow; remove from Grid

- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
- vaadin-popover-flow-parent/vaadin-popover-flow/src/test/java/com/vaadin/flow/component/popover/PopoverTest.java
Added a constructor to align with `Dialog()` which allows to pass content. This is a finding from DX tests.
- Feature
> feat: add constructor allowing to set Popover content

- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
- vaadin-popover-flow-parent/vaadin-popover-flow/src/test/java/com/vaadin/flow/component/popover/PopoverTest.java
Added `setModal()` override allowing to also call `setBackdropVisible()` so that the need for setting backdrop separately would be more easily discoverable. Also modified the `setModal()` JavaDoc accordingly. This is a DX test finding.
- Feature
> feat: add setModal override to allow setting backdrop visibility

- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
- Added default values to `setHoverDelay()`, `setFocusDelay()` and `setHideDelay()`
- Aligned default values for `setOpenOnClick()`, `setOpenOnFocus()` and `setOpenOnHover()`
- Added mention that `setPosition()` only works when the target is set
- Replaced a few mentions of "popup" with "popover" (copy-paste leftovers from VCF Popup)
> docs: improve Popover JavaDoc, add default values

- vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangingChartIT.java
Could reproduce [this test failure](https://bender.vaadin.com/buildConfiguration/FlowComponents_Snapshot/578590?buildTab=log&logView=flowAware&focusLine=25389&linesState=101.16335.25347) locally, sometimes the assertion failed with a stale element reference. Aquiring fresh references within the wait loop seems to fix it.
> test: improve flaky charts test

- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
- vaadin-popover-flow-parent/vaadin-popover-flow/src/test/java/com/vaadin/flow/component/popover/PopoverAutoAddTest.java
Based on DX tests findings, we decided to introduce auto-adding logic as all the participants were confused with `popover.open()` not working with no warnings when `Popover` is not manually added to the UI. 
**UPD**: the logic has been changed to auto-add when calling `setTarget()` instead of `open()` (and also remove the auto-attached Popover if the target is either detached or reset to `null`).
- Feature
> feat: add logic for Popover auto-adding on setting target

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/pom.xml
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardWidget.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-testbench/src/main/java/com/vaadin/flow/component/dashboard/testbench/DashboardElement.java
Adds add/remove widget functionality to dashboard.
Added API:
- `List<DashboardWidget> getWidgets()`: Returns the widgets in the dashboard
- `void add(DashboardWidget... widgets)`: Adds the given widgets to the dashboard
- `void addWidgetAtIndex(int index, DashboardWidget widget)`: Adds the given widget to the dashboard at the specific index
- `remove(DashboardWidget... widgets)`: Removes the given widgets from the dashboard
- `void removeAll()`: Removes all widgets from the dashboard
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=74589970
Feature
> feat: introduce add and remove widget functionality to dashboard

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java
This PR adds a check for an index larger than the widget count to `Dashboard.addWidgetAtIndex`. An `InvalidArgumentException` is thrown if this is the case.
This case was previously handled in the implementation internally. However during a refactoring, the implementation changed to one without this check.
> fix: handle invalid widget index

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java
Adds maximum column count functionality to dashboard.
Added API:
- `Integer getMaximumColumnCount()`: Returns the maximum column count of the dashboard
- `void setMaximumColumnCount(Integer maxCount)`: Sets the maximum column count of the dashboard
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=76144538
Feature
> feat: implement max col count feature

- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/test/java/com/vaadin/flow/component/richtexteditor/RichTextEditorSanitizationTest.java
- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/test/java/com/vaadin/flow/component/richtexteditor/RichTextEditorTest.java
Related to https://github.com/vaadin/web-components/pull/7392
- Enhancement
Currently `getColorOptions()` doesn't return the default value of the corresponding web component property.
This could be probably workarounded by adding `notify: true` and using `@Synchronize` annotation.
> feat: add API to set color options to RichTextEditor

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavItemTest.java
Adds a `matchNested` property to `vaadin-side-nav-item` that allows an item to match nested paths. When enabled, then an item with the path `/users` does not only match `/users`, but also `/users/1`, `/users/1/permissions`, etc.
WC PR: https://github.com/vaadin/web-components/pull/7693
Closes https://github.com/vaadin/flow-components/issues/5227
> feat: allow matching navigation hierarchies with side nav item

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardWidget.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-testbench/src/main/java/com/vaadin/flow/component/dashboard/testbench/DashboardWidgetElement.java
Adds colspan support to dashboard widget.
Added API:
- `int getColspan()`: Returns the colspan of the widget
- `void setColspan(int colspan)`: Sets the colspan of the widget
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=76144368
Feature
> feat: add dashboard widget colspan support

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java
Adds maximum and minimum column width support to dashboard.
Added API:
- `String getMinimumColumnWidth()`: Returns the minimum column width of the dashboard
- `void setMinimumColumnWidth(String minColWidth)`: Sets the minimum column width of the dashboard
- `String getMaximumColumnWidth()`: Returns the maximum column width of the dashboard
- `void setMaximumColumnWidth(String maxColWidth)`: Sets the maximum column width of the dashboard
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=76144368
Feature
> feat: add max min column width support

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java
Adds gap support to dashboard.
Added API:
- `String getGap()`: Returns the gap between the cells of the dashboard
- `void setGap(String gap)`: Sets the gap between the cells of the dashboard
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=76144419
Feature
> feat: add gap support to dashboard

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet.js
This was a tiny error left behind in Spreadsheet Lumo theme
> fix: Do not show error with theme property

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardSection.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java
This PR updates setting the items to use the components directly on the client side. The remaining changes are made to allow this change.
> feat: use components to set items on the client side

- pom.xml
after the `commons-compress` upgrade vaadin/flow#19840 , the `commons-lang3` should be upgraded to avoid the dependency convergence failure
> chore: upgrade commons-lang3 to 3.14.0 (14.12)

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java
Adds minimum row height support to dashboard.
Added API:
- `String getMinimumRowHeight()`: Returns the minimum row height of the dashboard
- `void setMinimumRowHeight(String minRowHeight)`: Sets the minimum row height of the dashboard
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=78740444
Feature
> feat: add min row height support to dashboard

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardChildDetachHandler.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardSection.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardWidget.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/HasWidgets.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-testbench/src/main/java/com/vaadin/flow/component/dashboard/testbench/DashboardSectionElement.java
Adds sections support to dashboard.
Added APIs for `HasWidgets` interface:
- `List<DashboardWidget> getWidgets()`: Returns the widgets in the component.
- `void add(DashboardWidget... widgets)`: Adds the given widgets to the component.
- `void addWidgetAtIndex(int index, DashboardWidget widget)`: Adds the given widget as child of the component at the specific index.
- `void remove(DashboardWidget... widgets)`: Removes the given widgets from the component.
- `void removeAll()`: Removes all widgets from the component.
Added APIs for `Dashboard`:
- `DashboardSection addSection()`: Adds an empty section to the dashboard.
- `DashboardSection addSection(String title)`: Adds an empty section with the provided title to the dashboard.
- `void addSection(DashboardSection section)`: Adds the given …
> feat: add dashboard sections support

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardSectionPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardSectionIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardWidget.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-testbench/src/main/java/com/vaadin/flow/component/dashboard/testbench/DashboardWidgetElement.java
Adds APIs for getting and setting widget content.
Added API:
- `Component getContent()`: Returns the content of the widget
- `void setContent(Component content)`:  Sets the content of the widget (`null` to remove content)
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=78740474
Feature
> feat: add content support to dashboard widget

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardWidget.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-testbench/src/main/java/com/vaadin/flow/component/dashboard/testbench/DashboardWidgetElement.java
Adds APIs for getting and setting widget header.
Added API:
- `Component getHeader()`: Returns the header of the widget
- `void setHeader(Component header)`:  Sets the header of the widget (`null` to remove header)
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=78854087
Feature
> feat: add header support to dashboard widget

- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/SwitchReceiversPage.java
- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/SwitchReceiversIT.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/SwitchReceiversTest.java
The PR fixes the regression where maxFiles could be reset to Infinity when it was set after MultiFileReceiver in the same round-trip or when switching between different MultiFileReceivers. This regression was introduced in https://github.com/vaadin/flow-components/pull/6253.
Fixes https://github.com/vaadin/flow-components/issues/6622
> fix: preserve maxFiles set after MultiFileReceiver in same roundtrip

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/FormulaFieldFormatIT.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java
This PR defers the update of the formula bar so that all the calculations are done beforehand. This fixes the case where the formula bar displays the number using the wrong locale when the cell is selected using the address field. This also applies for the case changing sheet after setting the value and returning to the sheet.
Partially fixes #5731
> fix: update formula bar after the other executions are done

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardDragDropPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardSectionPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardDragDropIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardSectionIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardChildDetachHandler.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardItemReorderEndEvent.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardItemReorderStartEvent.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardSection.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardDragDropTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTestBase.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetTest.java
Adds drag drop support for dashboard.
Added API:
- `void setEditable(boolean editable)`: Sets the option to make the dashboard editable
- `boolean isEditable()`: Returns whether the dashboard is editable
- `Registration addItemReorderStartListener(ComponentEventListener listener)`: Adds an item reorder start listener to the dashboard
- `Registration addItemReorderEndListener(ComponentEventListener listener)`: Adds an item reorder end listener to the dashboard
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=78740411
Feature
> feat: support drag drop for dashboard

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardDragReorderPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardDragResizePage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardDragReorderIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardDragResizeIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardItemResizeEndEvent.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardItemResizeStartEvent.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardDragReorderTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardDragResizeTest.java
Adds drag drop support for dashboard.
Added API:
- `Registration addItemResizeStartListener(ComponentEventListener listener)`: Adds an item resize start listener to the dashboard
- `Registration addItemResizeEndListener(ComponentEventListener listener)`: Adds an item resize end listener to the dashboard
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=79679054
Feature
> feat: add drag resize support to dashboard

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
Part of https://github.com/vaadin/flow-components/issues/6545
> docs(DatePicker, TimePicker): explain constraint validation

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardDragReorderPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardDragResizePage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardDragReorderIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardDragResizeIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardItemRemovedEvent.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardDragReorderTest.java
Adds remove item using button support for dashboard.
Note: This PR does not add functionality for canceling the removal.
Added API:
- `Registration addItemRemovedListener(ComponentEventListener listener)`: Adds an item removed listener to this dashboard
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=79872649
Feature
> feat: support dashboard item remove using button

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardDragReorderTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardDragResizeTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java
This PR adds a check for whether the dashboard is editable before handling client events (resize, reorder, remove).
Refactor
> refactor: do not handle clients events if dashboard is not editable

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardSection.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardWidget.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetTest.java
This PR makes `setVisible` and `isVisible` throw an `UnsupportedOperationException` for `Dashboard`, `DashboardSection`, and `DashboardWidget`.
Refactor
> refactor: throw exception when setting and getting visibility

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardI18nPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardI18nIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
This PR adds internationalization support through `Dashboard.DashboardI18n`.
Added API:
- For `Dashboard`
- `DashboardI18n getI18n()`: Gets the internationalization object previously set for the dashboard
- `void setI18n(DashboardI18n i18n)`: Sets the internationalization object for the dashboard
- For `Dashboard.DashboardI18n`
- `String getSelectSectionTitleForEditing()`: Gets the text for the `aria-label` attribute of section focus buttons
- `DashboardI18n setSelectSectionTitleForEditing(String selectSectionTitleForEditing)`: Sets the text for the `aria-label` attribute of section focus buttons
- `String getSelectWidgetTitleForEditing()`: Gets the text for the `aria-label` attribute of widget focus buttons
- `DashboardI18n setSelectWidgetTitleForEditing(String …
> feat: implement i18n support

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardItemMoveModeChangedEvent.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardItemResizeModeChangedEvent.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardItemSelectedChangedEvent.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardItemMoveTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardItemResizeTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTestHelper.java
This PR implements item mode changed events for the dashboard Flow counterpart.
Added API:
- `Dashboard.addItemSelectedChangedListener`: Adds an item selected change listener to the dashboard
- `Dashboard.addItemMoveModeChangedListener`: Adds an item move mode change listener to the dashboard
- `Dashboard.addItemResizeModeChangedListener`: Adds an item resize mode change listener to the dashboard
New events:
- `DashboardItemSelectedChangedEvent`:
-  `Component getItem()`: Returns the item of which the selected state has changed
-  `boolean isSelected()`: Returns whether the item is selected
- `DashboardItemResizeModeChangedEvent`:
-  `Component getItem()`: Returns the item of which the resize mode state has changed
-  `boolean isResizeMode()`: Returns whether the item is in resize mode
- …
> feat: implement item mode changed events

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardItemMovePage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardItemResizePage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardItemMoveIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardItemResizeIT.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardItemMoveModeChangedEvent.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardItemResizeModeChangedEvent.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardItemSelectedChangedEvent.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardSection.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTestBase.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTestHelper.java
This PR
- updates the dashboard to use `id` in items array instead of a custom `nodeid`, as introduced in the [web component](https://github.com/vaadin/web-components/pull/7869) 
- adds integration tests for keyboard item resize and keyboard item move
- updates handling the client item move event so that the widgets in sections do not get removed and readded
- renames some item move and item resize tests in order to align with the naming convention
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=81029438
Refactor
> refactor: use id instead of nodeid in client items array

- vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/package.json
Pin dependencies in package.json used by the Charts SVG generator
> chore: pin Charts SVG generator npm dependencies

- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/tests/BasicIT.java
Updated `BasicIT` to align with other `GridPro` ITs which use `AbstractComponentIT` to make running locally easier.
- Tests
> test: refactor GridPro IT to use AbstractComponentIT

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardTest.java
This PR
- renames gap APIs to use the name spacing
- updates the dashboard to use the property `--vaadin-dashboard-spacing` instead of `--vaadin-dashboard-gap` 
Renamed API:
- `Dashboard.getGap`-> `Dashboard.getSpacing`
- `Dashboard.setGap`-> `Dashboard.setSpacing`
Refactor
> refactor: rename gap to spacing

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardWidget.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetTest.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-testbench/src/main/java/com/vaadin/flow/component/dashboard/testbench/DashboardWidgetElement.java
This PR renames widget header APIs and updates the slot name to `header-content`.
Renamed API:
- `DashboardWidget.getHeader`-> `DashboardWidget.getHeaderComponent`
- `DashboardWidget.setHeader`-> `DashboardWidget.setHeaderComponent`
Refactor
> refactor: rename header apis and use header content slot

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/dataview/ComboBoxLazyDataView.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxLazyDataViewTest.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxListDataViewTest.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/Item.java
Previously only the generic and list data views would pass a custom identifier provider to the key mapper. This fixes lazy data view to do the same. Effectively, if there are duplicate items in the dropdown, this change will now show all of them as checked if one of them is selected.
Fixes https://github.com/vaadin/flow/issues/19361
> fix: also pass identifier provider to key mapper for lazy data views

- eclipse/VaadinJavaConventions.xml
- pom.xml
Currently we reference the formatter config from the Flow Github project. That has some downsides:
- Changes to the config are out of our control, and if it changes (as is happening right now) all PRs are blocked until we create a PR for updating the formatting
- It does not work offline
This adds a duplicate of the config to our repo so that we are not affected by changes in the Flow repo. We can try to sync. the configs from time to time.
> chore: add formatter config to repo

- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheetVariant.java
- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabsVariant.java
Related to #6652
Marked these incorrectly added variants as deprecated with the suggestion to use `TabVariant` instead:
- Deprecation
> chore: deprecate ICON_ON_TOP Tabs and TabSheet variants

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
The `setDropMode` and `setRowsDraggable` methods were [updated](https://github.com/vaadin/flow-components/pull/6339) to call `dataCommunicator.reset` to ensure drop filters are applied when the drop mode is set dynamically. While this fixed the original issue, it introduced an unintended side effect: an annoying scroll position reset that now happens e.g. when setting the drop mode dynamically on drag start. 
Unfortunately, resolving this new issue completely is impossible without introducing new API in `DataCommunicator`. An API that would allow us to request `refreshItem` for only items that are in the viewport. 
Since not working filters appear to be a more critical issue, it was decided to keep the original change but try to mitigate its impact by preventing the data reset when no …
> fix: do not trigger data communicator reset when no filters

- vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
- vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/VaadinItem.java
- vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/data/SelectDataViewTest.java
When refreshing a single item in a `Select` data provider, the component currently assumes that the existing item instance has been updated, but does not handle replacing item instances. However the `refreshItem` JavaDoc explicitly mentions that use case:
> Refreshes the given item. This method should be used to inform all DataProviderListeners that an item has been updated or replaced with a new instance.
This change makes `Select` handle replacing item instances as well.
Fixes https://github.com/vaadin/flow-components/issues/6579
> fix: allow replacing item instances with `refreshItem`

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridColumnOrderHelper.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridColumnOrderTest.java
Fixes https://github.com/vaadin/flow-components/issues/6730
> fix: ignore non-column children when setting column order

- vaadin-login-flow-parent/vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/AbstractLogin.java
- vaadin-login-flow-parent/vaadin-login-flow/src/test/java/com/vaadin/flow/component/login/LoginFormTest.java
- vaadin-login-flow-parent/vaadin-login-flow/src/test/java/com/vaadin/flow/component/login/LoginOverlayTest.java
Setting both login listeners and form action can cause unexpected behaviors because of concurrent processing of form submission processing and login event.
For example, if form submission ends in a session ID change and a redirect to a different page, the UIDL request may fail with a session expiration response, causing the Flow client to reload the page and potentially cancel the ongoing redirection.
In addition, after from submission, the login event would be sent to a dismissed UI.
This change removes the default login listener when setting a form action, and logs a warning when setting both an action and custom login listeners.
References vaadin/flow#12640
> fix: remove default login listener when setting form action

- vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/main/java/com/vaadin/flow/data/renderer/tests/ComponentRendererInNewThreadPage.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/test/java/com/vaadin/flow/data/renderer/tests/ComponentRendererInNewThreadIT.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/lit-renderer.ts
Using `UI.getCurrent()` isn't safe because even when the container is attached, it may return `null`. This PR updates the ComponentRenderer implementation to access the UI instance through the container element where it's guaranteed to be available if the container is attached.
Fixes #6751
> fix: access UI through container element in ComponentRenderer

- vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/main/java/com/vaadin/flow/data/renderer/tests/ComponentRendererInNewThreadPage.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/test/java/com/vaadin/flow/data/renderer/tests/ComponentRendererInNewThreadIT.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/lit-renderer.ts
Cherry-picks #6759 to 24.4
There was one merge conflict in `lit-renderer.ts` because the `renderFunction` function is written differently in 24.4
> fix: access UI through container element in ComponentRenderer (#6759) (CP: 24.4)

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuConnector.js
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuTargetConnector.js
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/test/env-setup.ts
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/env-setup.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/resources/META-INF/resources/frontend/menubarConnector.js
- vaadin-messages-flow-parent/vaadin-messages-flow/src/main/resources/META-INF/resources/frontend/messageListConnector.js
- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java
- vaadin-select-flow-parent/vaadin-select-flow/src/main/resources/META-INF/resources/frontend/selectConnector.js
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/vaadin-time-picker/timepickerConnector.js
Why tryCatchWrapper is problematic:
- It suppresses exceptions in favour of console error messages. However, the stack trace that the browser displays with these messages omits the function call that caused the original exception, making it much less helpful
- It introduces an extra layer of code nesting, which has a negative impact on the readability and maintainability
- Its error coverage is still limited e.g. it doesn't catch errors in asynchronous contexts created by the web component, where no connector methods are invoked
- It pollutes the stack trace with its own calls, which can be distracting when debugging
- It must be applied to every function including setTimeout callbacks, which is easy to miss
We have decided that the drawbacks now outweigh the benefits, so we are choosing …
> refactor: remove tryCatchWrapper for better stack trace

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/EditorImpl.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/editor/EditorBeanTest.java
The PR prevents an exception when opening beans that are Java records in GridEditor. The exception was caused by using `setBean` which since 24.5 throws when used with records. Instead, `readBean` should be used.
Fixes #6755
> fix: do not throw when opening Java record in GridEditor

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
Applied the workaround from https://github.com/vaadin/flow-components/pull/6781/commits/17839951dc47923efd0e316e76584f3147e1ee05 for `24.5` branch.
- Test
> test: don't test by generated item property names (CP: 24.5)

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
Applied the workaround from https://github.com/vaadin/flow-components/pull/6781/commits/17839951dc47923efd0e316e76584f3147e1ee05 for `24.4` branch.
- Test
> test: don't test by generated item property names (CP: 24.4)

- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
Refactor the sizing API to use the `height` and `width` properties introduced in the web component
Part of https://github.com/vaadin/web-components/issues/1060
- Feature
> refactor: use new sizing API in Dialog

- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
Adds the position API that uses the newly introduced `top` and `left` properties added to the Dialog web component.
Part of https://github.com/vaadin/web-components/issues/1060
- Feature
> feat: add position API to Dialog

- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
Adds the API to allow listening to the `dragged` event sent by the web component. 
This PR:
- Add the `DialogDraggedEvent` class and the `addDraggedListener` method in `Dialog` to allow registering event listeners.
- Adds a default listener to the event to allow synching the `top` and `left` values when the event is fired
- Modifies the `DialogResizeEvent` class to add the `top` and `left` values sent by the client event
- Modifies the default listener also to sync the `top` and `left` values on resize
Depends on #6782
Part of https://github.com/vaadin/web-components/issues/1060
- Feature
> feat: add `dragged` event to Dialog

- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
- vaadin-popover-flow-parent/vaadin-popover-flow/src/test/java/com/vaadin/flow/component/popover/PopoverAutoAddTest.java
Fixes #6752
Based on https://github.com/vaadin/flow-components/pull/4289 previously implemented for `Tooltip`. See also https://github.com/vaadin/flow-components/pull/5514 for an explanation why we need to pass `false`.
- Bugfix
> fix: make auto-added Popover work with PreserveOnRefresh

- vaadin-details-flow-parent/vaadin-details-flow-integration-tests/src/test/java/com/vaadin/flow/component/details/tests/BasicIT.java
Same as #6682 but for `Details`.
This component was initially using the setup of "Pro" components, let's change it to use `AbstractComponentIT`.
Note: there's a second IT test file that is already using it, so it makes sense to align these.
- Test
> test: refactor Details IT to use AbstractComponentIT

- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java
Updated Checkbox to use `accessibleName` and `accessibleNameRef` added in https://github.com/vaadin/web-components/pull/7285
This is needed to make the Lit based version work since `inputElement` isn't available synchronously.
- Refactor
> refactor: update Checkbox to use accessibleName properties

- vaadin-login-flow-parent/vaadin-login-flow/src/test/java/com/vaadin/flow/component/login/LoginFormTest.java
- vaadin-login-flow-parent/vaadin-login-flow/src/test/java/com/vaadin/flow/component/login/LoginOverlayTest.java
https://github.com/vaadin/flow-components/pull/6669 introduced static mocking of `LoggerFactory` in `LoginFormTest`, however that seems to cause flaky tests, such as the failure [here](https://teamcity.vaadin.com/buildConfiguration/VaadinFlowComponents_PullRequestValidation/248881?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false) on a PR for `Upload`.
Moving the mocking into the respective test methods [seems to help](https://teamcity.vaadin.com/buildConfiguration/VaadinFlowComponents_PullRequestValidation/248919?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true).
> test: isolate logger mocking into respective tests

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocaleIT.java
Ignore future flag warnings from React Router in integration tests.
> chore: ignore React Router warnings in tests

- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/DisabledUploadTest.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/UploadTest.java
Allows to disable the upload component, which disables all buttons, prevents drag and drop of files and focusing elements within the component.
When disabled, the upload component does not accept new uploads, but keeps processing existing ones.
Part of https://github.com/vaadin/web-components/issues/1278
Depends on https://github.com/vaadin/web-components/pull/8090
> feat: implement HasEnabled for Upload

- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasClientValidation.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/validation/AbstractBasicValidationTest.java
The PR deprecates `ClientValidatedEvent` and `HasClientValidation`, with plans to remove them in the next major where web components will stop dispatching `validated` events when used as part of their Flow counterparts, see https://github.com/vaadin/flow-components/pull/6792
> refactor: deprecate ClientValidatedEvent and HasClientValidation

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/ColorConverterUtil.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/XSSFColorConverter.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/XSSFColorConverterTest.java
Fixes logic for retrieving text and background color from formatting rules and adds handling of indexed and RGB colors.
Fixes https://github.com/vaadin/flow-components/issues/6819
> fix: apply colors from conditional formatting

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetPage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardWidget.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/tests/DashboardWidgetTest.java
This PR renames header component related API to use "header content" instead.
Fixes #[8149](https://github.com/vaadin/web-components/issues/8149)
> refactor: rename header component to header content

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardSection.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/HasWidgets.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/DashboardTest.java
Adds 2 new API to `HasWidgets`:
- `void add(Collection<DashboardWidget> widgets)`
- `void remove(Collection<DashboardWidget> widgets)`
Fixes [the project board issue](https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=87240740).
> feat: make haswidgets api also accept collections

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/DashboardWidget.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/DashboardWidgetTest.java
This PR adds the following convenience constructors for the `DashboardWidget`:
- `DashboardWidget(String title)`
- `DashboardWidget(Component content)`
- `DashboardWidget(String title, Component content)`
Fixes [the related project board issue](https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=87240651).
> feat: add constructor overloads for dashboard widget

- vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/ThemableLayout.java
- vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/test/java/com/vaadin/flow/component/orderedlayout/tests/ThemableLayoutTest.java
This pull request introduces new functionality to the `ThemableLayout` class in the `vaadin-ordered-layout-flow` package, adding support for item wrapping within the layout. Additionally, it includes corresponding test cases to ensure the new functionality works as expected.
New functionality:
* [`vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/ThemableLayout.java`](diffhunk://#diff-652e2ed58d8825aa2bbddc2a86f3c6eb8b29d76e81c7c3af6ebdca36578e9d19R108-R139): Added `setWrap` and `isWrap` methods to control and check whether items should wrap to new lines or columns when they exceed the layout's boundaries.
Testing:
* [`vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/test/java/com/vaadin/flow/component/ordered …
> feat: add wrap API to HorizontalLayout/VerticalLayout

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/validation/BigDecimalFieldBasicValidationTest.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/BasicValidationTest.java
The PR follows up on #6743 and updates TimePicker and BigDecimalField to not rely on `_hasInputValue` for detecting bad input. This change will allow us to remove some overrides in the [date-picker](https://github.com/vaadin/web-components/blob/0f883924dc1bc039c67d5b78091290a388ec33b6/packages/date-picker/src/vaadin-date-picker-mixin.js#L407-L421) and [time-picker](https://github.com/vaadin/web-components/blob/0f883924dc1bc039c67d5b78091290a388ec33b6/packages/time-picker/src/vaadin-time-picker-combo-box.js#L84-L95) web components.
Part of https://github.com/vaadin/web-components/issues/5639
> refactor: do not rely on _hasInputValue for detecting bad input

- vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
- vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationTest.java
- vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTest.java
Added missing Flow API for the `assertive` web component property added in https://github.com/vaadin/web-components/pull/7758
- Feature
> feat: add API for setting assertive to Notification

- vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/themes/LumoDarkTheme.java
- vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/themes/LumoLightTheme.java
Fixes https://github.com/vaadin/web-components/issues/8196
> fix: restore hover effect on pie charts when using Lumo theme classes

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/dataview/AbstractItemCountComboBoxIT.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/AbstractComponentIT.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ContextMenuIT.java
Cherry-pick of https://github.com/vaadin/flow-components/pull/6859
Sonar failure is an unrelated issue.
> test: make integration tests work with new headless mode (24.4)

- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/MultiFileBuffer.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/UploadSerializableTest.java
The files will be null after de-serialization, which will lead to NPE.
> fix: Files map is transient that needs to be restored if null

- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuItem.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuItemBase.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/internal/DisableOnClickController.java
Moves the disable on click logic to `MenuItemBase`, which also makes it available for `GridMenuItem`.
> refactor: move disable on click to menu item base

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/src/main/java/com/vaadin/flow/component/dashboard/tests/DashboardItemResizePage.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/DashboardTest.java
This PR splits the current spacing API to gap and dashboard.
Depends on https://github.com/vaadin/web-components/pull/8205.
The new API:
- `String getGap()`
- `void setGap(String gap)`
- `String getPadding()`
- `void setPadding(String padding)`
Fixes [the related project board issue](https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=88099241).
> refactor: separate spacing into gap and padding

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTest.java
Add `setAriaLabel`/`getAriaLabel` methods to `Grid` that uses the `accessibleName` property available in the web component to set the `aria-label` attribute on its internal `<table>` element.
Fixes vaadin/web-components#6749
> feat: add `setAriaLabel` to `Grid`

- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
Fixes #6889
Updated defaults to match the change from https://github.com/vaadin/web-components/pull/7682.
> docs: use correct Popover delay default values in JavaDoc

- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java
- vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java
Currently UploadElement.waitForUploads checks for in-progress uploads only once causing the test to fail if the upload does not complete in 500 milliseconds. This change repeats the check every 500 milliseconds, until the condition is verified or the script execution times out.
Fixes #3646
> fix: make waitForUploads poll for upload processing until completion or timeout

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/validation/ComboBoxInitialValueValidationPage.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/validation/ComboBoxInitialValueValidationIT.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/ClientValidationUtil.java
Change the `preventWebComponentFromModifyingInvalidState` method in `ClientValidationUtil` class to always set the invalid state of the component on the client to override any client-side validation that may happen before the `_shouldSetInvalid` is overridden.
That's the root cause of the linked issue where a `ComboBox` can stay stuck in the invalid state on the client when the user calls `setValue("")` on the initialization of the component instance.
Fixes https://github.com/vaadin/flow-components/issues/6881
> fix: ensure that invalid state is set from the server 

- vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
- vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java
Since `Select` uses the key mapper for converting presentation value to model value, the key mapper needs to be updated when individual items are refreshed via the data view.
Fixes https://github.com/vaadin/flow-components/issues/6908
> fix: update keymapper when refreshing select item

- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java
Since `RadioButtonGroup` uses the key mapper for converting presentation value to model value, the key mapper needs to be updated when individual items are refreshed via the data view.
Related to https://github.com/vaadin/flow-components/issues/6908
> fix: update keymapper when refreshing radio button item

- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupTest.java
Since `CheckboxGroup` uses the key mapper for converting presentation value to model value, the key mapper needs to be updated when individual items are refreshed via the data view.
Related to https://github.com/vaadin/flow-components/issues/6908
> fix: update keymapper when refreshing checkbox item

- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/main/java/com/vaadin/flow/component/richtexteditor/tests/RichTextEditorI18nPage.java
- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/tests/RichTextEditorI18nIT.java
- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
Currently the I18N settings are lost when detaching and reattaching RichTextEditor. This restores the I18N settings when attaching the component again.
Also:
- Allows setting partial I18N objects, similar to other components like Upload
- Replaces usage of the Polymer `set` API for nested path updates, which should help with Lit migration
> fix: restore i18n when detaching and reattaching

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavItemTest.java
Allows setting `SideNavItem` paths using views that implement `HasUrlParameter`.
The implementation is adapted from `RouterLink`.
Closes https://github.com/vaadin/flow-components/issues/6949
> feat: add support for views with HasUrlParameter to SideNavItem

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/pom.xml
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNav.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavItemTest.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavTest.java
Allows to create a side nav instance from a list of `MenuEntry`s which can be aquired from `MenuConfiguration.getMenuEntries`. Also adds a constructor to `SideNavItem` to create an item from a single `MenuEntry`.
- When an entry has a view class, it detects the path from the route annotation of that class and also adds route aliases
- When an entry has no view class (such as client-side routes), it uses the string path of the entry as path
- Automatically sets either an `Icon` or `SvgIcon` as prefix depending on whether the icon string references an iconset icon or an SVG file
Part of https://github.com/vaadin/flow-components/issues/6885
> feat: create side nav from menu entries

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/pom.xml
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNav.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavItemTest.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavTest.java
This reverts commit e3cb174e2cba7195c36ab1c521f3c0d95741ae57.
The import for `com.vaadin.flow.component.icon.Icon` results in adding the Vaadin iconset to the frontend bundle even if you never use icons from that iconset.
> Revert "feat: create side nav from menu entries (#6957)"

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/main/java/com/vaadin/flow/component/spreadsheet/tests/SizingPage.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/SizingIT.java
Recalculate sheet position as part of the method triggered by the `ResizeObserver` configured on the Spreadsheet component. It fixes an issue where the pane's positions are wrongly calculated when the component is attached to a hidden parent.
Fixes #6932
> fix: update panes positions on Spreadsheet resize 

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java
Refactored DatePickerIT to use the TestBench API for setting and reading properties instead of using direct JS execution.
Extracted from https://github.com/vaadin/flow-components/pull/6797
> test: refactor DatePickerIT to use TestBench API

- vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/main/java/com/vaadin/flow/component/virtuallist/tests/VirtualListPage.java
- vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListIT.java
- vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/java/com/vaadin/flow/component/virtuallist/VirtualList.java
- vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/resources/META-INF/resources/frontend/virtualListConnector.js
- vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListTest.java
Add item accessible name generator API to `VirtualList`.
Extracted from https://github.com/vaadin/flow-components/pull/6912
Part of https://github.com/vaadin/platform/issues/6838
Feature
> feat: add virtual list item accessible name generator

- vaadin-app-layout-flow-parent/vaadin-app-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/applayout/tests/AppLayoutIT.java
Same as #6801 but for `AppLayout`.
This component was initially using the setup of "Pro" components, let's change it to use `AbstractComponentIT`.
Note: there's a second IT test file that is already using it, so it makes sense to align these.
- Test
> test: refactor AppLayout IT to use AbstractComponentIT

- vaadin-checkbox-flow-parent/vaadin-checkbox-testbench/src/main/java/com/vaadin/flow/component/checkbox/testbench/CheckboxElement.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
The PR updates the `setChecked` method of `CheckboxElement` to dispatch a change event, allowing applications to use this method for selecting grid checkboxes after they were refactored to listen to the change event in https://github.com/vaadin/web-components/pull/8239.
> fix: dispatch change event in setChecked

- vaadin-login-flow-parent/vaadin-login-testbench/src/main/java/com/vaadin/flow/component/login/testbench/LoginFormElement.java
As part of https://github.com/vaadin/web-components/pull/8438 and https://github.com/vaadin/web-components/pull/8441, the Login component no longer uses `<h*>` elements internally, but the `LoginFormElement` references these elements tag names to find them. This updates the selectors to use part names instead.
This issue was first noticed from test failures at https://github.com/vaadin/flow-components/pull/7003
> test: update loginform element to use part names

- vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/AvatarGroupVariant.java
- vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/AvatarVariant.java
- vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/ButtonVariant.java
- vaadin-card-flow-parent/vaadin-card-flow/src/main/java/com/vaadin/flow/component/card/CardVariant.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroupVariant.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxVariant.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxVariant.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePickerVariant.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePickerVariant.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridVariant.java
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridProVariant.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBarVariant.java
- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/PopoverPosition.java
- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/PopoverVariant.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioGroupVariant.java
- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditorVariant.java
- vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/SelectVariant.java
- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheetVariant.java
- vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabsVariant.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextAreaVariant.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextFieldVariant.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePickerVariant.java
Since https://github.com/vaadin/flow-components/pull/7010 enum values are automatically put on individual lines, so the formatter instructions have become unnecessary.
> chore: remove unnecessary formatter instructions

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java
The PR fixes DatePicker and TimePicker to not set the initialValue as the default emptyValue. This was a regression accidentally introduced during the removal of the generated field classes in https://github.com/vaadin/flow-components/pull/4351/ and https://github.com/vaadin/flow-components/pull/4348.
Fixes #6325
> fix: prevent initialValue from becoming emptyValue

- vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow/src/main/java/com/vaadin/flow/theme/lumo/LumoUtility.java
Fixed typos: `:tems-start` -> `:items-start`.
- Bugfix
> fix: fix typo in Lumo utility align-start class names

- .env.example
- .gitignore
- shared/shared-vite-config.ts
- shared/web-components-vite-plugin.ts
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/vite.config.ts
Use the `.env`  config to define the path to the local web components repository to prevent the path from being accidentally committed to Git.
> chore: use .env config to define path to local web components

- vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/button/tests/ButtonIT.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/test/java/com/vaadin/flow/component/contextmenu/it/MenuItemDisableOnClickIT.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/internal/DisableOnClickController.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/resources/META-INF/resources/frontend/disableOnClickFunctions.js
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/DisableOnClickControllerTest.java
This PR replaces the requestAnimationFrame approach with a global click listener for disabling components when `disableOnClick` is set to true. This ensures the disabling happens synchronously, avoiding race conditions with server requests, and only after all other click listeners have been executed, allowing the context menu to properly close after a disable-on-click item was clicked.
Fixes https://github.com/vaadin/flow-components/issues/7009
> fix: replace requestAnimationFrame with global click listener

- vaadin-login-flow-parent/vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/tests/AbstractLoginIT.java
- vaadin-login-flow-parent/vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/tests/I18nIT.java
- vaadin-login-flow-parent/vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/tests/LoginFormIT.java
- vaadin-login-flow-parent/vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/tests/OverlayIT.java
Same as #6801 but for `LoginOverlay` and `LoginForm`.
This component was initially using the setup of "Pro" components, let's change it to use `AbstractComponentIT`.
Note: there are some IT test files that are already using it, so it makes sense to align these.
- Test
> test: refactor Login ITs to use AbstractComponentIT

- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BasicValidationTest.java
Fixes #7073
Due to the change in #6922, the component always sets `invalid` property on `isInvalid()` on attach. While this makes sense in general, it turns out that calling `setInvalid(true)` on the DateTimePicker does not update corresponding state on its slotted pickers and they end up sending `invalid = false` to the client on initialisation.
Note: I'm not sure if this needs an IT since the problem is that `isInvalid()` returns wrong value and that's now covered with a unit test. Just to clarify, this problem can't be reproduced in the web component  (without `ClientValidationUtil` logic).
- Bugfix
> fix: ensure invalid state is correctly set on slotted pickers

- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/tests/GridProItemDetailsPage.java
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/tests/GridProItemDetailsIT.java
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js
Adds an additional check for whether `cell._column` is defined to ignore row details cells when applying cell update animations.
Fixes https://github.com/vaadin/web-components/issues/8609
- Bugfix
> fix: ignore row details cells when applying cell update animation

- scripts/templates/apache2-license-header.txt
- scripts/templates/vaadin-commercial-license-header.txt
The current license header formatting enforces a specific year, which results in formatter checks failing in older version branches where we have not updated the copyright.
This updates the formatting to:
- Use the current year when adding a new license header
- Accept any year when checking an existing license header
> chore: improve license header formatting

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/component/spreadsheet/client/ConnectorBundleLoaderFactory.java
The Spreadsheet client uses an outdated license checker that has now been removed from Framework in https://github.com/vaadin/framework-es/pull/335. That in turn causes compilation issues when trying to bump the Framework version (https://github.com/vaadin/flow-components/pull/7083).
As I understand it, for the Flow Spreadsheet we build the client at build time, so a license check at that point seems unnecessary. Besides, the actual license check for the Flow Spreadsheet happens here: https://github.com/vaadin/flow-components/blob/a7152f830a9ee775ce7772f8ace53bff4c80da9a/vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java#L138-L143
Thus I figure we can remove the license check from the client completely.
> chore: remove obsolete license checker from spreadsheet

- pom.xml
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/pom.xml
exclude `log4j-api` dependency, as poi uses different log4j-api versions in its modules. 
```
[ERROR] Dependency convergence error for org.apache.logging.log4j:log4j-api:jar:2.24.3 paths to dependency are:
[ERROR] +-com.vaadin:vaadin:jar:24.7-SNAPSHOT
[ERROR]   +-com.vaadin:vaadin-spreadsheet-flow:jar:24.7-SNAPSHOT:compile
[ERROR]     +-org.apache.poi:poi:jar:5.4.0:compile
[ERROR]       +-org.apache.logging.log4j:log4j-api:jar:2.24.3:compile
[ERROR] and
[ERROR] +-com.vaadin:vaadin:jar:24.7-SNAPSHOT
[ERROR]   +-com.vaadin:vaadin-spreadsheet-flow:jar:24.7-SNAPSHOT:compile
[ERROR]     +-org.apache.poi:poi-ooxml:jar:5.4.0:compile
[ERROR]       +-org.apache.xmlbeans:xmlbeans:jar:5.3.0:compile
[ERROR]         +-org.apache.logging.log4j:log4j-api:jar:2.24.2:compile
[ERROR] and
[ERROR] …
```
> chore: upgrade spreadsheet dependency versions

- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/resources/META-INF/resources/frontend/vaadin-big-decimal-field.js
The PR refactors the `vaadin-big-decimal-field` web component to import the TextField class from `@vaadin/text-field` instead of using `customElements.get`.
> refactor: import TextField class from @vaadin/text-field

- vaadin-accordion-flow-parent/vaadin-accordion-testbench/src/main/java/com/vaadin/flow/component/accordion/testbench/AccordionElement.java
- vaadin-app-layout-flow-parent/vaadin-app-layout-testbench/src/main/java/com/vaadin/flow/component/applayout/testbench/AppLayoutElement.java
- vaadin-avatar-flow-parent/vaadin-avatar-testbench/src/main/java/com/vaadin/flow/component/avatar/testbench/AvatarElement.java
- vaadin-avatar-flow-parent/vaadin-avatar-testbench/src/main/java/com/vaadin/flow/component/avatar/testbench/AvatarGroupElement.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-testbench/src/main/java/com/vaadin/flow/component/checkbox/testbench/CheckboxGroupElement.java
- vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-testbench/src/main/java/com/vaadin/flow/component/cookieconsent/testbench/CookieConsentElement.java
- vaadin-crud-flow-parent/vaadin-crud-testbench/src/main/java/com/vaadin/flow/component/crud/testbench/CrudElement.java
- vaadin-custom-field-flow-parent/vaadin-custom-field-testbench/src/main/java/com/vaadin/flow/component/customfield/testbench/CustomFieldElement.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-testbench/src/main/java/com/vaadin/flow/component/dashboard/testbench/DashboardElement.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-testbench/src/main/java/com/vaadin/flow/component/datepicker/testbench/DatePickerElement.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-testbench/src/main/java/com/vaadin/flow/component/datetimepicker/testbench/DateTimePickerElement.java
- vaadin-details-flow-parent/vaadin-details-testbench/src/main/java/com/vaadin/flow/component/details/testbench/DetailsElement.java
- vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridElement.java
- vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/TreeGridElement.java
- vaadin-grid-pro-flow-parent/vaadin-grid-pro-testbench/src/main/java/com/vaadin/flow/component/gridpro/testbench/GridProElement.java
- vaadin-list-box-flow-parent/vaadin-list-box-testbench/src/main/java/com/vaadin/flow/component/listbox/testbench/ListBoxElement.java
- vaadin-login-flow-parent/vaadin-login-testbench/src/main/java/com/vaadin/flow/component/login/testbench/LoginOverlayElement.java
- vaadin-map-flow-parent/vaadin-map-testbench/src/main/java/com/vaadin/flow/component/map/testbench/MapElement.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-testbench/src/main/java/com/vaadin/flow/component/menubar/testbench/MenuBarElement.java
- vaadin-messages-flow-parent/vaadin-messages-testbench/src/main/java/com/vaadin/flow/component/messages/testbench/MessageElement.java
- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-testbench/src/main/java/com/vaadin/flow/component/richtexteditor/testbench/RichTextEditorElement.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-testbench/src/main/java/com/vaadin/flow/component/sidenav/testbench/SideNavElement.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-testbench/src/main/java/com/vaadin/flow/component/sidenav/testbench/SideNavItemElement.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-testbench/src/main/java/com/vaadin/flow/component/spreadsheet/testbench/SheetCellElement.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-testbench/src/main/java/com/vaadin/flow/component/spreadsheet/testbench/SpreadsheetElement.java
Remove usage of deprecated API in TestBench elements:
- Replace `TestBenchElement.getAttribute` with `TestBenchElement.getDOMAttribute` or `TestBenchElement.getDOM Property` respectively
- Replace `ElementQuery.attribute`, `ElementQuery.attributeContains` with respective replacements
Part of https://github.com/vaadin/flow-components/issues/7105
- Internal
> chore: replace deprecated api in testbench elements

- vaadin-app-layout-flow-parent/vaadin-app-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/applayout/tests/AppLayoutIT.java
- vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/BasicChartIT.java
- vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/PieWithLegendEventsIT.java
- vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/HelperIT.java
- vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/CompositeIT.java
- vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/CustomGridIT.java
- vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/DetachAttachIT.java
- vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/EditorButtonsIT.java
- vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/EventHandlingIT.java
- vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/NewButtonIT.java
- vaadin-custom-field-flow-parent/vaadin-custom-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/customfield/tests/BasicIT.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/InjectedDatePickerI18nIT.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/ModalityDialogsPageIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewEditorIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewSortingIT.java
- vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/src/test/java/com/vaadin/flow/theme/lumo/LumoIconIT.java
- vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/test/java/com/vaadin/flow/component/notification/tests/PreserveOnRefreshIT.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/HelperIT.java
- vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/tests/AbstractSelectIT.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ChartsIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldPageIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/EmailFieldPageIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/IntegerFieldPageIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldPageIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/PasswordFieldPageIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/TextAreaPageIT.java
- vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadI18nIT.java
Replace usages of the deprecated `attribute` and `attributeContains` APIs.
Part of https://github.com/vaadin/flow-components/issues/7105
- Internal
> chore: replace deprecated ElementQuery APIs in integration tests

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/TreeGridTest.java
As mentioned in the issue, unlike with the Grid you can not pass a Renderer into a TreeGrid to add a Column. To enhance the API and make it possible to do type matching on Renderers passed into the method, I have overloaded the "addComponentHierarchyColumn"-method.
Fixes #7107 
- [] I have not completed some of the steps above and my pull request can be closed immediately.
> feat: allow passing HierarchyColumnComponentRenderer to addComponentHierarchyColumn

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/TreeGridTest.java
Reverts https://github.com/vaadin/flow-components/pull/7120
The intent of the feature was to allow passing a `HierarchyColumnComponentRenderer` to `addComponentHierarchyColumn`. The only thing the new overload did was to define the `children` property on the renderer, however that is unnecessary as `HierarchyColumnComponentRenderer` sets that already in the constructor:
https://github.com/vaadin/flow-components/blob/a04f1e7942bb0248265a61b1209985447414bb65/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/HierarchyColumnComponentRenderer.java#L48-L49
So the overload isn't actually necessary, as the only thing it does is `addColumn(renderer)`, so you can call that directly instead.
In addition to reverting the PR, this adds a commit that removes the …
> Revert "feat: allow passing HierarchyColumnComponentRenderer to addComponentHierarchyColumn (#7120)"

- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/test/java/com/vaadin/flow/component/richtexteditor/RichTextEditorHtmlIsEmptyTest.java
- vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/test/java/com/vaadin/flow/component/richtexteditor/RichTextEditorIsEmptyTest.java
Make `isEmpty` for the RichTextEditor HTML value check whether a user has actually added some content which can be:
- Text, whitespace and line breaks
- Images
Fixes https://github.com/vaadin/web-components/issues/8453
- Bugfix
> fix: check wether HTML values contains user content

- vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/ThemableLayout.java
- vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/test/java/com/vaadin/flow/component/orderedlayout/tests/ThemableLayoutTest.java
This change adds:
- `setSpacing(String)` - method to set spacing passing a CSS length value (e.g. `10px`, `1em`)
- `setSpacing(float, Unit)` - method to set spacing passing a float value and a `Unit`
- `getSpacing()` - method to return the value set to the `gap` CSS property of the layout
It also changes `isSpacing()` to return whether the spacing has been set by the theme API or by setting the `gap` property.
Part of #6999 - the enum API is not part of this PR and should be added later
- Feature
> feat: add API to set spacing in HL/VL with custom values

- vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java
as flow has reverted the "feat: RpcHandlers to use Jackson (vaadin/flow#20985)" 
This reverts commit b828fcbdaba9009f6e0e65c4b7f39a64a1ea3038.
> chore: Revert "chore: fix compilation errors (#7149)"

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridUpdateDataProviderPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridUpdateDataProviderIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
Removes an extra `size` property change in `reset`, which would otherwise clear pending data provider requests.
When setting items and the page size at once, the Flow component does this:
- Set `size` property to the number of items, for example `3`
- Calls `reset`, which reverts `size` to `0`
- Calls `updateSize`, which changes `size` to `3` again
Reverting `size` to `0` causes `DataProviderController` to clear pending requests, and as such the connector can not resolve them in `confirm`, so the grid does not render the updated items automatically. In addition there is some issue with the virtualizer, where resetting the size does not clear rendered items, so that increasing the size again will not result in updates / new data provider requests. Combined those result in the grid not …
> fix: remove size reset to allow data provider calls to resolve

- vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/FlexComponent.java
- vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/test/java/com/vaadin/flow/component/orderedlayout/tests/FlexComponentTest.java
As mentioned in the issue below the setFlexGrow method in FlexComponent removes the flex-grow attribute if 0 is passed in. The expected behavior is that it is set to 0.
Fixes #1244  (issue)
- [] I have not completed some of the steps above and my pull request can be closed immediately.
> fix: allow setting flex-grow to 0 through FlexComponent

- vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
- vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutTest.java
Add a new `FormRow` class that maps to the `<vaadin-form-row>` web component introduced as part of the new `autoResponsive` mode. The class contains a few helper methods to add `FormItem` elements as child of the row.
Part of #7162
> feat(FormLayout): add `FormRow` class to `FormLayout`

- vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
- vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutTest.java
Add a set of methods to enable configuring `FormLayout` in the `autoResponsive` mode. Also change `setLabelWidth`/`getLabelWidth` to use the new CSS variable introduced with the lastest changes in the `FormLayout` web-component.
Part #7162
> feat(FormLayout): add autoResponsive API in FormLayout

- vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/validation/BasicValidationIT.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/validation/CheckboxBasicValidationIT.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/validation/ComboBoxBasicValidationIT.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/validation/MultiSelectComboBoxBasicValidationIT.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/validation/BasicValidationIT.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BasicValidationIT.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/ClientValidationUtil.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasValidationProperties.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/validation/AbstractValidationIT.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/validation/AbstractValidationPage.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/validation/BasicValidationIT.java
- vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/tests/validation/BasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/EmailFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/PasswordFieldBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaBasicValidationIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextFieldBasicValidationIT.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/BasicValidationIT.java
When a component is made invisible, Flow defers all JS executions from being sent to the client until the component becomes visible again. This includes JS executions added during attach, such as [invalid state synchronization after overriding _shouldSetInvalid](https://github.com/vaadin/flow-components/blob/e6fd1706797ccc8498df7a3f143e18446dde4b47/vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/ClientValidationUtil.java#L43-L44). Once the component is visible, all deferred JS executions are sent to the client, but they always execute after property updates. As a result, if `setInvalid(...)` was called earlier, it gets overridden by the deferred JS executions. 
To fix this issue, I currently added `executeJs` to …
> fix: additionally set invalid state via executeJs

- vaadin-card-flow-parent/vaadin-card-flow-integration-tests/src/main/java/com/vaadin/flow/component/card/tests/CardPage.java
- vaadin-card-flow-parent/vaadin-card-flow/src/main/java/com/vaadin/flow/component/card/Card.java
- vaadin-card-flow-parent/vaadin-card-flow/src/main/java/com/vaadin/flow/component/card/CardVariant.java
- vaadin-card-flow-parent/vaadin-card-flow/src/main/java/com/vaadin/flow/component/card/ExperimentalFeatureException.java
- vaadin-card-flow-parent/vaadin-card-flow/src/test/java/com/vaadin/flow/component/card/CardTest.java
- vaadin-card-flow-parent/vaadin-card-flow/src/test/java/com/vaadin/flow/component/card/FeatureFlagTest.java
This PR implements the Flow counterpart for the Card component.
Note 1: One difference from the API described in the issue is the getter for ARIA role. In the issue, the getter for the ARIA attributes are written as `public String getAria...()`. However, the already implemented API for ARIA labels in `HasAriaLabel` return `Optional<String>`. Therefore, the getter for the new ARIA role attribute also returns `Optional<String>` in this PR.
Note 2: Convenience APIs that take String parameters are not a part of this initial implementation.
Fixes #7008
> feat: implement card component flow counterpart

- vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow-integration-tests/src/main/java/com/vaadin/flow/component/masterdetaillayout/tests/MasterDetailLayoutPage.java
- vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/masterdetaillayout/tests/MasterDetailLayoutIT.java
- vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow/src/main/java/com/vaadin/flow/component/masterdetaillayout/MasterDetailLayout.java
- vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow/src/test/java/com/vaadin/flow/component/masterdetaillayout/MasterDetailLayoutTest.java
Adds some basic APIs to `MasterDetailLayout`:
- Implement `HasSize`
- Implement `RouterLayout` which automatically sets route content as detail
- Getters and setters for master and detail component
- Getters and setters for size / min size
Other properties are not covered yet as they are not part of the alpha used by the Flow component.
Part of https://github.com/vaadin/platform/issues/7173
- Feature
> feat: add initial APIs to MasterDetailLayout

- vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
- vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutTest.java
The web component was recently [refactored](https://github.com/vaadin/web-components/pull/8861) to support `null` values as a column width, in which case it defaults to `12em`, or to the value of the `--vaadin-default-field-width` CSS custom property if it is defined.
This PR updates the Flow counterpart to align with that behavior, allowing `setColumnWidth` to accept `null` values as well.
Related to https://github.com/vaadin/platform/issues/7172
> refactor!: allow setColumnWidth to accept null values

- vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
- vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutTest.java
The PR adds APIs for managing components' colspan inside rows:
- `FormRow#setColspan(Component component, int colspan)`
- `FormRow#getColspan(Component component)`
- `FormRow#add(Component component, int colspan)`
Follow-up to https://github.com/vaadin/flow-components/issues/7162
Related to https://github.com/vaadin/platform/issues/7172
> feat: add setColspan API to FormRow

- vaadin-card-flow-parent/vaadin-card-flow-integration-tests/src/main/java/com/vaadin/flow/component/card/tests/CardPage.java
- vaadin-card-flow-parent/vaadin-card-flow-integration-tests/src/test/java/com/vaadin/flow/component/card/tests/CardIT.java
- vaadin-card-flow-parent/vaadin-card-flow/src/main/java/com/vaadin/flow/component/card/Card.java
- vaadin-card-flow-parent/vaadin-card-flow/src/test/java/com/vaadin/flow/component/card/CardTest.java
- vaadin-card-flow-parent/vaadin-card-testbench/src/main/java/com/vaadin/flow/component/card/testbench/CardElement.java
Adds the following String based title API to the Card component:
- String getTitleAsText()
- void setTitle(String title)
- void setTitle(String title, Integer titleHeadingLevel)
- void setTitleHeadingLevel(Integer titleHeadingLevel)
Depends on the related [web component PR](https://github.com/vaadin/web-components/pull/8822) and [TestBench API PR](https://github.com/vaadin/flow-components/pull/7224).
Fixes #7212
> feat: add string based title api to card

- vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow/src/main/java/com/vaadin/flow/component/masterdetaillayout/MasterDetailLayout.java
- vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow/src/test/java/com/vaadin/flow/component/masterdetaillayout/MasterDetailLayoutTest.java
When showing a layout initially, for example when entering the URL for a nested route in the browser, there should not be any transition for the layout or the detail area. This change skips the view transition if details are set during the first roundtrip in which a layout is attached. 
Part of https://github.com/vaadin/platform/issues/7173
Depends on https://github.com/vaadin/web-components/pull/8894
- Refactor
> refactor: skip view transition in first roundtrip

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavIT.java
Two `SideNav` tests have been failing on CI and locally: `clickNavigableParent_urlChanged` and `clickChildOfNavigableParent_urlChanged`. The reason is that the URL assertion can happen before the navigation happens. This PR makes sure that the navigation occurs before the assertions.
> test: fix side nav tests by waiting for navigation

- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/HasSideNavItems.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNav.java
- vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java
This PR converts the base class for components that can contain `SideNavItem`s (`SideNavItemContainer`) into an interface (`HasSideNavItems`). This makes it possible to use the API in a more generic way.
NOTE 1: The protected method `setupSideNavItem` in `SideNavItemContainer` was made private. It seems that this method was intended to be used only internally. However, it can possibly be a breaking change if it was overridden for some reason.
NOTE 2: The 2 failing tests also fail on the main branch without any changes. Related PR: https://github.com/vaadin/flow-components/pull/7270
NOTE 3: An alternative PR https://github.com/vaadin/flow-components/pull/7237 exists and should be closed if this PR is merged.
Related issue: #5089
> refactor: convert side nav item container base class into an interface

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/Cell.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/MergeIT.java
In the `Cell` class, `z-index` of 1 is automatically applied to cells with text content. However, this should not be the case for sub-cells. The first sub-cell in a merged region still contains the text. Usually, this problem is hidden because initially the sub-cells are added to the DOM before the merged cell. When there are two cells with the same `z-index`, the last added cell is shown on top. However, when the sheet is scrolled, sometimes the sub-cell is removed and the merged cell still stays in the DOM. Scrolling back to the row, the sub-cell is added back to the DOM with the same `z-index` of 1. Since the sub-cell is the last added one in this case, it is shown on top. 
This PR adds a check in the `Cell` class to avoid setting `z-index` for sub-cells with text.
Fixes #7177
> fix: do not set z-index for sub-cells with text

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/ClearValueIT.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/ClearValuePage.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/ClearValueIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/IntegerFieldClearValueIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldClearValueIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/ClearValueIT.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
Fixes an issue where calling `setValue(null)` followed by `setValue(previousValue)` in the same round-trip cleared the input element's value, even though the second call should have restored it to a non-empty value. 
To fix this, the logic was refactored to store and read unparsable input from a separate field, rather than relying directly on `getInputElementValue()`.  
Relying directly on `getInputElementValue()` was the cause of the issue, as it required calling `setInputElementValue("")` on every `setValue(null)` call to prevent the validation logic from treating an empty value as bad input. However, `setInputElementValue("")` also triggered a client-side update of the `inputElementValue` property. When followed by `setValue(previousValue)`, this led to a situation where the `value` …
> fix: do not clear displayed value if component value was reverted

- vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/TreeGridElement.java
Adds JavaDoc to explain why `TreeGridElement.getRowCount` does not produce reliable results when nodes are expanded.
Related to https://github.com/vaadin/flow-components/issues/7293
- Chore
> chore: add JavaDoc to explain unreliable TreeGridElement.getRowCount behavior

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/Cell.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/MergeIT.java
Cherry pick of https://github.com/vaadin/flow-components/pull/7239 to 23.5.
> fix: do not set z-index for sub-cells with text (CP 23.5)

- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTargetTest.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenuTest.java
When detaching an element in `beforeClientResponse`, Flow doesn't seem to cancel pending Javascript invocations. This adds a detach listener to context menu targets to cancel invocations explicitly when the target is removed.
Fixes https://github.com/vaadin/flow-components/issues/7280
- Bugfix
> fix: cancel connector init if target is detached in beforeClientResponse

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SpreadsheetFactory.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SpreadsheetFilterTable.java
This PR adds 4 package private internal methods that provide bulk updates:
- `void setColumnsHidden(Map<Integer, Boolean>)`
- `void setRowsHidden(Map<Integer, Boolean>)`
- `void setRowHeights(Map<Integer, Float>)`
- `void setColumnWidths(Map<Integer, Integer>)`
The logic that updates the row is separated from the block that does the style reload. This allows the style reload to be executed once per a set of rows instead of executing for each of them. This greatly increases the filtering performance for large sheets.
Inspired by [another PR](https://github.com/vaadin/flow-components/pull/7252), and retains the main idea. The difference is avoiding the management of the state using a field and less changes to the code.
Fixes #7211
> refactor: add package private convenience bulk size updaters in spreadsheet for performance

- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldClearValueIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
BigDecimalField wasn't among the components affected by the regression fixed in #7277 because it reads the input element's value directly from the `value` property instead of using `_inputElementValue`. However, that fix also moved the logic of clearing bad input in a different place, which makes sense to do for BigDecimalField as well to make it consistent.
> refactor: align bad input clearing with other similar fields

- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
- vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/DashboardTest.java
This PR adds the Flow counterpart for the new API that controls the root heading level of the dashboard.
Fixes #[8779](https://github.com/vaadin/web-components/issues/8779)
> feat: add dashboard root heading level api

- vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/PolygonFeaturePage.java
- vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/PolygonFeatureIT.java
- vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Constants.java
- vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/feature/PolygonFeature.java
- vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/geometry/Polygon.java
- vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/synchronization/index.js
- vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/synchronization/util.js
- vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/feature/PolygonFeatureTest.java
- vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/geometry/PolygonTest.java
- vaadin-map-flow-parent/vaadin-map-testbench/src/main/java/com/vaadin/flow/component/map/testbench/MapElement.java
feat: Add PolygonFeature to the map
If applied, this PR will make it easy to add a styleable (fill, stroke) PolygonFeature to the map.
The ability to set and get the coordinates with a Geometry for Polygons also exists.
Holes within the polygon are supported to display real-life data.
Resolves #2891
- [] I have not completed some of the steps above and my pull request can be closed immediately.
> feat: add support for polygons to Map

- vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
- vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutTest.java
This PR adds the `minColumns` API to the `FormLayout` Flow component.
Depends on https://github.com/vaadin/web-components/pull/8935.
Part of [#8854](https://github.com/vaadin/web-components/issues/8854)
> feat: add mincolumn feature to form layout

- vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/serialization/MapSerializerTest.java
Looks like Flow added a new overload for `StreamResourceRegistry.registerResource`, so one Map test needs a type hint to make it compile again.
> chore: fix map serializer test compilation error

- vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/serializers/BeanSerializerDelegator.java
- vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/serializers/ThemeGradientColorBeanSerializer.java
Aligned the code with `BeanSerializer` in the latest `jackson-databind` where `_anyGetterWriter` was removed.
See https://github.com/FasterXML/jackson-databind/pull/4775 (dependency version bumped in Flow by https://github.com/vaadin/flow/pull/21355).
> chore: remove usage of internal field removed in Jackson 2.19

- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarDetachReattachPage.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarPreserveOnRefreshPage.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarTestPage.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarDetachReattachIT.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarPageIT.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarPreserveOnRefreshIT.java
Follow-up to #7355
Extracted some ITs that are usually placed in separate files in other components:
- `MenuBarDetachReattachIT`
- `MenuBarPreserveOnRefreshIT`
This also makes it easier to debug tests when serving `MenuBarTestPage` manually as `@PreserveOnRefresh` is now removed (with that annotation, all the changes were preserved on browser tab reload which sometimes can be undesired).
- Test
> test: extract more MenuBar ITs into separate files

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
Follow-up to https://github.com/vaadin/flow-components/pull/7232
Use optional chaining to avoid errors when clicking on empty grid, in which case click is on the `<tbody>` element and reference to the `cell` becomes `undefined`. Not sure if this needs a test, ideally it should be handled by TS but that would require enabling [`"noUncheckedIndexedAccess": true`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#checked-indexed-accesses---nouncheckedindexedaccess) and then also removing `// @ts-nocheck` from the connector.
- Bugfix
> fix: use optional chaining for cell button in the connector

- vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/button/tests/ButtonView.java
- vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/button/tests/ButtonIT.java
The logic for adding / removing theme variants on `Button` was covered by unit tests when adding `HasThemeVariant`, see https://github.com/vaadin/flow-components/pull/3284 and https://github.com/vaadin/flow-components/pull/3431. Removed the IT which is redundant so that we don't use Lumo related variant.
- Test
> test: cleanup Button theme variants IT covered by unit test

- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePickerPage.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerIT.java
This IT was added in https://github.com/vaadin/flow-components/pull/2887 alongside with unit tests. Later on the component was updated to use `HasThemeVariant` in https://github.com/vaadin/flow-components/pull/4409 and IMO this IT is now redundant. Let's remove it for consistency with other components, unit tests are enough.
- Test
> test: remove DateTimePicker theme variant IT covered by unit test

- vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/CheckboxDemoPage.java
- vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxIT.java
The IT for `setAriaLabel()` API only exists in Checkbox and was needed because it used to have custom JS logic. It was changed to `accessibleName` in https://github.com/vaadin/flow-components/pull/6808 to align with other components. As discussed in https://github.com/vaadin/flow-components/pull/4760#discussion_r1137039789, we haven't been adding Integration tests for the `HasAriaLabel` functionality so the IT can be removed.
- Test
> test: cleanup no longer needed Checkbox setAriaLabel IT

- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/EmailFieldPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/IntegerFieldPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/NumberFieldPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/PasswordFieldPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/TextAreaPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/TextFieldPage.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldPageIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/EmailFieldPageIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/IntegerFieldPageIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldPageIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/PasswordFieldPageIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/TextAreaPageIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/TextFieldPageIT.java
- vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/PrefixSuffixTest.java
Removed ITs for `placeholder` attribute as all the components implement `HasPlaceholder` interface since https://github.com/vaadin/flow-components/pull/5756 and have corresponding unit tests. There are also ITs added by #6276 - IMO they are questionable but I didn't change them.
Removed ITs for `required` attribute as they are leftovers from the very early version, see https://github.com/vaadin/vaadin-text-field-flow/pull/34.
Nowadays we have both unit tests and validation ITs using `setRequiredIndicatorVisible(true)` that cover actual logic.
Removed ITs for `prefix` and `suffix` only present in NumberField page. Also updated `PrefixSuffixTest` to check if components implement corresponding interfaces added in https://github.com/vaadin/flow-components/pull/4458 (that have proper unit …
> test: cleanup TextField ITs for features covered by unit tests

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerPage.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocaleIT.java
Removed redundant ITs that are mostly covered by `DatePickerLocaleIT` and `DatePickerI18nIT`, see comments below.
- Test
> test: cleanup duplicate and redundant DatePicker ITs

- vaadin-avatar-flow-parent/vaadin-avatar-flow-integration-tests/src/main/java/com/vaadin/flow/component/avatar/tests/AvatarGroupPage.java
- vaadin-avatar-flow-parent/vaadin-avatar-flow-integration-tests/src/main/java/com/vaadin/flow/component/avatar/tests/AvatarPage.java
- vaadin-avatar-flow-parent/vaadin-avatar-flow-integration-tests/src/test/java/com/vaadin/flow/component/avatar/tests/AvatarGroupIT.java
- vaadin-avatar-flow-parent/vaadin-avatar-flow-integration-tests/src/test/java/com/vaadin/flow/component/avatar/tests/AvatarIT.java
- vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/Avatar.java
- vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/AvatarGroup.java
- vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/SvgIcon.java
- vaadin-icons-flow-parent/vaadin-icons-flow/src/test/java/com/vaadin/flow/component/icon/tests/SvgIconTest.java
- vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/src/main/java/com/vaadin/flow/component/messages/tests/MessageListPage.java
- vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/src/test/java/com/vaadin/flow/component/messages/tests/MessageListIT.java
- vaadin-messages-flow-parent/vaadin-messages-flow/src/main/java/com/vaadin/flow/component/messages/MessageListItem.java
- vaadin-messages-flow-parent/vaadin-messages-flow/src/test/java/com/vaadin/flow/component/messages/tests/MessageListTest.java
Add methods/constructors for using the
new DownloadHandler instead of
AbstractStreamResource.
Part of vaadin/flow#21255
> feat: add possibilty to use the new DownloadHandler

- vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/main/java/com/vaadin/flow/component/contextmenu/it/ContextMenuView.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java
This PR adds `addSeparator` API to `ContextMenu` in order to align with `SubMenu`.
No related issue. Related comment: https://github.com/vaadin/flow-components/pull/7357#discussion_r2066447048
> feat: add addSeparator to ContextMenu to align with SubMenu

- vaadin-icons-flow-parent/vaadin-icons-flow/src/test/java/com/vaadin/flow/component/icon/tests/SvgIconTest.java
Updates references to `DownloadRequest` class to `DownloadEvent` in order to reflect the renaming on Flow. 
Fixes the compilation error on main.
Related Flow commit: https://github.com/vaadin/flow/commit/5c8ab80d57fd4b4d16d014a07c882441da7afac3
> fix: update class name based on flow change

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ComponentColumnWithHeightIT.java
- vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridElement.java
Fixes https://github.com/vaadin/testbench/issues/1892
> fix: Ensure row is visible before getting it

- vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/confirmdialog/tests/FeaturesDiy.java
`FeaturesDiy` creates confirm dialogs with custom buttons, but custom cancel or reject buttons are not visible because they need to be explicitly made visible using the respective API. The buttons work in tests as the elements get added to the dialog, they are just invisible. Let's make them visible, otherwise the examples look broken.
- Internal
> chore: show custom buttons in ConfirmDialog ITs

- vaadin-list-box-flow-parent/vaadin-list-box-flow/src/test/java/com/vaadin/flow/component/listbox/test/dataview/ListBoxDataViewTest.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java
- vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/dataview/RadioButtonGroupDataViewTest.java
- vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java
Fix tests that fail due to this Flow [Jsoup version bump](https://github.com/vaadin/flow/pull/21368) that causes whitespace to be stripped.
- Internal
> chore: update outer HTML usages in unit tests

- vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/ValueChangeModeButtonProvider.java
Fixes an invalid usage of `setAllowedCharPattern` in a text area integration test that otherwise causes a client-side error.
- Internal
> chore: fix allowed char pattern usage

- vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/UploadTest.java
The changes in https://github.com/vaadin/flow/pull/21439 introduced an `IOException` throws clause to the `ElementRequestHandler#handleRequest` method, which caused a compilation error in the `vaadin-upload-flow` module for an unhandled exception in one of the tests. Adding a throws clause to such testing method fixes the issue.
> test: add throws clause to Upload test

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/validation/BasicValidationPage.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/validation/BinderValidationPage.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BasicValidationIT.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BinderValidationIT.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
- vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BasicValidationTest.java
- vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
This PR implements DateTimePicker validation improvements for the Flow counterpart. The changes include:
- Use the new `unparsable-change` event from the web component
- Replace the `validated` event
- Prevent multiple validations during a single round-trip
- Improve validation consistency similar to the web component
- Postpone validation during navigation between DP and TP unless we are certain the value will be invalid (unless it is invalid or out of the range set using mix/max)
- Introduce a dedicated error message for incomplete values
- Handle the input element value changes caused by programmatically setting values 
Based on the [prototype](https://github.com/vaadin/flow-components/compare/proto/date-time-picker/unparsable-incomplete-change).
Depends on …
> feat!: date time picker validation improvements

- vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/feature/PolygonFeature.java
- vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/feature/PolygonFeatureTest.java
Currently all polygons use a static style instance by default, which would help reduce the number of configuration objects sent to the client. However that causes the following issues:
- When the style instance is used in multiple UIs, updating the style will result in an exception as only elements of the currently locked UI may be interacted with. This is similar to https://github.com/vaadin/flow-components/issues/3647 
- It would be unexpected that changing the style of a single polygon would affect all others
This change makes all polygons use an individual style instance. Maybe this could be optimized later by not having a style instance by default, and applying a default style in the client-side connector as a fallback.
-  Bugfix
> fix: do not reuse style instances between polygons

- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/HasMenuItems.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuManager.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/SubMenu.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/SubMenuBase.java
This PR
- deprecates all `HasComponents` `add` API and introduces `addComponent` as an alternative
- updates JavaDocs based on the deprecations
- moves `addSeperator` methods to base classes
Part of #5532
> refactor: deprecate hascomponents api and provide alternatives

- vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/main/java/com/vaadin/flow/component/contextmenu/it/AutoAttachedContextMenuPage.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/main/java/com/vaadin/flow/component/contextmenu/it/ContextMenuClosePage.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/main/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPage.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/main/java/com/vaadin/flow/component/contextmenu/it/ContextMenuView.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/main/java/com/vaadin/flow/component/contextmenu/it/MenuItemDisableOnClickView.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/HasMenuItems.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuManager.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/SubMenuBase.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/test/java/com/vaadin/flow/component/contextmenu/MenuManagerTest.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/test/java/com/vaadin/flow/component/contextmenu/SubMenuTest.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridViewContextMenuPage.java
- vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarClosePage.java
Removes the `HasComponents` interface from `ContextMenu` / `SubMenu` and drops the deprecated `add` method in favor of `addComponent`.
Closes https://github.com/vaadin/flow-components/issues/5532
> refactor!: remove HasComponents from ContextMenu

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/CustomEditorIT.java
After the latest changes, some tests in `CustomEditorIT` became [flaky](https://bender.vaadin.com/buildConfiguration/FlowComponents_Snapshot/702786?buildTab=tests#%2Fintegration-tests). It seems that the button is not yet fully rendered by the time the test tries to perform a click on it, so it errors as it has a stale reference to the element. Trying to solve it with a `waitUntil` invocation.
Tests
> test: try to reduce flakyness in CustomEditorIT

- vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/Labels.java
- vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/serializers/LabelsRotationSerializer.java
- vaadin-charts-flow-parent/vaadin-charts-flow/src/test/java/com/vaadin/flow/component/charts/LabelsSerializationTest.java
`Labels.getRotation` is stored and serialized as a string. Normally that works fine, and Highcharts parses the property as a number. However it doesn't work if you also configure `Labels.setStep` - in this case the property must be a number for rotation to work.
This adds a custom serializer for the property that attempts to serialize as number if a number can be parsed, otherwise it falls back to string serialization.
Fixes https://github.com/vaadin/flow-components/issues/7538
- Bugfix
> fix: serialize rotation as number if possible

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/AbstractSpreadsheetIT.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/FormulaFormatIT.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/GenericIT.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/HiddenAndFrozenIT.java
- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/RemoveInsertRowIT.java
Fixes some issues with flaky Spreadsheet ITs:
- Prevent the invalid formula overlay from showing up as it otherwise can block subsequent clicks on buttons
- Increased browser size in a test to allow making assertions on an otherwise invisible cell
- Changed a set of steps for testing keyboard controls to be more reliable
> test: try improve flaky spreadsheet ITs

- vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow-integration-tests/src/main/java/com/vaadin/flow/component/masterdetaillayout/tests/demo/CategoryView.java
- vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow/src/main/java/com/vaadin/flow/component/masterdetaillayout/MasterDetailLayout.java
- vaadin-master-detail-layout-flow-parent/vaadin-master-detail-layout-flow/src/test/java/com/vaadin/flow/component/masterdetaillayout/MasterDetailLayoutTest.java
Adds events to `MasterDetailLayout` to listen for:
- when the backdrop is clicked when the details are in drawer mode
- when the Escape key is pressed in the details area
Both enable developers to hide the details on the respective event.
Part of https://github.com/vaadin/web-components/issues/9049
- Feature
> feat: add BackdropClickEvent and DetailEscapePressEvent

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/CustomEditorIT.java
The fix for the `StaleElementReferenceException` added in https://github.com/vaadin/flow-components/pull/7536 is not effective ([build](https://bender.vaadin.com/buildConfiguration/VaadinFlowComponents_WcFcNightlyValidation/706118?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true)), as it can still occur if the element is removed in between getting the button reference and checking `isDisplayed` on it:
https://github.com/vaadin/flow-components/blob/b0cb2b0c31076164a41dd76addcb6e2aa45cb5a3/vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/CustomEditorIT.java#L439-L443
This makes the method handle the exception and retry in an …
> test: handle stale element reference exception in CustomEditorIT

- vaadin-popover-flow-parent/vaadin-popover-flow-integration-tests/pom.xml
- vaadin-popover-flow-parent/vaadin-popover-flow-integration-tests/src/main/java/com/vaadin/flow/component/popover/tests/PopoverView.java
- vaadin-popover-flow-parent/vaadin-popover-flow-integration-tests/src/test/java/com/vaadin/flow/component/popover/tests/PopoverIT.java
- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
If a popover tries to auto-add itself when another modal element is opened, it may end up being added as a child of said element. That can be problematic in case the target element is not part of the parent modal element and, when the modal is closed, the popover instance is removed with its parent and interacting with the target element won't work as expected.
This fix adds a detach listener to popover and tries to reattach it in case of:
- the popover instance has been auto-added
- the target element is present
- the target element is still attached to the page
Fixes #7505
- Bugfix
> fix: do not delay auto-adding Popover by `beforeClientResponse` 

- vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
- vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/UploadTest.java
To be compatible with Receivers,
UploadHandlers used with Upload
component are registered with
the getUrlPostfix `upload`.
Fixes vaadin/flow#21689
> fix: upload handlers always end with /upload

- pom.xml
Flow bumped Spring-Boot to 4.0.0-SNAPSHOT, so we need their pre-releases Maven repos to resolve the dependencies.
- Internal
> chore: add spring pre-releases repos

- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
- vaadin-popover-flow-parent/vaadin-popover-flow/src/test/java/com/vaadin/flow/component/popover/PopoverAutoAddTest.java
As part of working on https://github.com/vaadin/flow-components/pull/7563, popover was changed so that it auto-adds itself to the same parent as the target. Then it was discovered (https://github.com/vaadin/flow-components/pull/7563#discussion_r2128026091) that this breaks popovers from working in grid component renderers, so the approach was changed to run auto-add outside of `beforeClientResponse`. However the change for adding the popover to the target's parent was not reverted. Thus popovers are not working in grid's at the moment. There is also an exception when using `HasComponents.removeAll` that occurs as a side effect of having both the target and the popover in the same parent node.
This reverts popovers to be auto-added to the current UI modal. It also adds a check to make …
> fix: add popover to UI modal component again

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridScrollToIT.java
Improves the readability of `TreeGridScrollToIT` and increases test reliability by extending the wait time for scroll to index completion.
> test: make TreeGridScrollToIT more readable and reliable

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/AbstractTreeGridIT.java
The scrolling logic that the `assertCellTexts` method includes is already implemented in `TreeGridElement#getCell` which the method also calls.
Part of #7684
> test: simplify assertCellTexts method

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridSelectComponentColumnAfterExpandPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridSelectComponentColumnAfterExpandIT.java
- Renamed `SelectComponentColumnAfterExpandIT` to `TreeGridSelectComponentColumnAfterExpandIT`
- Updated it to extend `AbstractComponentIT` instead of `AbstractTreeGridIT` since it used only initialization logic
Part of #7684
> test: rename tree grid test and make it extend AbstractComponentIT

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridBasicFeaturesPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/AbstractTreeGridIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridBasicFeaturesIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandDataRequestIT.java
Cleanup of test classes that extend `AbstractTreeGridIT`.
Part of #7684
> test: clean up test classes that extend AbstractTreeGridIT

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandCollapseRecursivelyPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandCollapseRecursivelyIT.java
Integration tests should not rely on TestBench methods – such as `TreeGridElement#getNumberOfExpandedRows` – that require client-side access to expanded items. The `expandedItems` array will no longer be available on the client after `HierarchicalDataCommunicator` is refactored to support flat hierarchies.
Part of #7684
> test: avoid relying on TreeGridElement#getNumberOfExpandedRows (part 1)

- scripts/mergeITs.js
- scripts/templates/vite.config.ts
Adds a Vite config for running merged ITs. This allows configuring the ITs to use a local web-components checkout by adding a respective `.env` file.
- Internal
> chore: add vite config for merged ITs

- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerCustomFormatIT.java
- vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java
Updated DatePicker ITs to not rely on the overlay element in order to make them pass also with native popover.
One remaining IT that will be updated together with bumping WC version is the `InjectedDatePickerI18nIT`.
- Test
> test: update DatePicker ITs to not rely on overlay element

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-tree-toggle.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/shared.ts
Adds WTR tests to cover `$server.updateExpandedState` calls in gridConnector.
Part of #7684
> test: add test coverage for $server.updateExpandedState

- shared/web-components-vite-plugin.ts
Currently dependencies imported both from web-components and somewhere in the Flow integration test sources are loaded / bundled twice, which can result in errors, for example when one of those dependency uses `instanceof` checks. We also load Lit twice at the moment due to that.
This change de-dupes some common dependencies, so that only one version is loaded.
- Internal
> chore: dedupe dependencies when using local web components

- vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
Fixes https://github.com/vaadin/flow-components/issues/7744
Removed methods that were deprecated in V24 since https://github.com/vaadin/flow-components/pull/5495
> refactor!: remove deprecated Element APIs from ConfirmDialog

- vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/TreeGridElement.java
Deprecates TreeGridElement's `getNumberOfExpandedRows` and `isLoadingExpandedRows` with the intention of removing them in Vaadin 25 where hierarchy management is being moved to the server-side.
Fixes #7735
> refactor: deprecate legacy TestBench APIs

- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxDataController.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxSpringDataTest.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboboxSerializableTest.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxFilteringTest.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxDataViewTestHelper.java
- vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxLazyDataViewTest.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-data-range.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/shared.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridScrollTest.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTest.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridLazyDataViewTest.java
- vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/main/java/com/vaadin/flow/data/renderer/tests/LitRendererTestComponentWrapper.java
- vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/java/com/vaadin/flow/component/virtuallist/VirtualList.java
- vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/resources/META-INF/resources/frontend/virtualListConnector.js
This PR updates the codebase to use the modern `setViewportRange` method, which replaces the deprecated `setRequestedRange`.
Follow-up to  https://github.com/vaadin/flow/issues/21875
> refactor: use modern setViewportRange method

- vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
- vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/test/java/com/vaadin/flow/component/confirmdialog/ConfirmDialogTest.java
Allows to listen for when a ConfirmDialog's closing animation has finished. When conditionally rendering dialogs this allows to wait until the closing animation has finished before removing the component from the UI, which does not work when using listeners for the `confirm`, `cancel` or `reject` events.
Closes https://github.com/vaadin/flow-components/issues/7793
- Feature
> feat: add addClosedListener to ConfirmDialog

- pom.xml
https://nvd.nist.gov/vuln/detail/CVE-2025-48924
> chore: upgrade commons-lang3 to resolve vulnerable dependency (23.6)

- vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/test/java/com/vaadin/flow/component/contextmenu/it/AbstractContextMenuIT.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuCloseIT.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuDemoIT.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/test/java/com/vaadin/flow/component/contextmenu/it/SubMenuIT.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-testbench/src/main/java/com/vaadin/flow/component/contextmenu/testbench/ContextMenuElement.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-testbench/src/main/java/com/vaadin/flow/component/contextmenu/testbench/ContextMenuItemElement.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-testbench/src/main/java/com/vaadin/flow/component/contextmenu/testbench/ContextMenuOverlayElement.java
Improves the TestBench API for `ContextMenu`:
- Modified `ContextMenuElement.openByRightClick()` to wait for a menu to open and return it. Throws an exception if no menu opens (behavior change).
- Added `ContextMenuElement.getMenuItems()` to get all items from a menu
- Added `ContextMenuElement.getMenuItem(string)` to find an item by text
- Added `ContextMenuElement.waitUntilClosed()` to wait until a context menu has finished closing. Throws an exception if the menu does not close
- Modified `ContextMenuItemElement.openSubMenu()` to wait for a submenu to open and return it. Throws an exception if no menu opens (behavior change).
Also deprecates `ContextMenuOverlayElement`. The class is now a proxy to `ContextMenuElement` and should thus keep working as before.
Fixes …
> feat!: context menu test bench improvements

- vaadin-date-picker-flow-parent/vaadin-date-picker-testbench/src/main/java/com/vaadin/flow/component/datepicker/testbench/DatePickerElement.java
Remove some obsolete information on `DatePickerElement.getOverlayContent`.
> chore: improve DatePickerElement JavaDoc

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/HierarchyColumnComponentRenderer.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
The PR updates the hierarchy column Lit renderer to use the newly introduced `model.hasChildren` instead of defining its own `children` property, which should slightly reduce network traffic by avoiding the transmission of duplicate information.
Related to https://github.com/vaadin/web-components/pull/9956
> refactor: use model.hasChildren in hierarchy column renderer

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/AbstractTreeGridIT.java
The PR adds the assertion for the `aria-level` attribute to `AbstractTreeGridIT#assertRowLevel` to ensure its test coverage.
Extracted from #7676
> test: add assertion for aria-level attribute

- vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java
- vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/SubMenuBase.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
- Remove confusing mentions of "overlay" and just use the component name instead
- Remove mentions of content being added to a separate overlay element
Part of https://github.com/vaadin/flow-components/issues/7775
- Refactoring
> refactor: remove confusing mentions of overlay

- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogWithShortcutPage.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithShortcutIT.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
Removes the workaround for making shortcut registrations register on the overlay, now that the overlay is part of the dialog. Also restores shortcut ITs.
Part of https://github.com/vaadin/flow-components/issues/7775
- Refactoring
> refactor: remove custom Dialog shortcut registration

- vaadin-board-flow-parent/vaadin-board-flow/src/main/java/com/vaadin/flow/component/board/Board.java
- vaadin-board-flow-parent/vaadin-board-flow/src/main/java/com/vaadin/flow/component/board/Row.java
Deprecate `Board` with the intention to remove it in Vaadin 26;
Part of https://github.com/vaadin/web-components/issues/9741
- Refactor
> refactor: deprecate Board

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Original issue prevented grid items to be properly rendered once grid was reopened (in a dialog) and items re-set to new ones. 
Bug started to appear with the introduction of 14.12.8, but the underlying issue has been there for a while it seems. 
Targeting only 14.3 here, because latest branch already has same kind of check for this method.
Basically, there was a missing null / undefined check for cache. 
https://github.com/vaadin/flow-components/issues/7623
- No tests needed in my opinion
> fix: add root cache existence check when returning data

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTestPageIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
The PR simplifies gridConnector's `set` and `clear` methods and makes them more reliable by avoiding the `delete` operator. Using `delete` creates "holes" in the array and causes deleted items to be skipped by JS iteration methods like `forEach` and `reduce`, which can be unexpected and hard to debug.
> refactor: simplify connector set and clear

- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-page-size.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector.test.ts
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
The PR refactors `$connector.set` so that it can accept item arrays of any size, without mandating them to be aligned with the page size. This makes it possible to use this method for granular viewport updates, e.g. when refreshing items:
```js
$connector.set(0, [{ key: '0', state: 'refreshed' }])
$connector.set(5, [{ key: '5', state: 'refreshed' }])
```
Depends on 
- https://github.com/vaadin/flow-components/pull/7896
Part of https://github.com/vaadin/flow/issues/21989
Should be merged before https://github.com/vaadin/flow/pull/22085
> refactor: allow granular viewport updates with $connector.set

- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/treegrid/TreeGridSetViewportRangeByIndexPathTest.java
HierarchicalDataCommunicator can now make multiple `arrayUpdate.set(int, List)` calls, so the tests need to be updated to collect items from each call.
Follow-up to https://github.com/vaadin/flow/issues/21989
> test: update tests to collect items from all arrayUpdate.set calls

- pom.xml
bump jakarta.jakartaee-web-api from 10.0.0 to 11.0.0. bump jakarta.servlet-api from 5.0.0 to 6.1.0.
Fixes: #7634
> chore: update for Jakarta EE 11

- vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/ButtonRelativeTo.java
The enum values found in `DrillUpButtonRelativeTo` are useful for other types that are not related to the drill-up functionality. And since the drill-up button has been deprecated in Highcharts in favor of breadcrumbs, it makes sense to create a new enum with the same values to be used in places like the [reset zoom](https://api.highcharts.com/highcharts/chart.zooming.resetButton.relativeTo) and [breadcrumbs](https://api.highcharts.com/highcharts/drilldown.breadcrumbs.relativeTo) buttons.
Part of #7923
Part of #7946
- Feature
> feat: add `ButtonRelativeTo` enum; deprecate `DrillUpButtonRelativeTo`

- vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java
Removes the deprecated `setContent` and `addContent` methods from `Details` in v25.
Fixes https://github.com/vaadin/flow-components/issues/7530
> refactor!: remove setContent and addContent from Details

- vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/ChartOptions.java
This was missing from the update in how Charts configuration is parsed to the client.
Fixes the `GlobalOptionsIT` tests that started to fail in the snapshots build:
> fix: use JacksonUtils to serialize `ChartOptions`

- vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/src/test/java/com/vaadin/flow/component/messages/tests/MessageInputIT.java
- vaadin-messages-flow-parent/vaadin-messages-testbench/src/main/java/com/vaadin/flow/component/messages/testbench/MessageInputElement.java
Adds `getSubmitButton` to `MessageInputElement`. Follow up from https://github.com/vaadin/web-components/pull/10173 since the `vaadin-button` is replaced with the custom `vaadin-message-input-button`.
Related to [#10170](https://github.com/vaadin/web-components/issues/10170)
> feat: add api for getting message input submit button

- vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/main/java/com/vaadin/flow/component/charts/ui/ExamplesListView.java
Adds a view that makes it easier to access all Chart examples from the integration tests:
- Internal
> chore: add example listing for Chart ITs

- vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/AbstractSpreadsheetIT.java
Makes tests switch between Control and Command keys for selecting cells depending on the OS.
- Test improvements
> test: make Spreadsheet selection ITs work on Macs

- vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/Inactive.java
- vaadin-charts-flow-parent/vaadin-charts-flow/src/test/java/com/vaadin/flow/component/charts/ConfigurationJSONSerializationTest.java
The `Inactive` state in charts has a getter for `lineWidth`, but is missing the setter for it. This PR adds the setter and updates the serialization test to use the setter.
> feat: add missing line width setter for inactive state

- flow-components-bom/pom.xml
- vaadin-aura-theme-flow-parent/vaadin-aura-theme-flow/pom.xml
Rename `vaadin-aura-theme-flow` to `vaadin-aura-theme` to align with `vaadin-lumo-theme`.
- Chore
> chore: rename aura theme module

- vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
"rendered as its HTML text" can give the impression that the string is interpreted as HTML and would thus need to be escaped to avoid XSS. This is not the case – the string is in fact used as plain text.
> docs: remove confusing HTML mentions in Javadocs for Notification

- vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/ChangeUserProjectionPage.java
- vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/DefineCustomProjectionPage.java
- vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/MapEventsPage.java
- vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/MapBase.java
Deprecates:
- `addViewMoveEndEventListener` in favor of `addViewMoveEndListener`
- `addClickEventListener` in favor of `addClickListener`
Part of https://github.com/vaadin/flow-components/issues/3667
- Deprecation
> refactor: deprecate addViewMoveEndEventListener, addClickEventListener

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/treegrid/ScrollToIndexTest.java
The PR makes `scrollToIndex(int...)` throw an unsupported operation exception when it's called with a data provider that uses `HierarchyFormat.FLATTENED`. Instead, `scrollToIndex(int)` should be used with a flat index.
Related to https://github.com/vaadin/docs/issues/4529
> refactor: throw when attempting scrollToIndex(int...) with flat data provider

- vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointLegendItemClickEvent.java
- vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/SeriesLegendItemClickEvent.java
The `button` property points to the wrong path in which it is located in the `originalEvent` object sent by the client. It seems that it didn't fail before, but lately, that has caused some IT failures, as the mapping from `null` to `int` now causes an exception that prevents the Java event objects from being instantiated.
> fix: fix path to property in events

- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGridDataCommunicator.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/treegrid/ScrollToItemTest.java
This PR makes `TreeGrid#scrollToItem` throw `NoSuchElementException` instead of `IllegalArgumentException` in order to align with `Grid#scrollToItem`.
Follow-up to https://github.com/vaadin/flow-components/pull/8070
> refactor: align exception type with grid

- vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/button/tests/TooltipMarkdownPage.java
- vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/button/tests/TooltipMarkdownIT.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasTooltip.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/HasTooltipTest.java
- vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/TooltipTest.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridTooltipPage.java
- vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTooltipIT.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTooltipTest.java
Adds Markdown support to tooltips:
- Adds `Tooltip.setMarkdown(string)` to tooltip handles
- Adds `HasTooltip.setTooltipMarkdown(string)` to components that implement `HasTooltip`
- Adds `Grid.setTooltipMarkdownEnabled(boolean)` to enable Markdown for the Grid tooltip
Part of https://github.com/vaadin/web-components/issues/9771
- Feature
> feat: add markdown support to Tooltip

- vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/pom.xml
Add a missing concrete implementation of an SLF4J library, which prevented errors in the Charts IT module from being logged to the Java console.
> chore: add SLF4J Simple dependency to Charts IT's pom.xml

- vaadin-board-flow-parent/vaadin-board-flow-integration-tests/pom.xml
- vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/pom.xml
- vaadin-map-flow-parent/vaadin-map-flow-integration-tests/pom.xml
Add the missing `slf4j-simple` dependency to ITs modules.
- Chore
> chore: add missing SLF4J concrete library to IT modules
