vaadin/flow-components

scripts/updateNpmVer.js
because we have some @NpmPackage annotation inside the IT module (for example: [here](https://github.com/vaadin/vaadin-flow-components/blob/3651186a3ad91f480373729f15f709a989c3d968/vaadin-accordion-flow-parent/vaadin-accordion-flow-integration-tests/src/main/java/com/vaadin/flow/component/accordion/examples/AccordionInTemplate.java)), so the script should go through files there for the annotation update
=> Scan all files for @NpmPackage

scripts/updateFromMaster.sh
Charts used to have `examples` and `demo` folders but `demo` was removed from v15+
=> Remove the vaadin-charts-flow/demo folder

pom.xml, scripts/updateWebjars.js
it is necessary to fix `mvn dependency:tree | grep "version selected from constraint"`
=> ci: fix build by setting webjar versions

pom.xml
fix platform snapshot 14.4
Those dependencies are pinned in the original flow-component-base. 
when moving the project, they are only in the <dependencyMangement>, 
unless you declare the dependency, those dependencies have no effects.
=> chore: pin dependency versions

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Web-component: grid
Fixes: vaadin/vaadin-grid#1809
Details: Flow Grid's connector overrides the `ensureSubCacheForScaledIndex` function, and adds a debouncer for the logic, the data request gets made asynchronously when expanding the Grids item. If the request for `recalculateColumnWithds` is done on expand listener, the width calculation might occasionally happen before the node gets expanded on the client-side, thus resulting into columns with undesired widths.
=> fix: override isLoading to return proper value

scripts/updateWebjars.js
Add `dependencyManagement` updates
need to cherry-pick to 14.5 branch
Fixes: #249
=> ci: fix the faulty use of const type (#250) [skip ci]

scripts/updatePlatform.sh
the script takes the branch info directly from the build, which makes it impossible to work with PRs (as those branch name is not formulated. )
related: #233
=> ci: allow pass target to platform update script [skip ci]

vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/HelperPage.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/HelperIT.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
Cherry-pick fix into 14.4
Fixes: vaadin/vaadin-checkbox#191
Web-component: checkbox
=> fix: Keep HelperComponent after reset (14.4)

vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/listbox/test/ListBoxDataViewPage.java, vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/listbox/test/ListBoxViewDemoPage.java, vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxDataViewIT.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/ListBox.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/MultiSelectListBox.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/test/java/com/vaadin/flow/component/listbox/test/CustomItem.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxUnitTest.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/test/java/com/vaadin/flow/component/listbox/test/MultiSelectListBoxTest.java
Take IdentifierProvider into use for equality determination in `ListBox` and `MultiSelectListBox` by overriding `valueEquals`:
Fix: #225 
Fix: #227
=> feat: Take IdentifierProvider into use for equality determination in list-box

scripts/prepareDeploy.sh
currently, we have the `-am` parameter used in the component release build, 
as a side effect, if brings in unnecessary dependencies in the deploy list. 
To remove `-am`, we need to add the component parent project and root project 
into the `build.modules`
=> ci: Include root and component-parent into release parameter

scripts/prepareDeploy.sh
Details: currently, we have the `-am` parameter used in the component release build, 
as a side effect, if brings in unnecessary dependencies in the deploy list. 
To remove `-am`, we need to add the component parent project and root project 
into the `build.modules`
=> ci: Include root and component-parent into release parameter [skip ci] (#274)

vaadin-iron-list-flow-parent/vaadin-iron-list-flow-demo/src/main/java/com/vaadin/flow/component/ironlist/demo/IronListView.java
The linked ticket has been merged and closed.
=> chore: remove the outdate the workaround

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/frontend/src/detach-reattach.js, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/pom.xml, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/DetachReattachPage.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/DetachReattachTemplate.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/DetachReattachIT.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
Web-component: radio-button
Fixes: https://github.com/vaadin/vaadin-radio-button/issues/166
Details: RBG automatically adds RadioButtons inside of itself. If the RBG's value gets changed (setValue) while the component isn't in the DOM, the internal RB's remain unchanged. And once they're added back to DOM, Flow synchronizes the old RB values which causes the RBG to revert back to the old value. In order to fix it buttons will be reset on detach.
=> fix: override setValue to set proper value when detached

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-demo/pom.xml, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/entity/Ticket.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClientSideFilterIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/dataview/ComboBoxDataView.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/dataview/ComboBoxLazyDataView.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/dataview/ComboBoxListDataView.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxLazyDataViewTest.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxListDataViewTest.java
Web-component: vaadin-combo-box
The combo-box client filter now does not affect the items handling API of in-memory data view, i.e. the item count change event is not triggered and 'getItems' does not use the client filter.
Fixes https://github.com/vaadin/vaadin-flow-components/issues/210
=> fix: Not to fire an item count change event on client filter change

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
This fixes
````
ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
...flow-frontend/comboBoxConnector.js
24:37  error    'Vaadin' is not defined                no-undef
```
=> fix: add missing window prefix in the comboBoxConnector

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Cherry-pick: #241
Web-component: grid
Fixes: vaadin/vaadin-grid#1809
Details: Flow Grid's connector overrides the ensureSubCacheForScaledIndex function, and adds a debouncer for the logic, the data request gets made asynchronously when expanding the Grids item. If the request for recalculateColumnWithds is done on expand listener, the width calculation might occasionally happen before the node gets expanded on the client-side, thus resulting into columns with undesired widths.
=> fix: override isLoading to return proper value (#241)

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/frontend/src/detach-reattach.js, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/pom.xml, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/DetachReattachPage.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/DetachReattachTemplate.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/DetachReattachIT.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
Cherry-pick: #275
Web-component: radio-button
Fixes: https://github.com/vaadin/vaadin-radio-button/issues/166
Details: RBG automatically adds RadioButtons inside of itself. If the RBG's value gets changed (setValue) while the component isn't in the DOM, the internal RB's remain unchanged. And once they're added back to DOM, Flow synchronizes the old RB values which causes the RBG to revert back to the old value. In order to fix it buttons will be reset on detach.
* Override setValue
* Add test for attach-detach
=> fix: override setValue to set proper value when detached (#275)

vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/dataview/CheckboxGroupDataView.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/dataview/CheckboxGroupListDataView.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupTest.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/data/SelectDataView.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/data/SelectListDataView.java, vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java
If applied, it will fix the KeyMapper mappings were not being refreshed after setting the IdentifierProvider through data-view API in CheckboxGroup and Select. 
Fixes: #308
=> fix: Refresh KeyMapper on IdentifierProvider change

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDataViewPage.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDataViewPageIT.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/dataview/RadioButtonGroupDataView.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/dataview/RadioButtonGroupListDataView.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/CustomItem.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java
Take `IdentifierProvider` into use use for determining the equality of the items in `vaadin-radio-button-flow`.
Fix: #273
=> feat: Use IdentifierProvider for equality in radio-button-group

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
If applied, this update will enable users to obtain a fully functional `ComboBoxListDataView` by passing ItemFilter and an array of Items to the corresponding `setItem` method to be able to add/remove items through DataView API and not to encounter an `UnsupportedOperationException`. 
Fixes: #322
=> fix: Refactor usages of Arrays.asList to create ListDataView in ComboBox

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/dataview/ComboBoxDataView.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/dataview/ComboBoxLazyDataView.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/dataview/ComboBoxListDataView.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/dataview/ItemFetchHelper.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxDataViewTest.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxDataViewTestHelper.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxLazyDataViewTest.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxListDataViewTest.java
ComboBox's data views getItem() and getItems() methods implementations modified in a way to be not affected by client-side filter.
Fixes: https://github.com/vaadin/vaadin-flow-components/issues/282
=> fix: Ignore ComboBox client-side filter in data view items getters

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
Web-component: combo-box
Fixes: https://github.com/vaadin/vaadin-combo-box/issues/965
Details: with the update of 5.4.4 wc overlay is closed when there is no items filter, so `customItemFilter` test should be updated as well.
=> fix: update combo-box integration tests

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridDetachAttachPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridDetachAttachIT.java
Added Integration Tests to verify that `TreeGrid` keeps the expanded nodes state after being reattached or after the page is refreshed with a view annotated with `@PreserveOnRefresh`. These ITs added as complement to the changes made in https://github.com/vaadin/flow/pull/9275 .
Related-to: https://github.com/vaadin/flow/issues/9175
=> test: add ITs to verify reattach - refresh page should keep expansion

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
Web-component: combo-box
Fixes: https://github.com/vaadin/vaadin-combo-box/issues/965
Details: with the update of 5.4.4 wc overlay is closed when there is no items filter, so `customItemFilter` test should be updated as well.
=> fix: update combo-box integration tests (#365)

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridAllowNestedNullsPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridAllowNestedNullsIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
New API, setNestedNullBehavior, controls whether an exception is thrown or not when facing nested null values.
Related-to: https://github.com/vaadin/flow/issues/8891
Web-component: vaadin-grid
=> feat: add API to control nested properties null behavior (#217)

scripts/updateJavaPOMs.js, vaadin-charts-flow-parent/vaadin-charts-flow-demo/pom.xml
The maven-bundle-plugin is not needed in neither this module nor in its original project
having the plugin there cause the snapshot/release deployment failed with errors in the manifest file
=> Chore: Update the generated charts/demo pom

scripts/updateNpmVer.js, vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupListDataViewPage.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupListDataViewIT.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/dataview/CheckboxGroupListDataView.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComboBoxListDataViewPage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxListDataViewIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/dataview/ComboBoxListDataView.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxDataViewTest.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxDataViewTestHelper.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxListDataViewTest.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridListDataViewPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridListDataViewIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridListDataView.java, vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/listbox/test/ListBoxDataViewPage.java, vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxDataViewIT.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/ListBoxBase.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/dataview/ListBoxListDataView.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDataViewPage.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDataViewPageIT.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/dataview/RadioButtonGroupListDataView.java, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/main/java/com/vaadin/flow/component/select/examples/SelectListDataViewPage.java, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/SelectListDataViewIT.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/data/SelectListDataView.java
In-memory filtering and sorting are now stored directly in component, which gives an opportunity to change it through the data view API for a certain component separately from other components bound to the same data provider.
Fixes: https://github.com/vaadin/flow/issues/8655
=> fix: Store in-memory filtering and sorting in component

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComboBoxLazyDataViewPage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComboBoxListDataViewPage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/FilteringPage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxLazyDataViewIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxListDataViewIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/FilteringIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxLazyDataViewTest.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxListDataViewTest.java
Since the DataCommunicator erases the combo box non-empty filter after each request, the filter needs to be set again to DataCommunicator even if it's the same as last sent.
Fixes: https://github.com/vaadin/vaadin-flow-components/issues/388
=> fix: clear ComboBox filter on drop down close

vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/it/FileBufferView.java, vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/AbstractUploadIT.java, vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/FileBufferIT.java, vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/AbstractFileBuffer.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/FileBuffer.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/FileData.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/MultiFileBuffer.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/UploadOutputStream.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/FileBufferTest.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/MultiFileBufferTest.java
* Fix: FileBuffer getInputStream is closed
Note: This version does not create new public APIs
=> CP 18.0: FileBuffer getInputStream is closed (#405)

vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/it/FileBufferView.java, vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/AbstractUploadIT.java, vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/FileBufferIT.java, vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/AbstractFileBuffer.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/FileBuffer.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/FileData.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/MultiFileBuffer.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/UploadOutputStream.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/FileBufferTest.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/MultiFileBufferTest.java
* Fix: FileBuffer getInputStream is closed
Note: This version does not create new public APIs
=> CP 17.0: FileBuffer getInputStream is closed (#405)

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/dataview/ItemCountUnknownGridIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Web-component: grid
Details: Initially test was relying on not working `scrollToIndex` when cache is loading. The request to [scroll](https://github.com/vaadin/vaadin-grid/blob/3253c90bdb438980a9c1eb3d557d4cfb8b1663c4/src/vaadin-grid-scroller.js#L124) to the first visible (adjusted) index on `_effectiveSizeChanged` when [switching to defined size](https://github.com/vaadin/vaadin-flow-components/blob/36981ab480d6e41cfd770f8768eaad2be048c375/vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/dataview/ItemCountUnknownGridIT.java#L75) was done, but never properly performed before the [change released](https://github.com/vaadin/vaadin-grid/commit/a34fc19d1810dcdd3608cdc9dc5075e7e9979ce4) in wc 5.7.7 with `__scrollToPendingIndex`
=> test: update grid integration test

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/dataview/ItemCountUnknownGridIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Details: It is a **cherry-pick.** Initially, the Grid's ItemCountUnknownGridIT test was relying on not working `scrollToIndex` when cache is loading. The request to scroll to the first visible (adjusted) index on `_effectiveSizeChanged` was done, but never properly performed before the change released in Grid Web Component 5.7.7 with `__scrollToPendingIndex`.
=> test: update Grid's IT after scrolling improvements (#428)

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridMultiSelectionModel.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java
Selecting any row of the Grid with lazy loading and multi-select mode does not trigger the count callback to be invoked. Instead, it gets the item count from the cache for defined item count, and doesn't show the select all checkbox at all and skips checkbox state update for unknown item count.
Fixes: https://github.com/vaadin/vaadin-flow-components/issues/411
=> fix: not to call count callback for lazy Grid with multi-select

vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-demo/src/main/java/com/vaadin/flow/component/gridpro/vaadincom/GridProView.java, vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java, vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/test/java/com/vaadin/flow/component/gridpro/GridProTest.java
Add API to enable edit mode to Grid Pro with a single click on the cell.
Fix https://github.com/vaadin/vaadin-grid-pro/issues/73
=> feat: add EditOnClick API to enable edit on single click

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTest.java
Things should only throw when no items/callback has been set to the CB.
There is a possibility that the value is set but the backend doesn't have
this item available, but that is an edge case and something that should
not happen and should be possible to prevent by resetting the data and
thus a responsibility of the application developer.
Fixes #391
=> fix: Fix setting value to lazy loading ComboBox

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RequiredValidationPage.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RequiredValidationIT.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/FieldValidationUtil.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
- Disable client side validation
- Validation from Binder will happen upon Binder#validate() or if the field binding uses withValidator
fix vaadin/vaadin-radio-button#179
=> fix: disable client side validation (#461) (CP:18.0)

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RequiredValidationPage.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RequiredValidationIT.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/FieldValidationUtil.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
- Disable client side validation
- Validation from Binder will happen upon Binder#validate() or if the field binding uses withValidator
fix vaadin/vaadin-radio-button#179
=> fix: disable client side validation (#461) (CP:14.5)

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RequiredValidationPage.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RequiredValidationIT.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/FieldValidationUtil.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
- Disable client side validation
- Validation from Binder will happen upon Binder#validate() or if the field binding uses withValidator
fix vaadin/vaadin-radio-button#179
=> fix: disable client side validation (#461) (CP:14.4)

vaadin-crud-flow-parent/vaadin-crud-testbench/src/main/java/com/vaadin/flow/component/crud/testbench/CrudElement.java
Details: with the `_observer.flush` [update](https://github.com/vaadin/vaadin-flow-components/commit/8b5b88893fdf1954ee4eadf83c262d560a0415e6) to the grid's connector, caption#sizer is stamped before the rows in vaadin-crud. It has the first edit button, so we need to get `row + 1` crud-edit when selecting all of those in the crud.
=> fix: use the next row for getting crud-edit

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTestScrollingOver100kLinesIT.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
The fix https://github.com/vaadin/vaadin-flow-components/commit/8b5b88893fdf1954ee4eadf83c262d560a0415e6 seems to be causing regressions for untested use-cases:
- https://github.com/vaadin/vaadin-grid/issues/2112
- https://github.com/vaadin/vaadin-grid-pro/issues/155
Reverting the change. The test is ignored till the original issue is fixed. https://github.com/vaadin/vaadin-flow-components/issues/427 will be re-opened.
=> fix: revert ensure first page is loaded; ignore test till fixed

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridClearAfterDetachAndReattachPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridClearAfterDetachAndReattachIT.java
Verifies the fix on a Flow side for the case when the component with DataCommunicator is being detached-reattached and then being cleared.
Related-to: https://github.com/vaadin/vaadin-grid/issues/1837
=> test: Verify no errors after Grid detach and clear items

scripts/prepareDeploy.sh
for a commit like this https://github.com/vaadin/vaadin-flow-components/commit/ba9d55859b06c5d5dc920a6828819c299701bc40, the output of the `modules` contains the ` Related-to: https://github.com/vaadin/vaadin-grid-flow/pull/1014 which corrects Grid JavaDoc` part, which leads to a failure when updating the module versions.
=> Chore: fix the deploy script to filter keywords [skip ci]

vaadin-grid-flow-parent/vaadin-grid-flow/pom.xml, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/feature/feature.xml
Adds Karaf "feature" classifier for grid maven artifact.
The classifier can be used to install OSGi bundles with their dependencies into Karaf container.
Part of vaadin/platform#1826
=> feat: add feature classifier for Karaf Grid feature

vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/pom.xml, vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/src/main/java/com/vaadin/flow/component/messages/tests/MessageListPage.java, vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/src/test/java/com/vaadin/flow/component/messages/tests/MessageListIT.java, vaadin-messages-flow-parent/vaadin-messages-flow/src/main/java/com/vaadin/flow/component/messages/MessageList.java, vaadin-messages-flow-parent/vaadin-messages-flow/src/main/java/com/vaadin/flow/component/messages/MessageListItem.java, vaadin-messages-flow-parent/vaadin-messages-flow/src/test/java/com/vaadin/flow/component/messages/tests/MessageListTest.java, vaadin-messages-flow-parent/vaadin-messages-testbench/src/main/java/com/vaadin/flow/component/messages/testbench/MessageElement.java, vaadin-messages-flow-parent/vaadin-messages-testbench/src/main/java/com/vaadin/flow/component/messages/testbench/MessageListElement.java
Resolves https://github.com/vaadin/vaadin-messages/issues/10
Also adds TestBench APIs needed in ITs.
The testing is mostly done in integration tests, because of
the beforeClientResponse optimization that makes it hard to
test with unit tests (copied from AvatarGroup).
=> Add MessageList items API

.gitignore
When running the IT modules, this file `frontend/generated/vaadin.ts` appears, polluting the git status.
=> Ignore generated directory in IT modules

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridFilteringPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridFilteringIT.java
Adds a regression test to verify the case when the items are bound to Grid lazily with unknown items count and the filter is being applied to items in the middle of scrolling.
Related-to: https://github.com/vaadin/flow/issues/9988
=> test: lazy loading Grid shows items properly after filter apply

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/BeanGridPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/BeanGridIT.java, vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridElement.java
`grid.activeItem==tr._item` evaluates to `false` even when they refer to the same item if the grid that has an itemDetailsRenderer.
=> Testbench: On GridElement, use _itemEquals to compare with the activeItem instead of ==

scripts/prepareDeploy.sh
the older version doesn't take this into consideration: 
as the `tail -1` will take the wrong snapshot version.
```
<version>2.5.0.beta1</version>
<version>2.5-SNAPSHOT</version>
<version>2.5.osgi-SNAPSHOT</version>
<version>2.5.osgi-9186-SNAPSHOT</version>
<version>2.5.osgi-9269-SNAPSHOT</version>
<version>2.5.osgi-fixes-SNAPSHOT</version>
<version>2.5.osgi-httpclient-optional-SNAPSHOT</version>
<version>2.5.osgi-resource-provider-SNAPSHOT</version>
```
=> chore:fix version setting brings in wrong snapshot [skip-ci]

vaadin-flow-components-shared/pom.xml
This is a temporary solution that should be removed once flow has removed themes
=> chore: exclude transitive dependency of themes from flow demo helpers

pom.xml
Use a JDK11-compatible version of the maven-failsafe-plugin
Fixes #771
=> fix: build on JDK 11+

scripts/build.sh, scripts/prepareDeploy.sh
this fix the issue with validation build error `jq: error (at <stdin>:5): Cannot index string with string "xxxxx"`
https://teamcity.vaadin.com/viewLog.html?buildId=75771&buildTypeId=VaadinFlowComponents_PullRequestValidation&tab=buildLog&_focus=2413#_state=2398
=> chore: fix build script after repo renaming [skip ci]

vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValuePage.java, vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValueIT.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/ListBoxBase.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxUnitTest.java
The issue 93 is not occuring with ComboBox and I compared the logic of these two components. In ComboBox the value is cleared only when data provider is set first time, but not when attached. This PR makes the logic analogous to ComboBox.
Fixes: https://github.com/vaadin/vaadin-list-box/issues/93
=> fix: move clear from rebuild to correct places

vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValuePage.java, vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValueIT.java
On the page, there are two elements with id "button" and `findElement(By.id("button"))` is actually getting the wrong one, which causes the test to fail.
=> test: fix listBoxRetainValueWhenRemovedAndAdded test

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridCellFocusPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridCellFocusPageIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/CellFocusEvent.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
This PR should wait for v21 
This reverts commit fb0b80324c816950c360610a5a76f5f60202d27e.
feat: Flow integration for Grid's cell-focus event (#822)
Fixes: vaadin/vaadin-grid#1536
Extended grid connector to handle the client side cell-focus event, integrated the grid event context and added a CellFocusEvent class and respective listener to Grid.
=> Reapply "feat:Flow integration for Grid's cell-focus event (#822)"

.github/ISSUE_TEMPLATE/custom.md
Based on the [decision](https://docs.google.com/document/d/1Iy3tu4YrNi_Qcn-P3G7sjo7VwjbT3d5doUMK5dYUI78) to use flow-components and web-components monorepos for the component issues, this repo is the right place for the issues with the Java API of Vaadin components.
=> chore: allow Flow API issues to be reported to this repo

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/RecalculateColumnWidthsPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/RecalculateColumnWidthsIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
The grid collects all data provider updates (`refreshItem`, `refreshAll`) and defers them into a single client side update that is injected in the `beforeClientResponse` hook, which I assume is done to improve performance. This can be a problem when scheduling other client side calls that expect the data update to have already happened (like `recalculateColumnWidths`) because this will actually run on the client-side before that data was changed. Consider this example:
```
grid.getDataProvider().refreshAll();
grid.recalculateColumnWidths();
```
which on the client will actually run `recalculateColumnWidths` before updating the grid data through the grid connector.
This change modifies the `recalculateColumnWidths` behavior to also defer scheduling the client-side call into the …
=> fix: synchronize column width recalculation with data refresh

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/BeanGridTest.java
This allows you to use a typed Grid instance together with a template as e.g.
```
@Id
private Grid<Person> grid;
...
grid.setBeanType(Person.class, true);
```
Without this, the properties based `addColumn` methods of Grid cannot be used, not can columns be added automatically from the bean
=> feat: allow setting the bean type after the Grid has been created

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/PreserveOnRefreshPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/PreserveOnRefreshIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
If Editor is not closed on detach and preserve on refresh is used, the ghost editor will cause an exception.
fixes: https://github.com/vaadin/vaadin-grid/issues/2176
=> fix: Ensure editor closing when page refreshed while using PreserveOnRefresh

vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValuePage.java, vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValueIT.java
On the page, there are two elements with id "button" and
`findElement(By.id("button"))` is actually getting the wrong one, which
causes the test to fail.
=> test: fix listBoxRetainValueWhenRemovedAndAdded test (#814)

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/SortingPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Column reordering messes sort indicators, this should be the fix, testing for regressions, do not merge
fixes: https://github.com/vaadin/vaadin-grid/issues/2175
=> fix: restore sorting indicators after column order change

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/pom.xml, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/RemoveSortableColumnPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/RemoveSortableColumnsIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Fixes: https://github.com/vaadin/vaadin-grid/issues/1969 
Warranty: Fixes exception related to sorting when recreating columns
cherry-pick: #468
cherry-pick: #918
=> fix: Prevent IllegalArgumentException when sortable columns are removed and recreated(#468)(#918) (CP 19.0) 

vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/Configuration.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/test/java/com/vaadin/flow/component/charts/ConfigurationJSONSerializationTest.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/test/java/com/vaadin/flow/component/charts/ConfigurationTest.java
Because `setSeries(...series)` uses `Arrays.asList` to convert from array to `List`, one cannot call `addSeries` after calling `setSeries(...series)` since it throws a `UnsupportedOperationException`.
Fix vaadin/vaadin-charts#515
=> fix: change how setSeries converts array to ArrayList

vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/Configuration.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/test/java/com/vaadin/flow/component/charts/ConfigurationTest.java
Because setSeries(...series) uses Arrays.asList to convert from array to List, one cannot call addSeries after calling setSeries(...series) since it throws a UnsupportedOperationException.
Fix vaadin/vaadin-charts#515
Co-authored-by: Knoobie <Knoobie@gmx.de>
=> fix: change how setSeries converts array to ArrayList (#927) (#950)

vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/pom.xml, vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/pom.xml, vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/it/NonImmediateUploadView.java, vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/NonImmediateUploadIT.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
Fixes: vaadin/vaadin-upload#358
=> Fix: Prevent NPE with autoUpload=false and multiple files are being uploaded

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/pom-bower-mode.xml, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/pom.xml, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/RemoveSortableColumnPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/RemoveSortableColumnsIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
fix: Prevent IllegalArgumentException when sortable columns are removed and recreated(#468)(#918)
Fixes: https://github.com/vaadin/vaadin-grid/issues/1969
Warranty: Fixes exception related to sorting when recreating columns
chore: fix duplicate element id in RemoveSortableColumnsIT (#918)
=> CP: Prevent IllegalArgumentException (#468)(#918) (CP 14.5)

vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/Configuration.java
Add a paragraph to `Configuration#setSeries(List)` javadoc to clarrify that `Chart#drawChart(boolean)` needs to be called in case of the instance of `Chart` is already rendered on the client.
Fixes #vaadin/vaadin-charts#570
=> docs: clarify use of setSeries for rendered chart

pom.xml
fixes #957
should also be added to v20
Alternatives:
- package-info.java with `@org.osgi.annotation.bundle.Export` Annotation in every bundle that should be exported.
=> chore: fix package-name calculation by removing extra quotes

pom.xml
Fixes two issues when building platform OSGi smoke tests
```
⇒ osgi.wiring.package: (osgi.wiring.package=com.vaadin.flow.component.icon)
⇒ osgi.wiring.package: (osgi.wiring.package=com.vaadin.flow.component.treegrid)
```
First problem is because module name is `icons` and namespace `icon` 
Second is because `vaadin-grid` has an additional component `treegrid` which does not share namespace with grid
ping @stbischof
=> chore: fix icon and treegrid namespaces for OSGi bundle

vaadin-select-flow-parent/vaadin-select-flow-integration-tests/pom.xml, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/main/java/com/vaadin/flow/component/select/examples/OverrideClientValidationPage.java, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/BasicFeaturesIT.java, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/OverrideClientValidationIT.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/FieldValidationUtil.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java
The original issue occurs because the select web component triggers its own client-side validation in several places (specifically to the issue, when the dropdown is closed), which then overwrites the validation state set by the server. Investigating this also lead to another issue that changing the validation state on the client through JS / dev tools also changed the validation state on the server, which should not be allowed.
This change fixes that by:
- overwriting the client-side validation method with a no-op, as is done for other field components
- disabling synchronization of the client side validation state to the server
- semi-related change: fixes the initial value of the client side component to be an empty string instead of the string `null` which initially lead the client …
=> fix: disable client side validation

vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/src/main/java/com/vaadin/flow/component/messages/tests/MessageListPage.java, vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/src/test/java/com/vaadin/flow/component/messages/tests/MessageListIT.java, vaadin-messages-flow-parent/vaadin-messages-flow/src/main/java/com/vaadin/flow/component/messages/MessageListItem.java, vaadin-messages-flow-parent/vaadin-messages-flow/src/test/java/com/vaadin/flow/component/messages/tests/MessageListTest.java, vaadin-messages-flow-parent/vaadin-messages-testbench/src/main/java/com/vaadin/flow/component/messages/testbench/MessageElement.java
**NOTE**: This depends on https://github.com/vaadin/flow-components/pull/978 and won't pass in CI before that is merged.
Feature: add and remove `theme` attribute values to messages in a `MessageList`. Only with strings at this point, since no theme variants have been implemented so far. The API is copied from `HasTheme` interface, which can be directly implemented only by component classes.
This enables developers to apply custom theming per each message in a MessageList.
Related issue: https://github.com/vaadin/collaboration-engine/issues/30
=> feat: add theme API to MessageListItem

vaadin-select-flow-parent/vaadin-select-flow-integration-tests/pom-bower-mode.xml, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/pom.xml, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/main/java/com/vaadin/flow/component/select/examples/OverrideClientValidationPage.java, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/BasicFeaturesIT.java, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/OverrideClientValidationIT.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/FieldValidationUtil.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java
Fixes: vaadin/vaadin-select#265
Warranty: Fixes client-side select overriding validation state from server
Co-authored-by: Tulio Garcia <28783969+tulioag@users.noreply.github.com>
Co-authored-by: Tulio Garcia <28783969+tulioag@users.noreply.github.com>
(cherry picked from commit 14676def81188ec9a674bfe202ebac8d71b65067)
=> fix: disable client side validation (#973) (CP 14.6)

vaadin-select-flow-parent/vaadin-select-flow-integration-tests/pom-bower-mode.xml, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/pom.xml, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/main/java/com/vaadin/flow/component/select/examples/OverrideClientValidationPage.java, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/BasicFeaturesIT.java, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/OverrideClientValidationIT.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/FieldValidationUtil.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java
Fixes: vaadin/vaadin-select#265
Warranty: Fixes client-side select overriding validation state from server
Co-authored-by: Tulio Garcia <28783969+tulioag@users.noreply.github.com>
Co-authored-by: Tulio Garcia <28783969+tulioag@users.noreply.github.com>
(cherry picked from commit 14676def81188ec9a674bfe202ebac8d71b65067)
=> fix: disable client side validation (#973) (CP 14.7)

vaadin-select-flow-parent/vaadin-select-flow-integration-tests/pom.xml, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/main/java/com/vaadin/flow/component/select/examples/OverrideClientValidationPage.java, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/BasicFeaturesIT.java, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/OverrideClientValidationIT.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/FieldValidationUtil.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java
Fixes: vaadin/vaadin-select#265
Warranty: Fixes client-side select overriding validation state from server
Co-authored-by: Tulio Garcia <28783969+tulioag@users.noreply.github.com>
Co-authored-by: Tulio Garcia <28783969+tulioag@users.noreply.github.com>
(cherry picked from commit 14676def81188ec9a674bfe202ebac8d71b65067)
=> fix: disable client side validation (#973) (CP 19.0)

vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java
The `ID` attribute should not be used for tests, it was removed by https://github.com/vaadin/web-components/commit/5f3feb456a908b42519b97fb967798bef830e6ce
=> test: check notification cards by tag name

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerI18nPage.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/TestI18N.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerI18nIT.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, vaadin-date-picker-flow-parent/vaadin-date-picker-testbench/pom.xml, vaadin-date-picker-flow-parent/vaadin-date-picker-testbench/src/main/java/com/vaadin/flow/component/datepicker/testbench/DatePickerElement.java
Fixes: #1411
Warranty: Fixes date picker overlay not refreshing after changing I18N settings
* fix: update date picker overlay after setting I18N settings
* Extract date picker element helpers into TestBench element
* Add test for partial i18n configs
* Fix SonarQube issues
* Simplify shadow DOM interactions with test bench queries
(cherry picked from commit ec6054541b6fe1df6d40b044dc89059a9d3edbb2)
=> fix: update date picker overlay(#1742) (CP: 14.6)

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerI18nPage.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/TestI18N.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerI18nIT.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, vaadin-date-picker-flow-parent/vaadin-date-picker-testbench/pom.xml, vaadin-date-picker-flow-parent/vaadin-date-picker-testbench/src/main/java/com/vaadin/flow/component/datepicker/testbench/DatePickerElement.java
Fixes #1411
Warranty: Fixes date picker overlay not refreshing after changing I18N settings
* fix: update date picker overlay after setting I18N settings
* Extract date picker element helpers into TestBench element
* Add test for partial i18n configs
* Fix SonarQube issues
* Simplify shadow DOM interactions with test bench queries
(cherry picked from commit ec6054541b6fe1df6d40b044dc89059a9d3edbb2)
=> fix: update date picker overlay (#1742) (CP: 19.0)

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerI18nPage.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/TestI18N.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerI18nIT.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, vaadin-date-picker-flow-parent/vaadin-date-picker-testbench/pom.xml, vaadin-date-picker-flow-parent/vaadin-date-picker-testbench/src/main/java/com/vaadin/flow/component/datepicker/testbench/DatePickerElement.java
Fixes: #1411
Warranty: Fixes date picker overlay not refreshing after changing I18N settings
* fix: update date picker overlay after setting I18N settings
* Extract date picker element helpers into TestBench element
* Add test for partial i18n configs
* Fix SonarQube issues
* Simplify shadow DOM interactions with test bench queries
(cherry picked from commit ec6054541b6fe1df6d40b044dc89059a9d3edbb2)
=> fix: update date picker overlay (#1742) (CP: 14.7)

vaadin-iron-list-flow-parent/vaadin-iron-list-flow/src/main/java/com/vaadin/flow/component/ironlist/IronList.java
This PR deprecates `IronList` component and adds a recommendation to use `VirtualList` instead
Closes #854
=> chore: deprecate IronList in favor of VirtualList

vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/IronIcon.java
This PR deprecates IronIcon component and adds a recommendation to use Icon instead
Closes #884
=> chore: deprecate IronIcon in favor of Icon

vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/src/main/java/com/vaadin/flow/component/charts/export/ExportOptions.java, vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/src/main/java/com/vaadin/flow/component/charts/export/SVGGenerator.java
* docs: add mention of CSS styling not supported 
* docs: mention of the need to close the generator in its constructor 
* docs: reference the overload of the default generate() method in its docs
* docs: rename timeline variable in its mention in the ExportOptions class' javadoc
=> docs: improve SVGGenerator javadocs with DX test findings

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridCellFocusPageIT.java, vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridTHTDElement.java
Currently [platform tests](https://teamcity.vaadin.com/viewLog.html?buildId=82090&buildTypeId=VaadinPlatform_VaadinPlatformPrValidation&tab=buildResultsDiv) are failing due to the custom cell click implementation introduced in #1770.
This change removes the custom cell click implementation and instead uses an existing overload of `TestBenchElement.click`, which also uses Selenium API to trigger a native click.
=> chore: remove broken cell click implementation

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java, vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/ColumnGroup.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridColumnGroupTest.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridColumnTest.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTest.java, vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java, vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationTest.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java, vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java, vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/java/com/vaadin/flow/component/virtuallist/VirtualList.java, vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListTest.java
Adds the `suppress-template-warning` attribute for the Flow components in order to suppress the template warning that the template renderer shows when `<template>` is used with a component (https://github.com/vaadin/web-components/pull/2103).
_* Grid Pro doesn't require any specific changes since it extends Grid and we've suppressed the warning for Grid._
Closes #1746
=> feat: suppress template warning

vaadin-grid-flow-parent/vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ColumnResizeEventPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridSingleSelectionPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridView.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/RecalculateColumnWidthsPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridInitialExpandPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTest.java
Fixes: #1009
related: [web-components PR 2099](https://github.com/vaadin/web-components/pull/2099)
=> feat: deprecate setHeightByRows in favor of setAllRowsVisible in Grid

vaadin-icons-flow-parent/vaadin-icons-flow-integration-tests/src/test/java/com/vaadin/flow/component/icon/tests/IconIT.java, vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/Icon.java
Related to https://github.com/vaadin/web-components/issues/2108
This is no longer required since the deprecated icons were restored to the iconset in https://github.com/vaadin/web-components/pull/2111
=> chore: remove normalization of deprecated icons

vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListIT.java, vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/java/com/vaadin/flow/component/virtuallist/VirtualList.java
While building `VirtualList` on top of a copy of `IronList` an extra `<span>` wrapper inside the item template should've been removed but wasn't. This PR removes the unnecessary wrapper element.
Before:
After:
=> perf: remove the unnecessary span wrapper from virtual list items

vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/Chart.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java, vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java
`render()` and `update()` methods are deprecated for the Web Components so that means we don't want to use them in the Flow repository anymore.
- Replaces `render()` with `requestUpdateContent()`
- Replaces `update()` with `updateConfiguration()`
Closes https://github.com/vaadin/web-components/issues/73
=> refactor: use new methods instead of deprecated render() and update()

README.md, scripts/run.sh, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/benchmark/run-benchmark.js
Fixes the issue with the server starting up but client resources not getting processed when running with Jetty.
Demos:
IT page:
Fixed as suggested [here](https://github.com/vaadin/flow/issues/11371#issuecomment-872774648)
=> fix: run package before jetty:run

scripts/updateJavaPOMs.js
Script was removing `vaadin-charts-flow-svg-generator`
=> chore: fix pom updater so as it does not removes custom modules [skip ci]

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/dataview/ComboBoxLazyDataViewTest.java
It's not OK to expect the Unix line separator (`\n`) when running the test on Windows that uses (`\r\n`).
=> chore: make `ComboBoxLazyDataViewTest` platform-independent

vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/main/java/com/vaadin/flow/component/crud/examples/MainView.java, vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/BasicUseIT.java, vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java
When creating a Crud using the following constructor and using the `setGrid()` method: 
```java
crud = new Crud<>(
Person.class,
createEditor()
);
crud.setGrid(createGrid());
```
Two grids would show, instead of just one. The problem is that the first grid is added by default when the constructor runs but it is **not** removed when the `setGrid()` method is called. The crud fails to remove the grid because of an equality check (using the equality operator `==`) instead of the `equals()` method, when checking if the Grid's parent is the Crud itself.
Fixes #1005
=> fix: avoid adding a second grid to a crud when using a constructor without the grid argument

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
The `scrollToIndex(int)` method in `TreeGrid` is directly inherited from `Grid` but has some issues. The grid needs to know the entire tree structure to accurately calculate a node's index (in a pre-order traversal method). Since it uses lazy loading for performance reasons, there is no reliable way to consistently scroll to a node's position.
Let's document this behavior in the `TreeGrid` class version of the method and discourage the use of it until we find a proper solution.
Related: #1016, https://github.com/vaadin/web-components/issues/2228
=> docs: add warning about unreliable behaviour of scrollToIndex(int) in TreeGrid

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/SortingPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Add integration tests for sort column header change
Fixes: #1839
Co-authored-by: Sascha Ißbrücker <sascha.issbruecker@googlemail.com>
=> fix: Update client side sort indicators after header is updated (#1841)

pom.xml
Use a JDK11-compatible version of the maven-failsafe-plugin
Fixes #771
Co-authored-by: Zhe Sun <31067185+ZheSun88@users.noreply.github.com>
=> fix: build on JDK 11+ (#772)

vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/demo/examples/dynamic/DynamicExtremes.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicExtremesIT.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/ProxyChangeForwarder.java
Axis#setExtremes can be called with null params to reset to previous configuration.
Fixes #1915
Axis#setExtremes can be called with null params to reset to previous configuration and shouldn't throw NPE
=> Fix: make axisRescaled null safe

scripts/build.sh
if the `image` has not given, by default, we use the latest for the `selenium/standalone-chrome`, otherwise, the provided version will be used.  
fixes #1960
=> chore: allow passing selenium image version from cmd

vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/examples/dynamic/DynamicExtremes.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicExtremesIT.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/ProxyChangeForwarder.java
Axis#setExtremes can be called with null params to reset to previous configuration.
Fixes #1915
=> Fix: make axisRescaled null safe (#1938)

scripts/generateChangeLog.js
Group the WC update commit into one category to shorten the release note.
=> chore: update release note script [skip ci]

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/pom.xml, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java, vaadin-flow-components-shared/src/main/java/com/vaadin/tests/DataProviderListenersTest.java, vaadin-grid-flow-parent/vaadin-grid-flow/pom.xml, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTest.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/pom.xml, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/ListBoxBase.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxUnitTest.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/pom.xml, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java
This change is a fix for ComboBox and related to the fix made on the flow side to get rid of memory leaks caused by old listeners being hanging in the list - https://github.com/vaadin/flow/pull/11471.
Null-value checking of `dataProviderListener` is not needed in attach handler because:
1. Calling to a `remove()` is more robust and this is a normal way of handling listeners registrations in flow. Additionally, if, for some reason, a new data provider will be set up to the component, it's more correct to remove the old listener sitting in the old data provider.
2. Not calling of `remove()` method gives an inconsistency with the flow, which now (with the above fix) removes the listener on attach event.
The inconsistency described in 2. causes the ComboBox's and DataCommunicator data …
=> fix: Remove old data provider listener on component attach

vaadin-renderer-flow-parent/pom.xml, vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/pom.xml, vaadin-renderer-flow-parent/vaadin-renderer-flow/pom.xml
I just run `./scripts/updateJavaPOMs.sh` so as all pom files are regenerated and formatted.
=> chore: regenerate pom files in renderer module to align with other modules

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/pom.xml, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java, vaadin-flow-components-shared/src/main/java/com/vaadin/tests/DataProviderListenersTest.java, vaadin-grid-flow-parent/vaadin-grid-flow/pom.xml, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTest.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/pom.xml, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/ListBoxBase.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxUnitTest.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/pom.xml, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java
Removes the old data provider listener and adds a new one upon setting up a data provider and attaching a component to the page.
Reorders and makes the 'rebuild' method for ListBox not to being called in attach handler method, because it leads to loosing the data in cache.
Follows up the memory leak issue in Flow (vaadin/flow#11471) and fixes the regression in components caused by the change in Flow.
Related-to https://github.com/vaadin/flow-components/issues/1914.
(cherry picked from commit d47cce44b3476e8ff778bc37f4c734ea4df5a8dc)
=> fix: Remove old data provider listener on component attach (CP: 21.0)

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/TemplateRenderer.java
This PR deprecates `TemplateRenderer` component and adds a recommendation to use `LitRenderer` instead
Closes #857
=> chore: deprecate TemplateRenderer in favour of LitRenderer

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/pom.xml, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java, vaadin-flow-components-shared/src/main/java/com/vaadin/tests/DataProviderListenersTest.java, vaadin-grid-flow-parent/vaadin-grid-flow/pom.xml, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTest.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/pom.xml, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/ListBoxBase.java, vaadin-list-box-flow-parent/vaadin-list-box-flow/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxUnitTest.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/pom.xml, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java
Removes the old data provider listener and adds a new one upon setting up a data provider and attaching a component to the page.
Reorders and makes the 'rebuild' method for ListBox not to being called in attach handler method, because it leads to loosing the data in cache.
Follows up the memory leak issue in Flow (vaadin/flow#11471) and fixes the regression in components caused by the change in Flow.
Related-to https://github.com/vaadin/flow-components/issues/1914.
(cherry picked from commit d47cce44b3476e8ff778bc37f4c734ea4df5a8dc)
=> fix: Remove old data provider listener on component attach (CP: 20.0)

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js
Removes a workaround for a Chrome issue that has already been fixed.
The original PR that added the workaround: https://github.com/vaadin/flow/pull/5060
According to https://github.com/vaadin/flow/issues/5025#issuecomment-462668991, the issue was already fixed in Canary over 2 years ago
=> chore: remove an outdated Chrome bug workaround

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js
`flow-component-renderer.js` uses `dom-if` so it needs to import it. Without the import, the `<dom-if>` doesn't upgrade and ComponentRenderer renders empty content.
=> fix: make flow-component-renderer import dom-if

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/test/java/com/vaadin/flow/data/renderer/LitRendererTest.java
The `LitRenderer().withFunction(name, function)`'s function name gets evaluated as such in the JS renderer function passed to the component. For safety reasons, it's better to only allow alphanumeric characters in the function name.
=> fix: only allow alphanumeric function names with LitRenderer

vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/main/java/com/vaadin/flow/data/renderer/tests/LitRendererPage.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java
The previous logic had an issue where the `LitRenderer`'s properties/`valueProviders` were iterated only once (in `createDataGenerator()`) when the renderer got assigned to a component.
This basically made the `LitRenderer` ignore any `valueProviders` that got defined after the renderer was assigned:
```java
LitRenderer<String> renderer = LitRenderer.<String> of("<div>${item.value}</div>");
component.setRenderer(renderer);
renderer.withProperty("value", item -> item + " (details)"); // This would have no effect
```
After this change, the `valueProviders` are read dynamically whenever the data generator is invoked.
=> fix: read valueProviders dynamically in LitRenderer's data generator

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/main/java/com/vaadin/flow/data/renderer/tests/LitRendererTestComponent.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/Rendering.java, vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/java/com/vaadin/flow/component/virtuallist/VirtualList.java
LitRenderer currently has a dedicated rendering context called `LitRendering`. It only adds one method on top of the ones inherited from `Rendering`. The new one, `getRegistration()` returns a `Registration` instance which can be used to clean up after the renderer is no longer required. _In LitRenderer's case, it cleans up the `renderer` function from the element and the attach listener which adds it_.
Once we modify `ComponentRenderer` to also use `renderer` function instead of the `<template>` element, similar cleanup is most likely required, so it's better to have the API available for all Renderer types. _(In fact, removing the `<template>` element from the target component should already be handled by such cleanup registration instead of the component logic having to do the …
=> refactor: merge LitRendering to Rendering

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java
Change `LitRenderer` to use `<SOURCE>` instead of `<T>` to align with the other classes in the same package, including the superclass `Renderer`.
=> chore: align generic type name across renderers

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/Renderer.java
The primary purpose of this PR is to add a deprecated `withEventHandler` to the `LitRenderer` API to make the migrating experience from `TemplateRenderer` nicer:
However, `getEventHandlers()` in `LitRenderer` currently throws an `UnsupportedOperationException` and using `getFunctions()` is recommended instead. Since neither of the getters really serve any purpose in the public renderer APIs, decided to
1. remove `getFunctions()` completely
2. keep the deprecated `getEventHandlers()` (updated the deprecation message, still throws an exception)
=> chore: add deprecated withEventHandler to LitRenderer

vaadin-flow-components-shared/pom.xml
the LATEST version of Web Driver Manager requires higher version of JDK (instead of JDK8)
=> chore: use fixed web-driver-manager version

vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/button/tests/DetachReattachDisableOnClickButtonPage.java, vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/button/tests/DetachReattachDisableOnClickButtonIT.java, vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/Button.java
When enabling disabledOnClick, a javascript function is configured so the button gets immediately disabled (on client side) on click.
When detaching and re attaching the button, this JavaScript function is not working anymore, so then the button is disabled by doDisableOnClick(), but after a server side roundrip. 
So in this case if a click listener takes too long to be processed, the button will behave differently after detaching and reattaching again.
With the proposed change, the JavaScript function will be configured again by initDisableOnClick() method and button will be disable inmediately on click.
An IT is provided that will fail if the button is not immediately disabled on click after the detach-reattach cycle, but works fine with the fix.
Fixes #1401
=> fix: disable on click behavior after detach and reattach

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-demo/src/main/java/com/vaadin/flow/component/menubar/demo/MenuBarView.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarTestPage.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarPageIT.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
I18n for the menu bar was recently introduced to the web component, in order to customize the accessible aria-label of the overflow button. This adds a Java API for the same.
Depends on https://github.com/vaadin/web-components/pull/2384
Fixes #2043
=> feat: add menu bar i18n Java API

vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/main/java/com/vaadin/flow/component/crud/examples/MainView.java, vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/BasicUseIT.java, vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java, vaadin-crud-flow-parent/vaadin-crud-flow/src/test/java/com/vaadin/flow/component/crud/CrudTest.java
This PR adds Java API for letting developers to hide/show toolbar of crud component. it is done by setting an attribute on crud component and the toolbar is hide/shown by changing css display property.
Fixes vaadin/flow-components#1592
=> feat: add API for showing/hiding toolbar of crud

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerFormatPage.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerFormatIT.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/date-fns/.gitignore, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/date-fns/README.md, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/date-fns/index.js, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/date-fns/package-lock.json, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/date-fns/package.json, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/date-fns/rollup.config.js, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/pom.xml, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java
Cherry pick of #1975 
Marked as draft as this is supposed to target `14.8`, which is not available yet. Instead this PR temporarily targets `14.7` in order to have a PR for discussion and reviews.
Changes the original implementation to include a custom bundle of the date-fns library to allow back-porting the custom date format feature to Vaadin 14. The reason for the change is that the current mechanism of including the date-fns dependency though `@NpmPackage` is not compatible with Vaadin 14 compatibility mode.
General solution outline:
- adds a `date-fns` folder to the Flow date picker Maven module
- that folder contains a node.js / rollup build that bundles only the required date-fns function into a single JS file
- the rollup build is automatically executed during the …
=> feat: add support for custom formats to date picker (CP: 14.8)

vaadin-crud-flow-parent/vaadin-crud-flow-demo/src/main/java/com/vaadin/flow/component/crud/demo/CrudView.java, vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/main/java/com/vaadin/flow/component/crud/examples/MainView.java, vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/BasicUseIT.java, vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/EventHandlingIT.java, vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/TemplateSupportIT.java, vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java, vaadin-crud-flow-parent/vaadin-crud-flow/src/test/java/com/vaadin/flow/component/crud/CrudTest.java
Provide new item in `NewEvent`. Inside of event handler for `NewEvent`,  when we call `e.getItem()`, it used to return `null` value, which wasn't any useful. This PR modifies the event object of `NewEvent` to include an empty instance of type of the crud, so that end user can provide some default values to newly added objects via CRUD component.
Fixes https://github.com/vaadin/flow-components/issues/1105
=> feat: NewEvent provides a new item for setting pre-defined values.

vaadin-select-flow-parent/vaadin-select-testbench/src/main/java/com/vaadin/flow/component/select/testbench/SelectElement.java
=> chore: ensure the correct overlay is used when multiple selects are open

vaadin-select-flow-parent/vaadin-select-testbench/src/main/java/com/vaadin/flow/component/select/testbench/SelectElement.java
Uses textContent instead of getText so it does not fail if the popup is off screen
=> Trim the text before selecting to be more compatible with templates

vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/main/java/com/vaadin/flow/component/crud/examples/DetachAttachView.java, vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/DetachAttachIT.java, vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/EditorButtonsIT.java, vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java
Doesn't allow client to override save button disabled state when form is dirty
=> Override __isSaveBtnDisabled to preserve server side enabled state

README.md
Updates README.MD to point to the web components monorepo instead of individual web component repositories
=> chore: remove instructions to use individual component repos

vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuItemBase.java, vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuConnector.js, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-demo/src/main/java/com/vaadin/flow/component/menubar/demo/MenuBarView.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarTestPage.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarPageIT.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBarRootItem.java
This change enables theming individual menu bar items, for example to display one item as the primary item. As the menu bar uses the context menu to display submenus, most of the changes are in there.
Depends on https://github.com/vaadin/web-components/pull/2401
Part of vaadin/flow-components#880
=> feat: allow theming individual menu items

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/SortingPage.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Since [grid.notifyResize() is currently a no-op](https://github.com/vaadin/web-components/blob/2a05a00e6a92a247af8a4d845eed7d44b51973c4/packages/vaadin-grid/src/vaadin-grid.js#L993) all internal invocations to the function can be removed.
Removing the calls in `flow-components` enables us to add a deprecation warning message to the function in `<vaadin-grid>`
=> chore: remove grid.notifyResize() calls

vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePickerStepPage.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerStepIT.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
Fixes the DateTimePicker to apply steps if they were set before attaching the component. The issue is that the web component synchronizes the steps property from the TimePicker to the DateTimePicker, when using a slotted TimePicker. To solve this, I changed `setSteps` to additionally set the value on the TimePicker. I could not observe any issues with the solutions, it works when setting the steps before and after attaching the component.
Fixes #2164
=> fix: make DateTimePicker apply initial steps

vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/AbstractTBTest.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/BasicChartIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ChartSizeIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ChartStyleIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangesIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicExtremesIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/PieWithoutAccessibilityIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java, vaadin-flow-components-shared/src/main/java/com/vaadin/tests/AbstractParallelTest.java, vaadin-flow-components-shared/src/main/java/com/vaadin/tests/ComponentDemoTest.java
while at the current situation, `getRunOnHub`  returns a null, though we have set a `hubhostname`, it still returns **localhost** , while there is no local installed hub after the seleniod update, the test failed with 404 .
=> chore: correct the expression in test and fix chart tests

vaadin-flow-components-shared/src/main/java/com/vaadin/tests/AbstractParallelTest.java
This reverts commit 4ecff382
Reverted because the change had way too little gain and was
breaking binary compatibility with unknown amount of projects and add-ons.
Related-to https://github.com/vaadin/flow/pull/12207
=> Revert "chore: fix after flow new route feature (#2197)"

vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java
Fixes https://github.com/vaadin/flow-components/issues/1294
I didn't add any tests since there is no test for the other components.
=> feat: add HasSize to Details

PULL_REQUEST_TEMPLATE.md
The instruction template is marked as title and more often than not, it ends up not being deleted by contributors.
Making it into a comment so it won't show on the PR description, if it's not deleted.
=> chore: make template instruction into a comment

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridFilteringPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ItemClickListenerPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ItemClickListenerIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
This PR fixes the issue when a focusable element is used in header (prepended), and clicking on this element causes `item-click` event to be raised (with a pre condition that grid item's `key` values are changed by something like filtering and clearing the filter after a grid row is clicked). It fixes it by using `getEventContext` and do more checking in order not to fire click event.
It also removed usage of `$connector.activeItem` which was introduced as a workaround [before](https://github.com/vaadin/vaadin-grid-flow/commit/74b944acb2da62bc7fffe106a7d8e93f8173ba4f).
Fixes [#2247](https://github.com/vaadin/flow-components/issues/2247)
=> fix: don't raise item-click when focusable header is clicked after item keys are changed.

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-testbench/src/main/java/com/vaadin/flow/component/combobox/testbench/ComboBoxElement.java
Currently clearing the ComboBox using `ComboBox.clear()`, or using `ComboBox.setValue(null)`, does not clear the internal input element's value after entering a custom value. One cause here is that the [connector](https://github.com/vaadin/flow-components/blob/master/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js#L337) prevents propagating the value change event, probably because Flow uses item keys as values, and setting a custom value could interfere with that. That also means that the state of the value property is never updated on the server-side, which means setting the value to null/empty does not trigger a client-side update, since the values are the same.
To fix this I used a different property …
=> fix: clear input element value when clearing custom value in ComboBox

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ItemClickListenerPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ItemClickListenerIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector-es6.js, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
cherry-pick of https://github.com/vaadin/flow-components/pull/2334
Notable changes:
- The way that functions are imported is different, there are two places `gridConnector.js` and `gridConnector-es6.js`
- Because of recent changes in flow component, one particular test is failing, we needed to change scroll index from 1000 to 900 in order for it to pass.
=> fix: don't raise item-click when focusable header is clicked after item keys are changed. (#2327) (CP: 14.8) 

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ItemClickListenerPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ItemClickListenerIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
cherry-pick of this PR to version 21.0.
notable changes: change in imported names in `gridConnector.js`
=> fix: don't raise item-click when focusable header is clicked after item keys are changed. (#2327) (CP: 21.0)

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/pom.xml, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/pom.xml, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/pom.xml, vaadin-grid-flow-parent/vaadin-grid-flow/pom.xml, vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/pom.xml, vaadin-login-flow-parent/vaadin-login-flow/pom.xml, vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/pom.xml, vaadin-select-flow-parent/vaadin-select-flow/pom.xml, vaadin-text-field-flow-parent/vaadin-text-field-flow/pom.xml, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinEmailField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinNumberField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinPasswordField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextField.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/pom.xml
Bump version for vaadin-text-field in NpmPackage annotations and POM files to `2.9.0`
=> chore: bump NpmPackage and webjars version for vaadin-text-field

pom.xml
Fix the code formatter config to remove the invalid buildtools dependency, and load the config from Github instead. Based on the changes from: https://github.com/vaadin/flow/pull/12430
=> chore: fix formatter config

vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/SelectListDataViewIT.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/VaadinItem.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/resources/META-INF/resources/frontend/selectConnector.js, vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java, vaadin-select-flow-parent/vaadin-select-testbench/src/main/java/com/vaadin/flow/component/select/testbench/SelectElement.java
To align the Flow component to it's web-component counterpart with the changes introduced in https://github.com/vaadin/web-components/pull/2990, the `vaadin-select` component will now use `vaadin-select-list-box` and `vaadin-select-item` internally.
Fixes #2369
- Refactor
=> refactor: change internal components of vaadin-select to vaadin-select-list-box and vaadin-select-item

vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/DrilldownEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/HasItem.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointClickEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointLegendItemClickEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointMouseOutEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointMouseOverEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointRemoveEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointSelectEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointUnselectEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointUpdateEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/test/java/com/vaadin/flow/component/charts/HasItemTest.java
Context: Charts
Currently using `HasItem.getItem` (for example through `PointClickEvent.getItem`) with any series other than `DataSeries` results in a `ClassCastException`. The issue is that the method assumes that all series will be a `DataSeries`, and it can only return a `DataSeriesItem` as well. Additionally there are no obvious solutions for how to get the item from an event for other series, like `NodeSeries` or `ListSeries`.
As this is a common API we can not modify its signature or name to reflect that it only works with DataSeries. We also can not introduce major new APIs to handle other series types. Instead this change contains:
- throw a more appropriate `UnsupportedOperationException` with a relevant message that indicates that this method only works for `DataSeries`
- update …
=> fix: prevent HasItem.getItem throwing ClassCastException

vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/DrilldownEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/HasItem.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointClickEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointLegendItemClickEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointMouseOutEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointMouseOverEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointRemoveEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointSelectEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointUnselectEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/PointUpdateEvent.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/test/java/com/vaadin/flow/component/charts/HasItemTest.java
Cherry-pick of: #2390 
Fixes: #1040 
Changes:
- removed `HasItemTest.getItemWithNodeSeriesThrowsUnsupportedOperationException` - NodeSeries does not exist in 14
- updated JavaDoc for `HasItem.getItemId` - removed references to NodeSeries, updated example to use TreeSeries
(cherry picked from commit 5b6ba0608c1e728843c53f6331d0dee8b85508bd)
=> fix: prevent HasItem.getItem throwing ClassCastException (#2390) (CP: 14.8)

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocaleTest.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerLocaleTest.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/TimePickerDetachAttachPage.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerDetachAttachPageIT.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/pom.xml, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerLocaleTest.java
Extended version of #2380 that covers DatePicker, TimePicker and DateTimePicker. Also refactors the components to pull the locale on demand, rather than setting the custom locale fields to the UI locale on attach.
Opening this as a separate PR for now, in case we don't want to go ahead with the refactoring.
Fixes #2379
=> fix: fallback to super.getLocale() if no custom locale is set

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocaleTest.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerLocaleTest.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/TimePickerDetachAttachPage.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerDetachAttachPageIT.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/pom.xml, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerLocaleTest.java
Cherry-pick of: https://github.com/vaadin/flow-components/pull/2416
Fixes: https://github.com/vaadin/flow-components/issues/2379
Co-authored-by: Tatu Lund <tatu@vaadin.com>
(cherry picked from commit 1a2e3a8a9bc56a8a146505a13f38874626a01591)
=> fix: fallback to super.getLocale() if no custom locale is set (#2416) (CP: 14.8)

vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/AbstractTBTest.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/BasicChartIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ColumnWithLazyMultiLevelDrilldownCallbackTestsIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ColumnWithLazyMultiLevelDrilldownIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangesIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangingChartIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicExtremesIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/PieWithLegendEventsIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java, vaadin-charts-flow-parent/vaadin-charts-testbench/src/main/java/com/vaadin/flow/component/charts/testbench/ChartElement.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/EditorVerticalScrollingIT.java, vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridElement.java
Since the breaking changes in chrome driver 96, we need to replace the shadowroot usage
=> chore: fix shadowroot usage in component TB classes

vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/AbstractTBTest.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/BasicChartIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangesIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java, vaadin-charts-flow-parent/vaadin-charts-testbench/src/main/java/com/vaadin/flow/component/charts/testbench/ChartElement.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/EditorVerticalScrollingIT.java, vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridElement.java
* chore: fix shadowroot usage in component TB classes
charts and grid
=> chore: fix shadowroot usage in component TB classes (#2447) (CP:14.8)

vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/AbstractTBTest.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/BasicChartIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ColumnWithLazyMultiLevelDrilldownCallbackTestsIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ColumnWithLazyMultiLevelDrilldownIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangesIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangingChartIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java, vaadin-charts-flow-parent/vaadin-charts-testbench/src/main/java/com/vaadin/flow/component/charts/testbench/ChartElement.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/EditorVerticalScrollingIT.java, vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridElement.java
* chore: fix shadowroot usage in component TB classes
charts and grid
=> chore: fix shadowroot usage in component TB classes (#2447) (CP:21.0)

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridIT.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/contextmenu/DynamicContextMenuGridIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes the grid context menu to always provide the correct item information in the open event, as well as the dynamic content handler. Previously in both cases the item could be missing if the context click was not directly on the grid cell content element, but on the table cell element itself. The approach of using the `sourceEvent` to get the event context is taken from the Typescript example in the docs: https://vaadin.com/docs/latest/ds/components/grid/#context-menu
Fixes #2444
=> fix: make context menu clicks cover the whole cell

vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/themes/LumoLightTheme.java
This PR updates the color palette for Lumo Light Theme to the the new Lumo theme for charts introduced in https://github.com/vaadin/web-components/pull/3006.
=> fix: adapt color palette to new themes

scripts/build.sh
fixed the script, when there are changes in the root (e.g. pom.xml) and individual component modules
the build will run validation for the whole project
the current setting will run the validation on the individual component only.
=> chore: fix build script

vaadin-map-flow-parent/pom.xml, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/pom.xml, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/BackgroundLayerPage.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/MapView.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/BackgroundLayerIT.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/Map.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Constants.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/layer/Layer.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/layer/TileLayer.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/OSMSource.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/Source.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/TileImageSource.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/TileSource.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/UrlTileSource.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/VectorSource.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/XYZSource.java, vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/MapTest.java, vaadin-map-flow-parent/vaadin-map-testbench/pom.xml, vaadin-map-flow-parent/vaadin-map-testbench/src/main/java/com/vaadin/flow/component/map/testbench/MapElement.java
Finalizes the background layer and default OSM source features. This includes having a default background layer using an OSM source, being able to set a custom OSM URL, and being able to completely replace the default background layer.
Changes:
- Adds several OpenLayers classes that were missing from the layer and source class hierarchy
- Adds several properties / options to layers and sources that were easy to support
- Adds API docs for at least the classes that were relevant for the feature
- Adds integration test that verify that the map defaults, and configuration changes are synced correctly to OpenLayers
- Adds a testbench module and element class for the map, and some methods to support getting information from OpenLayers
Skipping CI because the required web component has no …
=> feat: finalize background layer

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridDetachAttachPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridDetachAttachIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes https://github.com/vaadin/web-components/issues/3292
The `gridConnector` patches certain functions from the `<vaadin-grid>`'s `ItemCache` type. The patched functions can reference the grid instance they're associated with using `this.grid`, and the related connector using `this.grid.$connector`. 
The patched `isLoading()` function was erroneously [referencing](https://github.com/vaadin/flow-components/blob/f94d5700368a850fee544392b78cd3150d8fb61d/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L40) the `ensureSubCacheQueue` array directly inside the connector, bypassing the related grid instance reference. Meaning that the `IsLoading()` check of each grid would use the `ensureSubCacheQueue` state of the first grid added on the …
=> fix: check sub cache queue of a grid instance in connector

vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/AbstractConfigurationObject.java, vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/AbstractConfigurationObjectTest.java
Adds a method to all configuration classes to allow updating them silently, without dispatching change events. This is useful for updating them based on client-side changes, where we don't want to send the changes back to the client again.
=> feat: allow silent configuration updates

vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/AbstractConfigurationObject.java
Fixes the thread local initialization for configuration classes. Updates running from a different thread than the one that initialized the thread local could end up with an initial value of false.
=> fix: notify flag thread local initial value

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridVirtualChildPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridVirtualChildIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes https://github.com/vaadin/flow-components/issues/2555
There were a couple of places in the connector where the `<vaadin-grid>` instance was assumed to have been fully finalized (access to `grid.$....`)
=> fix: handle unfinalized grid in the connector

vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/frontend/inject-checkbox.js, vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/InjectedCheckboxIT.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java
Currently, the custom `<label>` is always created even if there is one provided by the user via template.
This PR changes it to use `label` property instead, and only create `<label>` when using `.setLabelAsHtml()`.
Also, updated the IT for the checkbox in template to ensure the `label` attribute value is preserved.
Fixes #2551
- Bugfix
=> fix: only use custom label when setting HTML

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
The internal `_selectedKey` state is not maintained on the server so should be enough to clear it in the connector.
Fixes #2222
- Bugfix
=> fix: delete selected key when input is cleared

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/DisabledItemsPage.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/DisabledItemsPageIT.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
Turns out https://github.com/vaadin/flow-components/issues/2528 wasn't a regression after all, but also V22 suffers from it. Cherry-pick #2563 for V22
=> fix: enforce radio button web component disabled state (#2563)

vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupDisabledItemPage.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupDisabledItemIT.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
Fixes https://github.com/vaadin/flow-components/issues/2577
Same as https://github.com/vaadin/flow-components/pull/2563 but for CheckboxGroup
=> fix: enforce checkbox web component disabled state

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/frontend/benchmark.js, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridBenchmark.java
The `benchmark.js` file includes style registrations that are intended for `<vaadin-grid>` in benchmark tests. The styles aren't scoped so they currently leak to all Grid integration tests. This PR scopes the styles to only affect `<vaadin-grid benchmark>`
=> test: scope grid benchmark styles

vaadin-map-flow-parent/pom.xml, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/AttributionsPage.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/AttributionsIT.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/OSMSource.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/Source.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/XYZSource.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/synchronization/sources.js, vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/source/OSMSourceTest.java, vaadin-map-flow-parent/vaadin-map-testbench/src/main/java/com/vaadin/flow/component/map/testbench/MapElement.java
Adds support for configuring attributions.
- Keeping the default null value will display default attributions of the source (only applies to OSM source to my knowledge)
- Setting empty list clears attributions
- Setting list of attributions displays them in the attributions container
- Attributions collapsible flag is correctly applied
Fixes #2503
=> feat: configurable attributions

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDemoPage.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
Fixes https://github.com/vaadin/flow-components/issues/1681
I have updated the current test that is using a setRenderer(new TextRenderer()) since this is doing the same and setRenderer is already tested in the other tests with a Component renderer.
=> feat: add missing ItemLabelGenerator to the radiobuttongroup

vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/FeatureEventsPage.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/MapEventsPage.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/MapView.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/FeatureEventsIT.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/MapEventsIT.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/MapBase.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/events/MapFeatureClickEvent.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/mapConnector.js, vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/util.js, vaadin-map-flow-parent/vaadin-map-testbench/src/main/java/com/vaadin/flow/component/map/testbench/MapElement.java
Allows to get notified about clicks on features. The click events contain the clicked feature, as well as the layer and the source that contain the feature. Optionally a filter layer can be specified for the click listener, so that the listener is only triggered when features in a specific layer are clicked.
Also changes the OL event used for map clicks and feature clicks to `singleclick` in order to ignore double-clicks and drags.
Fixes #2513
=> feat: map feature click events

vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/RefreshOnValueChangePage.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/RefreshOnValueChangeIT.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RefreshOnValueChangePage.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RefreshOnValueChangeIT.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
A `CheckBoxGroup`/`RadioButtonGroup` with a value change listener that invokes `reset()` (via some public API) can result in excess radios/checkboxes getting created. This is due to the current order in which the old radios/checkboxes are removed and the component's value is cleared inside the `reset()` method.
The issue is fixed by having the discarded child components removed right before new ones are created/added (inside the same synchronized block).
Fixes #2525 
Note that checking a radio/checkbox in the IT page's group still ends up with the group having no value. This is because the group uses a value change listener that calls `dataView.refreshAll()` which in turn [clears the group's value](https://github.com/vaadin/vaadin-radio-button-flow/pull/53).
=> fix: discard radios/checkboxes right before adding new ones

pom.xml
Flow 23.0 (previously 10.0) is the version for V23 (master is 23.1)
=> chore: Update Flow snapshot version

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPageIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Updated to use `selected-item-changed` event for checking if `_selectedKey` is outdated.
Fixes #2615
- Bugfix
=> fix: clear selected key when item selected

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ComponentColumnWithHeightPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridDetailsRowPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ComponentColumnWithHeightIT.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridDetailsRowIT.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js
Fixes #2363
The `Virtualizer` (also used by `<vaadin-grid>`) [uses](https://github.com/vaadin/web-components/blob/87bbb0e333cd037c006c6cf279f574aa28cedd01/packages/component-base/src/virtualizer-iron-list-adapter.js#L34) a native `ResizeObserver` internally to detect and react to item height changes; in the case of `Grid`, it observes height changes on the body row (`<tr>`) elements. Typically it catches row height changes just fine and updates the row positions accordingly.
In this specific case, a `<flow-component-renderer>` on each row gets assigned a new element reference due to a dynamic data update, resulting in the [old element getting removed](https://github.com/vaadin/flow-components/blob/8dc595c13137613db970412956a38757272a7989/vaadin-renderer-flow-parent/vaadin-renderer-flow/src …
=> fix: avoid temporarily clearing the component renderer

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/pom.xml, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/PreMultiSortedPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/PreMultiSortedIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes https://github.com/vaadin/flow-components/issues/2069
This PR effectively backports the fix from https://github.com/vaadin/flow-components/pull/2392 with a valid test case obtained from https://github.com/vaadin/flow-components/issues/2069
Earlier, we [backported the test case only](https://github.com/vaadin/flow-components/pull/2395) because the [original issue only reproduced in V22](https://github.com/vaadin/flow-components/pull/2392#issuecomment-984370764).
=> fix: make grid connector request content update on missing data (CP2)

.gitignore, integration-tests/pom.xml
dependabot runs **all profiles** in the project, but this wont work with our own generated modules, for example, integration-tests.
so that this error can be seen from the build log ([under Insights tab](https://github.com/vaadin/flow-components/network/updates/277991666) )
```
Dependabot requires a pom.xml to evaluate your Java dependencies. It had expected to find one at the path: /integration-tests/pom.xml.
```
currently the bot doesn't allow us to configure to ignore modules. so we add this dummy integration-tests/pom.xml to the project
=> chore: Add dummy integration module [skip ci]

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/LazyHierarchicalDataProvider.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridBasicFeaturesPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridHashCollisionPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridHashCollisionIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
Backport of #2411 to Vaadin 14.
=> fix: Use getDataProvider().getId(item) instead of item.hashCode() (#2411)

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
The `i18n.toggle` and `i18n.clear` strings are not unused, as we no longer announce these buttons.
We can't remove corresponding fields right away, deprecating them for now.
- Deprecation
=> fix: deprecate no longer used i18n strings

vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/Map.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/View.java, vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/MapTest.java
Adds convenience methods for setting the center and the zoom level of the viewport to the map, in order to make these easier to use and to discover.
Fixes #2682
=> feat: add convenience methods for modifying the viewport

vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/Assets.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/ExperimentalFeatureException.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/Map.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/MapBase.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/AbstractConfigurationObject.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Configuration.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Constants.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Coordinate.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Extent.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Feature.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Projection.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/View.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/layer/ImageLayer.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/ImageSource.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/source/ImageWMSSource.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/events/MapClickEvent.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/events/MapFeatureClickEvent.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/events/MapViewMoveEndEvent.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/events/MouseEventDetails.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/serialization/MapSerializer.java
Polishes the Map JavaDocs a bit, adds JavaDoc for AbstractConfigurationObject to better document the inner workings of the configuration sync, and adds missing license headers.
Fixes https://github.com/vaadin/flow-components/issues/2602
Fixes https://github.com/vaadin/flow-components/issues/2646
=> chore: map javadoc improvements

vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/confirmdialog/examples/ModalityPage.java, vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/test/ModalityIT.java, vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
Fixes the confirm dialog to remove its server-side modality when the dialog is closed. Fixes a regression from #2608 . I think the assumption was that clicking one of the closing buttons in the confirm dialog would also call `close` or `setOpened` in the dialog. However for confirm dialog that is not the case, as the web component controls the default confirm / cancel buttons, adds the event listeners on them, and closes the dialog when they are clicked. The previous test case was only working because it was set up so that the element automatically removed itself from the UI on close, which I assume will also remove its server-side modality. 
Fixes #2706
=> fix: remove confirm dialog modality on close event

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DetachReattachPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachReattachIt.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Added the logic to update `deselectAllowed` on the connector when grid is attached.
Fixes #2696
- Bugfix
=> fix: ensure deselectAllowed is preserved on re-attach

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DetachReattachPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachReattachIt.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Similarly to #2711, use `getElement().setProperty()` so that Flow would take care of synchronizing the state on reattach.
Fixes #1485
- Bugfix
=> fix: preserve setDetailsVisibleOnClick on re-attach

vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/AppLayout.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/NodeLayout.java, vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow/src/main/java/com/vaadin/flow/component/cookieconsent/CookieConsent.java, vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/MainView.java, vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/Scroller.java, vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java
=> fix: Use English when converting code properties to lower case

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Fixes #1993 
I couldn't find a way to test this automatically so an IT isn't included. You can verify the fix manually:
- open http://localhost:8080/vaadin-combo-box/lazy-loading
- click "set renderer"
- furiously scroll the "ListDataProvider with beans" ComboBox
- scroll slowly and see the item content
Before:
https://user-images.githubusercontent.com/1222264/155691175-50b37a0f-c256-4ef4-ac73-234f8a3b6ca4.mp4
After:
https://user-images.githubusercontent.com/1222264/155691196-cd41a344-b2f0-4056-b808-81710cb274d0.mp4
=> fix: implement UpdateQueue.clear in ComboBox

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModelTest.java
Fixes selecting an item when an identifier provider is used through the
data provider or the data view API.
Fixes #2354
=> fix: fix selecting an item in a single select grid

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DetachReattachPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachReattachIt.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Cherry pick of https://github.com/vaadin/flow-components/pull/2711
(cherry picked from commit 0650abe33b966e38b8179d8ec4c787fe3d6e3378)
=> fix: ensure deselectAllowed is preserved on re-attach (#2711) (CP 22.0)

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java
Fixes https://github.com/vaadin/web-components/issues/3470
The current implementation that generates `aria-label='Sort by [content]'` for a `<vaadin-grid-sorter>` from its content doesn't take into account that a `ComponentRenderer` may be used for the sorter content.
The new implementation uses `org.jsoup.Jsoup.parse` to obtain the text content from the sorter content HTML and if non-empty, uses that for the `aria-label`.
=> fix: generate sorter aria-label using text content

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridDetailsRowIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes #2727 
This PR makes the connector not throw when a `cell-focus` event originates from "details" section.
NOTE:
This is merely a bugfix to avoid the client-side exception, and doesn't add the missing support for details cell-focus events. Adding the missing feat is a separate topic and requires some design (for example, do we want to add "details" to the `GridSection` enum or use the existing "body" section with `null` column for details cell focus...)
=> fix: don't throw on grid details cell focus

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
Cherry-pick of #2744 as requested [here](https://github.com/vaadin/flow-components/issues/2736#issuecomment-1057795594).
(cherry picked from commit 1a5cb4f1761d1fecfc2ee46f5a2c8923587f40b7)
=> fix: re-enable lazy loading when reducing page size (#2744) (CP: 14.8)

vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/ModalityDialogsPage.java, vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/ModalityDialogsPageIT.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
Fixes Dialog to remove server-side modality when closing the dialog on outside click, in case it has been added manually to the UI. 
Fixes a regression from #2608
=> fix: remove server-side modality on outside click

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/pom.xml, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/BinderValidationView.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/BinderValidationPage.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/Entity.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/BinderValidationPage.java
Removes the `hibernate-validator` dependency, and removes all bean validation constraints from all modules.
The `hibernate-validator` dependency is only necessary when using bean validation, for example by annotating a property with a constraint like `@NotNull`. In order to use bean validation, you need to use `BeanValidationBinder` instead of `Binder` [(see here)](https://vaadin.com/docs/latest/flow/binding-data/components-binder-beans/#defining-constraints-for-properties). However none of the integration tests actually use `BeanValidationBinder`, which means the dependency, and all bean validation constraints are not used at the moment. Also several IT modules have bean validation constraints without having the `hibernate-validator` dependency, which also would not work.
I checked if …
=> chore: remove bean validation from integration tests

vaadin-custom-field-flow-parent/vaadin-custom-field-flow/src/main/java/com/vaadin/flow/component/customfield/CustomField.java, vaadin-custom-field-flow-parent/vaadin-custom-field-flow/src/main/java/com/vaadin/flow/component/customfield/CustomFieldVariant.java, vaadin-custom-field-flow-parent/vaadin-custom-field-flow/src/test/java/com/vaadin/flow/component/customfield/CustomFieldVariantTest.java
Added `HasTheme` and corresponding theme variants:
- [`small`](https://github.com/vaadin/web-components/blob/c24d5b231876be92d3efef93ed79870df818d98e/packages/custom-field/theme/lumo/vaadin-custom-field-styles.js#L74)
- [`helper-above-field`](https://github.com/vaadin/web-components/blob/c24d5b231876be92d3efef93ed79870df818d98e/packages/vaadin-lumo-styles/mixins/helper.js#L37)
- [`whitespace`](https://github.com/vaadin/web-components/blob/c24d5b231876be92d3efef93ed79870df818d98e/packages/custom-field/theme/lumo/vaadin-custom-field-styles.js#L88)
Part of #2343
- Feature
=> feat: add theme variants support for CustomField

vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/pom.xml
=> chore: add the missing lumo-theme to dialog-integration-tests

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarTestPage.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarPageIT.java
This PR makes MenuBar ITs wait for resize observer tick whenever a test changes the size of an element. This is needed to fix MenuBar tests flakiness which, in particular, causes the build of #2839 to fail.
A follow-up to #2839.
=> test: wait for resize observer tick in MenuBar tests

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarTestPage.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarPageIT.java
Added a couple of missing tests for the `MenuBar` component that make sure:
- The menu item `theme` attribute is preserved during the item's visibility toggle in the case the theme has been specified initially.
- The menu item `theme` attribute is also removed in the visible state after resetting the theme in the hidden state.
They are intended to cover the following logic:
https://github.com/vaadin/flow-components/blob/9615db2466baf55cb86c90f9e71aa294d47fd9df/vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuItemBase.java#L51
https://github.com/vaadin/flow-components/blob/9615db2466baf55cb86c90f9e71aa294d47fd9df/vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuIte …
=> test: make sure menu item theme is preserved during item visibility toggle

vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuItemBase.java, vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuConnector.js
The private property `_theme` that Flow uses internally for storing the menu bar item theme must be renamed to `__theme` in order to prevent it from possible interference with the web component's property `_theme` that has recently appeared in https://github.com/vaadin/web-components/pull/3529.
=> refactor: rename private property `_theme` to `__theme`

vaadin-custom-field-flow-parent/vaadin-custom-field-flow/src/main/java/com/vaadin/flow/component/customfield/CustomField.java, vaadin-custom-field-flow-parent/vaadin-custom-field-flow/src/test/java/com/vaadin/flow/component/customfield/HasStyleTest.java
feat: Add HasStyle interface to CustomField
Some Flow components currently didn't implement the HasStyle interface, making it awkward to apply CSS classnames and inline styles to them. 
This code change adds this functionality.
Fixes #2852
=> feat: add HasStyle interface to CustomField

vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java, vaadin-crud-flow-parent/vaadin-crud-flow/src/test/java/com/vaadin/flow/component/crud/CrudTest.java
feat: Add HasStyle interface to CRUD component
Some Flow components currently didn't implement the HasStyle interface, making it awkward to apply CSS classnames and inline styles to them. 
This code change adds this functionality.
Fixes #2853
=> Add HasStyle interface to Crud #2853

vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/AppLayout.java, vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/test/java/com/vaadin/flow/component/applayout/AppLayoutTest.java
feat: Add HasStyle interface to App layout component
Some Flow components currently didn't implement the HasStyle interface, making it awkward to apply CSS classnames and inline styles to them. 
This code change adds this functionality.
Fixes #2853
=>  feat: Add HasStyle interface to AppLayout #2854

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePicker.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java
Fixes DatePicker such that to make it initialize the web component's `value` property with an empty string rather than leave it to be `null` when DatePicker is being instantiated with no value. This is needed to prevent the `value-changed` event on the server side which happens as a result of Polymer converting `null` to `""`.
It pretty much reproduces the fix made for Select a while ago in https://github.com/vaadin/flow-components/commit/14676def81188ec9a674bfe202ebac8d71b65067#diff-1c027c9076652ce3a2c641ac7407c10cc3a87846a37ee152c27aa9fe59aad609R126-R129
The same fix will be made for TimePicker, but in a separate PR.
Part of #2691
=> fix: ensure DatePicker initializes client side value property

vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java
Fixes TimePicker so that it initializes the web component's `value` property with an empty string rather than leaves it to be `null` when TimePicker is being instantiated with no value. This is needed to prevent the `value-changed` event on the server side which comes from the client side as a result of Polymer converting `null` to `""`.
Part of #2691
=> fix: ensure TimePicker initializes client side value property

vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerTest.java
Fixes DateTimePicker so that it initializes the web component's `value` property with an empty string rather than leave it to be `null` when DateTimePicker is being instantiated with no value. This is needed to prevent the `value-changed` event on the server side which comes from the client side as a result of Polymer converting `null` to `""`.
Part of #2691
=> fix: ensure DateTimePicker initializes client side value property

vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow-integration-tests/src/main/java/com/vaadin/flow/component/cookieconsent/examples/CustomMessages.java, vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow-integration-tests/src/main/java/com/vaadin/flow/component/cookieconsent/examples/DefaultSettings.java, vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow-integration-tests/src/test/java/com/vaadin/flow/component/cookieconsent/CustomMessagesIT.java, vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow-integration-tests/src/test/java/com/vaadin/flow/component/cookieconsent/DefaultSettingsIT.java
Fixed copy-paste: folder called `confirmdialog` placed in the `vaadin-cookie-consent-flow` IT package 🙈 
=> chore: use correct folder name for IT views

vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/confirmdialog/examples/StylingPage.java, vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/test/StylingIT.java, vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java, vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/resources/META-INF/resources/frontend/confirmDialogConnector.js
Added logic to copy `className` from `vaadin-confirm-dialog` to its overlay element for styling.
Fixes #2909
- Feature
=> feat: forward ConfirmDialog class name to overlay

pom.xml
This avoids issues when running `mvn formatter:format` on Windows machine.
=> Formatter should always use LF line ending

vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow-integration-tests/pom.xml, vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow-integration-tests/src/main/java/com/vaadin/flow/component/cookieconsent/examples/StylingPage.java, vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow-integration-tests/src/test/java/com/vaadin/flow/component/cookieconsent/StylingIT.java, vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow/src/main/java/com/vaadin/flow/component/cookieconsent/CookieConsent.java, vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow/src/main/resources/META-INF/resources/frontend/cookieConsentConnector.js
Added `HasStyle` and the connector to copy CSS class names from the host to the cookie banner.
The classes initially set on the client side are collected on attach before initializing the connector.
Fixes #2855
- Feature
=> feat: add HasStyle interface to CookieConsent

vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/pom.xml, vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/main/java/com/vaadin/flow/component/notification/tests/NotificationWithClassNamesPage.java, vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/test/java/com/vaadin/flow/component/notification/tests/NotificationWithClassNamesIT.java, vaadin-notification-flow-parent/vaadin-notification-flow/pom.xml, vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java, vaadin-notification-flow-parent/vaadin-notification-flow/src/main/resources/META-INF/resources/frontend/notificationConnector.js, vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationTest.java
Added HasStyle and the connector to copy CSS class names from the host to the notifications.
Fixes #2857
=> feat: add HasStyle to Notification and forward class to card

vaadin-accordion-flow-parent/vaadin-accordion-flow/src/main/java/com/vaadin/flow/component/accordion/Accordion.java, vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/AppLayout.java, vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/Avatar.java, vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/AvatarGroup.java, vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/Button.java, vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/Chart.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java, vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java, vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow/src/main/java/com/vaadin/flow/component/cookieconsent/CookieConsent.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java, vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java, vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java, vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/source/ImageWMSSourceTest.java, vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/source/OSMSourceTest.java, vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/source/TileWMSSourceTest.java, vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/source/VectorSourceTest.java, vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/configuration/source/XYZSourceTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java
The new descriptions of the components are mostly taken from their descriptions in the [docs](https://vaadin.com/docs/latest/ds/components). 
For example, instead of the Button docs saying
```
/**
* Server-side component for the <code>vaadin-button</code> element.
*/
```
It will be changed to say
```
/**
* The Button component allows users to perform actions. It comes in several
* style variants, and supports icons in addition to text labels.
*/
```
=> chore: Improve Javadocs 

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridSelectionColumn.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelWithHierarchicalDataProviderTest.java
Adds the missing indeterminate state to the Flow grid selection column.
Fixes #1060
=> fix: grid selection column indeterminate state

vaadin-iron-list-flow-parent/vaadin-iron-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/ironlist/tests/IronListIT.java
`IronListIT.listWithComponentRendererWithBeansAndPlaceholder_scrollToBottom_placeholderIsShown` fails randomly, it seems there is a race condition between checking if the list has rendered a placeholder after scrolling, and the Flow request resolving before that with updated data (in which case no placeholders are needed). 
The problem could be that the first check for a placeholder runs immediately after scrolling, at which point the list might not have re-rendered yet. The second check for a placeholder runs 20ms later, at which point the server-side roundtrip for new data could be completed. Attempt to fix this by adding a timeout for the first check, so that the list can re-render after scrolling.
Attempting this fix, because it affects the upgrade PRs for some reason:
- …
=> chore: attempt to make IronListIT more reliable

vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/button/tests/ButtonIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/ValueChangeModeIT.java
Removes usages of `WebDriverWait` constructor that accepts seconds, in order to prepare for bumping the testbench version which will also bump Selenium to a version that does not contain that constructor anymore.
=> chore: remove usages of deprecated WebDriverWait API

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/pom.xml
Bumps the version of `frontend-maven-plugin` that is used in the `vaadin-date-picker-flow` build to be compatible with M1 Macs. The current version of the plugin tries to download the node releases that do not exist, which results in a 404:
```
[INFO] Downloading https://nodejs.org/dist/v14.17.4/node-v14.17.4-darwin-arm64.tar.gz to /Users/sascha/.m2/repository/com/github/eirslett/node/14.17.4/node-14.17.4-darwin-arm64.tar.gz
```
Reference: https://github.com/eirslett/frontend-maven-plugin/issues/952
=> chore: bump frontend maven plugin version (14.8)

scripts/prepareDeploy.sh
as the demo module has been removed, we should not mention it here.
=> chore: remove the demo-helper for deployment [skip ci]

vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/ValidationPage.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupIT.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/ValidationIT.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/FieldValidationUtil.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckboxGroup.java
Disables client-side validation for the CheckboxGroup component, by overriding the client-side validation function and removing synchronization of the `invalid` property. The solution is adapted from a similar fix for RadioButtonGroup (https://github.com/vaadin/flow-components/pull/461). Note that the fix in RadioButtonGroup has changed quite a bit over time.
Fixes #2823
=> fix: disable client-side validation for CheckboxGroup

vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java
Add constructor to set both initial value and value change listener
Fixes #2944
=> feat: add constructor to set initial value and value change listener

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridSingleSelectionDeselectAllowedPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionDeselectAllowedIT.java
Renames existing grid single selection IT to clarify it's about testing single selection in combination with deselect allowed specifically.
Preparation for #3008
=> chore: rename single selection IT

vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogHeaderFooterIT.java
It looks like snapshot builds are failing due to some timing issue. 
This PR adds a check used in other ITs to wait for the `vaadin-dialog-overlay` element be attached in order to proceed with the test.
=> test: wait for dialog overlay on header-footer ITs

vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
Dialog new header and footer API add a root element on the server side to be used as the parent for the components to be added to these areas. 
One side effect with that approach is that it "blocks" the default styling behavior defined on the web-component by the Lumo/Material themes. Using `display: contents` to solve this, by making the styles applied to `[part=header]` and `[part=footer]` "go through" these roots and be applied to their children.
=> refactor: use display:contents on header/footer root

vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
Change `DialogHeaderFooter#add(Component)` into `DialogHeaderFooter#add(Component...)` and `DialogHeadeFooter#remove(Componento)` into `DialogHeaderFooter#remove(Component...) to make it easier to add one or more items in one call.
=> refactor: change add/remove API from dialog header/footer

vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java, vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuItemsArrayGenerator.java, vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuConnector.js, vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuTargetConnector.js, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenuTest.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/resources/META-INF/resources/frontend/menubarConnector.js
=> refactor: extract target connector, refactor items tree construction logic

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarVisibilityPage.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarPageIT.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarVisibilityIT.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBarRootItem.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/resources/META-INF/resources/frontend/menubarConnector.js
This PR adds a MutationObserver to the menu bar connector that watches for the `hidden` and `disabled` attributes and triggers re-generating the menu bar items if an attribute change occurs.
It solves the issue where changing the visibility or disabled state of a menu item wouldn't be applied if an ancestor of the menu bar was hidden at the same time. 
Fixes #2134
Depends on #3025
=> fix: re-generate items on the hidden or disabled property change

vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/CheckboxDemoPage.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupTest.java
Add shorthand constructors for CheckboxGroup
Fixes #3033
- Feature
=> feat: add shorthand constructors for CheckboxGroup 

vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerLocalizationIT.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js
The PR fixes a bug of TimePicker where `PM` could be interpreted as `AM` when it was written in lowercase. The fix improves the time parser to make it case and space insensitive.
Fixes #1179
=> fix: make AM/PM parser case and space insensitive

vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/confirmdialog/examples/EventView.java, vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/test/EventIT.java, vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
Add methods to disable "close on Esc" for ConfirmDialog
Fixes #1678
=> feat: add method to disable "close on Esc" for ConfirmDialog

.prettierrc, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js, vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuConnector.js, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js, vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js, vaadin-iron-list-flow-parent/vaadin-iron-list-flow/src/main/resources/META-INF/resources/frontend/ironListConnector.js, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/resources/META-INF/resources/frontend/menubarConnector.js, vaadin-messages-flow-parent/vaadin-messages-flow/src/main/resources/META-INF/resources/frontend/messageListConnector.js, vaadin-select-flow-parent/vaadin-select-flow/src/main/resources/META-INF/resources/frontend/selectConnector.js, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js, vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/resources/META-INF/resources/frontend/virtualListConnector.js
This PR is a result of running Prettier on Flow JS connectors. I decided to format connectors on the `22.0` branch as well to support automatic cherry-picks for future fixes.
It is recommended to review the PR with the enabled Hide whitespace to exclude indent changes.
A follow-up to https://github.com/vaadin/flow-components/pull/3036
=> chore: format JS connectors with Prettier (CP: 22.0)

.prettierrc, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js, vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuConnector.js, vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuTargetConnector.js, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js, vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js, vaadin-iron-list-flow-parent/vaadin-iron-list-flow/src/main/resources/META-INF/resources/frontend/ironListConnector.js, vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/mapConnector.js, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/resources/META-INF/resources/frontend/menubarConnector.js, vaadin-messages-flow-parent/vaadin-messages-flow/src/main/resources/META-INF/resources/frontend/messageListConnector.js, vaadin-select-flow-parent/vaadin-select-flow/src/main/resources/META-INF/resources/frontend/selectConnector.js, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js, vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/resources/META-INF/resources/frontend/virtualListConnector.js
This PR is a result of running Prettier on Flow JS connectors. I decided to format connectors on the `23.0` branch as well to support automatic cherry-picks for future fixes.
It is recommended to review the PR with the enabled Hide whitespace to exclude indent changes.
A follow-up to https://github.com/vaadin/flow-components/pull/3036
=> chore: format JS connectors with Prettier (CP: 23.0)

vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerLocalizationIT.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js
The PR cherry-picks the following fix to `23.0`:
- #3044
Fixes #1179
Depends on https://github.com/vaadin/flow-components/pull/3060
=> fix: make AM/PM parser case and space insensitive (#3044) (CP: 23.0)

vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerVariantTest.java
The package naming doesn't reflect the folder structure.
Fix the package name and add import for TimePicker classes.
=> chore: fix test package in TimePicker testing class

vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/pom.xml, vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/src/main/java/com/vaadin/flow/component/charts/export/NodeRunner.java, vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/src/test/java/com/vaadin/flow/component/charts/export/NodeRunnerTest.java
Prevent the SVG generator from downloading node.js if it can not be found, and throw an exception instead. First tries to locate a global node installation, and as a fallback looks for a node installation provided by Flow's frontend toolchain to cover development setups where developers don't use a global node installation.
Fixes #2837
- Bugfix
=> fix: throw exception instead of downloading node.js

vaadin-upload-flow-parent/vaadin-upload-flow/pom.xml, vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/UploadDropLabelTest.java
The test introduced with #3052 seems to fail randomly:
- https://teamcity.vaadin.com/viewLog.html?buildId=121901&buildTypeId=VaadinFlowComponents_PullRequestValidation
- https://teamcity.vaadin.com/viewLog.html?buildId=121904&buildTypeId=VaadinFlowComponents_PullRequestValidation
It seems setting the UI in `@Before` is not reliable for a test setup, and that moving the setup into the test itself solves the issue.
=> chore: fix flaky upload test

scripts/mergeITs.js, vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/AbstractParallelTest.java
Fixes an invalid null check in `AbstractParallelTest`. Solves this SonarCloud issue: https://sonarcloud.io/project/issues?resolved=false&types=BUG&pullRequest=3080&id=vaadin_flow-components&open=AYBrG-WEv9hxt65QaWaS
=> chore: fix invalid null check

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewSelectionIT.java, vaadin-grid-flow-parent/vaadin-grid-testbench/pom.xml, vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridElement.java, vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridTHTDElement.java
Fixes `GridElement.select` and `GridElement.deselect` to properly dispatch change events on the server-side. The fix involves changing the implementation to click on the selection checkboxes, which triggers the same logic in the grid connector as it would when a real user interacts with the component.
Ideally we would also change the single-selection logic to use a click instead of setting the active item, but that can be done as a separate change.
Fixes #1598 
- Bugfix
=> fix: make GridElement dispatch selection events

scripts/run.sh
Running `./scripts/run.sh`, and selecting option 2 or 3, results in the `vaadin-flow-components-shared-parent` module being listed as option:
```
18  vaadin-flow-components-shared-parent</module>
```
This change fixes the script to ignore the shared parent module, as it is not runnable.
=> chore: exclude shared parent module from run options [skip ci]

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/spreadsheet-styles-valo.css
Removed some no longer needed vendor prefixes from Spreadsheet Valo styles.
The following prefixes are still needed because Safari requires them:
- [`-webkit-user-select`](https://caniuse.com/mdn-css_properties_user-select)
- [`-webkit-backface-visibility`](https://caniuse.com/mdn-css_properties_backface-visibility)
- [`-webkit-touch-callout`](https://caniuse.com/mdn-css_properties_-webkit-touch-callout)
- [`-webkit-mask-image`](https://caniuse.com/mdn-css_properties_mask-image)
- Refactor
=> chore: cleanup obsolete vendor prefixes

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/TreeGridTest.java
Cherry pick of: #3046 
(cherry picked from commit 8fe08611e304779df01ecd6306d478a9c0edced0)
=> fix: Use incremental numeric id as a key for Tree Grid items (#3046) (CP: 23)

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/TreeGridTest.java
Cherry pick of: #3046 
(cherry picked from commit 8fe08611e304779df01ecd6306d478a9c0edced0)
=> fix: Use incremental numeric id as a key for Tree Grid items (#3046) (CP: 22)

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/TreeGridTest.java
Cherry pick of: #3046 
(cherry picked from commit 8fe08611e304779df01ecd6306d478a9c0edced0)
=> fix: Use incremental numeric id as a key for Tree Grid items (#3046) (CP: 14.8)

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/Renderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/test/java/com/vaadin/flow/data/renderer/LitRendererTest.java
Fixes #3086 
The PR also deprecates the method in `Renderer` because value providers are not something each type of a `Renderer` necessarily has/uses (for example `ComponentRenderer`).
This PR also doesn't fix the bug mentioned in [one of the comments](https://github.com/vaadin/flow-components/issues/3086#issuecomment-1116984857) on the issue (`Grid.addColumn(renderer)` doesn't automatically generate comparators for the value providers defined for the renderer). There's actually an [old issue](https://github.com/vaadin/flow-components/issues/1233) for it already and it should be resolved separately.
=> fix: implement LitRenderer.getValueProviders

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/Renderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/test/java/com/vaadin/flow/data/renderer/LitRendererTest.java
Cherry-pick https://github.com/vaadin/flow-components/pull/3148 for V23.1
=> fix: implement LitRenderer.getValueProviders (#3148) (CP: 23.1)

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/test/java/com/vaadin/flow/data/renderer/LitRendererTest.java
Backport #3148 for V23.0
[Deprecating](https://github.com/vaadin/flow-components/pull/3148/files#diff-684418efde22219990cc2380ec8a06391fb8232e3aa9f29a33e48ad4992eb14e) `Renderer.getValueProviders()` is omitted from this PR.
=> fix: implement LitRenderer.getValueProviders (#3148) (CP: 23.0)

vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java, vaadin-details-flow-parent/vaadin-details-flow/src/test/java/com/vaadin/flow/component/details/DetailsTest.java
Returns empty string instead of NPE when calling `getSummaryText` before any summary text is defined.
Decided to use empty string instead of `null` to make it consistent with `setSummaryText` which sets the content to `""` when called with `null`.
Fixes #3171
=> fix: return empty string if no summary text defined

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridViewClickListenersPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewClickListenersIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes #3177
This PR updates item click listener to not fire in case if `event.preventDefault()` was called for the `click` event on the client.
It's especially relevant for the Grid editor because of the following logic that closes the editor:
https://github.com/vaadin/flow-components/blob/6aefadf2db230a0a120c3b25122aea79c9d9d5c2/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/EditorImpl.java#L67
https://github.com/vaadin/flow-components/blob/6aefadf2db230a0a120c3b25122aea79c9d9d5c2/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/EditorImpl.java#L199-L205
Clarification about https://github.com/vaadin/flow-components/issues/3177#issuecomment-1125849666: the [`isFocusable` …
=> fix: do not trigger item click listener for prevented click

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/MergeIT.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java
Fixes #3186 
While https://github.com/vaadin/flow-components/pull/3215 does some nice cleanup for the code, I feel like the test coverage is not yet sufficient enough for such a refactor.
This PR fixes the issue with fewer changes.
=> fix: do not use merged regions index from POI

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridViewSortingPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewSortingIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Current logic for updating sorters in the connector only updates `vaadin-grid-sorter` elements that are added to the DOM.
When the column gets hidden while also calling `grid.sort(null)`, the connector does not update its sorter, because of not checking the actually applied sorters stored in `grid._sorters`. This causes the problem with restoring sort direction.
Fixes #1008
- Bugfix
=> fix: ensure the hidden grid sorters are reset

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/frontend/src/multi-select-combo-box-lit-wrapper.ts, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/frontend/src/multi-select-combo-box-polymer-wrapper.js, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxClientSideFilteringPage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxLitWrapperPage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxPolymerWrapperPage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxRefreshValuePage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxServerSideFilteringPage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxValueChangePage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxVirtualChildPage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxClientSideFilteringIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxLitWrapperIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxPolymerWrapperIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxRefreshValueIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxServerSideFilteringIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxServerValueChangeIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxValueChangeIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxVirtualChildIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js, vaadin-combo-box-flow-parent/vaadin-combo-box-testbench/src/main/java/com/vaadin/flow/component/combobox/testbench/MultiSelectComboBoxElement.java
Adds a `MultiSelectComboBoxElement` TestBench element, and integration tests for the `MultiSelectComboBox`. The tests are mostly intended to cover the differences compared to the regular combo box component regarding value handling and the client-side connector.
The PR also introduces some necessary changes to the connector in order to support both components. The new multi select combo box filtering ITs are supposed to cover that change.
Part of https://github.com/vaadin/platform/issues/2961
=> refactor: add multi select combo box integration tests

vaadin-avatar-flow-parent/vaadin-avatar-flow/pom.xml, vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/Avatar.java, vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/AvatarGroup.java, vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/AvatarGroupVariant.java, vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/AvatarVariant.java, vaadin-avatar-flow-parent/vaadin-avatar-flow/src/test/java/com/vaadin/flow/component/avatar/tests/AvatarGroupTest.java, vaadin-avatar-flow-parent/vaadin-avatar-flow/src/test/java/com/vaadin/flow/component/avatar/tests/AvatarTest.java
Implement `HasThemeVariant` for `Avatar` and `AvatarGroup`, and remove custom implementations of `addThemeVariants`, `removeThemeVariants`.
Part of https://github.com/vaadin/flow-components/issues/2948
- Refactor
=> refactor: implement HasThemeVariant for avatar components

vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/PieWithLegendEventsIT.java, vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/HiddenColumnIT.java, vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/OverrideClientValidationIT.java, vaadin-split-layout-flow-parent/vaadin-split-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/splitlayout/tests/OrientationChangeIT.java, vaadin-split-layout-flow-parent/vaadin-split-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitterPositionIT.java
The PR aligns the naming of setup methods in favor of `init()` for ITs based on https://github.com/vaadin/flow-components/pull/3280#discussion_r888740325.
=> test: align the naming of setup methods for ITs

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DetachReattachPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachReattachIt.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Added a check to ensure calling `grid.sort()` while grid is detached does not throw a JS error upon reattach.
Fixes #1672
- Bugfix
=> fix: update sorters only if grid is attached

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
The PR removes the use of Polymer API from the combo-box connector as a follow-up to https://github.com/vaadin/web-components/pull/4008
=> refactor: don't use Polymer API in the combo-box connector

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxBinderValidationTest.java
Adds unit tests for the `MultiSelectComboBox` for testing binder integration.
Part of https://github.com/vaadin/platform/issues/2961
=> test: add binder validation tests

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxTest.java
Allows setting the value / selection of the multi select combo box through a var args parameter. Should wait for #3275 to reuse the multi select model for identifying duplicates in the selection.
Part of https://github.com/vaadin/flow-components/issues/2948
=> refactor: allow setting value with var args

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/main/java/com/vaadin/flow/component/spreadsheet/tests/SpreadsheetPage.java
Align the Spreadsheet IT page naming to match that of other components. The current `DemoUIView.java` is too generic and hard to discover.
=> chore: align spreadsheet IT page naming

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridViewSortingPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewSortingIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
This PR addresses the bug reported in https://github.com/vaadin/flow-components/issues/3155#issuecomment-1122477130:
> when clicking the button, the grid sorts by multiple columns, even though multi-sort is not enabled. 
Closes #3155
- Bugfix
=> fix: only use first column with no multi-sorting

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
The PR refactors the combo-box connector to ensure `filteredItems` are reassigned after they are mutated because just mutating `filteredItems` will no longer trigger the web component's observers (see https://github.com/vaadin/web-components/pull/4008).
A follow-up to https://github.com/vaadin/flow-components/pull/3301
=> refactor: reassign filteredItems after mutating them

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/dataview/ItemCountUnknownComboBoxIT.java
Cherry-pick from master: changes in ComboBox IT after changes in Web Component
https://github.com/vaadin/flow-components/pull/3212/commits/54d5009adeda2584e2670ffb05bc22a58c1acd37
=> test: adapt combo-box tests to WC changes (CP: 23.0)

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/AbstractSpreadsheetIT.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ResizeIT.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SpreadsheetEventListener.java
Fixes #3329 
Fixes an issue in `toMapInt`/`toMapFloat` helpers where empty / `null` values got accidentally translated as `0`. This caused exceptions with column and row resize events.
before:
```js
// Given array of values
[,,100]
->
// Resulting Map
{
0: 0,
1: 0,
2: 100
}
```
after:
```js
// Given array of values
[,,100]
->
// Resulting Map
{
2: 100
}
```
=> fix: ignore empty values in resize arrays

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
This PR reverts https://github.com/vaadin/flow-components/pull/3327 because it turns out that the use of a mutation way of changing `filteredItems` was intentional and aimed to prevent Polymer from invoking observers.
=> Revert "refactor: reassign filteredItems instead of mutating them"

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java
Remove `HasComponents` and `Focusable` from the list of interfaces that `Spreadsheet` implements.
Fixes #3159
=> refactor!: remove HasComponents and Focusable from Spreadsheet

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxBaseTest.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasAllowedCharPattern.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/HasAllowedCharPatternTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldPageIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/resources/META-INF/resources/frontend/vaadin-big-decimal-field.js, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/EmailFieldTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/PasswordFieldTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/TextAreaTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/TextFieldTest.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java
Added support for `allowedCharPattern` to the following components:
- `ComboBox`
- `DatePicker`
- `EmailField`
- `NumberField`
- `PasswordField`
- `TextArea`
- `TextField`
- `TimePicker`
Note: this does not include `BigDecimalField` as it has a hardcoded pattern.
Part of https://github.com/vaadin/platform/issues/2963
Depends on https://github.com/vaadin/web-components/pull/3937
- Feature
=> feat: add HasAllowedCharPattern interface to field components

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java
This PR deprecates the `setPreventInvalidInpit()` API in favor of the newly added `setAllowedCharPattern()`.
Note: in `NumberField`, corresponding methods were already deprecated as not supported by web component.
Closes https://github.com/vaadin/web-components/issues/3837
-  Docs
=> docs: deprecate setPreventInvalidInput API

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Updated Grid connector to only use `grid.getEventContext()` once before opening context-menu, and get `column.id` there.
This adds `columnId` property to `vaadin-context-menu-before-open` event detail so that we can use it on the server.
https://github.com/vaadin/flow-components/blob/9ceb6c2c80486153c70850d217741d3065cf38fa/vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuTargetConnector.js#L18-L26
Related to #2258
Pre-requisite for #1939
- Refactor
=> refactor: pass column ID to before open event detail

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/TreeGridTest.java
Cherry-pick of #3251 
(cherry picked from commit c5f9e8470a2115ed7d4e707a19511cc65602abe0)
Depends on https://github.com/vaadin/flow/pull/13883 to be cherry-picked, and released for 23.1, as well as all other target versions (23.0, 22.0, 14.8).
=> refactor: Use KeyMapper by default to generate unique keys (#3251) (CP: 23.1)

.gitignore
This adds generated files created when running ITs to `.gitignore`. Example:
```
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/.npmrc
vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/.pnpmfile.cjs
```
=> chore: add generated files to .gitignore

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxTest.java
Allows setting the value of the `MultiSelectComboBox` as `Collection`. This would be a minor DX improvement when using the component without binder, and initializing the value from a list. This is kind of complementary to the setter using var args added here: https://github.com/vaadin/flow-components/pull/3304
=> refactor: allow setting value as collection

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/TreeGridTest.java
Cherry-pick of #3251
Solved a minor conflict in `Grid` and updated `TreeGridTest` to use a custom `MockUI` (added as part of a previous PR), as `DataCommunicator.MockUI` does not exist in 14.8.
=> refactor: Use KeyMapper by default to generate unique keys (#3251) (CP: 14.8)

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/spreadsheet-styles-valo.css
Add a max height with scrollable area to item filter content to avoid it growing to fit all its content, which can be a problem for table with lots of filter options.
The value of max height is the same of how it is defined on the FW8 version. The difference is that it was setting the value to height instead of max height.
Fixes #3416
=> fix: add max-height with scrollable area to item filter

vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/Avatar.java, vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/AvatarGroup.java, vaadin-avatar-flow-parent/vaadin-avatar-flow/src/test/java/com/vaadin/flow/component/avatar/tests/AvatarGroupTest.java, vaadin-avatar-flow-parent/vaadin-avatar-flow/src/test/java/com/vaadin/flow/component/avatar/tests/AvatarTest.java, vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/GeneratedVaadinButton.java, vaadin-button-flow-parent/vaadin-button-flow/src/test/java/com/vaadin/flow/component/button/tests/ButtonTest.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxVariantTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/EmailFieldTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/IntegerFieldTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/PasswordFieldTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/TextAreaTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/tests/TextFieldTest.java
Restore `addThemeVariants` and `removeThemeVariants` methods for those components where they have been removed as part of the refactoring to implement `HasThemeVariant`, in order to restore binary compatibility with previous Vaadin versions. I also had to revert the test changes, as redeclaring the method introduced runtime errors.
This should cover the changes from the following PRs:
- https://github.com/vaadin/flow-components/pull/3205
- https://github.com/vaadin/flow-components/pull/3278
- https://github.com/vaadin/flow-components/pull/3284
- https://github.com/vaadin/flow-components/pull/3310
Fixes: https://github.com/vaadin/flow-components/issues/3423
- Bugfix
=> fix: restore binary compatibility for theme variant methods

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/ClientValidationUtil.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasClientValidation.java
- add util class to override `shouldSetInvalid` on the web component
- add interface to be implemented by field components to listen to validated events from the web component
=> feat: add logic to handle client side validation

vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/DetachAttachPage.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/FeatureEventsPage.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/MapEventsPage.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/MarkerFeaturePage.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/PreserveOnRefreshPage.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/ViewPage.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/demo/ImageWMSDemo.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/demo/SamplerView.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/demo/TileWMSDemo.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/demo/XYZSourceDemo.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/DetachAttachIT.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/FeatureEventsIT.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/MapEventsIT.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/MarkerFeatureIT.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/PreserveOnRefreshIT.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/ViewIT.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/Map.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Coordinate.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Extent.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/View.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/feature/MarkerFeature.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/feature/PointBasedFeature.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/geometry/Point.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/events/MapClickEvent.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/mapConnector.js, vaadin-map-flow-parent/vaadin-map-testbench/src/main/java/com/vaadin/flow/component/map/testbench/MapElement.java
Changes the default coordinate system / user projection of the Map component to `EPSG:4326`, a.k.a. GPS coordinates. That means that all coordinates passed to, or returned from the public API are assumed to be in this projection. Internally the component will automatically convert coordinates into the configured view projection.
This is a breaking change, and all coordinates that were specified in the previous default (`EPSG:3857`) need to be changed to use `EPSG:4326`. A separate change will allow setting the user projection back to `EPSG:3857`. Also applications that only use `Coordinate.fromLonLat` are going to be covered by another separate change that removes the conversion to `EPSG:3857`, and just creates coordinates in `EPSG:4326` (the new default).
Part of …
=> feat!: use EPSG:4326 as default coordinate system

vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/ChangeUserProjectionPage.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/ChangeUserProjectionIT.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/Map.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Coordinate.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Extent.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/View.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/feature/MarkerFeature.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/feature/PointBasedFeature.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/geometry/Point.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/events/MapClickEvent.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/mapConnector.js, vaadin-map-flow-parent/vaadin-map-testbench/src/main/java/com/vaadin/flow/component/map/testbench/MapElement.java
Allows to set a different user projection for all coordinates passed to, or received from the public API. This allows to use coordinates in a projection other than `EPSG:4326`, which is the default user projection. Currently the feature is limited to `EPSG:4326` and `EPSG:3857` projections, a separate PR will add support for defining custom projection. The user projection applies to all maps in a browser page, it is not possible to configure this setting for individual maps.
For testing, [epsg.io](https://epsg.io/) is a handy website for looking up projections, and converting coordinates.
Part of https://github.com/vaadin/platform/issues/3106
=> feat: set projection for coordinates used in public API

vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/DefineCustomProjectionPage.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/DefineCustomProjectionIT.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/Map.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/mapConnector.js
Allows to define custom coordinate projections which can then be used as user projection or view projection. The definition is valid for the lifetime of a browser page, the constraints have been documented in the JavaDoc.
The feature uses the `proj4` JS library to allow defining projections in the Well Known Text (WKS) format, which is then integrated with OpenLayers. The library should add around 27kB to production builds, a future change could optimize this further by excluding the default projection definitions that come out of the box with the library. More background on that here: https://github.com/vaadin/platform/issues/3106#issuecomment-1176014836
Part of https://github.com/vaadin/platform/issues/3106
~~Depends on #3454~~
=> feat: define custom coordinate projections

vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Coordinate.java
Since 23.2, the default coordinate system has been changed to EPSG:4326, which allows passing latitude and longitude into the constructor directly. Usages of this method should be replaced with a call to the constructor.
Since the default coordinate system has been changed to EPSG:4326, and the purpose of this method is to return coordinates in EPSG:3857, this method will not return correct results anymore. As a temporary measure, the coordinate system can be changed back to EPSG:3857 using Map.setUserProjection(String). Long-term, usages of this method should be replaced.
Part of https://github.com/vaadin/platform/issues/3106
=> refactor: deprecate Coordinate.fromLonLat

vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/main/java/com/vaadin/flow/component/virtuallist/tests/VirtualListDataProviderRefreshPage.java, vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListDataProviderRefreshIT.java, vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/resources/META-INF/resources/frontend/virtualListConnector.js
When using a data provider with a size that exceeds the number of items that the virtual list fetches for a viewport, the connector stores `undefined` items as placeholders for items that have not been loaded. When updating individual items in the data provider, the connector iterates over all items, and tries to map updated to existing items - which fails if an existing item is `undefined` because it tries to access its key.
Updated the connector to check if the item is loaded before attempting to map updated to existing item.
Fixes #3487 
- Bugfix
=> fix: refresh individual items in virtual list

pom.xml, vaadin-grid-flow-parent/vaadin-grid-flow/pom.xml
Version 4.4.1 causes compatibility issues deploy plugin
because of mixed version of wagon artifacts
=> chore: Set version to karaf maven plugin

vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/BigDecimalFieldElement.java, vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/EmailFieldElement.java, vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/IntegerFieldElement.java, vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/NumberFieldElement.java, vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/PasswordFieldElement.java, vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextAreaElement.java, vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextFieldElement.java, vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextFieldElementHelper.java
This PR changes the `setValue` method for field components to make it emulate real user input firing `input` and `change` DOM events rather than just setting the `value` property on the host element. This is needed to allow using this method for testing validation behavior on invalid user input – the web components trigger validation on `change` DOM event but not all and not always on `value` property change.
Also, see https://github.com/vaadin/flow-components/issues/3420#issuecomment-1190086875 explaining why using `sendKeys` is not an option for `setValue`.
> **Warning**
> It is an altering behavior change.
Fixes #3420
=> fix!: make setValue emulate real user input

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/ValueChangeModeIT.java, vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/BigDecimalFieldElement.java, vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextFieldElement.java
This PR ensures `sendKeys` calls are delegated to the component's slotted input element as calling `sendKeys` directly on the component's host doesn't seem to be reliable.
Fixes https://github.com/vaadin/flow-components/issues/3502
=> fix: delegate sendKeys calls to the input element

vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java
Related to #1667
The `setLabelAsHtml()` API is not well designed (for example, it does not check for XSS).
As we added `setLabelComponent()` API in 23.1, it makes sense to deprecate this method.
- Deprecation
=> docs: deprecate setLabelAsHtml for Checkbox

vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/pom.xml, vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/UploadI18nView.java, vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadI18nIT.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
Fixes #3521
Fixes #1849
Some components that set `i18n` like `AppLayout` and `MenuBar` implement `onAttach` as follows:
https://github.com/vaadin/flow-components/blob/93105314241efb54c4b0e14d38739a2f5bba2564/vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/AppLayout.java#L122-L129
This logic was missing from `Upload`, so the client side `i18n` property was not updated.
- Bugfix
=> fix: ensure upload i18n is preserved on reattach

vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/GeneratedVaadinButton.java
Fixes the following error
>error: no summary or caption for table
=> docs: fix javadoc warnings for vaadin-button-flow

vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java
The `IronResizableBehavior` has been removed from `vaadin-split-layout` in https://github.com/vaadin/web-components/pull/3200.
So this API should be removed as well, as it's not really working anymore. Let's deprecate it for removal in V24.
- Deprecation
=> docs: deprecate legacy IronResizeEvent APIs

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/LazyLoadingTreeGridRefreshAllPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/LazyLoadingTreeGridRefreshAllIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
Backporting [3514](https://github.com/vaadin/flow-components/pull/3514) to v22.
Fixes #3434
=> fix: remove the block that resets tree grid connector (CP: 3514)

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DefaultMultiSortPriorityPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DefaultMultiSortPriorityIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Related to https://github.com/vaadin/platform/issues/3052
Added a static method to configure default multi-sort priority as proposed in https://github.com/vaadin/platform/issues/3052#issuecomment-1202325061
See https://github.com/vaadin/web-components/pull/4305 where the web component API for this was added.
- Feature
=> feat: add setDefaultMultiSortPriority to Grid

.gitignore
I'm using the latest Flow snapshot locally which already has Vite enabled by default and therefore a lot of `vite.*` files are generated each time I compile the project. Added those files to `.gitignore`.
=> chore: add vite.* files to gitignore

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractRow.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/FooterRow.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/HeaderRow.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java
Adds getters for the text or component content of column header and footer cells.
Closes https://github.com/vaadin/flow-components/issues/1676
Closes https://github.com/vaadin/flow-components/issues/1496
- Feature
=> feat: add getters for column header and footer contents

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/LockIT.java
Fixes `LockIT` to not use `SpreadSheetCellElement.setValue`, which does not work for locked cells, and instead check if double-clicking opens the cell value input.
=> chore: change test logic for locked cells

vaadin-date-picker-flow-parent/vaadin-date-picker-testbench/src/main/java/com/vaadin/flow/component/datepicker/testbench/DatePickerElement.java
This PR changes the `setInputValue` method of `DatePickerElement` to make it simulate real user input by sending the respective characters + <kbd>Enter</kbd> via the Selenium `sendKeys` API. The clearing of the input's value is now done by sending <kbd>Shift</kbd> + <kbd>Home</kbd> and then <kbd>Backspace</kbd> instead of clearing the input's `value` property, see https://github.com/vaadin/flow-components/pull/3576#discussion_r945471738.
In particular, this PR is needed to allow using the method for testing validation behavior on invalid user input – the web component trigger validation on `change` DOM event but not on `_inputValue` property change.
I also removed explicit opening and closing of the overlay as it doesn't seem to be necessary since `DatePicker` already automatically opens …
=> refactor!: make setInputValue simulate real user input

vaadin-time-picker-flow-parent/vaadin-time-picker-testbench/src/main/java/com/vaadin/flow/component/timepicker/testbench/TimePickerElement.java
The previous implementation used to clear the input element's `value` property which could result in missing the `input` event when `selectByText` is called with an empty string. This PR instead makes `selectByText` clear the value by sending <kbd>Shift</kbd> + <kbd>Home</kbd> (Select All) and then <kbd>Backspace</kbd> which doesn't have that drawback.
This is needed to allow using the `selectByText` method for testing validation in https://github.com/vaadin/flow-components/pull/3515.
=> refactor!: make selectByText clear input's value by sending keys

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/resources/vaadin-featureflags.properties, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/pom.xml, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerBinderValidationTest.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/resources/vaadin-featureflags.properties, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/pom.xml, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerBinderValidationTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/resources/vaadin-featureflags.properties, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/binder/AbstractTextFieldValidationTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/binder/EmailFieldValidationTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/binder/IntegerFieldValidationTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/binder/NumberFieldValidationTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/binder/PasswordFieldValidationTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/test/java/com/vaadin/flow/component/textfield/binder/TextAreaValidationTest.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/resources/vaadin-featureflags.properties, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/pom.xml, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerBinderValidationTest.java
The PR puts the `getDefaultValidator` implementation behind the feature flag `forceFieldValidation` as we agreed in https://github.com/vaadin/flow/pull/14285#issuecomment-1209102605.
Part of https://github.com/vaadin/platform/issues/3066
A follow-up to #3381
=> refactor!: put getDefaultValidator implementation behind a feature flag

vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/confirmdialog/tests/OverlayForwardingSourcePage.java, vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/confirmdialog/tests/OverlayForwardingTargetPage.java, vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/tests/OverlayForwardingIT.java, vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java, vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/OverlayForwardingSourcePage.java, vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/OverlayForwardingTargetPage.java, vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/OverlayForwardingIT.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java, vaadin-login-flow-parent/vaadin-login-flow-integration-tests/src/main/java/com/vaadin/flow/component/login/tests/OverlayForwardingSourcePage.java, vaadin-login-flow-parent/vaadin-login-flow-integration-tests/src/main/java/com/vaadin/flow/component/login/tests/OverlayForwardingTargetPage.java, vaadin-login-flow-parent/vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/tests/OverlayForwardingIT.java, vaadin-login-flow-parent/vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java, vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/main/java/com/vaadin/flow/component/notification/tests/ContainerForwardingSourcePage.java, vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/main/java/com/vaadin/flow/component/notification/tests/ContainerForwardingTargetPage.java, vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/test/java/com/vaadin/flow/component/notification/tests/ContainerForwardingIT.java, vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
The issue was caused by registrations regarding adding the component to UI persisting even after a forwarding/rerouting happens in `beforeEnter`.
This PR introduces an `AfterNavigationListener` for programmatic navigation events. Whenever such an event occurs, the listener removes the previously added registration regarding adding the component to UI.
Applies to ConfirmDialog, Dialog, LoginOverlay, and Notification.
Fixes #3414
=> fix: prevent adding overlay to UI when forwarding happens in beforeEnter

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
Restored the following APIs that were previously available through `GeneratedVaadinComboBox`:
- `protected void addToPrefix(Component... components)`
- `protected void remove(Component... components)`
- `protected void removeAll()`
- Refactor
=> refactor: restore protected API for children

vaadin-tabs-flow-parent/vaadin-tabs-flow/pom.xml, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/resources/META-INF/resources/frontend/tabsheet/src/vaadin-tabsheet.d.ts, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/resources/META-INF/resources/frontend/tabsheet/src/vaadin-tabsheet.js, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/resources/META-INF/resources/frontend/tabsheet/theme/lumo/vaadin-tabsheet-styles.js, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/resources/META-INF/resources/frontend/tabsheet/theme/lumo/vaadin-tabsheet.js, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/resources/META-INF/resources/frontend/tabsheet/theme/material/vaadin-tabsheet-styles.js, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/resources/META-INF/resources/frontend/tabsheet/theme/material/vaadin-tabsheet.js, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/resources/META-INF/resources/frontend/tabsheet/vaadin-tabsheet.d.ts, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/resources/META-INF/resources/frontend/tabsheet/vaadin-tabsheet.js, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetTest.java
Adds `TabSheet` component with basic features:
- add, remove, selectedTab, selectedIndex APIs
- Selected change listener
- Lazy loading of content (server-to-client)
- Unit tests
Excluded from this PR (to be submitted separately):
- HasTheme & Theme variants
- Prefix & Suffix API
- TestBench Element and ITs
- Feature
- The PR includes a temporary copy of the `<vaadin-tabsheet>` web component from https://github.com/vaadin/web-components/tree/feat/tabsheet/packages/tabsheet. Once the package is published to npm, the temporary copy should be removed.
=> feat: add TabSheet with basic features

vaadin-flow-components-shared-parent/vaadin-flow-components-base/pom.xml, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/TooltipTest.java
Adds `Tooltip` handle with basic features:
- `var handle = Tooltip.forComponent(component)` (also for `Element`)
- Creates a handle that controls a `<vaadin-tooltip>` instance that gets automatically attached/detached under `<body>` when the target component gets attached/detached.
- API for configuring the tooltip
- API for opening/closing the tooltip manually
- Unit tests
Excluded from this PR (to be submitted separately):
- `HasTooltip` interface and integration to components
- `TooltipGenerator` API for `Grid`
- TestBench Element and ITs
- Feature
- This PR is targeting the `feat/tooltip` branch, not `master`.
=> feat: add Tooltip handle

vaadin-flow-components-shared-parent/vaadin-flow-components-base/pom.xml, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasPrefixAndSuffix.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/PrefixSuffixTest.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java
Move the `HasPrefixAndSuffix` interface from `vaadin-text-field-flow` to `vaadin-flow-components-base`.
The interface is needed by the `TabSheet` component which also supports adding a prefix and a suffix.
- Refactor
=> refactor: move HasPrefixAndSuffix to flow-component-base

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePicker.java
Fixed the `@code` usage in `GeneratedVaadinDatePicker` 
This is needed to avoid problems with new versions of `formatter-maven-plugin`, see https://github.com/vaadin/flow-components/pull/3510#issuecomment-1193906770
Note: there is a similar `i18n` description for `GeneratedVaadinTimePicker` which does not use `@code`:
https://github.com/vaadin/flow-components/blob/c932d32aac2652fa20254248043d5fceb3c56da3/vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java#L672-L673
=> chore: fix generated JavaDoc for i18n object

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerValidationPage.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerViewDemoPage.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerValidationPageIT.java
This PR moves some basic tests from `DatePickerValidationPageIT` to `DatePickerIT` because they are not related to validation.
Related to https://github.com/vaadin/flow-components/pull/3496
=> test: move basic tests to DatePickerIT

vaadin-tabs-flow-parent/vaadin-tabs-flow/pom.xml, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetTest.java
Add prefix and suffix support to `TabSheet`
- Feature
=> feat: add prefix and suffix to TabSheet

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerLocalePage.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerValidationPage.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocaleIT.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerValidationPageIT.java
This PR moves locale tests from `DatePickerValidationPageIT` to `DatePickerLocaleIT` because it is a more appropriate place for them.
Related to https://github.com/vaadin/flow-components/pull/3496
=> test: move locale tests to DatePickerLocaleIT

scripts/mergeITs.js
since fcbac5ea043e120fee5dde23eaae2cb23a7c4c8a, `vaadin-flow-components-test-util` is needed under default scope instead of the original test scope.
=> chore: update mergeITs to use default scope to util dep

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasTooltip.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/HasTooltipTest.java
Adds the `HasTooltip` interface to `vaadin-flow-components-base`. Components implementing the interface will get the following API:
- `Tooltip setTooltip(String text)`
- Creates a `<vaadin-tooltip slot="tooltip" text="text">` element and adds it inside the target component
- Returns the `Tooltip` handle that can be used to configure and control the tooltip
- `String getTooltip()`
- Returns the `text` property that was set using `setTooltip(String text)`
Excluded from this PR (to be submitted separately):
- `HasTooltip` integration to components
- Feature
- This PR is targeting the `feat/tooltip` branch, not `master`.
=> feat: add HasTooltip interface

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/TooltipTest.java
Since there already are [component-specific defaults](https://github.com/vaadin/web-components/blob/8326a11bc382d74aed44926c998ac8d3f85d5648/packages/details/src/vaadin-details.js#L154) for the tooltip `position`, it's better to default to `null` in the Flow component `getPosition()` API than trying to keep up with the Web Component defaults.
- Refactor
- This PR is targeting the `feat/tooltip` branch, not `master`.
=> refactor: default to null for tooltip position

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxClientSideFilteringIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Pretty much all the properties related to data provider are available directly on the host combo-box / multi-select-combo-box element so there seems to be no reason for setting them through internal elements bypassing the host element. 
~~The only case when accessing internal elements is reasonable is when calling data provider methods such as `clearCache()`.~~ UPD: The multi-select-combo-box's host element already provides `clearCache()`.
Related to https://github.com/vaadin/web-components/pull/4019#pullrequestreview-1001168796
=> refactor: set data provider related properties on the host element

vaadin-avatar-flow-parent/vaadin-avatar-flow/src/main/java/com/vaadin/flow/component/avatar/Avatar.java, vaadin-avatar-flow-parent/vaadin-avatar-flow/src/test/java/com/vaadin/flow/component/avatar/tests/AvatarTest.java
Added `setTooltipEnabled()` to change `withTooltip` property on the `vaadin-avatar`.
Note, the `Avatar` is not supposed to implement `HasTooltip` because its tooltip is always pre-configured to show the name, the abbreviation, or the "anonymous" string in case when neither of those is set by the user.
- Feature
=> feat: add setTooltipEnabled() to Avatar

vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetTest.java
Even though it's an edge case, it is techincally possible to add the same `Tab` instance to a `TabSheet` more than once and with different content. In this case, make sure any possible content previously related to the same tab gets cleaned up.
- Fix
=> fix: clean up old content on tabsheet.add

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java
There was some discussion (in the API review meeting) around the topic of `Tooltip.forComponent`/`Tooltip.forElement` API naming. Eventually, it was decided that the current `Tooltip.forElement` API should be made private (for now at least).
- Refactor
=> refactor: make tooltip forElement api private

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridTooltipPage.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTooltipTest.java
Apply the following changes (as agreed in API review):
- Rename `gridColumn.setTooltipTextGenerator` to `gridColumn.setTooltipGenerator`
Related to (but does not depend on) https://github.com/vaadin/web-components/pull/4616
=> refactor: rename setTooltipTextGenerator to setTooltipGenerator

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/TooltipTest.java
Add tooltip method chaining API as specified in the [tooltip API summary](https://github.com/vaadin/platform/discussions/3196#discussioncomment-3626110)
Example:
```java
textField.setTooltip("Other users can see this")
.withFocusDelay(200)
.withHideDelay(1000)
.withHoverDelay(500)
.withPosition(TooltipPosition.BOTTOM_END);
```
- Feature
=> feat: add Tooltip method chaining API

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarTooltipPage.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarTooltipIT.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarTooltipTest.java
Added tooltip API to `MenuBar` as specified in the [tooltip API summary](https://github.com/vaadin/platform/discussions/3196#discussioncomment-3626110)
Note, the `MenuBar` is not supposed to implement `HasTooltip`.
- Feature
=> feat: add tooltip API to menubar

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasTooltip.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/HasTooltipTest.java
Apply the following changes (as agreed):
- Rename `HasTooltip::setTooltip` to `HasTooltip::setTooltipText`
- Make `getTooltip()` always return a `Tooltip` (even if `setTooltipText` is not called beforehand)
- Refactor
=> refactor: rename setTooltip to setTooltipText

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTooltipIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Grid's tooltip generator function made an assumption that the `item` is always truthy and that it contains a `gridtooltips` object. Align the implementation with that of `MenuBar` / check that the required properties are defined.
- Fix
=> fix: add better checks to grid tooltip generator function

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/resources/META-INF/resources/frontend/menubarConnector.js
This PR adds a missing contextMenuConnector import to MenuBar which is an attempt to fix https://github.com/vaadin/flow-components/issues/3655.
=> fix: add missing contextMenuConnector import

vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/button/tests/TooltipDefaultsPage.java, vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/button/tests/TooltipDefaultsIT.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/TooltipConfiguration.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/resources/META-INF/resources/frontend/tooltip.ts
Add tooltip defaults configuration as specified in the [tooltip API summary](https://github.com/vaadin/platform/discussions/3196#discussioncomment-3626110)
Example:
```java
TooltipConfiguration.setDefaultFocusDelay(500);
```
- Feature
=> feat: add tooltip defaults configuration

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
There was a single debouncer, and 2 ways to set it in the connector. In some cases, the debouncer is overridden by the other, which results in callbacks that are never completed and never cleared. Therefore, the loading state is never resolved.
This PR prevents the debouncer override. The data request is now performed without the debouncer. While the debouncer is active, the callbacks that do not contain filter changes are not executed right away, but within the debouncer. 
Fixes #3595
=> fix: prevent debouncer override in callback

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
Update date-fns to 2.29.1, required by https://github.com/vaadin/skeleton-starter-flow/pull/612
=> chore: update date-fns to 2.29.1

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/date-fns/package-lock.json, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/date-fns/package.json
Update `date-fns` to latest version in 14 branches.
See #3750
=> chore: update date-dns to 2.29.3

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/resources/META-INF/resources/frontend/tooltip.ts
While upgrading `docs`, we discovered that `docs-app` doesn't yet support this modern TS syntax. Let's downgrade the syntax used in `tooltip.ts` for now.
=> fix: downgrade ts syntax used in tooltip.ts

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java
Back-port of [3787](https://github.com/vaadin/flow-components/pull/3787) to 23.1 branch.
For a multi-select Grid, when a filter was introduced using the ListDataView, using the select all check box from the client doesn't take the filter into account. This PR changes the query so that the query contains the filter info that is already present in the DataCommunicator.
Fixes #3614
=> fix: change the fetch query so that the filter is passed (#3787) (CP: 23.1)

vaadin-accordion-flow-parent/vaadin-accordion-flow/src/main/java/com/vaadin/flow/component/accordion/AccordionPanel.java
The PR adds some missing JS imports to `AccordionPanel` so that it can be used alone on the page, without the main  `Accordion` component.
Fixes https://github.com/vaadin/flow-components/issues/3702
=> fix: add missing JS imports

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java
Updated JavaDoc for methods related to `focusDelay` to explicitly mention keyboard focus.
=> docs: clarify opening tooltip on keyboard focus

vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetTest.java
Rename `tabsheet.indexOf(Tab tab)` to `tabsheet.getIndexOf(Tab tab)` . Even though aligned with `tabs.indexOf(Component component)`, the discoverability of the current API proved to be insufficient during the DX test sessions.
=> refactor: rename tabsheet.indexOf to tabsheet.getIndexOf

vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetTest.java
Throw an `IllegalArgumentException` when `Text` is passed as the TabSheet's...
- content
- prefix
- suffix
- remove argument
Fixes https://github.com/vaadin/flow-components/issues/3803
=> refactor: throw an exception for Text as TabSheet content

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxDataController.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboboxSerializableTest.java
The PR fixes ComboBox serialization which was broken because one of the lambdas happened to capture an Optional variable when setting items.
Fixes https://github.com/vaadin/flow-components/issues/3814
=> fix: make ComboBox serializable when items are provided

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxDataController.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboboxSerializableTest.java
The PR cherry-picks the following fixes to `23.2`:
- https://github.com/vaadin/flow-components/pull/3823
> **Note**
> There were no conflicts. It is just the target label didn't have an effect in the original PR for some reason.
Fixes https://github.com/vaadin/flow-components/issues/3814
=> fix: make ComboBox serializable when items are provided (CP: 23.2) (#3823)

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/pom.xml, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/main/java/com/vaadin/flow/component/spreadsheet/tests/SpreadsheetTabSheetPage.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/SpreadsheetTabSheetIT.java
Part of https://github.com/vaadin/components-team-tasks/issues/604
Migrate [SpreadsheetTabsheetTest](https://github.com/vaadin/spreadsheet/blob/flow-port/legacy/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/SpreadsheetTabsheetTest.java) to Flow Spreadsheet
=> test: migrate tabsheet IT from v8 spreadsheet

pom.xml, scripts/build.sh
This should show meaningful messages and errors in the case of failure, otherwise there is no noise in the output when running ITs
=> chore: reduce verbosity when running Tests

vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetTest.java
Fixes https://github.com/vaadin/flow-components/issues/3843
=> fix: set tabsheet selected property on setSelectedIndex

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/CellValueChangeEventOnFormulaChangeTest.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/DefaultHyperlinkCellClickHandlerTests.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/MultipleSheetsTest.java
Add more unit tests for the server-side logic of Spreadsheet APIs concerning working with multiple sheets
=> test: add multiple sheets unit tests

vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetTest.java
Follow-up for https://github.com/vaadin/flow-components/pull/3846
Since the selected index can change due to various reasons, it's safer to synchronize the property value inside the internal selected change listener.
=> fix: update selected property on selected change

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
Improve JavaDoc for deprecated methods in `TreeGrid` to clarify that they have been deprecated to indicate that they are not supported. I don't think any further action is necessary to resolve the linked issue.
Closes #2762
=> docs: clarify usage of deprecated methods

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/FormulasTest.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/MultipleSheetsTest.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/TestHelper.java
Add a helper for dispatching simulated [client events](https://github.com/vaadin/flow-components/blob/b975fe57019cb9466ebb14ddd17857a0ba795aa4/vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet.js#L433-L598) in Spreadsheet Junit tests
=> test: add a helper for dispatching spreadsheet events

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/CellValueShorteningTest.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/ColumnFiltersTest.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/ConditionalFormatterTest.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/DefaultHyperlinkCellClickHandlerTests.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/EmptyFileTest.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/FilterTableTest.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/FormulasTest.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/MultipleSheetsTest.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/SpreadsheetReadWriteTest.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/TestHelper.java
Multiple unit tests read an Excel file and initiate a `Spreadsheet` with the file used as the data source. This PR adds a shared helper for it.
=> test: add a test helper for creating a spreadsheet from excel file

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/GroupingTest.java
Follow-up for https://github.com/vaadin/flow-components/pull/3876
Adds unit tests for level header clicks:
https://user-images.githubusercontent.com/1222264/195874486-cfecd58d-263d-47b2-82cd-ad685bcca350.mp4
=> test: add spreadsheet group level header click unit tests

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/ClipboardTest.java
Add Junit tests for the Spreadsheet clipboard feature. Aiming to cover the server-side cut and paste logic of [`SpreadsheetHandlerImpl`](https://github.com/vaadin/flow-components/blob/c46906cb1ef09b8cbc7056e19b13f091c4a68248/vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SpreadsheetHandlerImpl.java#L250-L459)
=> test: add spreadsheet paste and cut unit tests

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/FormulaColumnsIT.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/NavigationIT.java
- testFloatOperations passes locally now
- testNavigationInSelectionWithEnterAndTab was authored wrong, it applied 4 enter presses where 2 was expected. With the correct script, the tests passes locally
=> test: re-enable some ignored spreadsheet ITs

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java
This PR removes the empty event listener removal methods, such as `removeSelectionChangeListener`, and makes the related add listener methods return a `Registration` instead.
- Feature
=> feat: drop remove listener methods in favor of registrations

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Removes the `isSelectedOnGrid` function which has a flawed implementation in that it always returns false, effectively doing nothing in the places where it's used.
Closes #3829
- Refactor
=> refactor: remove useless function from grid connector

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
Fixes #3909 
The issue occurred when disposing of the `<input>` element that was used for editing the cell. This PR makes the `<input>` lose focus before disposal to avoid the undesired scroll position side effect.
=> fix: blur input when stopping spreadsheet cell edit

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTooltipIT.java
Fixes grid tooltip ITs to adapt to changes from https://github.com/vaadin/web-components/pull/4819
=> fix: flush grid scrolling before opening tooltip

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarTooltipIT.java
Tried to fast the following ITs by waiting for the overlay element to open:
```
MenuBarTooltipIT.hoverOverMenuBarButton_showTooltip[ANY_Chrome_]
--
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"tag name","selector":"vaadin-tooltip-overlay"}
MenuBarTooltipIT.toggleAttached_hoverOverTooltipColumnCell_showTooltip[ANY_Chrome_]
--
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"tag name","selector":"vaadin-tooltip-overlay"}
```
- Tests
=> test: wait for tooltip overlay to open

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ScrollingIT.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/client/CellData.java
`SheetWidget` keeps a map with cached `CellData`, but a new entry is only added if the `CellData` object has the property `value` different from `null`. The serialization done to send data from the server to the client ignores properties that have null or empty values.
This breaks the following logic because `SheetWidget` won't put the entry to the map due to the missing property:
https://github.com/vaadin/flow-components/blob/5876423ab1e14d4888ea5f8d800c6bfca5e0d6f1/vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java#L4193-L4197
Fixes #3911
=> fix: include `CellData.value` on object serialization

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DetachReattachPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachReattachIt.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Cherry-pick of #3292 
Part of #3959, see https://github.com/vaadin/flow-components/issues/3959#issuecomment-1293611904. I'll add tests for that issue in a separate PR.
(cherry picked from commit 6b697e4f222fe3214dd601933d22e24e95e5392f)
=> fix: update sorters only if grid is attached (#3292) (CP: 14.9)

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/InitialMultiSortPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/InitialMultiSortIT.java
Adds an integration test to verify that setting an initial multi-sort does not trigger client-side sort change events. This effectively tests this condition, which was added for a different reason as part of https://github.com/vaadin/flow-components/pull/3292:
https://github.com/vaadin/flow-components/blob/37071dd840b85c64d014bf42aebaea8317b8b6c1/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java#L3473-L3476
Adding this test and back-porting #3292 to 14 (see #3964) effectively resolves #3959.
Closes https://github.com/vaadin/flow-components/issues/3959
=> test: add initial multi-sort IT

pom.xml
this was added when flow doesn't have the related change now this should come from flow directly
so let us remove it here
part of https://github.com/vaadin/flow-components/issues/3816
=> chore: remove the license-checker dependency from project

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DetachReattachPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachReattachIt.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Cherry-pick of #3292 
(cherry picked from commit 6b697e4f222fe3214dd601933d22e24e95e5392f)
=> fix: update sorters only if grid is attached (#3292) (CP: 22)

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ImageIT.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java
Fixes #3261
This PR fixes the issue by adding special handling for type 3 images (`DONT_MOVE_AND_RESIZE`) defined in XSSF files. The new logic anchors the images to the first cell (`A1`) and then applies x/y offset obtained from `xssfAnchor.getPosition()` as advised in https://github.com/vaadin/flow-components/issues/3261#issuecomment-1291256453
Using absolutely positioned images still has some issues after this change. They can be covered separately: 
- switching to a sheet with a large initial scrollTop doesn't show the image until scrolled back to the top
- sheets with frozen panes have problems with positioning the image
This PR also migrates a related IT from V8 Spreadsheet ([ImageTests](https://github.com/vaadin/spreadsheet/blob/flow-port/legacy/vaadin-spreadsheet/src/test/java/com/v …
=> fix: handle absolutely positioned images in XSSF files

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
Follow-up fix to https://github.com/vaadin/flow-components/pull/3977
Improve the check in `SheetWidget.getEventTarget(NativeEvent event)` to also fall back to `composedPath()` if the event target is some custom element other than `<vaadin-spreadsheet>` (for example the spreadsheet itself may be wrapped inside another shadow root).
=> fix: improve the check if an event originates from shadow root

pom.xml
flow has removed the snapshot dependency, so let us remove the snapshot repo
fix #3816
=> chore: remove apache snapshot repo

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetConnector.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ContextMenuIT.java
If the document is scrolled, the coordinates for the Spreadsheet context menu get miscalculated. This PR fixes the positioning logic.
The issue also occurs with the V8 Spreadsheet but it becomes very apparent with the Flow spreadsheet once embedded on the Vaadin docs page where you need to scroll the document to see the Spreadsheet:
=> fix: fix spreadsheet context menu positioning

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerLocalePage.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocaleIT.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
Changes the date picker connector to use date-fns for locale-based parsing and formatting instead of implementing custom logic.
- creates a date-dns pattern from the output of `Date.toLocaleDateString(locale)` instead of creating a regex for parsing
- re-uses the existing date-fns parsing and formatting logic using the created pattern, removes custom parsing and formatting logic for locale-based mode
- adds additional check for unsupported locales and falls back to `en-US` if a valid pattern could not be created
- restructure locale-based ITs to use a single date picker that allows changing the locale
- Refactoring
=> refactor: use date-fns for locale-based parsing and formatting

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerLocalePage.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocaleIT.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
Cherry-pick of #4016 
(cherry picked from commit 4bf3adf96aa2ed735ed1560470a0d26ae430612d)
=> refactor: use date-fns for locale-based parsing and formatting (#4016) (CP: 23.3)

vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/FlexLayout.java, vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/test/java/com/vaadin/flow/component/orderedlayout/tests/FlexLayoutTest.java
The method `getFlexDirection` of `FlexLayout` is not a static method and has an unnecessary parameter that should just be the object itself. This PR removes that parameter.
This is a breaking change and should not be backported.
Fixes #2847
=> refactor!: remove unnecessary parameter from getter

vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/FlexLayout.java
The method getFlexDirection of FlexLayout is not a static method and has an unnecessary parameter that should just be the object itself. This PR deprecates that method and introduces a new method without parameters.
This is a temporary change and the deprecated method will be [removed](https://github.com/vaadin/flow-components/pull/4029) in v24.
Fixes #2847
=> feat: deprecate getFlexDirection with parameter, add a replacement

vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/GeneratedVaadinContextMenu.java
`ContextMenu` element is not clickable, therefore the implementation of `ClickNotifier` interface is unnecessary. This PR removes the implementation of this interface.
This is a breaking change and should not be back-ported.
Fixes #1250
=> refactor!: remove the implementation of clicknotifier interface

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPageIT.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Fixes the combo box to only show the current item as selected in the overlay. The fix mostly involves removing a workaround from the connector that broke updating the selected item in the overlay. The purpose of the workaround was to ensure that an item is still displayed as selected if its item key changes in the data communicator (can happen when scrolling it out of view or filtering), as an alternative it seems that just updating the `selectedItem.key` property does the same. Note that this also requires updating `value`, otherwise the web component will clear the selected item if its key does not match the value. I could not observe any unwanted selected item or value change events from the change, I'm guessing these are discarded in `AbstractSinglePropertyField` as the mapped value …
=> fix: properly update selected item key

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java, vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/FlexLayout.java
Deprecates the protected renderer APIs on the grid column, which are scheduled to be removed in 24 (see https://github.com/vaadin/flow-components/pull/4025). These APIs were intended to be used internally and have been given protected accessibility to facilitate internal features, but there is a change that someone is using them in custom grid column classes.
- Refactoring
=> refactor: deprecate grid column renderer APIs

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewFilteringIT.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewHeaderAndFooterRowsIT.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractRow.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/FooterRow.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/HeaderRow.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java
Removes the usage of `TemplateRenderer` and `ComponentRenderer` for rendering header and footer content in grid columns, and instead adds connector methods to define header/footer renderer functions on the client grid column that render the respective text or component content. This effectively removes any usage of the `<template>` element for grid headers and footers.
Breaking changes:
- Header and footer do not contain a `<flow-component-renderer>` tag anymore when using component header or footer
- removes protected `AbstractColumn.setHeaderRenderer`
- removes protected `AbstractColumn.getHeaderRenderer`
- removes protected `AbstractColumn.setFooterRenderer`
- removes protected `AbstractColumn.getFooterRenderer`
Closes https://github.com/vaadin/flow-components/issues/3574
Fixes …
=> refactor!: remove template usage from grid header and footer

vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
Constructors with a single string parameter should set the label for the component. Currently, RichTextEditor does not support labels but it has a single string parameter constructor which sets the value. For the behaviour to be in line with the other components, this PR deprecates the constructor for v23.3.
This is a temporary change which will be overridden with the [removal](https://github.com/vaadin/flow-components/pull/4027) of the constructor in v24.
Fixes #1276
=> refactor: deprecate constructor with a single string parameter

vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/GeneratedVaadinContextMenu.java
`ContextMenu` element is not clickable, therefore the implementation of `ClickNotifier` interface is unnecessary. This PR deprecates the use of the methods that are provided by this interface.
This is a temporary change and the interface will be [removed](https://github.com/vaadin/flow-components/pull/4031) in v24.
Fixes #1250
=> refactor: contextmenu deprecate clicknotifier methods v23

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/main/java/com/vaadin/flow/component/spreadsheet/tests/FreezePaneLocalePage.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/FreezePaneLocaleIT.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java
Addresses the issue described [here](https://docs.google.com/spreadsheets/d/1dpRq-pHZ8DwtEEmmSTVLraix-7AWTzzPp1YutVU0qRg/edit#gid=0&range=28:28): When the active sheet gets hidden, another sheet becomes the new active sheet, but the cell styles don't get automatically updated.
=> fix: update sheet styles when active sheet is hidden

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/FreezePaneIT.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SpreadsheetFactory.java
Addresses the issue described [here](https://docs.google.com/spreadsheets/d/1dpRq-pHZ8DwtEEmmSTVLraix-7AWTzzPp1YutVU0qRg/edit#gid=0&range=33:33): "Freezing panes on the "100_000_rows.xlsx" file leads to browser console error and the sheet breaks and can't be used after that."
The issue was caused by a regression from https://github.com/vaadin/spreadsheet/pull/532
=> fix: fix pane freezing in large spreadsheets

vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java
Replaces usage of `TemplateRenderer` in `Crud` with `LitRenderer`.
Part of https://github.com/vaadin/flow-components/issues/4059
- Refactoring
=> refactor: replace TemplateRenderer with LitRenderer in Crud

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/main/java/com/vaadin/flow/component/spreadsheet/tests/SizingPage.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/SizingIT.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet-styles.js
The `<vaadin-spreadsheet>` Web Component currently gets applied inline styles for `height: 100%; width: 100%` due to an internal call to `setSizeFull();`. The Web Component should size correctly even without inline styles.
This PR removes the internal `setSizeFull();` call and adds missing `width: 100%;` to the spreadsheet Web Component host styles.
=> refactor: remove spreadsheet inline styles

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
The `i18n.week` has been removed by https://github.com/vaadin/web-components/pull/4799
Let's deprecate it for `23.3` branch so that we can remove it in V24.
- Deprecation
=> refactor: deprecate no longer used week string

vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/NumberField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java
Remove deprecated `setPattern` API from `NumberField` as not supported by `<input type="number">`.
Note, we might revisit the field internals to use `<input type="text">` instead in the future.
However, there are no specific plans at this point, so let's remove this API in Vaadin 24.
If we decide to re-implement `NumberField`, we might add this API back in a future minor version.
=> refactor!: remove setPattern API from NumberField

vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/Button.java, vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/GeneratedVaadinButton.java
Deprecate `GeneratedVaadinButton` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
=> refactor: deprecate generated button class and methods

vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckbox.java
Deprecate `GeneratedVaadinCheckbox` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
Related to https://github.com/vaadin/components-team-tasks/issues/606
=> refactor: deprecate generated checkbox

vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
Deprecate `GeneratedVaadinDialog` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
=> refactor: deprecate generated dialog class and methods

vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUpload.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUploadFile.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
Deprecates `GeneratedVaadinUpload` and `GeneratedVaadinUploadFile`, which are scheduled for removal in 24.
There are several public event classes, however none of them are exposed in the public API of the main component, so we don't intend to introduce alternatives for them.
Part of https://github.com/vaadin/components-team-tasks/issues/606
- Refactoring
=> refactor: deprecate generated upload classes

vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
Deprecates the `GeneratedVaadinTimePicker` class which is scheduled for removal in 24.
Introduces an alternative `TimePicker.InvalidChangeEvent` as it is used in public API.
Part of https://github.com/vaadin/components-team-tasks/issues/606
- Refactoring
=> refactor: deprecate generated time picker class

vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java, vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormItem.java, vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.java
Deprecate `GeneratedVaadinFormItem` and `GeneratedVaadinFormLayout` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
Deprecate the methods in the classes.
=> refactor: deprecate generated form layout and form item classes

vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java, vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
Deprecate `GeneratedVaadinNotification` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
Deprecate the methods in the classes.
Add suppress warning annotation to the main component. 
Create an `OpenedChangeEvent` in `Notification` which extends the one in the generated class. Alter the listeners in both classes to use the new event class.
=> refactor: deprecate generated notification class and its methods

vaadin-progress-bar-flow-parent/vaadin-progress-bar-flow/src/main/java/com/vaadin/flow/component/progressbar/GeneratedVaadinProgressBar.java, vaadin-progress-bar-flow-parent/vaadin-progress-bar-flow/src/main/java/com/vaadin/flow/component/progressbar/ProgressBar.java
Deprecate `GeneratedVaadinProgressBar` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
=> refactor: deprecate generated progress bar class and its methods

vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java, vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/GeneratedVaadinContextMenu.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenu.java
Deprecate `GeneratedVaadinContextMenu` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
=> refactor: deprecate generated context menu class and methods

vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButton.java
Deprecate `GeneratedVaadinRadioButton` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
Deprecate the methods in the class.
=> refactor: deprecate generate radio button class and its methods

vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
Deprecate `GeneratedVaadinRadioGroup` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
=> refactor: deprecate generated radio button group class and its methods

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SpreadsheetFactory.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/SpreadsheetReadWriteTest.java
Addresses the DX test finding: "[Multiple saving to the same file seems not to work](https://docs.google.com/spreadsheets/d/1dpRq-pHZ8DwtEEmmSTVLraix-7AWTzzPp1YutVU0qRg/edit#gid=0)"
=> fix: remove existing file before writing the worksheet

vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/GeneratedVaadinRichTextEditor.java, vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
Deprecate `GeneratedVaadinRichTextEditor` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
=> refactor: deprecate generated rich text editor class and its methods

vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java, vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
Deprecate `GeneratedVaadinSplitLayout` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
Create a `SplitterDragendEvent ` in `SplitLayout` which extends the one in the generated class. Alter the listeners in both classes to use the new event class.
=> refactor: deprecate generated split layout class and its methods

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/SheetFilterTableIT.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/PopupButton.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java
This PR intends to fix ["Table filters stop working after deleting row in table"](https://docs.google.com/document/d/1U6uRAyUsSML_q7U2J6hmAX6q3EmLhmOJJaiJn4LHCrQ/edit#heading=h.cd50bw3zrwb5) issue found on the DX tests.
Make `CellReference` returned by `PopupButton#getCellReference` and created when a row is moved consistent with the ones used by the hash map. This is to ensure that [`Spreadsheet#onPopupButtonClick`](https://github.com/vaadin/flow-components/blob/e1a8c8faa070a4a38e3c3bd59a6f09298d9cd7ce/vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java#L647) will always be able to find the popup button by row and column.
=> fix: fix filter table content after a row is deleted

vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java
Deprecate `GeneratedVaadinTextArea` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
=> refactor: deprecate generated text area

vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tab.java
Deprecate `GeneratedVaadinTab` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
=> refactor: deprecate generated tab class and its methods

vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java
Deprecate `GeneratedVaadinTabs` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
=> refactor: deprecate generated tabs class and its methods

vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/Select.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java
Deprecate `GeneratedVaadinSelect` as a part of the https://github.com/vaadin/components-team-tasks/issues/606 considering the deprecation of generated classes.
Deprecate the methods in the class.
=> refactor: deprecate generated select class and its methods

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
Deprecates the generated protected methods for adding and removing a prefix component. The API should be replaced with a dedicated prefix component API in the future, similar to the one in `TextField`.
- Refactor
=> refactor: deprecate generated prefix component API in combo box

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/SheetFilterTableIT.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/ItemFilter.java, vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/test/java/com/vaadin/flow/component/spreadsheet/tests/FilterTableTest.java
This intends to fix ["Table filter hides row when opening"](https://docs.google.com/document/d/1U6uRAyUsSML_q7U2J6hmAX6q3EmLhmOJJaiJn4LHCrQ/edit#heading=h.j44p8x2gb4ch) issue discovered on the DX tests.
This change brings the same behavior from Spreadsheet for V8, where if a filtered row is unhidden from the context menu keeps its state when the popup button is opened.
=> fix: prevent filter on popup open

vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/GeneratedVaadinButton.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckbox.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckboxGroup.java, vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/GeneratedVaadinContextMenu.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePicker.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java, vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormItem.java, vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.java, vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java, vaadin-progress-bar-flow-parent/vaadin-progress-bar-flow/src/main/java/com/vaadin/flow/component/progressbar/GeneratedVaadinProgressBar.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java, vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/GeneratedVaadinRichTextEditor.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java, vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinEmailField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinNumberField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinPasswordField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextField.java
For the deprecation notices on generated classes we specifically wanted to mention that the *generated* classes will be removed, let's clarify the notices to do so.
=> chore: clarify deprecation notices

vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/main/java/com/vaadin/flow/component/richtexteditor/tests/RichTextEditorAsDeltaPage.java, vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/tests/RichTextEditorAsDeltaIT.java, vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java, vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/test/java/com/vaadin/flow/component/richtexteditor/RichTextEditorTest.java
Deprecates the `RichTextEditor` value getter and setter in favor of a new `asDelta` wrapper. In 24 we want to make the HTML format the default, so the intention is to temporarily deprecate the value property in order to move existing users of the delta format over to the new wrapper. In 24 we switch the implementation of the value property to use the HTML format, and remove the deprecation.
Part of https://github.com/vaadin/flow-components/issues/1063
- Refactoring
=> refactor: deprecate RTE value property in favor of asDelta

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/CellShiftValuesUndoRedoIT.java
Disables a spreadsheet test that consistently fails in Flow component snapshot: https://bender.vaadin.com/buildConfiguration/FlowComponents_Snapshot/355959?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true
Disabling, as fixing the test has little value, since 23.1 is not going to be maintained for much longer, and only contains spreadsheet in an experimental state.
=> chore: disable flaky spreadsheet test (23.1)

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxListDataViewIT.java
The `addItemCountChangeListener_newItemAdded_itemCountChanged` IT fails regularly in CI and [snapshot validation](https://bender.vaadin.com/buildConfiguration/FlowComponents_Snapshot/356410?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&hideTestsFromDependencies=false), as well as when debugging locally. There seems to be an actual issue with committing a value or changing the underlying data while the component is loading. Modified the test to wait until loading has finished before committing the value.
=> chore: improve flaky combo box test

vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/main/java/com/vaadin/flow/component/menubar/tests/MenuBarSerializationPage.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarSerializationIT.java, vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
Deserialization of a UI containing a `MenuBar` component failed with a `ClassCastException`. 
This PR changes the lambda expression `this::resetContent` and adds an anonymous class instead.
Fixes #4056
=> fix: lambda expression was refactored into an anonymous class

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/EditorVerticalScrollingPage.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Deprecates the `Grid.setVerticalScrollingEnabled` method, which is scheduled to be removed in v24.
Part of #4168
=> refactor: deprecate Grid.setVerticalScrollingEnabled

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java
The `Spreadsheet` logs `Spreadsheet.registerRpc()` for each new instance which adds unnecessary noise to CI logs etc.
- Chore
=> chore: stop logging registerRpc in spreadsheet

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/test/java/com/vaadin/flow/data/renderer/NativeButtonRendererTest.java
LitRenderer prefixes the names of properties to scope them. The current `NativeButtonRendererTest` made an assumption that the scope would be `lr_0_` while that may be untrue depending on the run environment.
=> test: fix native button renderer test

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet.js
Fixes an issue with frontend compilation in docs:
=> chore: use a static getter for spreadsheet styles

vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/AbstractComboBoxIT.java
Fixes ITs checking `innerHTML` of component renderer output, by stripping HTML comments created by Lit renderer output.
=> chore: fix combo box component renderer ITs

vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java
Removed `IronResizeEvent` API from `GeneratedSplitLayout`, previously deprecated in #3545.
=> refactor!: remove deprecated IronResizeEvent API

vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java
Removed `TimePicker` APIs that have been deprecated in https://github.com/vaadin/flow-components/pull/2246.
=> refactor!: remove deprecated setMinTime and setMaxTime

vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/UploadTestsI18N.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/UploadI18N.java
Removed no longer needed `UploadI18N` API that was deprecated in https://github.com/vaadin/flow-components/pull/2215.
=> refactor!: remove deprecated UploadI18N.setCancel

vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java
Remove the `SelectedChangeEvent` constructor that has been deprecated in https://github.com/vaadin/vaadin-tabs-flow/pull/83.
=> refactor!: remove deprecated SelectedChangeEvent constructor

vaadin-grid-pro-flow-parent/vaadin-grid-pro-testbench/src/main/java/com/vaadin/flow/component/gridpro/testbench/GridTHTDElement.java
As part of https://github.com/vaadin/web-components/pull/4260 we changed GridPro cells to wrap their slot in a button element, when run on macOS. This causes GridPro ITs to fail when run on macOS, as TestBench selectors currently expect the slot to be the direct child of the cell.
This change modifies these selectors to query for the slot instead.
=> chore: fix Grid testbench selectors to work on macOS

vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListViewIT.java, vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/java/com/vaadin/flow/component/virtuallist/VirtualList.java, vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/resources/META-INF/resources/frontend/virtualListConnector.js
Follow-up for https://github.com/vaadin/flow-components/pull/4148
This PR fixes an issue where a LitRenderer-based VirtualList would not show the placeholder item. This is because the placeholder item wasn't mapped by the renderer's data generator. Just like all the other virtual list items, the data generator should process the placeholder item before sending it to the client.
In LitRenderer's case, the data generator prefixes the item properties with an instance-specific namespace identifier.
In ComponentRenderer's case, processing the placeholder item with the [data generator](https://github.com/vaadin/flow-components/blob/master/vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/ComponentDataGenerator.java) results in a Component getting …
=> fix: map virtual-list placeholder item with data generator

vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListIT.java, vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/java/com/vaadin/flow/component/virtuallist/VirtualList.java
Replace `TemplateRenderer` with `LitRenderer` in `VirtualList` 
Part of https://github.com/vaadin/flow-components/issues/4059
- Refactoring
=> refactor: remove internal TemplateRenderer use from VirtualList

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridPreloadIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/HierarchyColumnComponentRenderer.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
Replace `TemplateRenderer` with `LitRenderer` in `TreeGrid` 
Part of https://github.com/vaadin/flow-components/issues/4059
- Refactoring
=> refactor: remove internal TemplateRenderer use from TreeGrid

vaadin-upload-flow-parent/vaadin-upload-flow/pom.xml, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/UploadSlotsTest.java
Fixes #3542
Based on https://github.com/vaadin/web-components/pull/4857
Changed the `Upload` APIs to create slotted elements on the server side, as proposed in https://github.com/vaadin/flow-components/issues/3542#issuecomment-1200823976.
This makes the following methods return correct components by default, instead of `null`:
- `getUploadButton()`
- `getDropLabel()`
- `getDropLabelIcon()`
- Feature
=> feat: make upload slots API work as expected

vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/UploadSlotsTest.java
There is a problem with unit tests introduced in #4207 and now it causes snapshot and other PRs to fail.
Apparently, unit tests for Upload module are not configured correctly adn don't run with ITs. 
Here is the error, it's unclear to me why it happens but at least `@After` block is missing.
```
java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.component.UI.getUIId()" because the return value of "com.vaadin.flow.component.UI.getCurrent()" is null
at com.vaadin.flow.component.upload.tests.UploadSlotsTest.setDropLabelNull_defaultLabelIsRestored(UploadSlotsTest.java:76)
```
- Tests
=> test: reset UI in teardown for Upload slot tests

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTooltipTest.java
The null check in `setTooltipGenerator` is incorrectly using `classNameGenerator` 🙈 
- Bugfix
=> fix: use correct null check in setTooltipGenerator

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxRenderManager.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridViewUsingTemplatesPage.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/BasicRenderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LocalDateRenderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LocalDateTimeRenderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/NativeButtonRenderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/NumberRenderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/test/java/com/vaadin/flow/data/renderer/ComponentRendererTest.java, vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/java/com/vaadin/flow/component/virtuallist/VirtualList.java
Follow up for https://github.com/vaadin/flow-components/pull/4148
Extracted from https://github.com/vaadin/flow-components/pull/4224
Clean up outdated references to "template renderer" in code comments and test names
=> docs: clean up references to TemplateRenderer in comments

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDemoPage.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
Deprecates the `RadioButtonGroup` implementation of `HasItemComponents` and `HasComponents`, as the component is not intended to be used as a generic component container.
Part of #4194
- Refactoring
=> refactor: deprecate RadioButtonGroup implementation of HasItemComponents

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/main/resources/vaadin-featureflags.properties
The spreadsheet component is no longer behind a feature flag so the properties file can be removed
=> chore: remove spreadsheet feature flag property

vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet-styles.js
Use Lumo colors for the popup button overlay
Fixes https://github.com/vaadin/flow-components/issues/4266
Before:
After:
Bugfix
=> fix: use Lumo colors for popup button overlay

pom.xml
keep jetty version in sync with flow 23.3 https://github.com/vaadin/flow/blob/23.3/pom.xml#L110
=> chore: update jetty to 10 (23.3)

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BinderValidationPage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/TextAreaPage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaValidationBasicPage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaValidationBinderPage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BinderValidationPageIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/TextAreaPageIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaValidationBasicIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/TextAreaValidationBinderIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java
Adds chained validation support to `TextArea`. For more details, please refer to https://github.com/vaadin/platform/issues/3066.
Depends on 
- https://github.com/vaadin/flow-components/pull/4263 
Closes #4213 
- Feature
=> feat: integrate client-side validation into TextArea

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePicker.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java, vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java, vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java, vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java, vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
When sub-classing components, and using an implicit import for events such as `SplitterDragendEvent`, then the event classes introduced as an alternative to the deprecated events in generated classes can cause compilation errors. The problem is that the newly introduced event class now shadows the deprecated class, and the new class does not have the generic type param of the deprecated class.
Fixed this by adding a generic type param to the new event classes as well. The param will be dropped in v24, which will require developers to update their code during migration accordingly. The breaking change should be mentioned in the release notes, and in the migration guide.
Fixes https://github.com/vaadin/flow-components/issues/4286
- Bugfix
=> fix: restore backward compatibility of new event classes

vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
Drops logic that tries to provide a friendly UX for hackers after they tampered with the component on the client-side, similar to what has been done for `Select` in https://github.com/vaadin/flow-components/pull/4295.
RBG had tests for restoring client-side state, which where dropped as well. Remaining tests still verify that the server-side value can not be modified.
=> refactor: drop unnecessary logic from RadioButtonGroup

vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupIT.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
Drops logic that tries to provide a friendly UX for hackers after they tampered with the component on the client-side, similar to what has been done for `Select` in https://github.com/vaadin/flow-components/pull/4295.
CBG had tests for restoring client-side state, which where dropped as well. Remaining tests still verify that the server-side value can not be modified.
=> refactor: drop unnecessary logic from CheckboxGroup

vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/Button.java, vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/GeneratedVaadinButton.java
From a [Discord thread](https://discord.com/channels/732335336448852018/1053292376036212857/1053292376036212857), it seems that Eclipse marks `Button.addThemeVariant`, `Button.removeThemeVariant` as deprecated, even though the methods are not deprecated - only the `GeneratedVaadinButton` class that defines them is.
Let's add overrides for these methods to `Button` like we have done for other components. It seems that for every other component we already have an override for these methods.
=> fix: avoid deprecation notice in Eclipse for button theme variant methods

vaadin-flow-components-shared-parent/vaadin-flow-components-test-util/src/main/java/com/vaadin/tests/validation/AbstractBasicValidationTest.java
The PR adds a license header that I missed in https://github.com/vaadin/flow-components/pull/4356.
=> chore: add a missing license header

vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java, vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java
Fixes #1275
Removing the constructor that has been deprecated since 23.1 - see https://github.com/vaadin/flow-components/issues/1275#issuecomment-1104824035
=> refactor!: remove deprecated Select constructor

vaadin-grid-flow-parent/vaadin-grid-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridElement.java
Removed the deprecated and no longer working method from TestBench API for Grid.
Its usage was previously removed - see e.g. https://github.com/vaadin/vaadin-grid-flow/pull/1138
=> refactor!: remove deprecated GridElement.findInShadowRoot

vaadin-accordion-flow-parent/vaadin-accordion-flow/src/main/java/com/vaadin/flow/component/accordion/Accordion.java, vaadin-accordion-flow-parent/vaadin-accordion-flow/src/main/java/com/vaadin/flow/component/accordion/AccordionPanel.java, vaadin-accordion-flow-parent/vaadin-accordion-testbench/src/main/java/com/vaadin/flow/component/accordion/testbench/AccordionElement.java, vaadin-accordion-flow-parent/vaadin-accordion-testbench/src/main/java/com/vaadin/flow/component/accordion/testbench/AccordionPanelElement.java, vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/AppLayout.java, vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/DrawerToggle.java, vaadin-app-layout-flow-parent/vaadin-app-layout-testbench/src/main/java/com/vaadin/flow/component/applayout/testbench/AppLayoutElement.java, vaadin-app-layout-flow-parent/vaadin-app-layout-testbench/src/main/java/com/vaadin/flow/component/applayout/testbench/DrawerToggleElement.java, vaadin-custom-field-flow-parent/vaadin-custom-field-flow/src/main/java/com/vaadin/flow/component/customfield/CustomField.java, vaadin-custom-field-flow-parent/vaadin-custom-field-testbench/src/main/java/com/vaadin/flow/component/customfield/testbench/CustomFieldElement.java, vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java, vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/DetailsVariant.java, vaadin-details-flow-parent/vaadin-details-testbench/src/main/java/com/vaadin/flow/component/details/testbench/DetailsElement.java, vaadin-login-flow-parent/vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/AbstractLogin.java, vaadin-login-flow-parent/vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginForm.java, vaadin-login-flow-parent/vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginI18n.java, vaadin-login-flow-parent/vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java, vaadin-login-flow-parent/vaadin-login-testbench/src/main/java/com/vaadin/flow/component/login/testbench/Login.java, vaadin-login-flow-parent/vaadin-login-testbench/src/main/java/com/vaadin/flow/component/login/testbench/LoginFormElement.java, vaadin-login-flow-parent/vaadin-login-testbench/src/main/java/com/vaadin/flow/component/login/testbench/LoginOverlayElement.java
Updated license header for the Flow components originally created by Pro team:
- `AppLayout`
- `CustomField`
- `Details`
- `Login`
Also updated `Accordion` that has the correct comment - just moved it to the first line.
The license is still the same (Apache 2.0), only the comment style has changed.
=> chore: align license header for core components

vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/EmailField.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java
Fixed a regression from the [accidental removal](https://github.com/vaadin/flow-components/pull/4377/files#diff-fea9ce1496969ddcbb3608e138125a5eb86e8d86050a9ce106f7fb622bd2a2d9L410-L422) of `setRequired` in #4337 - somehow I missed that 😞 
Also added this override to `EmailField` that has `getValidationSupport` but didn't have this. 
See internal discussion: https://vaadin.slack.com/archives/C3TGRP4HY/p1671547876459429
- Bugfix
=> fix: restore incorrectly removed setRequired override

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasAutoOpen.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/HasAutoOpenTest.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
Extracted `HasAutoOpen` interface to be used by following components:
- `ComboBox`
- `MultiSelectComboBox`
- `DatePicker`
- `DateTimePicker`
- `TimePicker`
- Refactor
=> refactor: extract HasAutoOpen interface to shared module

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/ClearValuePage.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/validation/DatePickerValidationBasicPage.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/validation/DatePickerValidationBinderPage.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/ClearValueIT.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/validation/DatePickerValidationBasicIT.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/validation/DatePickerValidationBinderIT.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
The PR cherry-picks the following fix to `23.3`:
- #4413
> **Note**
> There were a few conflicts due to the new test naming and structure that we introduced in `24.0` but that we didn't backport to `23.3`.
=> fix(DatePicker): clear possible bad input when setting an empty value (#4413) (CP: 23.3)

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/ValueChangeModeIT.java
There's currently a test case which keeps failing because it uses invalid text input value (`"11111"`) for `EmailField` while testing value change modes.
This change sets an initial value for the email field so that appending "1"s in the test case still keeps the field value valid (`"foo@test.com11111"`)
=> test: use a valid email field value in a test case

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/IntegerFieldClearValuePage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/NumberFieldClearValuePage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldValidationBasicPage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldValidationBinderPage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBasicValidationPage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBinderValidationPage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/IntegerFieldClearValueIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldClearValueIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBasicValidationIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/IntegerFieldBinderValidationIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBasicValidationIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBinderValidationIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
The PR overrides AbstractNumberField's `setValue()` to support clearing the input element from possible bad input when setting an empty value in the case the previous value was already empty. Or, in other words, this PR guarantees that bad input won't remain in the field after you assign an *empty* Binder bean that in fact relates to *another* record.
The PR targets both NumberField and IntegerField.
=> fix(AbstractNumberField): clear possible bad input when setting an empty value

vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
Replaced an ugly workaround in https://github.com/vaadin/flow-components/pull/4436/commits/449083a6c68eb34cbfe2ed0a74f3591d7a28519d with a proper fix - thanks @vursen for the help 🙏 
- Bugfix
=> fix: set correct flag on the default slotted elements

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldClearValuePage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBasicValidationPage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBinderValidationPage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldClearValueIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBasicValidationIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/validation/BigDecimalFieldBinderValidationIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
The PR overrides BigDecimalField's `setValue()` to support clearing the input element from possible bad input when setting an empty value in the case the previous value was already empty. Or, in other words, this PR guarantees that bad input won't remain in the field after you assign an *empty* Binder bean that in fact relates to *another* record.
=> fix(BigDecimalField): clear possible bad input when setting an empty value

vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java, vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/SlotUtils.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/SlotUtilsTest.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/HasPrefixAndSuffix.java, vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
Follow-up to #4427 inspired by https://github.com/vaadin/flow-components/pull/4427#discussion_r1057763912 - once again thanks @knoobie for the idea 🙇‍♂️ 
Related to #1574 - there will be a proper exception now for `Text`, like the one in `TabSheet`:
https://github.com/vaadin/flow-components/blob/35154825bca56b8b91dc0e92e7e3178ff0d0bfb7/vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java#L297-L300
Also added missing unit tests for `addToSlot` as well as for the newly added `setSlot`.
- Refactor
=> refactor: add setSlot helper, check for adding Text

vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/ClearValuePage.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/validation/TimePickerValidationBasicPage.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/validation/TimePickerValidationBinderPage.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/ClearValueIT.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/TimePickerValidationBasicIT.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/validation/TimePickerValidationBinderIT.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
The PR cherry-picks the following fix to `23.3`:
- #4430
> **Note**
> There were a few conflicts due to the new test naming and structure that we introduced in `24.0` but that we didn't backport to `23.3`.
=> fix(TimePicker): clear possible bad input when setting an empty value (#4430) (CP: 23.3)

vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/ClearValuePage.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/validation/DateTimePickerValidationBasicPage.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/validation/DateTimePickerValidationBinderPage.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/ClearValueIT.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/validation/DateTimePickerValidationBasicIT.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/validation/DateTimePickerValidationBinderIT.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
The PR cherry-picks the following fix to `23.3`:
- #4431
> **Note**
> There were a few conflicts due to the new test naming and structure that we introduced in `24.0` but that we didn't backport to `23.3`.
=> fix(DateTimePicker): clear possible bad input when setting an empty value (#4431) (CP: 23.3)

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/IntegerFieldClearValuePage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/NumberFieldClearValuePage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/IntegerFieldClearValueIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/NumberFieldClearValueIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
The PR partially cherry-picks the following fix to `23.3`:
- #4431
> **Note**
> The new validation behavior isn't implemented for number fields in 23.3, so there are no `BasicValidationIT`, `BinderValidationIT`.
=> fix(AbstractNumberField): clear possible bad input when setting an empty value (#4438) (CP: 23.3)

vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldClearValuePage.java, vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BigDecimalFieldClearValueIT.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/BigDecimalField.java
The PR partially cherry-picks the following fix to `23.3`:
- #4442
> **Note**
> The new validation behavior isn't implemented for number fields in 23.3, so there are no `BasicValidationIT`, `BinderValidationIT`.
=> fix(BigDecimalField): clear possible bad input when setting an empty value (#4442) (CP: 23.3)

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasPrefix.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasSuffix.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/HasPrefixTest.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/HasSuffixTest.java
Inspired by https://github.com/vaadin/flow-components/pull/4377#discussion_r1050102495 
Pre-requisite for #1594
Created two separate interfaces: `HasPrefix` and `HasSuffix` based on the `HasPrefixAndSuffix` interface.
I will create a separate PR to update `TextField` and other components to use these new interfaces.
After all the components are updated, we could probably drop `HasPrefixAndSuffix` as no longer needed.
- Internal feature
=> feat: add HasPrefix and HasSuffix shared interfaces

vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/Button.java
Based on #4458
Removed `addToPrefix` and `addToSuffix` as these methods are deprecated in 23.3.
- Breaking change / Refactor
=> refactor!: add HasPrefix and HasSuffix to Button

vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
The `Dialog` component currently uses a `<template>` tag internally to add the `flow-component-renderer` inside its overlay. This PR
- replaces the `<template>` with a `renderer` function
- removes the dependency to `@vaadin/polymer-legacy-adapter/template-renderer.js`
- removes the `suppress-template-warning` attribute from the `<vaadin-dialog>` element
Refactor
=> refactor: replace template with renderer function in dialog

vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java, vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationTest.java
The `Notification` component currently uses a `<template>` tag internally to populate its overlay. This PR
- replaces the `<template>` with a `renderer` function
- removes the dependency to `@vaadin/polymer-legacy-adapter/template-renderer.js`
- removes the `suppress-template-warning` attribute from the `<vaadin-dialog>` element
Refactor
=> refactor: replace template with renderer function in notification

vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/ColumnPathRenderer.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/EditorRenderer.java, vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/Renderer.java
Follow-up for https://github.com/vaadin/flow-components/pull/4224
Moves the `render(Element container, DataKeyMapper<SOURCE> keyMapper, String rendererName)` API from `LitRenderer` to `Renderer`. Every type of `Renderer` should accept a custom name for the renderer function.
Example:
Before the change, `Grid` [needed to cast the renderer](https://github.com/vaadin/flow-components/blob/cea5c82ea950a600e4a2b65acd4db58ae15c524b/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java#L2868-L2869) passed to `setItemDetailsRenderer` as a `LitRenderer` to make it plug into the `rowDetailsRenderer` function on the Web Component. After the change, since the API is defined on the `Renderer`, casting is no longer necessary and any `Renderer` can be passed as …
=> refactor!: relocate Renderer API with custom function name

vaadin-tabs-flow-parent/vaadin-tabs-flow-integration-tests/src/main/java/com/vaadin/flow/component/tabs/tests/SelectedTabPage.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/SelectionEventTest.java
`Tabs` used to implement `HasOrderedComponents` and `HasComponents`. However, it does not support adding arbitrary content. This PR removes these interfaces from `Tabs` while retaining the functionality using `Tab` instead of `Component` in parameters.
This is a breaking change.
Fixes #1636
=> refactor!: stop implementing and retain functionality of hascomponents

vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupDemoPage.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupIT.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupTest.java
Calling `setItemLabelGenerator` for `CheckboxGroup` used to clear the selected values.
This PR makes the `CheckboxGroup` retain the selection by refreshing the checkboxes instead of resetting the `CheckboxGroup` when `setItemLabelGenerator` is called.
This is a breaking change.
Fixes #3131
=> fix!: retain checkbox group value on item label generator change

vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
Updated `DateTimePicker` to replace `import com.vaadin.flow.component.*` with actually needed imports.
- Refactor
=> refactor: update DateTimePicker to not use wildcard import

vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogChildrenTest.java, vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java, vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationChildrenTest.java
Fixes a regression from https://github.com/vaadin/flow-components/pull/4499
The previous PR didn't consider that child components may be removed by calling `child.removeFromParent()` (or by adding them to another parent). This PR adds a detach listener to each child component to take care of the issue.
- Bugfix
=> fix: update dialog and notification child ids on child remove

vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/CloseListenerReopenDialogIT.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/resources/META-INF/resources/frontend/dialogConnector.js
Avoid client-side errors on init when a `Dialog` is added as a child of another `Dialog`.
- Bugfix
=> fix: do not access dialog internals before the element is ready

vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java, vaadin-custom-field-flow-parent/vaadin-custom-field-flow/src/main/java/com/vaadin/flow/component/customfield/CustomField.java, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasValidationProperties.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/HasValidationPropertiesTest.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java, vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/InternalFieldBase.java, vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
1. Added `HasValidationProperties` interface which is based on [`HasValidation`](https://github.com/vaadin/flow/blob/fd04f545ee3f13b0cf3cdf2b694c6d9ab215c689/flow-server/src/main/java/com/vaadin/flow/component/HasValidation.java#L27) and provides same method signatures. 
The difference is that this interface actually sets / gets corresponding properties: `invalid` and `errorMessage`.
2. Updated all the components that provide these methods to use the new interface instead of `HasValidation`.
- Refactor
=> refactor: extract common logic to HasValidationProperties

vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/main/java/com/vaadin/flow/component/richtexteditor/tests/RichTextEditorAsDeltaPage.java, vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/tests/RichTextEditorAsDeltaIT.java, vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java, vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/test/java/com/vaadin/flow/component/richtexteditor/RichTextEditorTest.java
Cherry-pick of #4087 to `master` / v24.
Adding this as a basis for switching the default format to HTML to hopefully reduce the changes from [that PR](https://github.com/vaadin/flow-components/pull/4521) a bit.
Part of https://github.com/vaadin/flow-components/issues/1063
- Refactoring
=> refactor: deprecate RTE value property in favor of asDelta (#4087)

vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/FlexComponent.java, vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/FlexLayout.java, vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/test/java/com/vaadin/flow/component/orderedlayout/tests/FlexComponentTest.java, vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/test/java/com/vaadin/flow/component/orderedlayout/tests/FlexLayoutTest.java
Closes https://github.com/vaadin/flow-components/issues/3772
Move the `setFlexShrink` and `getFlexShrink` methods from `FlexLayout` to `FlexComponent`, effectively making them available for `HorizontalLayout` and `VerticalLayout` also.
Relates to https://github.com/vaadin/web-components/pull/5281: `"Should introduce HorizontalLayout/VerticalLayout.setFlexShrink so Flow devs can easily revert the flex-shrink change in Button and badge"`
- Feature
=> feat: move flex-shrink API to FlexComponent

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LocalDateRenderer.java, vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LocalDateTimeRenderer.java
chore: removed non-serializable constructors from LocalDateRenderer and LocalDateTimeRenderer
Part of #4536
=> refactor!: removed non-serializable constructors from LocalDateRenderer

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxBaseTest.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
Based on #4502
Note, the `HasOverlayClassName` is now moved to `ComboBoxBase` where other shared interfaces are placed.
- Feature
=> feat: add HasOverlayClassName interface to MultiSelectComboBox

vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/FlexComponent.java, vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/FlexLayout.java, vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/HorizontalLayout.java, vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/VerticalLayout.java
Addresses https://github.com/vaadin/flow-components/pull/4541#discussion_r1071911284
Rename the confusing `elementContainers` parameter used in number of methods of the `ordered-layout` module.
Refactor
=> refactor: rename confusing elementContainers parameter

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/pom.xml, vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePicker.java, vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/pom.xml
Updated `vaadin-date-picker` to the new minor with `referenceDate` functionality.
- Version bump
=> chore: update vaadin-date-picker web component to 4.5.0

vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogChildrenTest.java, vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/main/java/com/vaadin/flow/component/notification/tests/NestedNotificationPage.java, vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/test/java/com/vaadin/flow/component/notification/tests/NestedNotificationIT.java, vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java, vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationChildrenTest.java
Fixes the regression discovered in https://github.com/vaadin/flow-components/pull/4538#discussion_r1072032428.
The issue occurred when scheduled JS executions would trigger for a virtual child component before it was actually added to the DOM. The PR fixes the issue by appending the child components as regular elements to the `<vaadin-notification>` and `<vaadin-dialog>` hosts. The script which teleports the child components inside the overlay still works as before.
Bugfix
=> fix: add dialog and notification children to host element

vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java, vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabSheetTest.java
=> fix: forward unregisterListener to the correct event in TabSheet

vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupTest.java, vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
Changes `CheckboxGroup` to remove any previously set item renderer when setting an item label generator. This ensures that the item label generator is actually used after setting it, and aligns the behavior of the component with `RadioButtonGroup`.
Closes #4522 
=> refactor!: remove renderer when setting item label generator

vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogHasStyleTest.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogSerializableTest.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/InternalOverlayClassListProxy.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/InternalOverlayClassListProxyTest.java
Follow-up to #4549. 
Moved the class into shared package and added `Internal` prefix with appropriate JavaDoc, as discussed.
- Refactor
=> refactor: extract OverlayClassListProxy to shared package

vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java, vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogHasStyleTest.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/internal/OverlayClassListProxy.java, vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/internal/OverlayClassListProxyTest.java
Moved the class as suggested by https://github.com/vaadin/flow-components/pull/4576#discussion_r1082421277.
- Refactor
=> refactor: move OverlayClassListProxy to the internal namespace

vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java
Remove the deprecated `withEventHandler` from LitRenderer. The method was added [here](https://github.com/vaadin/flow-components/pull/2042).
=> refactor!: remove deprecated withEventHandler from LitRenderer

vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/pom.xml, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridDateTimePickerPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridDateTimePickerIT.java
This was a difficult one to debug. It seems to have something to do with the old `ComponentRenderer` relying on a `<template>` and Polymer Templatizer to populate the cell content.
For some reason, this setup lead to a timing where setting the `<vaadin-date-picker>`'s `i18n` property synchronously in the connector wouldn't invoke any effects in the Web Component but instead, got soon after overridden by the default value. Setting the value in microtask timing works around the issue.
Note that the issue didn't produce with a `<vaadin-date-picker>`, but required a `<vaadin-date-time-picker>`.
Fixes https://github.com/vaadin/flow-components/issues/4500
- Bugfix
=> fix: use microtask when setting i18n object to date-picker

vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
Remove the ComboBox `remove(Component... components)` and `removeAll()` API that was [deprecated in 23.3](https://github.com/vaadin/flow-components/pull/4115)
=> refactor!: remove deprecated remove and removeAll from ComboBox

vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/RefreshDataProviderPage.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java, vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupTest.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/PreSelectedValuePage.java, vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
Remove the deprecated `setItems(Stream<T> streamOfItems)` method from `CheckboxGroup` and `ComboBoxBase`.
Also, make the deprecated `getDataProvider()` in `CheckboxGroup` private.
=> refactor!: remove or hide deprecated setItems and getDataProvider

vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerInAGridHeaderPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/contextmenu/DynamicContextMenuGridPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridScrollToPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridSingleSelectionDeselectAllowedPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridTestScrollingOver100kLines.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ToggleVisibilityPage.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Remove the deprecated `setItems(Stream<T> streamOfItems)` method from `Grid`
=> refactor!: remove deprecated setItems method from Grid

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasTooltip.java
Fixes https://github.com/vaadin/flow-components/issues/4293
The `HasTooltip` interface has caused some confusion among users because of its poor documentation. This PR improves the interface's Javadoc to make it better understandable.
=> docs: document the purpose of HasTooltip interface better

pom.xml
This reverts commit 2d0b5e8887d6753036a9d3030e8c2389021040ff.
=> Revert "chore: bump ci-sauce from 1.166 to 1.167 (#4575)"

pom.xml
also enable the `vaadin.frontend.hotdeploy`
=> chore: upgrade jetty-maven-plugin and properties

vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/Tooltip.java
Remove the static `WeakHashMap<Element, Tooltip>` that is used for tracking the `Tooltip` instances associated with `HasTooltip` instances in favor of `ComponentUtil.setData`
Fixes https://github.com/vaadin/flow-components/issues/4637
Refactor
=> refactor: remove static element to tooltip map

vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridViewItemDetailsPage.java, vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewItemDetailsIT.java, vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
The grid connector should remove cleared items from the `grid.detailsOpenedItems` array on `grid.$connector.clear`
Fixes https://github.com/vaadin/flow-components/issues/4516
Bugfix
=> fix: close open details for cleared items in grid connector

vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/main/java/com/vaadin/flow/component/map/FeatureLabelPage.java, vaadin-map-flow-parent/vaadin-map-flow-integration-tests/src/test/java/com/vaadin/flow/components/map/FeatureLabelIT.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Feature.java, vaadin-map-flow-parent/vaadin-map-flow/src/main/resources/META-INF/resources/frontend/vaadin-map/synchronization/index.js, vaadin-map-flow-parent/vaadin-map-testbench/src/main/java/com/vaadin/flow/component/map/testbench/MapElement.java
Allows to set and remove text labels for map markers. Labels are rendered with a default style for now, I'll add customization of the marker's label style in a follow-up PR.
Part of: https://github.com/vaadin/flow-components/issues/2898
AC: https://github.com/vaadin/platform/issues/3533
Research: https://github.com/vaadin/flow-components/issues/4278#issuecomment-1411810550
- Feature
=> feat: set labels for map markers

vaadin-details-flow-parent/vaadin-details-flow-integration-tests/src/main/java/com/vaadin/flow/component/details/tests/DetailsEventsPage.java, vaadin-details-flow-parent/vaadin-details-flow-integration-tests/src/main/java/com/vaadin/flow/component/details/tests/Home.java, vaadin-details-flow-parent/vaadin-details-flow-integration-tests/src/test/java/com/vaadin/flow/component/details/tests/BasicIT.java, vaadin-details-flow-parent/vaadin-details-flow-integration-tests/src/test/java/com/vaadin/flow/component/details/tests/DetailsEventsIT.java, vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java
Currently the opened change listener for `Details` listens for the `opened-changed` event from the client, which means that even when changing the opened state on the server, the event will always be from the client.
This change fixes that by using a property change listener instead, so that the event will correctly report whether the state was changed on the client or on the server. This also properly initializes the opened state on the server, so that the initial opened change event from initializing the Polymer property is discarded.
Fixes #4659
Fixes #4654
- Bugfix
=> fix: use property change listener for opened change event
